README.md

- github.com repo: https://github.com/a8m/rql
- godoc.org: https://godoc.org/github.com/a8m/rql
- goreportcard.com: https://goreportcard.com/report/github.com/a8m/rql
- No coverage link. However, it is high (~98%).  [![cover.run](https://cover.run/go/github.com/a8m/rql.svg?style=flat&tag=golang-1.10)](https://cover.run/go?tag=golang-1.10&repo=github.com%2Fa8m%2Frql)

doc: add rql

---

README.md

- github.com repo: https://github.com/gchaincl/httplab
- godoc.org: https://godoc.org/github.com/gchaincl/httplab
- goreportcard.com: https://goreportcard.com/report/github.com/gchaincl/httplab

Add HTTPLab

---

README.md

- github.com repo: https://github.com/pantrif/url-shortener
- godoc.org: https://godoc.org/github.com/pantrif/url-shortener
- goreportcard.com: https://goreportcard.com/report/github.com/pantrif/url-shortener
- coverage service link: https://gocover.io/github.com/pantrif/url-shortener/shortener

Add url-shortener

---

README.md

The go-cmp Github repo has 575 stars and is under the Google organization there. Ranked by Github stars, go-cmp would be #8 in the **Testing** section.
**Package links**
- github.com repo: https://github.com/google/go-cmp
- godoc.org: https://godoc.org/github.com/google/go-cmp/cmp
- goreportcard.com: https://goreportcard.com/report/github.com/google/go-cmp
- coverage service link: https://gocover.io/github.com/google/go-cmp/cmp

Added go-cmp, a "package for comparing Go values in tests".

---

README.md

- github.com repo: https://github.com/aerogo/packet
- godoc.org: https://godoc.org/github.com/aerogo/packet
- goreportcard.com: https://goreportcard.com/report/github.com/aerogo/packet
- coverage service link: [![coverage](https://codecov.io/gh/aerogo/packet/branch/master/graph/badge.svg)](https://codecov.io/gh/aerogo/packet) (codecov shows 80%, go test shows 85.1%) …

Add packet

---

README.md

- github.com repo: https://github.com/gilbertchen/duplicacy
- godoc.org: https://godoc.org/github.com/gilbertchen/duplicacy
- goreportcard.com: https://goreportcard.com/report/github.com/gilbertchen/duplicacy
----------------------------------------------------------
This change adds a link to the command line version of …

Add Duplicacy

---

README.md

Fix: typo for Sydney

---

README.md

- github.com repo: https://github.com/jaegertracing/jaeger
- godoc.org: https://godoc.org/github.com/jaegertracing/jaeger
- goreportcard.com: https://goreportcard.com/report/github.com/jaegertracing/jaeger
- coverage service link ![codecov](https://codecov.io/gh/jaegertracing/jaeger/branch/master/graph/badge.svg)
- [v] I have added my package in alphabetical order.
- [v] I have an …

Move Jaeger to distributed system

---

README.md

- github.com repo: https://github.com/g3n/engine
- godoc.org: https://godoc.org/github.com/g3n/engine
- goreportcard.com: https://goreportcard.com/report/github.com/g3n/engine
- coverage service: Can't automate visual testing! We've developed a comprehensive test program - [g3nd](https://github.com/g3n/engine) - which is updated when changes to the engine are made. It tests all features of the engine. It's prominently linked in the main repo) …

Added g3n - Go 3D Game Engine!

---

README.md

- github.com repo: https://github.com/maxatome/go-testdeep
- godoc.org: https://godoc.org/github.com/maxatome/go-testdeep
- goreportcard.com: [![Go Report Card](https://goreportcard.com/badge/github.com/maxatome/go-testdeep)](https://goreportcard.com/report/github.com/maxatome/go-testdeep)
- coverage service link: [![Coverage Status](https://coveralls.io/repos/github/maxatome/go-testdeep/badge.svg?branch=master)](https://coveralls.io/github/maxatome/go-testdeep?branch=master) …

Add go-testdeep to the Testing Frameworks list

---

README.md

- github.com repo: https://github.com/yunabe/lgo
- godoc.org: N/A
- goreportcard.com: https://goreportcard.com/report/github.com/yunabe/lgo
- coverage service link ([cover.run](https://cover.run/), [gocover](http://gocover.io/), [coveralls](https://coveralls.io/) etc.), example: `![cover.run](https://cover.run/go/https:/github.com/yunabe/lgo.svg?style=flat&tag=golang-1.9)`
Thanks …

Add yunabe/lgo - Interactive Go programming with Jupyter.

---

README.md

- github.com repo: https://github.com/google/gnxi
- godoc.org: https://godoc.org/github.com/google/gnxi
- goreportcard.com: https://goreportcard.com/report/github.com/google/gnxi
- coverage service link ([cover.run](https://cover.run/), [gocover](http://gocover.io/), [coveralls](https://coveralls.io/) etc.), example: https://cover.run/go?tag=golang-1.10&repo=https%3A%2Fgithub.com%2Fgoogle%2Fgnxi)
[![cover.run](https://cover.run/go/https:/github.com/google/gnxi.svg?style=flat&tag=golang-1.10)](https://cover.run/go?tag=golang-1.10&repo=https%3A%2Fgithub. …

added gNxI

---

README.md

- github.com repo: https://github.com/miracl/conflate
- godoc.org: https://godoc.org/github.com/miracl/conflate
- goreportcard.com: https://goreportcard.com/report/github.com/miracl/conflate
- coverage service link : https://coveralls.io/github/miracl/conflate?branch=master
[![Build Status](https://secure.travis-ci.org/miracl/conflate.png?branch=master)](https://travis-ci.org/miracl/conflate?branch=master)
[![Coverage Status](https://coveralls.io/repos/miracl/conflate/badge.svg?branch=master&service=github)](https://coveralls.io/github/miracl/conflate? …

Add conflate config library/tool

---

README.md

- github.com repo: [github.com/auyer/steganography](https://github.com/auyer/steganography)
- godoc.org: [![GoDoc](https://godoc.org/github.com/golang/gddo?status.svg)](http://godoc.org/github.com/auyer/steganography) 
- goreportcard.com:  [![Go Report Card](https://goreportcard.com/badge/github.com/auyer/steganography)](https://goreportcard.com/report/github.com/auyer/steganography)
- coverage service link [![cover.run](https://cover.run/go/github.com/auyer/steganography.svg?style=flat&tag=golang-1.10)](https://cover.run/go?tag=golang-1.10&repo=github.com%2Fauyer%2Fsteganography) + [GoCover.io](https://gocover.io/github.com/auyer/steganography)
Thanks for Awesome-Go, you guys are …

Added LSB Steganography Library

---

README.md

- github.com repo: [bhmj/jsonslice](https://www.github.com/bhmj/jsonslice)
- godoc.org: [https://godoc.org/github.com/bhmj/jsonslice](https://godoc.org/github.com/bhmj/jsonslice)
- goreportcard.com: [![Go Report Card](https://goreportcard.com/badge/github.com/bhmj/jsonslice)](https://goreportcard.com/report/github.com/bhmj/jsonslice)
- coverage service link [![cover.run](https://cover.run/go/github.com/bhmj/jsonslice.svg?style=flat&tag=golang-1.10)](https://cover.run/go?tag=golang-1.10&repo=github.com%2Fbhmj%2Fjsonslice)
**Note**: …

Add jsonslice

---

README.md

Monad, Functional Programming features for Golang
https://github.com/TeaEntityLab/fpGo
https://godoc.org/github.com/TeaEntityLab/fpGo
https://goreportcard.com/report/github.com/TeaEntityLab/fpGo
[![cover.run](https://cover.run/go/github.com/TeaEntityLab/fpGo.svg?style=flat&tag=golang-1.8)](https://cover.run/go?tag=golang-1.8&repo=github.com%2FTeaEntityLab%2FfpGo)

Add fpGo record

---

README.md

- github.com repo: https://github.com/OGFris/GoStats/
- godoc.org: https://godoc.org/github.com/OGFris/GoStats
- goreportcard.com: https://goreportcard.com/report/github.com/OGFris/GoStats
- coverage service link: [![cover.run](https://cover.run/go/github.com/OGFris/GoStats.svg?style=flat&tag=golang-1.10)](https://cover.run/go?tag=golang-1.10&repo=github.com%2FOGFris%2FGoStats)

Added GoStats

---

README.md

- github.com repo: https://github.com/gookit/config
- godoc.org: https://godoc.org/github.com/gookit/config
- goreportcard.com: [![Go Report Card](https://goreportcard.com/badge/github.com/gookit/config)](https://goreportcard.com/report/github.com/gookit/config)
- coverage service link: [![Coverage Status](https://coveralls.io/repos/github/gookit/config/badge.svg?branch=master)](https://coveralls.io/github/gookit/config?branch=master) …

Add gookit/config

---

README.md

- github.com repo: https://github.com/percolate/retry
- godoc.org: https://godoc.org/github.com/percolate/retry
- goreportcard.com: https://goreportcard.com/report/github.com/percolate/retry
- coverage service link: [![cover.run](https://cover.run/go/github.com/percolate/retry.svg?style=flat&tag=golang-1.10)](https://cover.run/go?tag=golang-1.10&repo=github.com%2Fpercolate%2Fretry) …

Add percolate/retry

---

README.md

I just released flaggy to the world yesterday.  Please add it to aewsome-go!
- github.com repo: github.com/integrii/flaggy
- godoc.org: [![](https://godoc.org/github.com/integrii/flaggy?status.svg)](http://godoc.org/github.com/integrii/flaggy)
- goreportcard.com: [![Go Report Card](https://goreportcard.com/badge/github.com/integrii/flaggy)](https://goreportcard.com/report/github.com/integrii/flaggy)
- coverage service link: [![cover.run](https://cover.run/go/github.com/integrii/flaggy.svg?style=flat&tag=golang-1.10)](https://cover.run/go?tag=golang-1.10&repo=github.com%2Fintegrii%2Fflaggy)
- [ x ] I have added my package in alphabetical …

Add flaggy

---

README.md

- github.com repo: https://github.com/topfreegames/pitaya
- godoc.org: https://godoc.org/github.com/topfreegames/pitaya
- goreportcard.com: https://goreportcard.com/report/github.com/topfreegames/pitaya
- coverage service link: https://coveralls.io/github/topfreegames/pitaya?branch=master

Added topfreegames/pitaya - Scalable game server framework

---

README.md

- github.com repo: https://github.com/hako/branca
- godoc.org: https://godoc.org/github.com/hako/branca
- goreportcard.com: [![Go Report Card](https://goreportcard.com/badge/github.com/hako/branca)](https://goreportcard.com/report/github.com/hako/branca)
- coverage service link ![cover.run go](https://cover.run/go/github.com/hako/branca.svg?style=flat&tag=golang-1.10)

add branca

---

README.md

Please consider adding  Dataflow kit to awesome-go list. 
- github.com repo: https://github.com/slotix/dataflowkit
- godoc.org: https://godoc.org/github.com/slotix/dataflowkit
- goreportcard.com: https://goreportcard.com/report/github.com/slotix/dataflowkit
[![codecov](https://codecov.io/gh/slotix/dataflowkit/branch/master/graph/badge.svg)](https://codecov.io/gh/slotix/dataflowkit)

Add Dataflow kit

---

README.md

- github.com repo: https://github.com/shettyh/threadpool
- godoc.org: https://godoc.org/github.com/shettyh/threadpool
- goreportcard.com: https://goreportcard.com/report/github.com/shettyh/threadpool
- coverage service link ([cover.run](https://cover.run/), [gocover](http://gocover.io/), [coveralls](https://coveralls.io/) etc.), example: `![cover.run go](https://cover.run/go/github.com/user/repository.svg)` https://codecov.io/gh/shettyh/threadpool …

Added thread pool library

---

README.md

- github.com repo: https://github.com/golang/vgo
- godoc.org: https://godoc.org/golang.org/x/vgo
- goreportcard.com: https://goreportcard.com/report/golang.org/x/vgo
Thanks …

Adding VGo and separating non-official package managers

---

README.md

- github.com repo: https://github.com/gortc/sdp
- godoc.org: https://godoc.org/github.com/gortc/sdp
- goreportcard.com: [![Go Report Card](https://goreportcard.com/badge/github.com/gortc/sdp)](https://goreportcard.com/report/github.com/gortc/sdp)
- coverage service link: [![codecov](https://codecov.io/gh/gortc/sdp/branch/master/graph/badge.svg)](https://codecov.io/gh/gortc/sdp) …

add gortc/sdp

---

README.md

- github.com repo: https://github.com/ozgio/strutil
- godoc.org: https://godoc.org/github.com/ozgio/strutil
- goreportcard.com: https://goreportcard.com/report/github.com/ozgio/strutil
- coverage service link: https://cover.run/go?tag=golang-1.10&repo=github.com%2Fozgio%2Fstrutil

Add strutil

---

README.md

https://github.com/Parquery/gocontracts
https://coveralls.io/github/Parquery/gocontracts?branch=master
https://goreportcard.com/report/github.com/Parquery/gocontracts
https://godoc.org/github.com/Parquery/gocontracts/gocontracts

added gocontracts to go generate tools

---

README.md

- github.com repo: https://github.com/alwindoss/morse
- godoc.org: https://godoc.org/github.com/alwindoss/morse
- goreportcard.com: https://goreportcard.com/report/github.com/alwindoss/morse
- coverage service link [![codecov](https://codecov.io/gh/alwindoss/morse/branch/master/graph/badge.svg)](https://codecov.io/gh/alwindoss/morse)

Added Library to convert to and from morse code

---

README.md

- github.com repo: https://github.com/gookit/color
- godoc.org: https://godoc.org/github.com/gookit/color
- goreportcard.com: [![Go Report Card](https://goreportcard.com/badge/github.com/gookit/color)](https://goreportcard.com/report/github.com/gookit/color)
- coverage service link: [![Coverage Status](https://coveralls.io/repos/github/gookit/color/badge.svg?branch=master)](https://coveralls.io/github/gookit/color?branch=master) …

add gookit/color

---

README.md

- github.com repo: https://github.com/dannyvankooten/extemplate
- godoc.org: https://godoc.org/github.com/dannyvankooten/extemplate
- goreportcard.com: https://goreportcard.com/report/github.com/dannyvankooten/extemplate
- coverage service link: https://gocover.io/github.com/dannyvankooten/extemplate (91%)

add dannyvankooten/extemplate, replaces dannyvankooten/grender

---

README.md

Fixed URL for Selenoid (moved to Aerokube organization)

---

README.md

- github.com repo: [pdfcpu](https://github.com/hhrutter/pdfcpu)
- [godoc.org](https://godoc.org/github.com/hhrutter/pdfcpu)
- [goreportcard.com](https://goreportcard.com/report/github.com/hhrutter/pdfcpu)
- [coverage service link](https://coveralls.io/github/hhrutter/pdfcpu?branch=master)
-  [x] I have an appropriate description with correct grammar. …

Added entry for pdfcpu (#2105)

---

README.md

- github.com repo: https://github.com/hyfather/pipeline
- godoc.org: https://godoc.org/github.com/hyfather/pipeline
- goreportcard.com: https://goreportcard.com/report/github.com/hyfather/pipeline
- coverage service link: https://cover.run/go?repo=github.com%2Fhyfather%2Fpipeline&tag=golang-1.10

Add pipeline

---

README.md

fix yakvs link

---

README.md

Add GoWayFest & GoDays

---

README.md

- github.com repo: https://github.com/centerorbit/depcharge
- godoc.org: https://godoc.org/github.com/centerorbit/depcharge
- goreportcard.com: https://goreportcard.com/report/github.com/centerorbit/depcharge
- coverage service link: https://gitlab.com/centerorbit/depcharge/pipelines
[![pipeline status](https://gitlab.com/centerorbit/depcharge/badges/master/pipeline.svg)](https://gitlab.com/centerorbit/depcharge/commits/master)
[![coverage report](https://gitlab.com/centerorbit/depcharge/badges/master/coverage.svg)](https://gitlab.com/centerorbit/depch …

Adding depcharge to devops list

---

README.md

- github.com repo: https://github.com/fyne-io/fyne
- godoc.org: https://godoc.org/github.com/fyne-io/fyne
- goreportcard.com: https://goreportcard.com/report/github.com/fyne-io/fyne
- coverage service link: [coveralls](https://coveralls.io/github/fyne-io/fyne)
- [✓] I have added my package in alphabetical order.
- [✓] I have an appropriate description with correct grammar.
- [✓] I …

Add Fyne to GUI list

---

README.md

- github.com repo:  https://github.com/gotestyourself/gotest.tools
- godoc.org: https://godoc.org/gotest.tools
- goreportcard.com: https://goreportcard.com/report/gotest.tools
- coverage service link https://codecov.io/gh/gotestyourself/gotest.tools

Add gotest.tools

---

README.md

- github.com repo: https://github.com/philippgille/ln-paywall
- godoc.org: https://www.godoc.org/github.com/philippgille/ln-paywall, major package is https://www.godoc.org/github.com/philippgille/ln-paywall/wall
- goreportcard.com: https://goreportcard.com/report/github.com/philippgille/ln-paywall
- coverage service link: /
---
I see I don't have any coverage yet, and no real tests either, but I'd like to talk about this. I could add some tests for the storage implementations in …

Add ln-paywall

---

README.md

- github.com repo: https://github.com/pupizoid/ormlite
- godoc.org: https://godoc.org/github.com/pupizoid/ormlite
- goreportcard.com: https://goreportcard.com/report/github.com/pupizoid/ormlite
- coverage service link: https://gocover.io/github.com/pupizoid/ormlite

Add ormlite

---

README.md

- github.com repo: https://github.com/esurdam/go-sophos
- godoc.org: https://godoc.org/github.com/esurdam/go-sophos
- goreportcard.com: https://goreportcard.com/report/github.com/esurdam/go-sophos
- coverage service link: [![codecov](https://codecov.io/gh/esurdam/go-sophos/branch/master/graph/badge.svg)](https://codecov.io/gh/esurdam/go-sophos)
You're awesome! :+1:

Add go-sophos

---

README.md

- github.com repo: https://github.com/antchfx/htmlquery
- godoc.org: https://godoc.org/github.com/antchfx/htmlquery
- goreportcard.com: https://goreportcard.com/report/github.com/antchfx/htmlquery
- coverage service link [![Coverage Status](https://coveralls.io/repos/github/antchfx/htmlquery/badge.svg?branch=master)](https://coveralls.io/github/antchfx/htmlquery?branch=master) …

Add htmlquery

---

README.md

go-pinyin:
- github.com repo: https://github.com/mozillazg/go-pinyin
- godoc.org: https://godoc.org/github.com/mozillazg/go-pinyin
- goreportcard.com: https://goreportcard.com/report/github.com/mozillazg/go-pinyin
- coverage service link: [![Coverage Status](https://coveralls.io/repos/github/mozillazg/go-pinyin/badge.svg?branch=master)](https://coveralls.io/github/mozillazg/go-pinyin?branch=master)
kagome:
- github.com repo: https://github.com/ikawaha/kagome
- godoc.org: https://godoc.org/github.com/ikawaha/kagome …

NLP libraries in Chinese, Japanese

---

README.md

- github.com repo: https://github.com/CovenantSQL/CovenantSQL
- godoc.org: https://godoc.org/github.com/CovenantSQL/CovenantSQL
- goreportcard.com: https://goreportcard.com/report/github.com/CovenantSQL/CovenantSQL
- coverage service link [![Coverage](https://codecov.io/gh/CovenantSQL/CovenantSQL/branch/develop/graph/badge.svg)](https://codecov.io/gh/CovenantSQL/CovenantSQL) …

add CovenantSQL

---

README.md

add golangch twitter

---

README.md

- github.com repo: https://github.com/go-furnace/go-furnace
- godoc.org: https://godoc.org/github.com/go-furnace/go-furnace
- goreportcard.com: https://goreportcard.com/report/github.com/go-furnace/go-furnace
- coverage service link [![Coverage Status](https://coveralls.io/repos/github/go-furnace/go-furnace/badge.svg?branch=master)](https://coveralls.io/github/go-furnace/go-furnace?branch=master) …

Added furnace to awesome-go

---

README.md

- github.com repo: https://github.com/adrg/libvlc-go
- godoc.org: https://godoc.org/github.com/adrg/libvlc-go
- goreportcard.com: https://goreportcard.com/report/github.com/adrg/libvlc-go
- coverage service link: It is very difficult to write tests for this library because it requires an external, compiled C library and also relates to video playback. …

Add libvlc-go

---

README.md

- github.com repo: https://github.com/GuilhermeCaruso/Kair
- godoc.org: https://godoc.org/github.com/GuilhermeCaruso/Kair
- goreportcard.com: https://goreportcard.com/report/github.com/GuilhermeCaruso/Kair
- coverage service link :  [![cover.run](https://cover.run/go/github.com/GuilhermeCaruso/Kair.svg?style=flat&tag=golang-1.10)](https://cover.run/go?tag=golang-1.10&repo=github.com%2FGuilhermeCaruso%2FKair) r …

Kair - Time and Date Lib - Insert

---

README.md

- github.com repo: https://github.com/yitsushi/go-commander
- godoc.org: https://godoc.org/github.com/yitsushi/go-commander
- goreportcard.com: [![Go Report Card](https://goreportcard.com/badge/github.com/yitsushi/go-commander)](https://goreportcard.com/report/github.com/yitsushi/go-commander)
- coverage: [![Coverage Status](https://coveralls.io/repos/github/yitsushi/go-commander/badge.svg)](https://coveralls.io/github/yitsushi/go-commander)
**Make …

Add go-commander

---

README.md

- github.com repo: https://github.com/StudioSol/async
- godoc.org: https://godoc.org/github.com/StudioSol/async
- goreportcard.com: https://goreportcard.com/report/github.com/StudioSol/async
- coverage: [![codecov](https://codecov.io/gh/StudioSol/async/branch/master/graph/badge.svg)](https://codecov.io/gh/StudioSol/async)

Include StudioSol/async

---

README.md

- github.com repo: https://github.com/StudioSol/set
- godoc.org: https://godoc.org/github.com/StudioSol/set
- goreportcard.com: https://goreportcard.com/report/github.com/StudioSol/set
- coverage: [![codecov](https://codecov.io/gh/StudioSol/set/branch/master/graph/badge.svg)](https://codecov.io/gh/StudioSol/set)

Include StudioSol/set

---

README.md

https://github.com/wit-ai/wit-go
https://godoc.org/github.com/wit-ai/wit-go
https://goreportcard.com/report/github.com/wit-ai/wit-go
https://travis-ci.org/wit-ai/wit-go

Add wit-go official wit.ai Go client

---

README.md

Add package main YouTube channel link

---

README.md

I changed my GitHub username a few weeks ago (from sheng to aofei), so I fixed the URLs of my repos.
https://github.com/sheng/air -> https://github.com/aofei/air
https://github.com/sheng/sandid -> https://github.com/aofei/sandid
https://github.com/sheng/cameron -> https://github.com/aofei/cameron

Fix repo URLs

---

README.md

Hi,
Mercure is a protocol allowing to push data updates to web browsers and other HTTP clients. It is especially useful to publish real-time updates of resources served through web APIs, to reactive web and mobile apps.
The reference implementation is written in Go, and also contains a standalone library.
Package links:
- github.com repo: https://github.com/dunglas/mercure
- godoc.org: https://godoc.org/github.com/dunglas/mercure/hub
- goreportcard.com: https://goreportcard.com/report/github.com/dunglas/mercure
- coverage service link: https://coveralls.io/github/dunglas/mercure?branch=master

Add the Mercure

---

README.md

- github.com repo:    https://github.com/zhulongcheng/testsql
- godoc.org:     [![GoDoc](https://godoc.org/github.com/zhulongcheng/testsql?status.svg)](https://godoc.org/github.com/zhulongcheng/testsql)
- goreportcard.com:     [![Go Report Card](https://goreportcard.com/badge/github.com/zhulongcheng/testsql)](https://goreportcard.com/report/github.com/zhulongcheng/testsql)
- coverage service link:    [![codecov.io](https://codecov.io/github/zhulongcheng/testsql/branch/master/graph/badge.svg)](https://codecov.io/github/zhulongcheng/testsql) 
Very good …

Add package testsql

---

README.md

- github.com repo: https://github.com/sideshow/apns2
- godoc.org: https://godoc.org/github.com/sideshow/apns2
- goreportcard.com: https://goreportcard.com/report/github.com/sideshow/apns2
- coverage service link: https://coveralls.io/github/sideshow/apns2?branch=master

Add APNs2 HTTP/2 Apple Push Notification library

---

README.md

- github.com repo: https://github.com/xujiajun/gotokenizer
- godoc.org: https://godoc.org/github.com/xujiajun/gotokenizer
- goreportcard.com: https://goreportcard.com/report/github.com/xujiajun/gotokenizer
- coverage service link: https://coveralls.io/github/xujiajun/gotokenizer?branch=master
- [✔️ ] I have added my package in alphabetical order.
- [✔️ ] I have an appropriate …

add  https://github.com/xujiajun/gotokenizer  library

---

README.md

Closes #2175
No tests, latest commit Oct 31, 2016.

Remove blogcin/ToTo

---

README.md

- github.com repo: https://github.com/gookit/filter
- godoc.org: https://godoc.org/github.com/gookit/filter
- goreportcard.com: [![Go Report Card](https://goreportcard.com/badge/github.com/gookit/filter)](https://goreportcard.com/report/github.com/gookit/filter)
- coverage service link [![Coverage Status](https://coveralls.io/repos/github/gookit/filter/badge.svg?branch=master)](https://coveralls.io/github/gookit/filter?branch=master) …

add package filter

---

README.md

- github.com repo: https://github.com/hugocarreira/go-decent-copy
- godoc.org: [![GoDoc](https://godoc.org/github.com/hugocarreira/go-decent-copy?status.svg)](https://godoc.org/github.com/hugocarreira/go-decent-copy)
- goreportcard.com: [![Go Report Card](https://goreportcard.com/badge/github.com/hugocarreira/go-decent-copy)](https://goreportcard.com/report/github.com/hugocarreira/go-decent-copy)
- coverage service link: [![codecov](https://codecov.io/gh/hugocarreira/go-decent-copy/branch/master/graph/badge.svg)](https://codecov.io/gh/hugocarreira/go-d …

Adding Go-Decent-Copy

---

README.md

Closes #2178
No tests, Latest commit 74f941f on Feb 27, 2017, issues abandoned

Remove zachlatta/postman

---

README.md

closes #2045 
No docs, no tests, no examples, even code is not formatted.

remove gostat

---

README.md

closes #2046 
No docs, no examples, no tests, no updates since 2015.

remove gofrac

---

README.md

- github.com repo: https://github.com/gookit/validate
- godoc.org: https://godoc.org/github.com/gookit/validate
- goreportcard.com: [![Go Report Card](https://goreportcard.com/badge/github.com/gookit/validate)](https://goreportcard.com/report/github.com/gookit/validate)
- coverage service link [![Coverage Status](https://coveralls.io/repos/github/gookit/validate/badge.svg?branch=master)](https://coveralls.io/github/gookit/validate?branch=master) …

add package validate

---

README.md

- github.com repo: https://github.com/zRedShift/mimemagic/
- godoc.org: [![GoDoc](https://godoc.org/github.com/zRedShift/mimemagic?status.svg)](https://godoc.org/github.com/zRedShift/mimemagic)
- goreportcard.com: [![Go Report Card](https://goreportcard.com/badge/github.com/zRedShift/mimemagic)](https://goreportcard.com/report/github.com/zRedShift/mimemagic)
- coverage service link: [![Codecov](https://codecov.io/gh/zRedShift/mimemagic/branch/master/graph/badge.svg)](https://codecov.io/gh/zRedShift/mimemagic/)
- build status: [![Build …

Add mimemagic to the list

---

README.md

- github.com repo: https://github.com/rocketlaunchr/dataframe-go
- godoc.org: http://godoc.org/github.com/rocketlaunchr/dataframe-go
- goreportcard.com: https://goreportcard.com/report/github.com/rocketlaunchr/dataframe-go
- coverage service link: https://cover.run/go?tag=golang-1.10&repo=github.com%2Frocketlaunchr%2Fdataframe-go
OR 
https://gocover.io/github.com/rocketlaunchr/dataframe-go …

added dataframe-go

---

README.md

- github.com repo: **None**
- godoc.org: **None**
- goreportcard.com: **None**
- coverage service link: **None**

Used shields.io for the slack badge in the README file. Fixes #1751.

---

README.md

- github.com repo: https://github.com/posener/ctxutil
- godoc.org: https://godoc.org/github.com/posener/ctxutil
- goreportcard.com: https://goreportcard.com/report/github.com/posener/ctxutil
- coverage service link: https://codecov.io/gh/posener/ctxutil

Add ctxutil

---

README.md

coverage service link : Code Coverage
- github.com repo:  https://github.com/two/tspool
- godoc.org: https://godoc.org/github.com/two/tspool
- goreportcard.com: https://goreportcard.com/report/github.com/two/tspool
- coverage service link   [![Code Coverage](https://codecov.io/gh/two/tspool/branch/master/graph/badge.svg)](https://codecov.io/gh/two/tspool) …

add tspool package

---

README.md

- github.com repo: N/A
- godoc.org: N/A
- [ x] I …

Add article: Canceling MySQL in Go

---

README.md

Go client library for interacting with Coinpaprika's API
#hactoberfest #coinpaprika
**Building link**: https://travis-ci.org/coinpaprika/coinpaprika-api-go-client
**Documentation**: https://godoc.org/github.com/coinpaprika/coinpaprika-api-go-client
**Reportcard**: https://goreportcard.com/report/github.com/coinpaprika/coinpaprika-api-go-client
- godoc.org:
- coverage service link ([cover.run](https://cover.run/), [gocover](http://gocover.io/), [coveralls](https://coveralls.io/) etc.), example: …

Coinpaprika.com api client in go

---

README.md

moved violetear from frameworks to routers

---

README.md

Publish Your GIS Data(Vector Data) to PostGIS and Geoserver
- github.com repo:https://github.com/hishamkaram/gismanager
- godoc.org: https://godoc.org/github.com/hishamkaram/gismanager
- goreportcard.com: https://goreportcard.com/report/github.com/hishamkaram/gismanager
- coverage service link: [![Coverage Status](https://coveralls.io/repos/github/hishamkaram/gismanager/badge.svg?branch=master&service=github)](https://coveralls.io/github/hishamkaram/gismanager?branch=master&service=github)

add gismanager

---

README.md

- github.com repo: https://github.com/borderstech/artifex
- godoc.org: http://godoc.org/github.com/borderstech/artifex
- goreportcard.com: https://goreportcard.com/report/github.com/borderstech/artifex
- coverage service link: https://codecov.io/gh/borderstech/artifex

Add artifex

---

README.md

- github.com repo: https://github.com/qeesung/image2ascii
- godoc.org: https://godoc.org/github.com/qeesung/image2ascii
- goreportcard.com: https://goreportcard.com/report/github.com/qeesung/image2ascii
- coverage service link: https://coveralls.io/github/qeesung/image2ascii?branch=master

Add image2ascii

---

README.md

- github.com repo: https://mholt.github.io/json-to-go/
- [ x] I have an appropriate description with correct grammar.
- [ x] I know that this package was not listed before.
- [ x] I have added godoc link to the repo and to my pull request.
- [ x] I have added coverage service link to the repo and to my pull request.
- [ x] I …

Added JSON-to-Go under Go Tools

---

README.md

Go Playground for iPhone / iPad. It's free and comes with truckload of samples.

Add Go Playground for iOS

---

README.md

No docs, no examples, no tests as stated in #2043

Remove blas

---

README.md

No documentation
https://godoc.org/github.com/hoisie/redis
Bad goreportcard
https://goreportcard.com/report/github.com/hoisie/redis
Definitely not awesome.

Remove hoisie/redis

---

README.md

- github.com repo: https://github.com/edwingeng/doublejump
- godoc.org: https://godoc.org/github.com/edwingeng/doublejump
- goreportcard.com: https://goreportcard.com/report/github.com/edwingeng/doublejump
- coverage service link: It seems cover.run does not support go 1.11. Here is the coverage result:
```
$ go test -v -cover
=== RUN   TestHash_Basic
--- PASS: TestHash_Basic (0.06s)
=== RUN   TestHash_Add
--- PASS: TestHash_Add (0.00s)
=== RUN   TestHash_Get
--- PASS: TestHash_Get (0.00s)
=== RUN   TestHash_LooseLen
--- PASS: TestHash_LooseLen …
```

add doublejump

---

README.md

- github.com repo: https://github.com/rkoesters/xdg
- godoc.org: https://godoc.org/github.com/rkoesters/xdg
- goreportcard.com: https://goreportcard.com/report/github.com/rkoesters/xdg
- coverage service link: https://travis-ci.org/rkoesters/xdg (recommended services won't work because tests for `trash` require initialization (creation of trash directory) and `userdirs` depends on `xdg-user-dirs` package. See https://github.com/rkoesters/xdg#testing for more info) …

Add github.com/rkoesters/xdg

---

README.md

- github.com repo: https://github.com/quangngotan95/go-m3u8
- godoc.org: https://godoc.org/github.com/quangngotan95/go-m3u8/m3u8
- goreportcard.com: https://goreportcard.com/report/github.com/quangngotan95/go-m3u8
- coverage service link: https://codecov.io/gh/quangngotan95/go-m3u8

Add go-m3u8 under Video

---

README.md

Leprechaun is tool where you can schedule your recurring tasks to be performed over and over. It supports cron, webhooks and classic job scheduling
- github.com repo: [here](https://github.com/kilgaloon/leprechaun)
- godoc.org: [here](https://godoc.org/github.com/kilgaloon/leprechaun)
- goreportcard.com: [here](https://goreportcard.com/report/github.com/Kilgaloon/Leprechaun)
- coverage service link [![codecov](https://codecov.io/gh/Kilgaloon/Leprechaun/branch/master/graph/badge.svg)](https://codecov.io/gh/Kilgaloon/Leprechaun)

Add Leprechaun

---

README.md

Add package fuego and created new category *Functional* for similar packages.
Many thanks and regards!
- github.com repo: https://github.com/seborama/fuego
- godoc.org: https://godoc.org/github.com/seborama/fuego
- goreportcard.com: https://goreportcard.com/report/github.com/seborama/fuego
- coverage service link ([cover.run](https://cover.run/), [gocover](http://gocover.io/), [coveralls](https://coveralls.io/) etc.), [![cover.run](https://cover.run/go/github.com/seborama/fuego.svg?style=flat&tag=golang-1.10)](https://cover.run/go?tag=golang-1.11&repo= …

[fuego] Add fuego

---

README.md

Remove Florest, no longer exist

---

README.md

**Provide package links**
- github.com repo: https://github.com/knocknote/octillery
- godoc.org: https://godoc.org/go.knocknote.io/octillery
- goreportcard.com: https://goreportcard.com/report/go.knocknote.io/octillery
- coverage service link: [![codecov](https://codecov.io/gh/knocknote/octillery/branch/master/graph/badge.svg?token=hRKqugQMsg)](https://codecov.io/gh/knocknote/octillery)
**I checked the following items**

Add Octillery

---

README.md

* No PR reviews
* last Commits on Mar 28, 2017

Remove https://github.com/mgutz/dat

---

README.md

` github.com/imdario/medeina` is archived. Should we remove it?

Deprecate github.com/imdario/medeina

---

README.md

* Commits on Aug 15, 2017
* PR No reviews

Remove https://github.com/bmizerany/pat

---

README.md

fix project link

---

README.md

I have added mvn-golang into Package Management section because the tool provides way to load project dependencies automatically and tune them through external CVS tools (tune for branch, revision and tag)
- godoc.org:
- coverage service link ([cover.run](https://cover.run/), [gocover](http://gocover.io/), [coveralls](https://coveralls.io/) etc.), example: `[![cover.run](https://cover.run/go/github.com/user/repository.svg?style=flat&tag=golang-1.10)](https://cover.run/go?tag=golang-1.10&repo=github.com%2Fuser%2Fre …

added mvn-golang into Package Management section

---

README.md

- github.com repo: https://github.com/aofei/mimesniffer
- godoc.org: 
https://godoc.org/github.com/aofei/mimesniffer
https://goreportcard.com/report/github.com/aofei/mimesniffer
- coverage service link ([cover.run](https://cover.run/), [gocover](http://gocover.io/), [coveralls](https://coveralls.io/) etc.): [![Coverage Status](https://coveralls.io/repos/github/aofei/mimesniffer/badge.svg?branch=master)](https://coveralls.io/github/aofei/mimesniffer?branch=master)

Add MIMESniffer

---

README.md

- https://github.com/khezen/jwc
- https://godoc.org/github.com/khezen/jwc
- https://goreportcard.com/report/github.com/khezen/jwc
- https://codecov.io/gh/khezen/jwc

add khezen/jwc

---

README.md

- https://github.com/khezen/evoli
- https://godoc.org/github.com/khezen/evoli
- https://goreportcard.com/report/github.com/khezen/evoli
- https://codecov.io/gh/khezen/evoli

Add khezen/evoli

---

README.md

- github.com repo: https://github.com/rhnvrm/simples3
- godoc.org: https://godoc.org/github.com/rhnvrm/simples3
- goreportcard.com: https://goreportcard.com/report/github.com/rhnvrm/simples3
- coverage service link [![GoCover](https://gocover.io/_badge/github.com/rhnvrm/simples3)](https://gocover.io/_badge/github.com/rhnvrm/simples3)

Add simples3

---

README.md

- github.com repo: https://github.com/sj14/dbbench
- godoc.org: https://godoc.org/github.com/sj14/dbbench
- goreportcard.com: https://goreportcard.com/report/github.com/sj14/dbbench
- coverage service link: https://coveralls.io/github/sj14/dbbench?branch=master

Add dbbench

---

README.md

- https://github.com/khezen/rootfinding
- https://godoc.org/github.com/khezen/rootfinding
- https://goreportcard.com/report/github.com/khezen/rootfinding
- https://codecov.io/gh/khezen/rootfinding

Add khezen/rootfinding

---

README.md

- github.com repo: [gostrutils](https://github.com/ik5/gostrutils)
- godoc.org: [![GoDoc](https://godoc.org/github.com/ik5/gostrutils?status.svg)](https://godoc.org/github.com/ik5/gostrutils)
- goreportcard.com: [![Go Report Card](https://goreportcard.com/badge/github.com/ik5/gostrutils)](https://goreportcard.com/report/github.com/ik5/gostrutils)
- coverage service link: [![Coverage Status](https://coveralls.io/repos/github/ik5/gostrutils/badge.svg?branch=master)](https://coveralls.io/github/ik5/gostrutils?branch=master)
**Note**: that new categories …

added my gostrutils collection

---

README.md

I have all the required links for doc, coverage, Golang report, ... etc in the top of README.md as badges with links to their sources.
- github.com repo: [Github Repo](https://github.com/uadmin/uadmin)
- godoc.org: [Godocs](https://godoc.org/github.com/uadmin/uadmin)
- goreportcard.com: [Go Report](https://goreportcard.com/report/github.com/uadmin/uadmin)
- coverage service link: [Codecov](https://codecov.io/gh/uadmin/uadmin) …

Add uAdmin to web frameworks

---

README.md

- github.com repo: https://github.com/pions/webrtc
- godoc.org: https://godoc.org/github.com/pions/webrtc
- goreportcard.com: https://goreportcard.com/report/github.com/pions/webrtc
- coverage service: [![coveralls](https://coveralls.io/repos/github/pions/webrtc/badge.svg)](https://coveralls.io/github/pions/webrtc)

Add pion-WebRTC

---

README.md

- github.com repo: https://github.com/ucirello/pglock (https://cirello.io/pglock)
- godoc.org: http://godoc.org/cirello.io/pglock
- goreportcard.com: https://goreportcard.com/report/github.com/ucirello/pglock
- coverage service link: https://coveralls.io/github/ucirello/pglock?branch=master

Add cirello.io/pglock

---

README.md

- github.com repo: https://github.com/wzshiming/gotype
- godoc.org: [![GoDoc](https://godoc.org/github.com/wzshiming/gotype?status.svg)](https://godoc.org/github.com/wzshiming/gotype)
- goreportcard.com: [![Go Report Card](https://goreportcard.com/badge/github.com/wzshiming/gotype)](https://goreportcard.com/report/github.com/wzshiming/gotype)
- coverage service link : [![cover.run](https://cover.run/go/github.com/wzshiming/gotype.svg?style=flat&tag=golang-1.10)](https://cover.run/go?tag=golang-1.10&repo=github.com%2Fwzshiming%2Fgotype)
Very good …

Add wzshiming/gotype

---

README.md

- github.com repo: https://github.com/btnguyen2k/olaf
- godoc.org: https://godoc.org/github.com/btnguyen2k/olaf
- goreportcard.com: https://goreportcard.com/report/github.com/btnguyen2k/olaf
- coverage service link ([cover.run](https://cover.run/), [gocover](http://gocover.io/), [coveralls](https://coveralls.io/) etc.): https://cover.run/go?repo=github.com%2Fbtnguyen2k%2Folaf&tag=golang-1.10 …

Add package btnguyen2k/olaf

---

README.md

Done
- github.com repo: https://github.com/saniales/golang-crypto-trading-bot
- godoc.org: https://godoc.org/github.com/saniales/golang-crypto-trading-bot
- goreportcard.com: https://goreportcard.com/report/github.com/saniales/golang-crypto-trading-bot
- coverage service link : https://travis-ci.org/saniales/golang-crypto-trading-bot

Added Golang Crypto Trading Bot to "other software section"

---

README.md

Add go-rejson to go-awesome list under the NoSQL Databases, as an
alternate way to use redis to store and manipulate Go structs as JSON
objects using Redislab Rejson module.
- github.com repo: https://github.com/nitishm/go-rejson
- godoc.org: https://godoc.org/github.com/nitishm/go-rejson
- goreportcard.com: https://goreportcard.com/report/github.com/nitishm/go-rejson
- coverage service: https://coveralls.io/github/nitishm/go-rejson?branch=master …

Add go-rejson to the list

---

README.md

- github.com repo: https://github.com/leaanthony/slicer
- godoc.org: [![GoDoc](https://img.shields.io/badge/godoc-reference-blue.svg)](http://godoc.org/github.com/leaanthony/slicer)
- goreportcard.com: [![Go Report Card](https://goreportcard.com/badge/github.com/leaanthony/slicer)](https://goreportcard.com/report/github.com/leaanthony/slicer) 
- coverage service link: [![CodeFactor](https://www.codefactor.io/repository/github/leaanthony/slicer/badge)](https://www.codefactor.io/repository/github/leaanthony/slicer) …

Add Slicer

---

README.md

- github.com repo: https://github.com/ucirello/oversight ( https://cirello.io/oversight )
- godoc.org: https://godoc.org/cirello.io/oversight
- goreportcard.com: https://goreportcard.com/report/github.com/ucirello/oversight
- coverage service link: https://gocover.io/cirello.io/oversight

Add cirello.io/oversight

---

README.md

- github.com repo: https://github.com/Fs02/wire
- godoc.org: https://godoc.org/github.com/Fs02/wire
- goreportcard.com: https://goreportcard.com/report/github.com/Fs02/wire
- coverage: [![cover.run](https://cover.run/go/github.com/Fs02/wire.svg?style=flat&tag=golang-1.10)](https://cover.run/go?tag=golang-1.10&repo=github.com%2FFs02%2Fwire)

add https://github.com/Fs02/wire

---

README.md

- github.com repo: https://github.com/DimitarPetrov/stegify
- godoc.org: https://godoc.org/github.com/DimitarPetrov/stegify
- goreportcard.com: https://goreportcard.com/report/github.com/DimitarPetrov/stegify …

Add stegify (https://github.com/DimitarPetrov/stegify)

---

README.md

- github.com repo: https://github.com/boyter/scc
- godoc.org: https://godoc.org/github.com/boyter/scc
- goreportcard.com: https://goreportcard.com/report/github.com/boyter/scc
- coverage service link: https://coveralls.io/github/boyter/scc?branch=master

Add Sloc Cloc and Code to other software section of Awesome Go

---

README.md

Break misc and utilities into other categories

---

README.md

- github.com repo: https://github.com/PaesslerAG/gval
- godoc.org: https://godoc.org/github.com/PaesslerAG/gval
- goreportcard.com: https://goreportcard.com/report/github.com/PaesslerAG/gval
- coverage service link: https://coveralls.io/github/PaesslerAG/gval?branch=master

Added gval to Embeddable Scripting Languages

---

README.md

This PR adds [glo](https://github.com/lajosbencz/glo) to the Loggers category.
The library was inspired by PHP's Monolog package, severity levels are identical.
- github.com repo: [github.com/lajosbencz/glo](https://github.com/lajosbencz/glo)
- godoc.org: [![GoDoc](https://godoc.org/github.com/lajosbencz/glo?status.svg)](https://godoc.org/github.com/lajosbencz/glo)
- goreportcard.com: [![Go Report Card](https://goreportcard.com/badge/github.com/lajosbencz/glo)](https://goreportcard.com/report/github.com/lajosbencz/glo)
- coverage service link [![codecov](https://codecov.io/gh/lajosbencz/glo/branch/master/graph/badge.svg)](https://codecov.io/gh/lajosbencz/glo)
Thanks for your curated list, you're awesome! :+1:

Add glo to Loggers

---

README.md

goconcurrentqueue is a (concurrent safe) FIFO queue.
- github.com repo: https://github.com/enriquebris/goconcurrentqueue
- godoc.org: [![godoc reference](https://img.shields.io/badge/godoc-reference-blue.svg)](https://godoc.org/github.com/enriquebris/goconcurrentqueue)
- goreportcard.com: [![Go Report Card](https://goreportcard.com/badge/github.com/enriquebris/goconcurrentqueue)](https://goreportcard.com/report/github.com/enriquebris/goconcurrentqueue)
- coverage service link: [![codecov](https://codecov.io/gh/enriquebris/goconcurrentqueue/branch/master/graph/badge.svg)](https://codecov.io/gh/enriquebris/goconcurrentqueue)
- compatible with go 1.9.x, 1.10.x, 1.11.x: [![Build Status](https://api.travis-ci.org/enriquebris/goconcurrentqueue.svg?branch=master)](https://travis-ci.org/enriquebri …

Add goconcurrentqueue to Data Structures

---

README.md

add tutorials

---

README.md

This PR adds [gokv](https://github.com/philippgille/gokv) to the list of database drivers. It's a simple key-value store abstraction and contains multiple implementations (Redis, Consul, etcd, bbolt, BadgerDB, LevelDB, Memcached, DynamoDB, S3, PostgreSQL, MongoDB, CockroachDB and many more).
- github.com repo: https://github.com/philippgille/gokv
- godoc.org: [![GoDoc](http://www.godoc.org/github.com/philippgille/gokv?status.svg)](http://www.godoc.org/github.com/philippgille/gokv)
- goreportcard.com: [![Go Report Card](https://goreportcard.com/badge/github.com/philippgille/gokv)](https://goreportcard.com/report/github.com/philippgille/gokv)
- coverage service link: [![codecov](https://codecov.io/gh/philippgille/gokv/branch/master/graph/badge.svg)](https://codecov.io/gh/philippgille/gokv) …

Add gokv to database drivers

---

README.md

Package ring provides a high performance and thread safe Go implementation of a bloom filter.
- github.com repo: https://github.com/TheTannerRyan/ring
- godoc.org: https://godoc.org/github.com/TheTannerRyan/ring
- goreportcard.com: https://goreportcard.com/report/github.com/thetannerryan/ring
- coverage service link: [![coveralls](https://coveralls.io/repos/github/TheTannerRyan/ring/badge.svg?branch=master)](https://coveralls.io/github/TheTannerRyan/ring?branch=master)
**Note**: that new categories can be added only when there are 3 …

Add thetannerryan/ring

---

README.md

Jump is a command-line tool that integrates into your shell and learns your habits, so you jump to your most visitted directories with short fuzzy input. It's around 5 years old, had 20 releases throughout the years and has around 560 GitHub stars currently.
It's available on homebrew and can be installed with `brew install jump`.
- github.com repo: https://github.com/gsamokovarov/jump
- godoc.org: https://godoc.org/github.com/gsamokovarov/jump
- goreportcard.com: https://goreportcard.com/report/github.com/gsamokovarov/jump
- coverage: The package uses Go 1.11 modules and a custom assertion package and the current gocover utilities cannot easily list it.
```
?   	github.com/gsamokovarov/jump	[no test files] # There is only a main.go here.
ok  	github.com/gsamokovarov/jump/cli	0.008s …
```

Add jump to Utilities

---

README.md

- github.com repo: [zhenghaoz/gorse](https://github.com/zhenghaoz/gorse)
- godoc.org: [![GoDoc](https://godoc.org/github.com/zhenghaoz/gorse?status.svg)](https://godoc.org/github.com/zhenghaoz/gorse)
- goreportcard.com: [![Go Report Card](https://goreportcard.com/badge/github.com/zhenghaoz/gorse)](https://goreportcard.com/report/github.com/zhenghaoz/gorse)
- coverage service link: [![codecov](https://codecov.io/gh/zhenghaoz/gorse/branch/master/graph/badge.svg)](https://codecov.io/gh/zhenghaoz/gorse)
**Note**: that new categories can …

Add zhenghaoz/gorse

---

README.md

github.com repo: https://github.com/blind-oracle/nginx-prometheus
godoc.org: https://godoc.org/github.com/blind-oracle/nginx-prometheus
goreportcard.com:https://goreportcard.com/report/github.com/blind-oracle/nginx-prometheus
coverage service link: https://cover.run/go?repo=github.com%2Fblind-oracle%2Fnginx-prometheus&tag=golang-1.10
- [*] I know that this package was not listed before.
- [*] I have added godoc link to the repo and to my pull request.
- [*] I have added coverage service link to the repo and to my pull request.
- [*] I have added goreportcard link to the repo and to my pull request.
- [*] I have read [Contribution …

Add nginx-prometheus to Server Applications

---

README.md

- github.com repo: https://github.com/edwingeng/deque
- godoc.org: https://godoc.org/github.com/edwingeng/deque
- goreportcard.com: https://goreportcard.com/report/github.com/edwingeng/deque
- coverage service link: [![cover.run](https://cover.run/go/github.com/edwingeng/deque.svg?style=flat&tag=golang-1.10)](https://cover.run/go?tag=golang-1.10&repo=github.com%2Fedwingeng%2Fdeque)
- [v] I have …

add github.com/edwingeng/deque

---

README.md

Adding a new Go community to the list of websites

---

README.md

Added library to read silk files.
Silk project website: https://tools.netsa.cert.org/silk/docs.html
Normally you need to use their C code to read silk files but this package allows reading them with native Go code.
- github.com repo: https://github.com/chrispassas/silk
- godoc.org: https://godoc.org/github.com/chrispassas/silk
- goreportcard.com: https://goreportcard.com/report/github.com/chrispassas/silk
- coverage service link [![cover.run](https://cover.run/go/github.com/chrispassas/silk.svg?style=flat&tag=golang-1.10)](https://cover.run/go?tag=gola …

added silk to utilities

---

README.md

- github.com repo: https://github.com/antham/ghokin
- godoc.org: https://godoc.org/github.com/antham/ghokin
- goreportcard.com: https://goreportcard.com/report/github.com/antham/ghokin
- coverage service link : https://codecov.io/gh/antham/ghokin

Add ghokin

---

README.md

- github.com repo: https://github.com/kinbiko/jsonassert
- godoc.org: https://godoc.org/github.com/kinbiko/jsonassert
- goreportcard.com: https://goreportcard.com/report/github.com/kinbiko/jsonassert
- coverage service link: https://coveralls.io/github/kinbiko/jsonassert

Add jsonassert testing package

---

README.md

Links:
- github.com repo: https://github.com/jfilipczyk/gomatch
- godoc.org: https://godoc.org/github.com/jfilipczyk/gomatch
- goreportcard.com: https://goreportcard.com/report/github.com/jfilipczyk/gomatch
- coverage service link: https://codecov.io/gh/jfilipczyk/gomatch

Add jfilipczyk/gomatch

---

README.md

remove go-type-assertion-benchmark

---

README.md

This is just a fix of the link to this repo. This is now maintained by me.

Fix broken link for conflate

---

README.md

- Github: https://github.com/pomerium/pomerium
- [![Travis CI](https://travis-ci.org/pomerium/pomerium.svg?branch=master)](https://travis-ci.org/pomerium/pomerium) 
- [![Go Report Card](https://goreportcard.com/badge/github.com/pomerium/pomerium)](https://goreportcard.com/report/github.com/pomerium/pomerium) 
- [![GoDoc](https://godoc.org/github.com/pomerium/pomerium?status.svg)](https://godoc.org/github.com/pomerium/pomerium)
- Additional docs: https://www.pomerium.io/
- [![codecov](https://codecov.io/gh/pomerium/pomerium/branch/master/graph/badge.svg)](https://codecov.io/gh/pomerium/pomerium)

add pomerium

---

README.md

- github.com repo: https://github.com/ztrue/tracerr
- godoc.org: [![GoDoc](https://godoc.org/github.com/ztrue/tracerr?status.svg)](https://godoc.org/github.com/ztrue/tracerr)
- goreportcard.com: [![Report](https://goreportcard.com/badge/github.com/ztrue/tracerr)](https://goreportcard.com/report/github.com/ztrue/tracerr)
- coverage service: [![Coverage Status](https://coveralls.io/repos/github/ztrue/tracerr/badge.svg?branch=master)](https://coveralls.io/github/ztrue/tracerr?branch=master)
**Note**: that new categories can be added …

Add github.com/ztrue/tracerr

---

README.md

- github.com repo: https://github.com/zekroTJA/timedmap
- godoc.org: <a href="https://godoc.org/github.com/zekroTJA/timedmap"><img src="https://godoc.org/github.com/zekroTJA/timedmap?status.svg" /></a>
- goreportcard.com: <a href="https://goreportcard.com/report/github.com/zekroTJA/timedmap"><img src="https://goreportcard.com/badge/github.com/zekroTJA/timedmap"/></a>
- coverage service link: <a href="https://coveralls.io/github/zekroTJA/timedmap"><img src="https://coveralls.io/repos/github/zekroTJA/timedmap/badge.svg" /></a>

add github.com/zekroTJA/timedmap

---

README.md

- github.com repo: https://github.com/italolelis/outboxer
- godoc.org: [![GoDoc](https://godoc.org/github.com/italolelis/outboxer?status.svg)](https://godoc.org/github.com/italolelis/outboxer)
- goreportcard.com: [![Go Report Card](https://goreportcard.com/badge/github.com/italolelis/outboxer)](https://goreportcard.com/report/github.com/italolelis/outboxer)
- coverage service link: [![Coverage Status](https://coveralls.io/repos/github/italolelis/outboxer/badge.svg?branch=master)](https://coveralls.io/github/italolelis/outboxer?branch=master)

Added italolelis/outboxer

---

README.md

- github.com repo: https://github.com/kamilsk/breaker
- godoc.org: https://godoc.org/github.com/kamilsk/breaker
- goreportcard.com: https://goreportcard.com/report/github.com/kamilsk/breaker
- coverage service link: [![cover.run](https://cover.run/go/github.com/kamilsk/breaker.svg?style=flat&tag=golang-1.10)](https://cover.run/go?tag=golang-1.10&repo=github.com%2Fkamilsk%2Fbreaker)

add github.com/kamilsk/breaker

---

README.md

- github.com repo: https://github.com/tylfin/dynatomic
- godoc.org: [![GoDoc](https://godoc.org/github.com/tylfin/dynatomic/pkg/dynatomic?status.svg)](https://godoc.org/github.com/tylfin/dynatomic/pkg/dynatomic)
- goreportcard.com: [![Go Report Card](https://goreportcard.com/badge/github.com/tylfin/dynatomic)](https://goreportcard.com/report/github.com/tylfin/dynatomic)
- coverage service link: [![Coverage Status](https://coveralls.io/repos/github/tylfin/dynatomic/badge.svg)](https://coveralls.io/github/tylfin/dynatomic)
**Note**: …

Added dynatomic

---

README.md

- github.com repo: https://github.com/guptarohit/asciigraph
- godoc.org: [![godoc](https://godoc.org/github.com/guptarohit/asciigraph?status.svg)](https://godoc.org/github.com/guptarohit/asciigraph)
- goreportcard.com: [![go report](https://goreportcard.com/badge/github.com/guptarohit/asciigraph)](https://goreportcard.com/report/github.com/guptarohit/asciigraph)
- coverage service link: [![coverage](https://coveralls.io/repos/github/guptarohit/asciigraph/badge.svg?branch=master)](https://coveralls.io/github/guptarohit/asciigraph?branch=master)

Add asciigraph

---

README.md

- github.com repo: https://github.com/DavidGamba/go-getoptions
- godoc.org: https://godoc.org/github.com/DavidGamba/go-getoptions
- goreportcard.com: https://goreportcard.com/report/github.com/DavidGamba/go-getoptions
- coverage service link: https://codecov.io/github/DavidGamba/go-getoptions?branch=master

Add DavidGamba/go-getoptions

---

README.md

- github.com repo: https://github.com/arthurkushman/pgo
- godoc.org: https://godoc.org/github.com/arthurkushman/pgo
- goreportcard.com: https://goreportcard.com/report/github.com/arthurkushman/pgo
- coverage service link [![codecov](https://codecov.io/gh/arthurkushman/pgo/branch/master/graph/badge.svg)](https://codecov.io/gh/arthurkushman/pgo) …

Add - Go library for PHP community with convenient functions

---

README.md

https://github.com/GuilhermeCaruso/kair
https://godoc.org/github.com/GuilhermeCaruso/kair
https://goreportcard.com/report/github.com/GuilhermeCaruso/kair
https://codecov.io/gh/GuilhermeCaruso/kair

Update Kair project url

---

README.md

- github.com repo: https://github.com/miguelpragier/handy
- godoc.org: https://godoc.org/github.com/miguelpragier/handy
- goreportcard.com: https://goreportcard.com/report/miguelpragier/handy
- coverage service link https://cover.run/go?tag=golang-1.10&repo=https%3A%2Fgithub.com%2Fmiguelpragier%2Fhandy

Proposing miguelpragier/handy

---

README.md

- github.com repo: https://github.com/qmuntal/opc
- godoc.org: [![Documentation](https://godoc.org/github.com/qmuntal/opc?status.svg)](https://godoc.org/github.com/qmuntal/opc)
- goreportcard.com: [![Go Report Card](https://goreportcard.com/badge/github.com/qmuntal/opc)](https://goreportcard.com/report/github.com/qmuntal/opc)
- coverage service link: [![codecov](https://coveralls.io/repos/github/qmuntal/opc/badge.svg)](https://coveralls.io/github/qmuntal/opc?branch=master)

add qmuntal/opc

---

README.md

- github.com repo: github.com/tylerwince/godbg
- godoc.org: https://godoc.org/github.com/tylerwince/godbg
- goreportcard.com: https://goreportcard.com/report/github.com/tylerwince/godbg
- coverage service link: [travis-ci](https://travis-ci.org/tylerwince/godbg)

Add tylerwince/godbg

---

README.md

- github.com repo: https://github.com/32leaves/bel
- godoc.org: https://godoc.org/github.com/32leaves/bel
- goreportcard.com: https://goreportcard.com/report/github.com/32leaves/bel
- coverage service link: [![gocover.run](https://gocover.run/github.com/32leaves/bel.svg?style=flat&tag=1.10)](https://gocover.run?tag=1.10&repo=github.com%2F32leaves%2Fbel)

Adding 32leaves/bel

---

README.md

- github.com repo: https://github.com/pilosa/go-pilosa
- godoc.org: https://godoc.org/github.com/pilosa/go-pilosa
- goreportcard.com: https://goreportcard.com/report/github.com/pilosa/go-pilosa
- coverage service link ([cover.run](https://cover.run/), [gocover](http://gocover.io/), [coveralls](https://coveralls.io/) etc.), example: [![coveralls](https://coveralls.io/repos/github/pilosa/go-pilosa/badge.svg?branch=master)](https://coveralls.io/github/pilosa/go-pilosa?branch=master) …

Added go-pilosa

---

README.md

- [gitlab.com repo](https://gitlab.com/qosenergy/squalus)
- [godoc.org](https://godoc.org/gitlab.com/qosenergy/squalus)
- [goreportcard.com](https://goreportcard.com/report/gitlab.com/qosenergy/squalus)
- [coverage service link](https://qosenergy.gitlab.io/squalus/coverage/master)

Add Squalus

---

README.md

Add gophercon Vietnam

---

README.md

- github.com repo: https://github.com/markphelps/flipt
- godoc.org: https://godoc.org/github.com/markphelps/flipt
- goreportcard.com: https://goreportcard.com/report/github.com/markphelps/flipt
- coverage service link: https://codeclimate.com/github/markphelps/flipt

Add markphelps/flipt

---

README.md

- github.com repo: https://github.com/C2FO/vfs
- godoc.org: [![GoDoc](https://godoc.org/github.com/c2fo/vfs?status.png)](http://godoc.org/github.com/c2fo/vfs)
- goreportcard.com: [![Go Report Card](https://goreportcard.com/badge/github.com/c2fo/vfs)](https://goreportcard.com/report/github.com/c2fo/vfs)
- coverage service link: [![codecov](https://codecov.io/gh/c2fo/vfs/branch/master/graph/badge.svg)](https://codecov.io/gh/c2fo/vfs) …

Add C2FO/vfs to Files section.

---

README.md

- github.com repo: https://github.com/Henry-Sarabia/sliceconv
- godoc.org: https://godoc.org/github.com/Henry-Sarabia/sliceconv
- goreportcard.com: https://goreportcard.com/report/github.com/Henry-Sarabia/sliceconv
- coverage service link: [![Coverage Status](https://coveralls.io/repos/github/Henry-Sarabia/sliceconv/badge.svg?branch=master)](https://coveralls.io/github/Henry-Sarabia/sliceconv?branch=master) …

Add Henry-Sarabia/sliceconv package

---

README.md

- github.com repo: https://github.com/xujiajun/nutsdb
- godoc.org: https://godoc.org/github.com/xujiajun/nutsdb
- goreportcard.com: https://goreportcard.com/report/github.com/xujiajun/nutsdb
- coverage service link ：https://coveralls.io/github/xujiajun/nutsdb?branch=master
- [ ✔️] I have added my package in alphabetical order.
- [ ✔️] I have an appropriate description with correct …

Add NutsDB

---

README.md

https://github.com/gabstv/go-bsdiff
[![GoDoc](https://godoc.org/github.com/gabstv/go-bsdiff?status.svg)](https://godoc.org/github.com/gabstv/go-bsdiff)
[![Go Report Card](https://goreportcard.com/badge/github.com/gabstv/go-bsdiff)](https://goreportcard.com/report/github.com/gabstv/go-bsdiff)
[![Build Status](https://travis-ci.org/gabstv/go-bsdiff.svg?branch=master)](https://travis-ci.org/gabstv/go-bsdiff)
[![Coverage Status](https://coveralls.io/repos/github/gabstv/go-bsdiff/badge.svg?branch=master)](https://coveralls.io/github/gabstv/go-bsdiff?branch=master)
- [ x ] I have added my package in alphabetical order.
- [ x ] I have an appropriate description with correct grammar.
- [ x ] I know that this package was not …

added github.com/gabstv/go-bsdiff under Utilities

---

README.md

- github.com repo: https://github.com/Henry-Sarabia/blank
- godoc.org: [![GoDoc](https://godoc.org/github.com/Henry-Sarabia/blank?status.svg)](https://godoc.org/github.com/Henry-Sarabia/blank)
- goreportcard.com:[![Go Report Card](https://goreportcard.com/badge/github.com/Henry-Sarabia/blank)](https://goreportcard.com/report/github.com/Henry-Sarabia/blank)
- coverage service link: [![Coverage Status](https://coveralls.io/repos/github/Henry-Sarabia/blank/badge.svg?branch=master)](https://coveralls.io/github/Henry-Sarabia/blank?branch=master)
**Note**: …

Add Henry-Sarabia/blank package

---

README.md

- github.com repo: https://github.com/cheynewallace/tabby
- godoc.org: https://godoc.org/github.com/cheynewallace/tabby
- goreportcard.com: https://goreportcard.com/report/github.com/cheynewallace/tabby
- coverage service link  [![cover.run](https://cover.run/go/github.com/cheynewallace/tabby.svg?style=flat&tag=golang-1.10)](https://cover.run/go?tag=golang-1.10&repo=github.com%2Fcheynewallace%2Ftabby)

Adding tabby

---

README.md

Added Brisbane Gophers to Meetups

---

README.md

- github.com repo: https://github.com/gentee/gentee
- godoc.org: https://godoc.org/github.com/gentee/gentee
- goreportcard.com: https://goreportcard.com/report/github.com/gentee/gentee
- coverage service link: [gocover](https://gocover.io/github.com/gentee/gentee)

Add gentee programming language

---

README.md

- github.com repo: https://github.com/novalagung/gubrak
- godoc.org: https://godoc.org/github.com/novalagung/gubrak
- goreportcard.com: [![Go Report Card](https://goreportcard.com/badge/github.com/novalagung/gubrak?nocache=1)](https://goreportcard.com/report/github.com/novalagung/gubrak?nocache=1)
- coverage service link: [![cover.run](https://cover.run/go/github.com/novalagung/gubrak.svg?style=flat&tag=golang-1.10)](https://cover.run/go?tag=golang-1.10&repo=github.com%2Fnovalagung%2Fgubrak) …

update gubrak link

---

README.md

Gophercises is a great platform for new programmers in the parade who are already familiar with another language but new to Go. It takes a _DYI_ approach which I think is absolutely fantastic! I think it will help others as it helped me :heart: 
Note that I am adding this as a resource under _websites_ so I didn't use the normal PR template which was more geared to new projects.

Add gophercises as a resource

---

README.md

I released new version v4 and want to update the package description. I hope no one minds, folks.
Improved code quality
- https://goreportcard.com/report/github.com/kamilsk/retry
- https://golangci.com/r/github.com/kamilsk/retry
- https://scrutinizer-ci.com/g/kamilsk/retry/
- https://travis-ci.org/kamilsk/retry

update description for kamilsk/retry package

---

README.md

- github.com repo: https://github.com/jarcoal/httpmock/
- godoc.org: [![GoDoc](https://godoc.org/github.com/jarcoal/httpmock?status.svg)](https://godoc.org/github.com/jarcoal/httpmock)
- goreportcard.com: [![Go Report Card](https://goreportcard.com/badge/github.com/jarcoal/httpmock)](https://goreportcard.com/report/github.com/jarcoal/httpmock)
- coverage service link: [![Coverage Status](https://coveralls.io/repos/github/jarcoal/httpmock/badge.svg?branch=v1)](https://coveralls.io/github/jarcoal/httpmock?branch=v1) …

Add httpmock package

---

README.md

- github.com repo: [github.com/xuri/toml-to-go](https://github.com/xuri/toml-to-go)
- godoc.org: N/A, this Go type code generator written by JavaScript
- goreportcard.com: N/A, this Go type code generator written by JavaScript
- coverage service link N/A, this Go type code generator written by JavaScript

add TOML-to-Go to the Go Generate Tools list

---

README.md

- github.com repo: https://github.com/GuilhermeCaruso/bellt
- godoc.org: https://godoc.org/github.com/GuilhermeCaruso/bellt
- goreportcard.com:  https://goreportcard.com/report/github.com/GuilhermeCaruso/bellt
- coverage service link: https://codecov.io/gh/GuilhermeCaruso/bellt

Add Routers:bellt repository

---

README.md

- github.com repo: https://github.com/otiai10/ocrserver
- godoc.org: [![GoDoc](https://godoc.org/github.com/otiai10/ocrserver?status.svg)](https://godoc.org/github.com/otiai10/ocrserver)
- goreportcard.com: [![Go Report Card](https://goreportcard.com/badge/github.com/otiai10/ocrserver)](https://goreportcard.com/report/github.com/otiai10/ocrserver)
- coverage service link: [![codecov](https://codecov.io/gh/otiai10/ocrserver/branch/master/graph/badge.svg)](https://codecov.io/gh/otiai10/ocrserver)
----
----
Thanks for your review, you're awesome! :+1:

Add "ocrserver"

---

README.md

- github.com repo: [https://github.com/stellar/kelp](https://github.com/stellar/kelp)
- godoc.org: [![Godoc](https://godoc.org/github.com/stellar/kelp?status.svg)](https://godoc.org/github.com/stellar/kelp)
- goreportcard.com: [![Go Report Card](https://goreportcard.com/badge/github.com/stellar/kelp)](https://goreportcard.com/report/github.com/stellar/kelp)
- coverage service link: ([cover.run](https://cover.run/), [gocover](http://gocover.io/), [coveralls](https://coveralls.io/) etc.), example: …

Add Kelp cryptocurrency trading bot

---

README.md

Update README.md to add Golang Marseille Meetup

---

README.md

* https://github.com/src-d/go-git/
* https://godoc.org/github.com/src-d/go-git
* https://goreportcard.com/report/github.com/src-d/go-git
* https://codecov.io/github/src-d/go-git

Add go-git

---

README.md

- https://github.com/src-d/hercules
- http://godoc.org/gopkg.in/src-d/hercules.v10
- https://goreportcard.com/report/github.com/src-d/hercules
- https://codecov.io/gh/src-d/hercules

Add src-d/hercules

---

README.md

- github.com repo: [https://github.com/nikhilsaraf/go-tools](https://github.com/nikhilsaraf/go-tools)
- godoc.org: [![Godoc](https://godoc.org/github.com/nikhilsaraf/go-tools/multithreading?status.svg)](https://godoc.org/github.com/nikhilsaraf/go-tools/multithreading)
- goreportcard.com: [![Go Report Card](https://goreportcard.com/badge/github.com/nikhilsaraf/go-tools)](https://goreportcard.com/report/github.com/nikhilsaraf/go-tools)
- coverage service link: Travis CI [![Build Status](https://travis-ci.org/nikhilsaraf/go-tools.svg?branch=master)](https …

Add `go-tools/multithreading` library for managing goroutines

---

README.md

- github.com repo: [tvastar/test](https://github.com/tvastar/test/)
- godoc.org: https://godoc.org/github.com/tvastar/test/cmd/testmd
- goreportcard.com: [![Go Report Card](https://goreportcard.com/badge/github.com/tvastar/test)](https://goreportcard.com/report/github.com/tvastar/test)
- coverage service link: [![codecov](https://codecov.io/gh/tvastar/test/branch/master/graph/badge.svg)](https://codecov.io/gh/tvastar/test)

Add `testmd` -- a markdown-to-golang-test converter

---

README.md

Eventually consistent distributed in-memory  cache Go library
- github.com repo: https://github.com/iwanbk/bcache
- godoc.org: [![godoc](https://godoc.org/github.com/iwanbk/bcache?status.svg)](http://godoc.org/github.com/iwanbk/bcache)
- goreportcard.com: [![Go Report Card](https://goreportcard.com/badge/github.com/iwanbk/bcache)](https://goreportcard.com/report/github.com/iwanbk/bcache)
- coverage service link: [![codecov](https://codecov.io/gh/iwanbk/bcache/branch/master/graph/badge.svg)](https://codecov.io/gh/iwanbk/bcache) …

Add iwanbk/bcache.

---

README.md

Hey!
Thank you for maintaining this greate awesome list.
I would like to add my project to the list. :+1: 
- github.com repo: https://github.com/SimonBaeumer/commander
- godoc.org: https://godoc.org/github.com/SimonBaeumer/commander
- goreportcard.com: https://goreportcard.com/report/github.com/SimonBaeumer/commander
- coverage service link ([cover.run](https://cover.run/), [gocover](http://gocover.io/), [coveralls](https://coveralls.io/) etc.), example: [![Test Coverage](https://api.codeclimate.com/v1/badges/cc848165784e0f809a51/test_coverage)](https://codeclimate.com/github/SimonBaeumer/commander/test_coverage)

Add commander

---

README.md

- github.com repo: https://github.com/dotchain/dot/
- godoc.org: [![GoDoc](https://godoc.org/github.com/dotchain/dot?status.svg)](https://godoc.org/github.com/dotchain/dot)
- goreportcard.com: [![Go Report Card](https://goreportcard.com/badge/github.com/dotchain/dot)](https://goreportcard.com/report/github.com/dotchain/dot)
- coverage: [![codecov](https://codecov.io/gh/dotchain/dot/branch/master/graph/badge.svg)](https://codecov.io/gh/dotchain/dot) …

Add dotchain/dot

---

README.md
repo_test.go

Improve test

---

README.md

Another resource with gopher graphics
- github.com repo: https://github.com/MariaLetta/free-gophers-pack
Thank you, guys! ❤

Add Free Gophers Pack

---

README.md

- github.com repo: https://github.com/miku/zek
- godoc.org: https://godoc.org/github.com/miku/zek
- goreportcard.com: https://goreportcard.com/report/github.com/miku/zek
- coverage service link ([cover.run](https://cover.run/), [gocover](http://gocover.io/), [coveralls](https://coveralls.io/) etc.):
[![cover.run](https://cover.run/go/github.com/miku/zek.svg?style=flat&tag=golang-1.10)](https://cover.run/go?tag=golang-1.10&repo=github.com%2Fmiku%2Fzek) …

add miku/zek

---

README.md

https://github.com/pascaldekloe/metrics
[![godoc](https://godoc.org/github.com/pascaldekloe/metrics?status.svg)](https://godoc.org/github.com/pascaldekloe/metrics)
[![Go Report Card](https://goreportcard.com/badge/github.com/pascaldekloe/metrics)](https://goreportcard.com/report/github.com/pascaldekloe/metrics)
[![cover.run](https://cover.run/go/github.com/pascaldekloe/metrics.svg?style=flat&tag=golang-1.10)](https://cover.run/go?tag=golang-1.10&repo=github.com%2Fpascaldekloe%2Fmetrics)

Add github.com/pascaldekloe/metrics

---

README.md

- github.com repo: https://github.com/golang-standards/project-layout 
**PR Checklist**

Add go project layout

---

README.md

- github.com repo: https://github.com/Clivern/Beaver
- godoc.org:
- goreportcard.com: https://goreportcard.com/report/github.com/Clivern/Beaver
- coverage service link (Coverage is part of the testing): https://travis-ci.org/Clivern/Beaver 

Add beaver to messaging packages

---

README.md

- github.com repo: https://github.com/JeremyLoy/config
- godoc.org: https://godoc.org/github.com/JeremyLoy/config
- goreportcard.com:  https://goreportcard.com/report/github.com/JeremyLoy/config
- coverage service link: https://coveralls.io/github/JeremyLoy/config

Add JeremyLoy/config

---

README.md

- github.com repo: [errlog](https://github.com/snwfdhmp/errlog)
- godoc.org: [errlog](https://godoc.org/github.com/snwfdhmp/errlog)
- goreportcard.com: [errlog](https://goreportcard.com/report/github.com/snwfdhmp/errlog)
- coverage service link [![cover.run](https://cover.run/go/github.com/snwfdhmp/errlog.svg?style=flat&tag=golang-1.10)](https://cover.run/go?tag=golang-1.10&repo=github.com%2Fsnwfdhmp%2Ferrlog) (not testable) …

Add errlog

---

README.md

- github.com repo: https://github.com/ndabAP/assocentity
- godoc.org: https://godoc.org/github.com/ndabAP/assocentity
- goreportcard.com: https://goreportcard.com/report/github.com/ndabAP/assocentity …

Add assocentity

---

README.md

- github.com repo: https://github.com/osamingo/checkdigit
- godoc.org: https://godoc.org/github.com/osamingo/checkdigit
- goreportcard.com: https://goreportcard.com/report/github.com/osamingo/checkdigit
- coverage service link: https://codecov.io/gh/osamingo/checkdigit

Add osamingo/checkdigit lib

---

README.md

https://github.com/blockloop/scan
[![GoDoc](https://godoc.org/github.com/blockloop/scan?status.svg)](https://godoc.org/github.com/blockloop/scan) [![Travis](https://img.shields.io/travis/blockloop/scan.svg)](https://travis-ci.org/blockloop/scan) [![Coveralls github](https://img.shields.io/coveralls/github/blockloop/scan.svg)](https://coveralls.io/github/blockloop/scan) [![Report Card](https://goreportcard.com/badge/github.com/blockloop/scan)](https://goreportcard.com/report/github.com/blockloop/scan) [![Dependabot Status](https://api.dependabot.com/badges/status?host=github&repo=blockloop/scan)](https://dependabot.com)

add https://github.com/blockloop/scan

---

README.md

- github.com repo: https://github.com/Antonito/gfile
- godoc.org: https://godoc.org/github.com/Antonito/gfile
- goreportcard.com: https://goreportcard.com/report/github.com/Antonito/gfile
- coverage service link: https://coveralls.io/github/Antonito/gfile?branch=master

Added gfile

---

README.md

- github.com repo: https://bitbucket.org/vahidi/interpol
- godoc.org: https://godoc.org/bitbucket.org/vahidi/interpol
- goreportcard.com:https://goreportcard.com/report/bitbucket.org/vahidi/interpol
- coverage service link: https://gocover.io/bitbucket.org/vahidi/interpol

added interpol / police

---

README.md

- github.com repo:https://github.com/pingcap/failpoint
- godoc.org: https://godoc.org/github.com/pingcap/failpoint
- goreportcard.com: https://goreportcard.com/report/github.com/pingcap/failpoint
- coverage service link: https://codecov.io/gh/pingcap/failpoint

Added failpoint

---

README.md

add caching db article

---

README.md

Note: Hey guys, thanks so much for the awesome resources! Hope this contribution is well received :)

Added a guide to Golang e-commerce

---

README.md

- github.com repo: https://github.com/jirenius/resgate/tree/master/examples/book-collection
- godoc.org: https://godoc.org/github.com/jirenius/resgate
- goreportcard.com: https://goreportcard.com/report/github.com/jirenius/resgate
- coverage service link: https://coveralls.io/github/jirenius/resgate?branch=master

Add resgate

---

README.md

- github.com repo: https://github.com/philipjkim/goreadability
- godoc.org: https://godoc.org/github.com/philipjkim/goreadability
- goreportcard.com: [![Go Report Card](https://goreportcard.com/badge/github.com/philipjkim/goreadability)](https://goreportcard.com/report/github.com/philipjkim/goreadability)
- coverage service link ([cover.run](https://cover.run/), [gocover](http://gocover.io/), [coveralls](https://coveralls.io/) etc.): [![gocover](http://gocover.io/_badge/github.com/philipjkim/goreadability)](https://gocover.io/github.com/philipjkim/gore …

Add goreadability

---

README.md

- github.com repo: https://github.com/psampaz/go-mod-outdated
- godoc.org: https://godoc.org/github.com/psampaz/go-mod-outdated
- goreportcard.com: https://goreportcard.com/report/github.com/psampaz/go-mod-outdated
- coverage service link: https://codecov.io/gh/psampaz/go-mod-outdated

Added go-mod-outdated

---

README.md

- github.com repo: https://github.com/srfrog/dict
- godoc.org: https://godoc.org/github.com/srfrog/dict
- goreportcard.com: https://goreportcard.com/report/github.com/srfrog/dict
- coverage service link: https://coveralls.io/github/srfrog/dict?branch=master

Add srfrog's dict package

---

README.md

- github.com repo: https://github.com/mrbenosborne/tripadvisor-golang
- godoc.org: https://godoc.org/github.com/mrbenosborne/tripadvisor-golang
- goreportcard.com: https://goreportcard.com/report/github.com/mrbenosborne/tripadvisor-golang

Tripadvisor

---

README.md

- github.com repo: https://github.com/arthurkiller/rollingWriter
- godoc.org: [![GoDoc](https://godoc.org/github.com/arthurkiller/rollingWriter?status.svg)](https://godoc.org/github.com/arthurkiller/rollingWriter)
- goreportcard.com:[![Go Report Card](https://goreportcard.com/badge/github.com/arthurkiller/rollingwriter)](https://goreportcard.com/report/github.com/arthurkiller/rollingwriter)
- coverage service link [![codecov](https://codecov.io/gh/arthurkiller/rollingwriter/branch/master/graph/badge.svg)](https://codecov.io/gh/arthurkiller/rollingwriter)

Add rollingwriter

---

README.md

This is a package that allows the user to compare a bunch of pairings ( game matches, document relevance, etc ) to see what the most preferred or likely winner is. It's used a lot in R, but I needed a Go version so I wrote this.
- github.com repo: https://github.com/seanhagen/bradleyterry
- godoc.org: https://godoc.org/github.com/seanhagen/bradleyterry
- goreportcard.com: https://goreportcard.com/report/github.com/seanhagen/bradleyterry
- coverage service link: https://codecov.io/gh/seanhagen/bradleyterry

Data Science: Bradley-Terry model package

---

README.md

- github.com repo: https://github.com/mustafaturan/bus
- godoc.org: [![GoDoc](https://godoc.org/github.com/mustafaturan/bus?status.svg)](https://godoc.org/github.com/mustafaturan/bus)
- goreportcard.com: [![Go Report Card](https://goreportcard.com/badge/github.com/mustafaturan/bus)](https://goreportcard.com/report/github.com/mustafaturan/bus)
- coverage service link [![Build Status](https://travis-ci.org/mustafaturan/bus.svg?branch=master)](https://travis-ci.org/mustafaturan/bus)

Add bus package

---

README.md

should probably be removed from the list

gomodel is unmaintained

---

README.md

**Links:**
- github.com repo: https://github.com/vanng822/go-premailer
- godoc.org: https://godoc.org/github.com/vanng822/go-premailer/premailer
- goreportcard.com: https://goreportcard.com/report/github.com/vanng822/go-premailer
- coverage service link: https://gocover.io/github.com/vanng822/go-premailer/premailer
**PR checklist:**

Add go-premailer, inline styling for HTML mail

---

README.md

Add goview

---

README.md

github.com repo: [currency](https://github.com/bnkamalesh/currency)
godoc.org: [![](https://godoc.org/github.com/nathany/looper?status.svg)](https://godoc.org/github.com/bnkamalesh/currency)
goreportcard.com: [![](https://goreportcard.com/badge/github.com/bnkamalesh/currency)](https://goreportcard.com/report/github.com/bnkamalesh/currency)
coverage service:  [![gocover.run](https://gocover.run/github.com/bnkamalesh/currency.svg?style=flat&tag=1.10)](https://gocover.run?tag=1.10&repo=github.com%2Fbnkamalesh%2Fcurrency) 
- [✓] I have added my package in alphabetical order.
- [✓] I have an appropriate description with correct grammar.
- [✓] I know that this package was not listed before.
- [✓] I have added godoc link to …

Add currency computation package

---

README.md

* github.com repo: https://github.com/vardius/gollback
* godoc.org: [![](https://godoc.org/github.com/vardius/gollback?status.svg)](http://godoc.org/github.com/vardius/gollback)
* goreportcard.com: [![Go Report Card](https://goreportcard.com/badge/github.com/vardius/gollback)](https://goreportcard.com/report/github.com/vardius/gollback)
* coverage service link: [![codecov](https://codecov.io/gh/vardius/gollback/branch/master/graph/badge.svg)](https://codecov.io/gh/vardius/gollback)

Add vardius/gollback

---

README.md

- github.com repo: https://github.com/AnikHasibul/queue
- godoc.org: https://godoc.org/github.com/AnikHasibul/queue
- goreportcard.com: https://goreportcard.com/report/github.com/AnikHasibul/queue
- coverage service link: https://gocover.io/github.com/AnikHasibul/queue

Added AnikHasibul/queue

---

README.md

- github.com repo: https://github.com/codingsince1985/checksum
- godoc.org: https://godoc.org/github.com/codingsince1985/checksum
- goreportcard.com: https://goreportcard.com/report/github.com/codingsince1985/checksum
- coverage service link: https://gocover.io/github.com/codingsince1985/checksum

compute message digest for large files

---

README.md

- github.com repo: https://github.com/aerogo/log
- godoc.org: [![Godoc][godoc-image]][godoc-url]
- goreportcard.com: [![Report][report-image]][report-url]
- coverage service link: [![Coverage][coverage-image]][coverage-url]
[godoc-image]: https://godoc.org/github.com/aerogo/log?status.svg
[godoc-url]: https://godoc.org/github.com/aerogo/log
[report-image]: https://goreportcard.com/badge/github.com/aerogo/log
[report-url]: https://goreportcard.com/report/github.com/aerogo/log
[coverage-image]: https://codecov.io/gh/aerogo/log/graph/badge.svg
[coverage-url]: https://codecov.io/gh/aerogo/log

Add aerogo/log

---

README.md

- github.com repo: https://github.com/akyoto/cache
- godoc.org: [![Godoc][godoc-image]][godoc-url]
- goreportcard.com: [![Report][report-image]][report-url]
- coverage service link: [![Coverage][coverage-image]][coverage-url]
[godoc-image]: https://godoc.org/github.com/akyoto/cache?status.svg
[godoc-url]: https://godoc.org/github.com/akyoto/cache
[report-image]: https://goreportcard.com/badge/github.com/akyoto/cache
[report-url]: https://goreportcard.com/report/github.com/akyoto/cache
[coverage-image]: https://codecov.io/gh/akyoto/cache/graph/badge.svg
[coverage-url]: https://codecov.io/gh/akyoto/cache

Add akyoto/cache

---

README.md

- github.com repo: https://github.com/c-robinson/iplib
- godoc.org: https://godoc.org/github.com/c-robinson/iplib
- goreportcard.com: https://goreportcard.com/report/github.com/c-robinson/iplib
- coverage service link [![Coverage Status](https://coveralls.io/repos/github/c-robinson/iplib/badge.svg?branch=master)](https://coveralls.io/github/c-robinson/iplib?branch=master)

Add iplib to networking section

---

README.md

- [github](https://github.com/dawidd6/go-appindicator) 
- [godoc](https://godoc.org/github.com/dawidd6/go-appindicator)
- [goreportcard](https://goreportcard.com/report/github.com/dawidd6/go-appindicator)
- [cirrus-ci](https://cirrus-ci.com/github/dawidd6/go-appindicator)
No coverage, because there are no tests. Package provides only bindings to C library.

Add go-appindicator

---

README.md

- github.com repo: https://github.com/blind-oracle/psql-streamer
- godoc.org: Not applicable
- goreportcard.com: https://goreportcard.com/report/github.com/blind-oracle/psql-streamer
- coverage service link: https://coveralls.io/github/blind-oracle/psql-streamer
- [*] I know that this package was not listed before.
- [-] I have added godoc link to the repo and to my pull request.
- [*] I have added coverage service link to the repo and to my pull request.
- [*] I have added goreportcard link to the repo and to my pull request.
- [*] I have read [Contribution …

Add psql-streamer to Server Applications

---

README.md

- github.com repo: https://github.com/codingconcepts/datagen
- godoc.org: https://godoc.org/github.com/codingconcepts/datagen
- goreportcard.com: https://goreportcard.com/report/github.com/codingconcepts/datagen
- coverage service link ([cover.run](https://cover.run/), [gocover](http://gocover.io/), [coveralls](https://coveralls.io/) etc.), example: gocover looks to be failing with an internal error at the moment. …

Added datagen

---

README.md

- github.com repo: [https://github.com/liujianping/job](https://github.com/liujianping/job)
- godoc.org:[![GoDoc](https://godoc.org/github.com/liujianping/job?status.svg)](https://godoc.org/github.com/liujianping/job)
- goreportcard.com: [![Go Report Card](https://goreportcard.com/badge/github.com/liujianping/job)](https://goreportcard.com/report/github.com/liujianping/job)
- build status: [![Build Status](https://travis-ci.org/liujianping/job.svg?branch=master)](https://travis-ci.org/liujianping/job) …

add  command-line-tool

---

README.md

- github.com repo: https://github.com/x-mod/routine
- godoc.org: https://godoc.org/github.com/x-mod/routine
- goreportcard.com: https://goreportcard.com/report/github.com/x-mod/routine
- coverage service link [![Coverage Status](https://coveralls.io/repos/github/x-mod/routine/badge.svg?branch=master)](https://coveralls.io/github/x-mod/routine?branch=master) …

add x-mod/routine package

---

README.md

mgo is a great driver implementation, but is not maintained anymore
- godoc.org: …

update maintenance status of mgo

---

README.md

- github.com repo: https://github.com/VictoriaMetrics/VictoriaMetrics
- godoc.org: not applicable for app. Libs: https://godoc.org/github.com/VictoriaMetrics/VictoriaMetrics/lib
- goreportcard.com: https://goreportcard.com/report/github.com/VictoriaMetrics/VictoriaMetrics
- coverage link: TBD

Add victoriametrics to database list

---

README.md

add migrator library to database schema migration section
- github.com repo: https://github.com/lopezator/migrator
- godoc.org: https://github.com/lopezator/migrator
- goreportcard.com: https://goreportcard.com/report/github.com/lopezator/migrator
- coverage service link: https://codecov.io/gh/lopezator/migrator

db-migration: add migrator

---

README.md

I added the Golang Korea meetup. This is not a package, so I deleted all package related questions.
Thank you.

Add Golang Korea meetup

---

README.md

- github.com repo: https://github.com/mvmaasakkers/certificates
- godoc.org: https://godoc.org/github.com/mvmaasakkers/certificates
- goreportcard.com: https://goreportcard.com/report/github.com/mvmaasakkers/certificates
- coverage service link [![Coverage Status](https://coveralls.io/repos/github/mvmaasakkers/certificates/badge.svg?branch=master)](https://coveralls.io/github/mvmaasakkers/certificates?branch=master) …

Add certificates

---

README.md

- github.com repo: https://github.com/defval/inject
- godoc.org: https://godoc.org/github.com/defval/inject
- goreportcard.com: https://goreportcard.com/report/github.com/defval/inject
- coverage service link: [codecov.io](https://codecov.io/gh/defval/inject)

Add inject

---

README.md

- github.com repo: https://github.com/qmuntal/gltf
- godoc.org: https://godoc.org/github.com/qmuntal/gltf
- goreportcard.com: https://goreportcard.com/report/github.com/qmuntal/gltf
- coverage service link [![codecov](https://coveralls.io/repos/github/qmuntal/gltf/badge.svg)](https://coveralls.io/github/qmuntal/gltf?branch=master)

Add qmuntal/gltf

---

README.md

Simple Dependency Injection Container
- github.com repo: https://github.com/vardius/gocontainer
- godoc.org: [![](https://godoc.org/github.com/vardius/gocontainer?status.svg)](http://godoc.org/github.com/vardius/gocontainer)
- goreportcard.com: [![Go Report Card](https://goreportcard.com/badge/github.com/vardius/gocontainer)](https://goreportcard.com/report/github.com/vardius/gocontainer)
- coverage service link: [![codecov](https://codecov.io/gh/vardius/gocontainer/branch/master/graph/badge.svg)](https://codecov.io/gh/vardius/gocontainer)

Add gocontainer

---

README.md

- before: wedriver
- after: WebDriver
---
- godoc.org: …

typo fix to WebDriver

---

README.md

I added the GoSF meetup. This is not a package, so I deleted all package related questions.
Thank you.

Added GoSF to meetups list

---

README.md

- github.com repo: https://github.com/prashantgupta24/activity-tracker
- godoc.org: https://godoc.org/github.com/prashantgupta24/activity-tracker
- goreportcard.com: https://goreportcard.com/report/github.com/prashantgupta24/activity-tracker
- coverage service link:  https://codecov.io/gh/prashantgupta24/activity-tracker (100% coverage)

add mac-activity-tracker library

---

README.md

Added Canberra Gohpers

---

README.md

Compact, sortable and fast unique IDs with embedded metadata.
Added to the **UUID** category.
- github.com repo:  https://github.com/muyo/sno
- godoc.org: [![GoDoc](https://img.shields.io/badge/godoc-reference-00a1fe.svg?style=flat-square)](https://godoc.org/github.com/muyo/sno) 
- goreportcard.com: [![Go Report Card](https://goreportcard.com/badge/github.com/muyo/sno?style=flat-square)](https://goreportcard.com/report/github.com/muyo/sno) 
- coverage service link: [![Coverage](https://img.shields.io/codecov/c/github/muyo/sno.svg?logo=codecov&style=flat-square)](https://codecov.io/gh/muyo/sno)

Add muyo/sno

---

README.md

- github.com repo: https://github.com/corona10/goimghdr
- godoc.org: https://godoc.org/github.com/corona10/goimghdr
- goreportcard.com: https://goreportcard.com/report/github.com/corona10/goimghdr
- coverage service link: [![Coverage Status](https://coveralls.io/repos/github/corona10/goimghdr/badge.svg)](https://coveralls.io/github/corona10/goimghdr) …

README.md: Add goimghdr

---

README.md

Go bindings for ExifTool, the well-known library used to extract as much metadata as possible (EXIF, IPTC, ...) from files (pictures, PDF, office, ...).
- github.com repo: https://github.com/barasher/go-exiftool
- godoc.org: [![GoDoc](https://godoc.org/github.com/barasher/go-exiftool?status.svg)](https://godoc.org/github.com/barasher/go-exiftool)
- goreportcard.com: [![go report card](https://goreportcard.com/badge/github.com/barasher/go-exiftool "go report card")](https://goreportcard.com/report/github.com/barasher/go-exiftool)
- coverage service link: [![Coverage Status](https://coveralls.io/repos/github/barasher/go-exiftool/badge.svg)](https://coveralls.io/github/barasher/go-exiftool)

Add go-exiftool

---

README.md

I'd like to submit 'dbt' for your consideration.
- code: https://github.com/nikogura/dbt
- godoc.org: https://godoc.org/github.com/nikogura/dbt/pkg/dbt
- goreportcard.com: https://goreportcard.com/report/github.com/nikogura/dbt
- coverage service link: https://coveralls.io/github/nikogura/dbt?branch=master
Test coverage is 65%, but given the nature of the things that aren't covered (I didn't test things like being unable to write to the local filesystem), I still think it's worth submitting.
Thank you for your consideration!

Added dbt to Utilities section

---

README.md

- github.com repo: https://github.com/prashantgupta24/mac-sleep-notifier
- godoc.org: https://godoc.org/github.com/prashantgupta24/mac-sleep-notifier/notifier
- goreportcard.com: https://goreportcard.com/report/github.com/prashantgupta24/mac-sleep-notifier
- coverage service link https://codecov.io/gh/prashantgupta24/mac-sleep-notifier

added OSX sleep/wake notifier

---

README.md

- github.com repo: https://github.com/zoomio/tagify
- godoc.org: https://godoc.org/github.com/zoomio/tagify
- goreportcard.com: https://goreportcard.com/report/github.com/zoomio/tagify
- coverage service link https://gocover.io/github.com/zoomio/tagify

Added project Tagify

---

README.md

Add studygolang.com and ebook

---

README.md

Could you please merge my PR to make my Go project awesome?
- github.com repo: https://github.com/lni/dragonboat
- godoc.org: https://godoc.org/github.com/lni/dragonboat
- goreportcard.com: https://goreportcard.com/report/github.com/lni/dragonboat
- coverage service link: https://codecov.io/gh/lni/dragonboat

Added dragonboat

---

README.md

A simple ORM for Google/Firebase Cloud Firestore
- github.com repo: https://github.com/jschoedt/go-firestorm
- godoc.org: https://godoc.org/github.com/jschoedt/go-firestorm
- goreportcard.com: https://goreportcard.com/report/github.com/jschoedt/go-firestorm
- coverage service link [![coverage report](https://gitlab.com/jens.schoedt/go-firestorm/badges/master/coverage.svg)](https://gitlab.com/jens.schoedt/go-firestorm/commits/master)

Added go-firestorm ORM lib for firestore

---

README.md

- github.com repo: https://github.com/AaronJan/Hunch
- godoc.org: https://godoc.org/github.com/AaronJan/Hunch
- goreportcard.com: https://goreportcard.com/report/github.com/aaronjan/hunch
- coverage service link: [![codecov](https://codecov.io/gh/AaronJan/Hunch/branch/master/graph/badge.svg)](https://codecov.io/gh/AaronJan/Hunch)
Good enough coverage and battle tested …

add github.com/AaronJan/Hunch

---

README.md

name correction

---

README.md

add gophercon australia

---

README.md

- github.com repo: https://github.com/beatlabs/harvester
- godoc.org: https://godoc.org/github.com/beatlabs/harvester
- goreportcard.com: https://goreportcard.com/report/github.com/beatlabs/harvester
- coverage service link ([cover.run](https://cover.run/), [gocover](http://gocover.io/), [coveralls](https://coveralls.io/) etc.), example: `[![cover.run](https://cover.run/go/github.com/user/repository.svg?style=flat&tag=golang-1.10)](https://cover.run/go?tag=golang-1.10&repo=github.com%2Fuser%2Frepository)` https://codecov.io/gh/beatlabs/harvester
Very …

Adding harvester

---

README.md

- github.com repo: https://github.com/beatlabs/patron
- godoc.org: https://godoc.org/github.com/beatlabs/patron
- goreportcard.com: https://goreportcard.com/report/github.com/beatlabs/patron
- coverage service link ([cover.run](https://cover.run/), [gocover](http://gocover.io/), [coveralls](https://coveralls.io/) etc.), example: `[![cover.run](https://cover.run/go/github.com/user/repository.svg?style=flat&tag=golang-1.10)](https://cover.run/go?tag=golang-1.10&repo=github.com%2Fuser%2Frepository)` : https://codecov.io/gh/beatlabs/patron
Very good …

Adding patron framework

---

README.md

- github.com repo: https://github.com/kamilsk/tracer
- godoc.org: https://godoc.org/github.com/kamilsk/tracer
- goreportcard.com: https://goreportcard.com/report/github.com/kamilsk/tracer
- coverage service: https://codeclimate.com/github/kamilsk/tracer/test_coverage

add tracer package

---

README.md

For context, I'm the main author and maintainer of [slackscot](https://github.com/alexandre-normand/slackscot). I have a personal [slack bot](https://github.com/alexandre-normand/youppi) built using slackscot and it's actively used within my employer's infrastructure so I'm not dropping support anytime soon ☺️. 
- github.com repo: https://github.com/alexandre-normand/slackscot
- godoc.org: https://godoc.org/github.com/alexandre-normand/slackscot
- goreportcard.com: https://goreportcard.com/report/github.com/alexandre-normand/slackscot
- codeclimate coverage: [![Test Coverage](https://api.codeclimate.com/v1/badges/9fe1722ab2f31036c44c/test_coverage)](https://codeclimate.com/github/alexandre-normand/slackscot/test_coverage)
**Made sure that:**
Thanks for considering the addition to the list …

Add slackscot to Bot Building Packages

---

README.md

- github.com repo: [https://github.com/knadh/koanf](https://github.com/knadh/koanf)
- godoc.org: [https://godoc.org/github.com/knadh/koanf](https://godoc.org/github.com/knadh/koanf)
- goreportcard.com: [https://goreportcard.com/report/github.com/knadh/koanf](https://goreportcard.com/report/github.com/knadh/koanf)
- coverage service link: [gocover (88%)](https://gocover.io/github.com/knadh/koanf)

Add knadh/koanf under the Configuration section

---

README.md

- github.com repo: github.com/nanovms/ops
- godoc.org: https://godoc.org/github.com/nanovms/ops/lepton
- goreportcard.com: https://goreportcard.com/badge/github.com/nanovms/ops
- coverage service link: https://gocover.io/github.com/nanovms/ops 

adding in ops

---

README.md

- github.com repo: https://gitlab.com/skilstak/code/uniq/go"
- godoc.org: https://godoc.org/gitlab.com/skilstak/code/uniq/go
- goreportcard.com: https://goreportcard.com/report/gitlab.com/skilstak/code/uniq/go
- coverage service link: https://gocover.io/gitlab.com/skilstak/code/uniq/go
- [x ] I know that this package was not listed before.
- [x ] I have added godoc link to the repo and to my pull request.
- [x ] I have added coverage service link to the repo and to my pull request.
- [x ] I have added goreportcard link to the repo and to my pull request.
- [x ] I have read [Contribution guidelines](https://github.com/avelino/awesome-go/blob/master/CONTRIBUTING.md#contributio …

uniq added under UUID

---

.gitignore
README.md

I have added the Golang Gurgaon meetup. This is not a package, so I deleted all package related questions.

Added Golang Gurgaon meetup.

---

README.md

- github.com repo: [gojek/darkroom](https://github.com/gojek/darkroom)
- godoc.org: [gojek/darkroom](https://godoc.org/github.com/gojek/darkroom)
- goreportcard.com: [gojek/darkroom](https://goreportcard.com/report/github.com/gojek/darkroom)
- coverage service link: [coveralls](https://coveralls.io/github/gojek/darkroom?branch=master)
Coverage: ~90%

Add Darkroom to the Images section

---

README.md

- github.com repo: https://github.com/aidarkhanov/nanoid
- godoc.org: https://godoc.org/github.com/aidarkhanov/nanoid
- goreportcard.com: https://goreportcard.com/report/github.com/aidarkhanov/nanoid
- gocover.io: https://gocover.io/github.com/aidarkhanov/nanoid
- [👍] I have added my package in alphabetical order.
- [👍] I have an appropriate description with correct grammar.
- [👍] I know that this …

Add Nano ID - unique ID generator

---

README.md

- github.com repo:  http://github.com/viant/ptrie
- godoc.org: https://godoc.org/github.com/viant/ptrie
- goreportcard.com:  https://goreportcard.com/report/github.com/viant/ptrie
- coverage service link: https://gocover.io/github.com/viant/ptrie

Added ptrie

---

README.md

- github.com repo: [https://github.com/piaohao/godis](https://github.com/piaohao/godis)
- godoc.org: [https://godoc.org/github.com/piaohao/godis](https://godoc.org/github.com/piaohao/godis)
- goreportcard.com: [https://goreportcard.com/report/github.com/piaohao/godis](https://goreportcard.com/report/github.com/piaohao/godis)
- codecov.io: [https://codecov.io/gh/piaohao/godis](https://codecov.io/gh/piaohao/godis) …

Add godis, a redis client library

---

README.md

- github.com repo: https://github.com/unidoc/unioffice
- godoc.org: https://godoc.org/github.com/unidoc/unioffice
- goreportcard.com: https://goreportcard.com/report/github.com/unidoc/unioffice
https://gocover.io/github.com/unidoc/unioffice

Add unioffice to Microsoft Office

---

README.md

- godoc.org:
Note: This is a tutorial so have not included the godoc, coverage, reportcard.

Add golang from zero to hero

---

README.md

- github.com repo: https://github.com/ddymko/go-jsonerror
- godoc.org: https://godoc.org/github.com/ddymko/go-jsonerror
- goreportcard.com: https://goreportcard.com/report/github.com/ddymko/go-jsonerror
- coverage service link: [codecov](https://codecov.io/github/ddymko/go-jsonerror?branch=master)

added go-jsonerror package

---

README.md

All other requirements previously met and have not changed.

uniq url package path change

---

README.md

- github.com repo: https://github.com/robinjoseph08/redisqueue
- godoc.org: https://godoc.org/github.com/robinjoseph08/redisqueue
- goreportcard.com: https://goreportcard.com/report/github.com/robinjoseph08/redisqueue
- coverage service link ([gocover](http://gocover.io/), [coveralls](https://coveralls.io/) etc.): https://coveralls.io/github/robinjoseph08/redisqueue?branch=master …

Add redisqueue

---

README.md

- github.com repo: https://github.com/liujianping/ts
- godoc.org: [![GoDoc](https://godoc.org/github.com/liujianping/ts?status.svg)](https://godoc.org/github.com/liujianping/ts)
- goreportcard.com:[![Go Report Card](https://goreportcard.com/badge/github.com/liujianping/ts)](https://goreportcard.com/report/github.com/liujianping/ts)
- coverage service link [![Coverage Status](https://coveralls.io/repos/github/liujianping/ts/badge.svg?branch=master)](https://coveralls.io/github/liujianping/ts?branch=master) …

add ts command line tool

---

README.md

- github.com repo: https://github.com/steinfletcher/apitest
- godoc.org: https://godoc.org/github.com/steinfletcher/apitest
- goreportcard.com: https://goreportcard.com/report/github.com/steinfletcher/apitest
- coverage service link [coveralls](https://coveralls.io/github/steinfletcher/apitest?branch=master&service=github)

Add apitest

---

README.md

- github.com repo: https://github.com/reugn/go-streams
- godoc.org: [![GoDoc](https://godoc.org/github.com/reugn/go-streams?status.svg)](https://godoc.org/github.com/reugn/go-streams)
- goreportcard.com: [![Go Report Card](https://goreportcard.com/badge/github.com/reugn/go-streams)](https://goreportcard.com/report/github.com/reugn/go-streams)
- coverage service link : [![codecov](https://codecov.io/gh/reugn/go-streams/branch/master/graph/badge.svg)](https://codecov.io/gh/reugn/go-streams)
**Note**: that new categories can be added …

add go-streams library

---

README.md

- github.com repo: https://github.com/gookit/rux
- godoc.org: https://godoc.org/github.com/gookit/rux
- goreportcard.com: [![Go Report Card](https://goreportcard.com/badge/github.com/gookit/rux)](https://goreportcard.com/report/github.com/gookit/rux)
- coverage service link [![Coverage Status](https://coveralls.io/repos/github/gookit/rux/badge.svg?branch=master)](https://coveralls.io/github/gookit/rux?branch=master) …

Add package: rux

---

README.md

- github.com repo: https://github.com/c-bata/goptuna
- godoc.org: https://godoc.org/github.com/c-bata/goptuna
- goreportcard.com: https://goreportcard.com/report/github.com/c-bata/goptuna
- coverage service link https://gocover.io/github.com/c-bata/goptuna

goptuna: hyperparameter optimization framework.

---

README.md

Remove cosiner/zerver

---

README.md

remove low-quality repo

---

README.md

- github.com repo: https://github.com/drakkan/sftpgo
- godoc.org: https://godoc.org/github.com/drakkan/sftpgo
- goreportcard.com: https://goreportcard.com/report/github.com/drakkan/sftpgo
- coverage service link: https://codecov.io/gh/drakkan/sftpgo/branch/master
Note: this is a server application and not a library for other developers. I included godoc link to my pull request but …

Add SFTPGo a full featured and highly configurable SFTP server

---

README.md

- github.com repo: https://github.com/goroute/route
- godoc.org: https://godoc.org/github.com/goroute/route
- goreportcard.com: https://goreportcard.com/report/github.com/goroute/route
-----------------
Hi @kirillDanshin @appleboy,
The project …

Nio has moved

---

README.md

- github.com repo: https://github.com/abraithwaite/jeff
- godoc.org: https://godoc.org/github.com/abraithwaite/jeff
- goreportcard.com: https://goreportcard.com/report/github.com/abraithwaite/jeff
- coverage service link: https://circleci.com/gh/abraithwaite/jeff/64 (under tests header)

authentication: add jeff

---

README.md

- github.com repo: https://github.com/vimeda/pletter
- godoc.org: https://godoc.org/github.com/vimeda/pletter
- goreportcard.com: https://goreportcard.com/report/github.com/vimeda/pletter
- coverage service link [coveralls](https://coveralls.io/github/vimeda/pletter)

Add new repository: pletter

---

README.md

I would like to suggest adding my error handling library to this list. I'm working on it for a few years now and I feel it's really close to 1.0.0.
I actually submitted two libraries: one is a drop-in replacement for `errors` and `github.com/pkg/errors` packages. It contains quite a few additional features. The other one is a set of tools to make error handling itself easier.
I wrote about using these tools here: https://banzaicloud.com/blog/error-handling-go/
I'm not 100% sure whether I should have submitted the project itself (since there are quite a few more libraries in the project) or not, but I felt these two libraries are the most important ones.
Thank you for considering my package!
(Note: some goreportcard warnings are not fixed intentionally. Some test files are downloaded from …

Add emperror

---

README.md

- github.com repo: https://github.com/neuronlabs/errors
- godoc.org: [![GoDoc](https://godoc.org/github.com/neuronlabs/errors?status.svg)](https://godoc.org/github.com/neuronlabs/errors)
- goreportcard.com: [![Go Report Card](https://goreportcard.com/badge/github.com/neuronlabs/errors)](https://goreportcard.com/report/github.com/neuronlabs/errors)
- coverage service link [gocover](https://gocover.io/github.com/neuronlabs/errors), [![Coverage Status](https://coveralls.io/repos/github/neuronlabs/errors/badge.svg?branch=master)](https://coveralls.io/githu …

Added neuronlabs/errors Error Handling package

---

README.md

- github.com repo: https://github.com/swithek/sessionup
- godoc.org: https://godoc.org/github.com/swithek/sessionup
- goreportcard.com: https://goreportcard.com/report/github.com/swithek/sessionup
- coverage service link ([gocover](http://gocover.io/), [coveralls](https://coveralls.io/) etc.): https://gocover.io/github.com/swithek/sessionup

Added swithek/sessionup package

---

README.md

- github.com repo: https://github.com/dnote/dnote
- godoc.org: https://godoc.org/github.com/dnote/dnote
- goreportcard.com: https://goreportcard.com/report/github.com/dnote/dnote
- coverage service link ([gocover](http://gocover.io/), [coveralls](https://coveralls.io/) etc.): https://coveralls.io/github/dnote/dnote
It is a mono repository comprising of frontend app, server, CLI, browser extension, etc. The coverall page shows the coverage for the CLI project.
**Note**: that new categories can be added only when there are 3 packages …

Add Dnote to the Command Line section

---

README.md

Updating description of already accepted project to reflect new features.
github.com repo: https://github.com/gabrie30/ghorg
godoc.org: https://godoc.org/github.com/gabrie30/ghorg
goreportcard.com: https://goreportcard.com/report/github.com/gabrie30/ghorg
coverage service link: https://gocover.io/github.com/gabrie30/ghorg

update description of existing app

---

README.md

- github.com repo: https://github.com/AppsFlyer/go-sundheit
- godoc.org: https://godoc.org/github.com/AppsFlyer/go-sundheit
- goreportcard.com: https://goreportcard.com/report/github.com/AppsFlyer/go-sundheit
- coverage service link: https://coveralls.io/github/AppsFlyer/go-sundheit?branch=master

Added go-sundheit - a service health checks lib to distributed systems section

---

README.md

- github.com repo: https://github.com/clevabit/libgoffi
- godoc.org: https://godoc.org/github.com/clevabit/libgoffi
- goreportcard.com: https://goreportcard.com/report/github.com/clevabit/libgoffi
- coveralls.io: https://coveralls.io/github/clevabit/libgoffi?branch=master

Added libgoffi, an adapter library for integrating libffi in a way that it looks like native Go functions

---

README.md

- github.com repo: https://github.com/abdullahselek/go-here
- godoc.org: https://godoc.org/github.com/abdullahselek/go-here/here
- goreportcard.com: https://goreportcard.com/report/github.com/abdullahselek/go-here
- coverage service link: https://codecov.io/gh/abdullahselek/go-here

Add go-here under third party apis.

---

README.md

- github.com repo: https://github.com/sagikazarmark/modern-go-application
- godoc.org: https://godoc.org/sagikazarmark/modern-go-application
- goreportcard.com: https://goreportcard.com/report/github.com/sagikazarmark/modern-go-application
Coverage does not really make sense for this package as it's mostly a template project with dummy content.
**Make sure …

Add modern go application

---

README.md

- github.com repo: https://github.com/ozankasikci/dockerfile-generator
- godoc.org: https://godoc.org/github.com/ozankasikci/dockerfile-generator
- goreportcard.com: https://goreportcard.com/report/github.com/ozankasikci/dockerfile-generator
- coverage service link: https://coveralls.io/github/ozankasikci/dockerfile-generator?branch=master

Add Dockerfile-Generator under DevOps Tools

---

README.md

- github.com repo: https://github.com/ztrue/shutdown
- godoc.org: https://godoc.org/github.com/ztrue/shutdown
- goreportcard.com: https://goreportcard.com/report/github.com/ztrue/shutdown
- coverage service link: https://coveralls.io/github/ztrue/shutdown?branch=master

Add ztrue/shutdown in utils

---

README.md

- github.com repo: https://github.com/nasermirzaei89/env
- godoc.org: https://godoc.org/github.com/nasermirzaei89/env
- goreportcard.com: https://goreportcard.com/report/github.com/nasermirzaei89/env
- coverage service link ([gocover](http://gocover.io/), [coveralls](https://coveralls.io/) etc.): https://codecov.io/gh/nasermirzaei89/env

add env package

---

README.md

- github.com repo: https://github.com/joeig/go-powerdns
- godoc.org: https://godoc.org/github.com/joeig/go-powerdns
- goreportcard.com: https://goreportcard.com/report/github.com/joeig/go-powerdns
- coverage service link ([gocover](http://gocover.io/), [coveralls](https://coveralls.io/) etc.): https://coveralls.io/github/joeig/go-powerdns?branch=master …

Add go-powerdns

---

README.md

- github.com repo: https://github.com/skeema/skeema
- godoc.org: https://godoc.org/github.com/skeema/skeema
- goreportcard.com: https://goreportcard.com/report/github.com/skeema/skeema (A+, gocyclo 98%)
- coverage service link: https://coveralls.io/github/skeema/skeema (91%)

Add Skeema to section for database schema migration

---

README.md

- github.com repo: https://github.com/bigfile/bigfile
- godoc.org: https://godoc.org/github.com/bigfile/bigfile
- goreportcard.com: [![go-report](https://goreportcard.com/badge/github.com/bigfile/bigfile)](https://goreportcard.com/report/github.com/bigfile/bigfile) [![golangci](https://golangci.com/badges/github.com/bigfile/bigfile.svg)](https://golangci.com/r/github.com/bigfile/bigfile)
- coverage service link: [![codecov](https://codecov.io/gh/bigfile/bigfile/branch/master/graph/badge.svg)](https://codecov.io/gh/bigfile/bigfile) …

add bigfile

---

README.md

- github.com repo: https://github.com/edermanoel94/rest-go
- godoc.org: https://godoc.org/github.com/edermanoel94/rest-go
- goreportcard.com: https://goreportcard.com/report/github.com/edermanoel94/rest-go
- coverage service link ([gocover](https://gocover.io/github.com/edermanoel94/rest-go), [coveralls](https://coveralls.io/) etc.) https://gocover.io/github.com/edermanoel94/rest-go …

Add rest-go

---

README.md

- github.com repo: https://github.com/SonicRoshan/falcon, https://github.com/SonicRoshan/straf
- godoc.org: https://godoc.org/github.com/SonicRoshan/falcon,  https://godoc.org/github.com/SonicRoshan/straf
- goreportcard.com: https://goreportcard.com/report/github.com/SonicRoshan/falcon, https://goreportcard.com/report/github.com/SonicRoshan/straf
- coverage service link https://gocover.io/github.com/SonicRoshan/falcon, https://gocover.io/github.com/SonicRoshan/straf
- I have added my package in alphabetical order.
- I have an appropriate description …

Add Falcon And Straf

---

README.md

- github.com repo: https://github.com/viant/afs
- godoc.org: https://godoc.org/github.com/viant/afs
- goreportcard.com: https://goreportcard.com/report/github.com/viant/afs
- coverage service link: https://gocover.io/github.com/viant/afs

Added abstract file storage (file,scp,gs,s3,mem)

---

README.md

Add Golang Developer Job Board

---

README.md

- github.com repo: https://github.com/krotik/dudeldu
- godoc.org: https://godoc.org/devt.de/krotik/dudeldu
- goreportcard.com: https://goreportcard.com/report/devt.de/krotik/dudeldu
- coverage service link [gocover](https://gocover.io/github.com/krotik/dudeldu) / <a href="https://void.devt.de/pub/dudeldu/coverage.txt"><img src="https://void.devt.de/pub/dudeldu/test_result.svg" alt="Code coverage"></a>
Note: The linked github repo in the README.md is a mirror of (devt.de/krotik/dudeldu) - I would like to use it to cope with traffic and receive stars. …

Add dudeldu

---

README.md

Adds github.com/adlio/schema.
- github.com repo: https://github.com/adlio/schema
- godoc.org: https://godoc.org/github.com/adlio/schema
- goreportcard.com: https://goreportcard.com/report/github.com/adlio/schema
- coveralls.io: https://codecov.io/gh/adlio/schema (94% code coverage)

Adds adlio/schema

---

README.md

- github.com repo: https://github.com/loveleshsharma/gohive
- godoc.org: https://godoc.org/github.com/loveleshsharma/gohive
- goreportcard.com: https://goreportcard.com/report/github.com/loveleshsharma/gohive
- coverage service link ([gocover](http://gocover.io/), [coveralls](https://coveralls.io/) etc.) https://codecov.io/gh/loveleshsharma/gohive …

Add gohive

---

CONTRIBUTING.md

Remove requirement for two reviews

---

README.md

https://github.com/tdewolff/canvas
[![GoDoc](http://godoc.org/github.com/tdewolff/canvas?status.svg)](http://godoc.org/github.com/tdewolff/canvas) [![Build Status](https://travis-ci.org/tdewolff/canvas.svg?branch=master)](https://travis-ci.org/tdewolff/canvas) [![Go Report Card](https://goreportcard.com/badge/github.com/tdewolff/canvas)](https://goreportcard.com/report/github.com/tdewolff/canvas) [![Coverage Status](https://coveralls.io/repos/github/tdewolff/canvas/badge.svg?branch=master)](https://coveralls.io/github/tdewolff/canvas?branch=master)
Creating a new pull request. I've increased test coverage from 20% to 90%, which was a lot of work but I've fixed at least 5 bugs in the meantime, so that's worth the effort! Thanks!

Add tdewolff/canvas

---

README.md

- github.com repo: https://github.com/rocketlaunchr/remember-go/
- godoc.org: https://godoc.org/github.com/rocketlaunchr/remember-go
- goreportcard.com: https://goreportcard.com/report/github.com/rocketlaunchr/remember-go
- coverage service link: https://gocover.io/github.com/rocketlaunchr/remember-go
- [ *] I have added my package in alphabetical order.
- [ *] I have an …

Add remember-go

---

README.md

- github.com repo: https://github.com/go-jet/jet
- godoc.org: https://godoc.org/github.com/go-jet/jet
- goreportcard.com: https://goreportcard.com/report/github.com/go-jet/jet
- coverage service link ([gocover](http://gocover.io/), [coveralls](https://coveralls.io/) etc.) https://codecov.io/gh/go-jet/jet/branch/master
[![Go Report Card](https://goreportcard.com/badge/github.com/go-jet/jet)](https://goreportcard.com/report/github.com/go-jet/jet)
[![Documentation](https://godoc.org/github.com/go-jet/jet?status.svg)](http://godoc.org/github.com/go-jet/jet …

Add go-jet. Type safe SQL Builder for Go with automatic scan to desired arbitrary object structure.

---

README.md

- github.com repo: https://github.com/qmuntal/stateless/
- godoc.org: https://godoc.org/github.com/qmuntal/stateless
- goreportcard.com: https://goreportcard.com/report/github.com/qmuntal/stateless
- coverage service link [coveralls](https://coveralls.io/github/qmuntal/stateless?branch=master)

Add qmuntal/stateless

---

README.md

- github.com repo: https://github.com/wI2L/jettison
- godoc.org: https://godoc.org/github.com/wI2L/jettison
- goreportcard.com: https://goreportcard.com/report/wI2L/jettison
- coverage service link: https://codecov.io/gh/wI2L/jettison
**Disclaimer**: I am the author and maintainer of this package. Please also note that the coverage …

Add wI2L/jettison

---

README.md

- github.com repo: https://github.com/mennanov/limiters
- godoc.org: https://godoc.org/github.com/mennanov/limiters
- goreportcard.com: https://goreportcard.com/report/github.com/mennanov/limiters
- coverage service link ([gocover](http://gocover.io/), [coveralls](https://coveralls.io/) etc.) https://codecov.io/gh/mennanov/limiters

Add mennanov/limiters

---

README.md

- github.com repo: https://github.com/xhit/go-simple-mail
- godoc.org: https://godoc.org/github.com/xhit/go-simple-mail
- goreportcard.com: https://goreportcard.com/report/github.com/xhit/go-simple-mail
- coverage service link: https://gocover.io/github.com/xhit/go-simple-mail
- [CHECKED] I have added my package in alphabetical order.
- [CHECKED] I have an appropriate description with correct …

Added go-simple-mail

---

README.md

> `github.com/cabify/logrusiowriter` is an `io.Writer` implementation that
used `logrus` logger as output.
- github.com repo: https://github.com/cabify/logrusiowriter
- godoc.org: https://godoc.org/github.com/cabify/logrusiowriter
- goreportcard.com: https://goreportcard.com/report/github.com/cabify/logrusiowriter
- coverage service link: https://coveralls.io/github/cabify/logrusiowriter?branch=master

Add github.com/cabify/logrusiowriter

---

README.md

- github.com repo: https://github.com/bsm/redislock
- godoc.org: http://godoc.org/github.com/bsm/redislock
- goreportcard.com: https://goreportcard.com/report/github.com/bsm/redislock
- coverage service link ([gocover](http://gocover.io/), [coveralls](https://coveralls.io/) etc.) : 

update redis-lock deprecated repository link

---

README.md

- github.com repo: https://github.com/tmrts/go-patterns
- godoc.org:
- goreportcard.com: https://goreportcard.com/report/github.com/tmrts/go-patterns

add Go design patterns

---

README.md

The prose package is only for English

---

README.md

- github.com repo:https://github.com/golobby/container
- godoc.org:https://godoc.org/github.com/golobby/container
- goreportcard.com:https://goreportcard.com/report/github.com/golobby/container
- coverage service link ([coveralls](https://coveralls.io/github/golobby/container?branch=master))

Add golobby/container to the list of Dependency Injection packages

---

README.md

Gorgonia has moved to an organization, the old URL is still valid, but no more updates are made on the repository owned by chewxy one.
---
- github.com repo: https://github.com/gorgonia/gorgonia
- godoc.org: https://godoc.org/gorgonia.org/gorgonia
- goreportcard.com: https://goreportcard.com/report/github.com/gorgonia/gorgonia
- coverage service link [coveralls](https://coveralls.io/github/gorgonia/gorgonia?branch=master ) …

fix(gorgonia): repo URL has changed

---

README.md

- github.com repo: https://github.com/google/cel-go
- godoc.org: https://godoc.org/github.com/google/cel-go
- goreportcard.com: https://goreportcard.com/report/github.com/google/cel-go
- coverage service link ([gocover](https://gocover.io/github.com/google/cel-go/cel))

Add cel-go

---

README.md

- github.com repo: https://github.com/parsyl/parquet
- godoc.org: https://godoc.org/github.com/parsyl/parquet
- goreportcard.com: https://goreportcard.com/report/github.com/parsyl/parquet
- coverage service link ([gocover](http://gocover.io/), [coveralls](https://coveralls.io/) etc.) https://gocover.io/github.com/parsyl/parquet

Add Parsyl's parquet reader/writer lib

---

README.md

- https://github.com/prologic/bitcask
- https://godoc.org/github.com/prologic/bitcask
- https://goreportcard.com/report/github.com/prologic/bitcask
- https://codecov.io/gh/prologic/bitcask

Adds bitcask & bitraft to Database section

---

README.md

- github.com repo: https://github.com/jgroeneveld/schema
- godoc.org: https://godoc.org/github.com/jgroeneveld/schema
- goreportcard.com: https://goreportcard.com/report/github.com/jgroeneveld/schema
https://gocover.io/github.com/jgroeneveld/schema (92%) …

add schema

---

README.md

- github.com repo: https://github.com/zhshch2002/goribot
- godoc.org: https://godoc.org/github.com/zhshch2002/goribot
- goreportcard.com: https://goreportcard.com/report/github.com/zhshch2002/goribot
- coverage service link ([gocover](http://gocover.io/), [coveralls](https://coveralls.io/) etc.): https://codecov.io/gh/zhshch2002/goribot

add goribot

---

README.md

- github.com repo: https://github.com/johnfercher/maroto
- godoc.org: https://godoc.org/github.com/johnfercher/maroto
- goreportcard.com: https://goreportcard.com/report/github.com/johnfercher/maroto
- coverage service link: https://codecov.io/gh/johnfercher/maroto

Add maroto

---

README.md

gev is a lightweight, fast non-blocking TCP network library based on Reactor mode.
[![Github Actions](https://github.com/Allenxuxu/gev/workflows/CI/badge.svg)](https://github.com/Allenxuxu/gev/actions)
[![Go Report Card](https://goreportcard.com/badge/github.com/Allenxuxu/gev)](https://goreportcard.com/report/github.com/Allenxuxu/gev)
[![Codacy Badge](https://api.codacy.com/project/badge/Grade/a2a55fe9c0c443e198f588a6c8026cd0)](https://www.codacy.com/manual/Allenxuxu/gev?utm_source=github.com&amp;utm_medium=referral&amp;utm_content=Allenxuxu/gev&amp;utm_campaign=Badge_Grade)
[![GoDoc](https://godoc.org/github.com/Allenxuxu/gev?status.svg)](https://godoc.org/github.com/Allenxuxu/gev)
[![LICENSE](https://img.shields.io/badge/LICENSE-MIT-blue)](https://github.com/Allenxuxu/gev/blob/master/LIC …

Add Allenxuxu/gev

---

README.md

- github.com repo: https://github.com/fxamacker/cbor
- godoc.org: https://godoc.org/github.com/fxamacker/cbor
- goreportcard.com: https://goreportcard.com/report/github.com/fxamacker/cbor
- coverage service link: https://codecov.io/gh/fxamacker/cbor

Add fxamacker/cbor

---

README.md

Add new resource

---

README.md

doc: Add link for Berlin meetup group

---

README.md

- github.com repo: [https://github.com/wroge/wgs84](https://github.com/wroge/wgs84)
- godoc.org: [https://godoc.org/github.com/wroge/wgs84](https://godoc.org/github.com/wroge/wgs84)
- goreportcard.com: [https://goreportcard.com/report/github.com/wroge/wgs84](https://goreportcard.com/report/github.com/wroge/wgs84)
- coverage service link: [Codegov](https://codecov.io/gh/wroge/wgs84), [GoCover](https://gocover.io/github.com/wroge/wgs84) …

Add wroge/wgs84

---

README.md

The next location for GopherCon will be Berlin, Germany (https://twitter.com/gopherconeu) Just updated this small change :)
Thanks for this beautiful list!

Update GopherCon Europe to Berlin

---

README.md

- github.com repo: https://github.com/PumpkinSeed/bucket
- godoc.org: http://godoc.org/github.com/PumpkinSeed/bucket
- goreportcard.com: https://goreportcard.com/report/github.com/PumpkinSeed/bucket
- coverage service link: coverage not provided, because of the docker dependencies
- travis: https://travis-ci.com/PumpkinSeed/bucket

Add bucket to the database tools

---

README.md

- github.com repo: https://github.com/jenkins-zh/jenkins-cli
- godoc.org: https://godoc.org/github.com/jenkins-zh/jenkins-cli
- goreportcard.com: https://goreportcard.com/report/github.com/jenkins-zh/jenkins-cli
- coverage service link ([sonarqube](https://sonarcloud.io/dashboard?id=jenkins-zh_jenkins-cli))

Add jcli add a devops tool

---

README.md

- github.com repo: https://github.com/verifid/vl-go
- godoc.org: https://godoc.org/github.com/verifid/vl-go/vlgo
- goreportcard.com: https://goreportcard.com/report/github.com/verifid/vl-go
- coverage service link: https://codecov.io/gh/verifid/vl-go

Add vl-go api client.

---

README.md

- github.com repo: https://github.com/eko/gocache
- godoc.org: https://godoc.org/github.com/eko/gocache
- goreportcard.com: https://goreportcard.com/report/github.com/eko/gocache
- coverage service link ([gocover](http://gocover.io/), [coveralls](https://coveralls.io/) etc.): https://codecov.io/gh/eko/gocache

Add eko/gocache

---

README.md

- github.com repo: [GitHub](https://github.com/jfeliu007/goplantuml)
- godoc.org: [GoDoc](https://godoc.org/github.com/jfeliu007/goplantuml/parser)
- goreportcard.com: [Go Report](https://goreportcard.com/report/github.com/jfeliu007/goplantuml)
- coverage service link: [codecov.io](https://codecov.io/gh/jfeliu007/goplantuml)

Added GoPlantUML to awesome-go

---

README.md

- github.com repo: https://github.com/dikhan/terraform-provider-openapi
- godoc.org: https://godoc.org/github.com/dikhan/terraform-provider-openapi
- goreportcard.com: https://goreportcard.com/report/github.com/dikhan/terraform-provider-openapi
- coverage service link ([gocover](http://gocover.io/), [coveralls](https://coveralls.io/) etc.): https://codecov.io/gh/dikhan/terraform-provider-openapi/ …

Add terraform-provider-openapi

---

README.md

Package without tests.
Latest update  Dec 21, 2014

Removed untested ian-kent/goose

---

README.md

Update http clients section

---

README.md

The repository has been archived and marked as deprecated in the README.

remove jwc

---

README.md

The repo has been archived and the readme claims that there is no
maintenance.

remove color

---

README.md

- github.com repo: https://github.com/claygod/coffer
- godoc.org: https://godoc.org/github.com/claygod/coffer
- goreportcard.com: https://goreportcard.com/report/github.com/claygod/coffer
- coverage service link [codecov](https://codecov.io/gh/claygod/coffer)

Add Coffer

---

README.md

- github.com repo: https://github.com/i-love-flamingo/flamingo
- godoc.org: https://godoc.org/flamingo.me/flamingo
- goreportcard.com: https://goreportcard.com/report/github.com/i-love-flamingo/flamingo
- coverage service link ([gocover](http://gocover.io/), [coveralls](https://coveralls.io/github/i-love-flamingo/flamingo ) - pending setup
Coverage report:
ok  	flamingo.me/flamingo/v3/core/cache	0.040s	coverage: 18.2% of statements
ok  	flamingo.me/flamingo/v3/core/gotemplate	0.035s	coverage: 5.5% of statements
ok  	flamingo.me/flamingo/v3/core/healthcheck	0.036s	coverage: 72.7% of statements
?   	flamingo.me/flamingo/v3/core/healthcheck/domain/healthcheck	[no test files]
ok  	flamingo.me/flamingo/v3/core/healthcheck/interfaces/controllers	0.032s	coverage: 75.0% of statements
ok …

Add flamingo framework

---

README.md

- github.com repo: https://github.com/gopinath-langote/1build
- godoc.org: https://godoc.org/github.com/gopinath-langote/1build
- goreportcard.com: https://goreportcard.com/report/github.com/gopinath-langote/1build
- coverage service link : https://app.codacy.com/manual/gopinath-langote/1build/dashboard

Add 1build - command line

---

README.md

- github.com repo:https://github.com/golobby/config
- godoc.org:https://godoc.org/github.com/golobby/config
- goreportcard.com:https://goreportcard.com/report/github.com/golobby/config
- coverage service link ([coveralls](https://coveralls.io/github/golobby/config?branch=master))

Add golobby/config

---

README.md

- github.com repo: https://github.com/grafov/m3u8
- godoc.org: http://godoc.org/github.com/grafov/m3u8
- goreportcard.com: https://goreportcard.com/report/github.com/grafov/m3u8

Add video/m3u8 library

---

README.md

- github.com repo: https://github.com/mailchain/mailchain
- godoc.org: https://godoc.org/github.com/mailchain/mailchain
- goreportcard.com: https://goreportcard.com/report/github.com/mailchain/mailchain
- coverage service link: https://coveralls.io/github/mailchain/mailchain?branch=master

Added Mailchain to awesome-go

---

README.md

- github.com repo: https://github.com/1set/cronrange
- godoc.org: https://godoc.org/github.com/1set/cronrange
- goreportcard.com: https://goreportcard.com/report/github.com/1set/cronrange
- coverage service link ([gocover](http://gocover.io/), [coveralls](https://coveralls.io/) etc.) https://codecov.io/gh/1set/cronrange/branch/master

Add cronrange package in 'Date and Time' section

---

README.md

- github.com repo: https://github.com/ovh/cds
- godoc.org: https://godoc.org/github.com/ovh/cds/sdk/cdsclient
- goreportcard.com: https://goreportcard.com/report/github.com/ovh/cds
- coverage service link: Free coverage services are crashing due to the number of tests and the size of codebase.

Add CDS entry in 'Continuous Integration' section

---

README.md

- github.com repo: https://github.com/ovh/utask
- godoc.org: https://godoc.org/github.com/ovh/utask
- goreportcard.com: https://goreportcard.com/report/github.com/ovh/utask
- coverage service link: https://coveralls.io/github/ovh/utask?branch=master

Add uTask in 'DevOps Tools' section

---

README.md

- github.com repo: https://github.com/posener/cmd
- godoc.org: https://godoc.org/github.com/posener/cmd
- goreportcard.com: https://goreportcard.com/report/github.com/posener/cmd
- coverage service link: https://codecov.io/gh/posener/cmd

add posener/cmd

---

README.md

- github.com repo: https://github.com/wesovilabs/beyond
- godoc.org: https://godoc.org/github.com/wesovilabs/beyond
- goreportcard.com: https://goreportcard.com/report/github.com/wesovilabs/beyond
- coverage service link ([gocover](http://gocover.io/), [coveralls](https://coveralls.io/) etc.) https://codecov.io/gh/wesovilabs/beyond
- [ X] I have added my package in alphabetical …

feat: adding beyond as a new utility

---

README.md

- github.com repo: https://github.com/m1/gospin
- godoc.org: https://godoc.org/github.com/m1/gospin
- goreportcard.com: https://goreportcard.com/report/github.com/m1/gospin
- coverage service link ([gocover](http://gocover.io/), [coveralls](https://coveralls.io/) etc.) https://coveralls.io/github/m1/gospin

add gospin

---

README.md

- github.com repo: https://github.com/zhenghaoz/gorse
- godoc.org: [![GoDoc](https://godoc.org/github.com/zhenghaoz/gorse?status.svg)](https://godoc.org/github.com/zhenghaoz/gorse)
- goreportcard.com: [![Go Report Card](https://goreportcard.com/badge/github.com/zhenghaoz/gorse)](https://goreportcard.com/report/github.com/zhenghaoz/gorse)
- coverage service link [![codecov](https://codecov.io/gh/zhenghaoz/gorse/branch/master/graph/badge.svg)](https://codecov.io/gh/zhenghaoz/gorse) …

update gorse in ML section

---

README.md

pipe doesn't exist anymore

---

README.md

- github.com repo: https://github.com/lacion/cookiecutter-golang
- godoc.org: NA
- goreportcard.com: https://goreportcard.com/report/github.com/lacion/cookiecutter_golang_example
- coverage service link: NA

Add cookiecutter-golang

---

README.md

- github.com repo: https://github.com/m1/go-generate-password
- godoc.org: https://godoc.org/github.com/m1/go-generate-password
- goreportcard.com: https://goreportcard.com/report/github.com/m1/go-generate-password 
- coverage service link ([gocover](http://gocover.io/), [coveralls](https://coveralls.io/) etc.): https://codecov.io/gh/m1/go-generate-password …

add go-generate-password

---

README.md

- github.com repo: https://github.com/disksing/iter
- godoc.org: https://godoc.org/github.com/disksing/iter
- goreportcard.com: https://goreportcard.com/report/github.com/disksing/iter
- coverage service link ([gocover](http://gocover.io/), [coveralls](https://coveralls.io/) etc.) https://codecov.io/gh/disksing/iter

add disksing/iter

---

README.md

- github.com repo: https://github.com/go-joe/joe
- godoc.org: https://godoc.org/github.com/go-joe/joe
- goreportcard.com: https://goreportcard.com/report/github.com/go-joe/joe
- coverage service link: https://codecov.io/gh/go-joe/joe
- Very good coverage: :heavy_check_mark: 
- Library meets [quality standards](https://github.com/avelino/awesome-go/blob/master/CONTRIBUTING.md#quality-standard): :heavy_check_mark: 
- No new category: :heavy_check_mark: 

add goe-joe

---

README.md

Add [queryparam](https://github.com/tomwright/queryparam) to list.
- Repo: https://github.com/tomwright/queryparam
- 100% coverage: https://codecov.io/gh/TomWright/queryparam
- 100% on goreportcard: https://goreportcard.com/report/github.com/tomwright/queryparam
- Godoc with examples: https://godoc.org/github.com/TomWright/queryparam

Add queryparam package to readme.

---

README.md

Was missing ecommerce section and added that with a reference to Flamingo Commerce (not sure if there is a better fitting section?)
- github.com repo: https://github.com/i-love-flamingo/flamingo-commerce
- goreportcard.com: https://goreportcard.com/report/github.com/i-love-flamingo/flamingo-commerce
- godoc.org: https://godoc.org/flamingo.me/flamingo-commerce/cart/domain/cart
- coverage service link ([gocover](http://gocover.io/), [coveralls](https://coveralls.io/github/i-love-flamingo/flamingo-commerce ) - pending setup
- Demo: https://demoshop.flamingo.me

Add ecommerce section with flamingo commerce

---

README.md

- github.com repo: https://github.com/i-love-flamingo/dingo
- godoc.org: https://godoc.org/flamingo.me/dingo
- goreportcard.com: https://goreportcard.com/report/flamingo.me/dingo
- coverage service link: https://gocover.io/flamingo.me/dingo (gocover.io seems broken, overall coverage is at 81%)
- [*] I know that this package was not listed before.
- [*] I have added …

Add Dingo dependency injection

---

README.md

- github.com repo: https://github.com/scryinfo/dp
- godoc.org: https://godoc.org/github.com/scryinfo/dp
- goreportcard.com: https://goreportcard.com/report/github.com/scryinfo/dp
- coverage service link ([gocover](http://gocover.io/), [coveralls](https://coveralls.io/) etc.): https://codecov.io/gh/scryinfo/dp

add dp project to miscellaneous

---

README.md

- github.com repo: https://github.com/cyruzin/tome
- godoc.org: https://godoc.org/github.com/cyruzin/tome
- goreportcard.com: https://goreportcard.com/report/github.com/cyruzin/tome
- coverage service link: https://coveralls.io/github/cyruzin/tome?branch=master

Added package tome to the utilities list

---

README.md

- github.com repo: https://github.com/panjf2000/gnet
- godoc.org: [![Doc for panjf2000/gnet](https://img.shields.io/badge/api-reference-blue.svg?style=flat-square)](https://gowalker.org/github.com/panjf2000/gnet?lang=en-US)
- goreportcard.com: [![Go Report Card](https://goreportcard.com/badge/github.com/panjf2000/gnet?style=flat-square)](https://goreportcard.com/report/github.com/panjf2000/gnet)
- coverage service link: [![codecov for panjf2000/gnet](https://img.shields.io/codecov/c/github/panjf2000/gnet?style=flat-square)](https://codecov.io/gh/panjf2000/gnet)

Update description of networking framework: gnet

---

README.md

Library for easy use Random Forest - https://en.wikipedia.org/wiki/Random_forest
Github: https://github.com/malaschitz/randomForest
GoDoc: https://godoc.org/github.com/malaschitz/randomForest
GoReportCard: https://goreportcard.com/report/github.com/malaschitz/randomForest
Coverage is >95%, but tests are very long - test are done for https://en.wikipedia.org/wiki/MNIST_database (10 min)

randomforest library

---

README.md

- github.com repo: https://github.com/ilyakaznacheev/cleanenv
- godoc.org: https://godoc.org/github.com/ilyakaznacheev/cleanenv
- goreportcard.com: https://goreportcard.com/report/github.com/ilyakaznacheev/cleanenv
- coverage service link: https://codecov.io/gh/ilyakaznacheev/cleanenv

Add cleanenv configuration library

---

README.md

- github.com repo: https://github.com/m1/go-localize
- godoc.org: https://godoc.org/github.com/m1/go-localize
- goreportcard.com: https://goreportcard.com/report/github.com/m1/go-localize
- coverage service link ([gocover](http://gocover.io/), [coveralls](https://coveralls.io/) etc.) https://codecov.io/gh/m1/go-localize

add go-localize

---

README.md

- github.com repo: https://github.com/gotidy/ptr
- godoc.org: https://godoc.org/github.com/gotidy/ptr
- goreportcard.com: https://goreportcard.com/report/github.com/gotidy/ptr
- coverage service link ([gocover](http://gocover.io/), [coveralls](https://goreportcard.com/) etc.): https://gocover.io/github.com/gotidy/ptr

Added "ptr" package to miscellaneous

---

README.md

- github.com repo: https://github.com/detectlanguage/detectlanguage-go
- godoc.org: https://godoc.org/github.com/detectlanguage/detectlanguage-go
- goreportcard.com: https://goreportcard.com/report/github.com/detectlanguage/detectlanguage-go
- gocover.io: https://gocover.io/github.com/detectlanguage/detectlanguage-go

Add Language Detection API Go client

---

README.md

- github.com repo: https://github.com/unit-io/tracedb
- godoc.org: https://godoc.org/github.com/unit-io/tracedb
- goreportcard.com: https://goreportcard.com/report/github.com/unit-io/tracedb
- coverage service link ([gocover](http://gocover.io/), [coveralls](https://coveralls.io/) etc.): https://coveralls.io/github/unit-io/tracedb
- [*] I have added my package in alphabetical …

Add tracedb to readme file

---

README.md

- github.com repo: https://github.com/ianlopshire/go-ssm-config
- godoc.org: https://godoc.org/github.com/ianlopshire/go-ssm-config
- goreportcard.com: https://goreportcard.com/report/github.com/ianlopshire/go-ssm-config
- coverage service link ([gocover](http://gocover.io/), [coveralls](https://coveralls.io/) etc.): https://gocover.io/github.com/ianlopshire/go-ssm-config
Thanks …

Add go-ssm-config

---

README.md

- github.com repo:[https://github.com/panjf2000/ants](https://github.com/panjf2000/ants)
- godoc.org:[![godoc for panjf2000/ants](https://godoc.org/github.com/panjf2000/ants?status.svg)](https://godoc.org/github.com/panjf2000/ants)
- goreportcard.com:[![goreportcard for panjf2000/ants](https://goreportcard.com/badge/github.com/panjf2000/ants)](https://goreportcard.com/report/github.com/panjf2000/ants)
- coverage service link:[![codecov](https://codecov.io/gh/panjf2000/ants/branch/master/graph/badge.svg)](https://codecov.io/gh/panjf2000/ants)
- build status:[![Build Status](https://travis-ci.com/panjf2000/ants.svg?branch=master)](https://travis-ci.com/panjf2000/ants)

Update description of ants

---

README.md

- github.com repo: [wzshiming/httpproxy](https://github.com/wzshiming/httpproxy)
- godoc.org: [![GoDoc](https://godoc.org/github.com/wzshiming/httpproxy?status.svg)](https://godoc.org/github.com/wzshiming/httpproxy)
- goreportcard.com: [![Go Report Card](https://goreportcard.com/badge/github.com/wzshiming/httpproxy)](https://goreportcard.com/report/github.com/wzshiming/httpproxy)
- coverage service link: [![gocover.io](https://gocover.io/_badge/github.com/wzshiming/httpproxy)](https://gocover.io/github.com/wzshiming/httpproxy) …

Add httpproxy

---

README.md

- github.com repo: https://github.com/koltyakov/gosip
- godoc.org: https://godoc.org/github.com/koltyakov/gosip
- goreportcard.com: https://goreportcard.com/report/github.com/koltyakov/gosip
- coverage service link: https://codecov.io/gh/koltyakov/gosip

Add gosip, client library for SharePoint API

---

README.md

- github.com repo: [lucassscaravelli/ej](https://github.com/lucassscaravelli/ej)
- godoc.org: [![GoDoc](https://godoc.org/github.com/lucassscaravelli/ej?status.svg)](https://godoc.org/github.com/lucassscaravelli/ej)
- goreportcard.com: [![Go Report Card](https://goreportcard.com/badge/github.com/lucassscaravelli/ej)](https://goreportcard.com/report/github.com/lucassscaravelli/ej)
- coverage service link: [![Coverage Status](https://coveralls.io/repos/github/lucassscaravelli/ej/badge.svg?branch=master)](https://coveralls.io/github/lucassscaravelli/ej?br …

Add lucassscaravelli/ej

---

README.md

- github.com repo:https://github.com/ITcathyh/conexec
- godoc.org:https://godoc.org/github.com/ITcathyh/conexec
- goreportcard.com:https://goreportcard.com/report/github.com/ITcathyh/conexec
- coverage service link ([gocover](http://gocover.io/), [coveralls](https://coveralls.io/) etc.):https://codecov.io/gh/ITcathyh/conexec

Add conexec package to Goroutines category

---

README.md

Wasn't really sure where should this go, but I guess people would look for it in Testing section.
- github.com repo: https://github.com/cabify/timex
- godoc.org: https://godoc.org/github.com/cabify/timex
- goreportcard.com: https://goreportcard.com/report/github.com/cabify/timex
- coverage service link: https://coveralls.io/github/cabify/timex?branch=master (100%)
Thanks, you're awesome! :+1:

Add github.com/cabify/timex to Testing/Mocks

---

README.md

Just a quick change to an existing project entry.

Update Fyne description to match new release info

---

README.md

bolt is archived by the owner
- godoc.org:

add database bbolt

---

README.md

- github.com repo: https://github.com/dathoangnd/gonet
- godoc.org: https://godoc.org/github.com/dathoangnd/gonet
- goreportcard.com: https://goreportcard.com/report/github.com/dathoangnd/gonet
- coverage service link: [gocover](https://gocover.io/github.com/dathoangnd/gonet)

Add dathoangnd/gonet

---

README.md

- github.com repo: https://github.com/twharmon/gostore
- godoc.org: https://godoc.org/github.com/twharmon/gostore
- goreportcard.com: https://goreportcard.com/report/github.com/twharmon/gostore
- coverage service link: https://gocover.io/github.com/twharmon/gostore

add entry to databases

---

README.md

- github.com repo: https://github.com/m1/go-finnhub
- godoc.org: https://godoc.org/github.com/m1/go-finnhub
- goreportcard.com: https://goreportcard.com/report/github.com/m1/go-finnhub
- coverage service link ([gocover](http://gocover.io/), [coveralls](https://coveralls.io/) etc.) https://codecov.io/gh/m1/go-finnhub

add go-finnhub

---

README.md

- github.com repo: https://github.com/pdupub/go-pdu
- godoc.org: https://godoc.org/github.com/pdupub/go-pdu
- goreportcard.com: https://goreportcard.com/report/github.com/pdupub/go-pdu
- coverage service link: https://coveralls.io/github/pdupub/go-pdu?branch=master

Add go-pdu

---

README.md

- github.com repo: https://github.com/gempir/go-twitch-irc
- godoc.org: https://godoc.org/github.com/gempir/go-twitch-irc
- goreportcard.com: https://goreportcard.com/report/github.com/gempir/go-twitch-irc
- coverage service link: https://coveralls.io/github/gempir/go-twitch-irc?branch=master

Add go-twitch-irc

---

README.md

- [github.com repo](https://github.com/PumpkinSeed/errors)
- [godoc.org](https://godoc.org/github.com/PumpkinSeed/errors)
- [goreportcard.com](https://goreportcard.com/report/github.com/PumpkinSeed/errors)
- [gocover](https://gocover.io/github.com/PumpkinSeed/errors)

Add github.com/PumpkinSeed/errors

---

README.md

- github.com repo: https://github.com/dnote/dnote
- godoc.org: https://godoc.org/github.com/dnote/dnote
- goreportcard.com: https://goreportcard.com/report/github.com/dnote/dnote
- coverage service link ([gocover](http://gocover.io/), [coveralls](https://coveralls.io/) etc.) https://coveralls.io/github/dnote/dnote
---
I have updated an …

Update outdated description

---

README.md

I'm adding meetup organised by Polish gophers living in Krakow. The group is active and next meetup is happening on March 10th - everyone is welcome!

add GoCracow (Krakow, Poland) meetup

---

README.md

- godoc.org:
- [x ] I have added coverage service link to the repo and to my pull request.
- [ x] I have read [Contribution guidelines](https://github.com/avelino/awesome-go/blob/master/CONTRIBUTING.md#contribution-guidelines), [maintainers …

add social media section incl. reddit

---

README.md

Hi!
I what you want to add package to `awesome-go` and confirm that it meets [quality standards](https://github.com/avelino/awesome-go/blob/master/CONTRIBUTING.md#quality-standard). :)
- github.com repo: https://github.com/spacetab-io/mpath-go
- godoc.org: https://godoc.org/github.com/spacetab-io/mpath-go
- goreportcard.com: https://goreportcard.com/report/github.com/spacetab-io/mpath-go
- coverage service link ([gocover](http://gocover.io/), [coveralls](https://coveralls.io/) etc.): https://codecov.io/gh/spacetab-io/mpath-go
Thanks! You're awesome! :+1:

adding mpath package

---

README.md

- github.com repo: https://github.com/rbretecher/go-postman-collection
- godoc.org: https://godoc.org/github.com/rbretecher/go-postman-collection
- goreportcard.com: https://goreportcard.com/report/github.com/rbretecher/go-postman-collection
- coverage service link: https://codecov.io/gh/rbretecher/go-postman-collection

Add go-postman-collection

---

README.md

Add countries package: https://github.com/biter777/countries
Countries - ISO 3166 (ISO3166-1, ISO3166, Digit, Alpha-2, Alpha-3) countries codes and names (on eng and rus), ISO 4217 currency designators, ITU-T E.164 IDD calling phone codes, countries capitals, UN M.49 regions codes, IANA ccTLD countries domains, IOC/NOC and FIFA codes, VERY FAST, NO maps[], NO slices[], NO external links/files/data, NO interface{}, NO specific dependencies, Databases compatible, Emoji countries flags and currencies support, full support ISO-3166-1, ISO-4217, ITU-T E.164, Unicode CLDR and IANA ccTLD standarts.
Full support ISO-3166-1, ISO-4217, ITU-T E.164, Unicode CLDR and IANA ccTLD standarts.
Please check if what you want to add to `awesome-go` list meets [quality …

Add countries package

---

README.md

**Links**
- github.com repo: https://github.com/otiai10/copy
- godoc.org: https://godoc.org/github.com/otiai10/copy
- goreportcard.com: https://goreportcard.com/report/github.com/otiai10/copy
- coverage service link: https://codecov.io/gh/otiai10/copy
**I checked...**
Thanks you for facilitating, you're awesome! :+1:

Add "copy" package

---

README.md

- github.com repo: https://github.com/alexpantyukhin/go-pattern-match
- godoc.org: https://godoc.org/github.com/alexpantyukhin/go-pattern-match
- goreportcard.com: https://goreportcard.com/report/github.com/alexpantyukhin/go-pattern-match
- coverage service link ([gocover](http://gocover.io/), [coveralls](https://coveralls.io/) etc.): https://gocover.io/github.com/alexpantyukhin/go-pattern-match …

Add pattern matching lib.

---

README.md

- github.com repo: https://github.com/twharmon/goweb
- godoc.org: https://godoc.org/github.com/twharmon/goweb
- goreportcard.com: https://goreportcard.com/report/github.com/twharmon/goweb
- coverage service link: https://gocover.io/github.com/twharmon/goweb

Add Goweb to web frameworks

---

README.md

- github.com repo: https://github.com/xtaci/gaio
- godoc.org: https://godoc.org/github.com/xtaci/gaio
- goreportcard.com: https://goreportcard.com/report/github.com/xtaci/gaio
- coverage service link: https://codecov.io/gh/xtaci/gaio

add package https://github.com/xtaci/gaio

---

README.md

- github.com repo: https://github.com/xiaoxin01/typeregistry
- godoc.org: https://godoc.org/github.com/xiaoxin01/typeregistry
- goreportcard.com: https://goreportcard.com/report/github.com/xiaoxin01/typeregistry
- coverage service link: https://gocover.io/github.com/xiaoxin01/typeregistry

Add typeregistry

---

README.md

- github.com repo: https://github.com/dustinblackman/gomodrun
- godoc.org: https://godoc.org/github.com/dustinblackman/gomodrun
- goreportcard.com: https://goreportcard.com/report/github.com/dustinblackman/gomodrun
- coverage service link: https://coveralls.io/github/dustinblackman/gomodrun?branch=master

Add github.com/dustinblackman/gomodrun

---

README.md

- github.com repo: https://github.com/cyruzin/golang-tmdb
- godoc.org: https://godoc.org/github.com/cyruzin/golang-tmdb
- goreportcard.com: https://goreportcard.com/report/github.com/cyruzin/golang-tmdb
- coverage service link: https://coveralls.io/github/cyruzin/golang-tmdb?branch=master

Add golang-tmdb wrapper

---

README.md

🔌 **[Fiber](https://github.com/gofiber/fiber)** is an [Express.js](https://expressjs.com/en/4x/api.html) styled HTTP web framework implementation running on 🚀 [Fasthttp](https://github.com/valyala/fasthttp), the **fastest** HTTP engine for Go. The package make use of **similar framework convention** as they are in Express.
People switching from [Node.js](https://nodejs.org/en/about/) to [Go](https://golang.org/doc/) often end up in a bad learning curve to start building their webapps, this project is meant to **ease** things up for **fast** development, but with **zero memory allocation** and **performance** in mind.
- github.com repo: https://github.com/gofiber/fiber
- api documentation: https://fiber.wiki
- godoc.org: …

🚀 Add Fiber to Web Frameworks

---

README.md

- github.com repo: http://github.com/Comcast/trickster
- godoc.org: https://godoc.org/github.com/Comcast/trickster
- goreportcard.com: https://goreportcard.com/report/github.com/Comcast/trickster
- coverage service link: https://coveralls.io/github/Comcast/trickster

add trickster to awesome-go:performance

---

README.md

- github.com repo: https://github.com/twharmon/govalid
- godoc.org: https://godoc.org/github.com/twharmon/govalid
- goreportcard.com: https://goreportcard.com/report/github.com/twharmon/govalid
- coverage service link: [gocover](https://gocover.io/github.com/twharmon/govalid)

add govalid

---

README.md

* https://github.com/n0madic/twitter-scraper
* https://godoc.org/github.com/n0madic/twitter-scraper
* https://gocover.io/github.com/n0madic/twitter-scraper
* [![Go Report Card](https://goreportcard.com/badge/github.com/n0madic/twitter-scraper)](https://goreportcard.com/report/github.com/n0madic/twitter-scraper)

twitter-scraper

---

README.md

- github.com repo: https://github.com/consbio/mbtileserver
- godoc.org: [![GoDoc](https://godoc.org/github.com/consbio/mbtileserver?status.svg)](http://godoc.org/github.com/consbio/mbtileserver)
- goreportcard.com: [![Go Report Card](https://goreportcard.com/badge/github.com/consbio/mbtileserver)](https://goreportcard.com/report/github.com/consbio/mbtileserver)
- coverage service link: [![Coverage Status](https://coveralls.io/repos/github/consbio/mbtileserver/badge.svg?branch=master)](https://coveralls.io/github/consbio/mbtileserver?branch=master) …

Add mbtileserver

---

README.md

- github.com repo: https://github.com/guiferpa/gody
- godoc.org: https://godoc.org/github.com/guiferpa/gody
- goreportcard.com: https://goreportcard.com/report/github.com/guiferpa/gody
- coverage service link: https://coveralls.io/github/guiferpa/gody?branch=master

Added gody package

---

README.md

Adding `podcast` to the collection under Text Processing.
**NOTE**: `gocyclo` at 93% will remain because this repo is used as a teaching tool for exactly that type of code quality, and for others to fork and demonstrate improving upon.  After extensive community feedback and discord chats, the community also felt the method length is warranted to keep the logic simple.  
There is really no alternative, as adding private funcs would still require `if` statements - and only removes 6 lines of code from the method overall (which still only got a 95% rating).
As this repo doubles as a teaching tool in many presentations we give, I constantly point out that the line length of the `AddItem` is where sometimes it is warranted to keep the ease of readability.  
The reason why it is so long is …

Add Podcast, iTunes and RSS 2.0 Podcast Generator in Golang

---

README.md

Update repo url for pdfcpu

---

README.md

A simple change to the readme to add the local meetup I help run
- godoc.org:

Add golang north east meetup

---

README.md

- github.com repo: https://github.com/oxyno-zeta/s3-proxy
- godoc.org: https://godoc.org/github.com/oxyno-zeta/s3-proxy
- goreportcard.com: https://goreportcard.com/report/github.com/oxyno-zeta/s3-proxy
- coverage service link ([gocover](http://gocover.io/), [coveralls](https://coveralls.io/) etc.): https://coveralls.io/github/oxyno-zeta/s3-proxy?branch=master

Add s3-proxy project

---

README.md

- github.com repo: https://github.com/mickep76/mapslice-json
- godoc.org: https://godoc.org/github.com/mickep76/mapslice-json
- goreportcard.com: https://goreportcard.com/report/github.com/mickep76/mapslice-json
- coverage service: ```make test``` 87%
- [-] I have added coverage service link to the repo and to my pull request.

add mapslice-json package to json section

---

README.md

Feature-complete web framework aimed at clean code and fast development, with powerful built-in functionalities.
- github.com repo: https://github.com/System-Glitch/goyave
- godoc.org: https://godoc.org/github.com/System-Glitch/goyave
- pkg.go.dev: https://pkg.go.dev/github.com/System-Glitch/goyave/v2
- goreportcard.com: https://goreportcard.com/report/github.com/System-Glitch/goyave
- coverage service link : https://coveralls.io/github/System-Glitch/goyave
Very good coverage (98.588%)

Add Goyave web framework

---

README.md

Hello
- github.com repo: https://github.com/paranoidguy/databunker
- godoc.org: https://godoc.org/github.com/paranoidguy/databunker/src
- goreportcard.com: https://goreportcard.com/report/github.com/paranoidguy/databunker
- coverage service link: https://gocover.io/github.com/paranoidguy/databunker/src
Thanks

Add Paranoidguy Databunker project

---

README.md

- github.com repo: https://github.com/epiclabs-io/elastic
- godoc.org: https://godoc.org/github.com/epiclabs-io/elastic
- goreportcard.com: https://goreportcard.com/report/github.com/epiclabs-io/elastic
- coverage service link ([gocover](https://gocover.io/github.com/epiclabs-io/elastic)

Add elastic type conversion library

---

README.md

- github.com repo: https://github.com/is5/r
- godoc.org: https://godoc.org/github.com/is5/r
- goreportcard.com: https://goreportcard.com/report/github.com/is5/r
- coverage service link: https://codecov.io/gh/is5/r/branch/master

Add is5/r in Utilities section

---

README.md

- github.com repo: https://github.com/utekaravinash/gopaapi5
- godoc.org:https://godoc.org/github.com/utekaravinash/gopaapi5
- goreportcard.com:https://goreportcard.com/report/github.com/utekaravinash/gopaapi5
- coverage service link ([gocover](http://gocover.io/), [coveralls](https://coveralls.io/) etc.): https://coveralls.io/github/utekaravinash/gopaapi5?branch=master
Thanks for …

Add gopaapi5 project

---

README.md

- github.com repo: https://github.com/pjebs/optimus-go
- godoc.org: https://godoc.org/github.com/pjebs/optimus-go
- goreportcard.com: https://goreportcard.com/report/github.com/pjebs/optimus-go
https://gocover.io/github.com/pjebs/optimus-go
- [x ] I have added my package in …

- add github.com/pjebs/optimus-go

---

README.md

- github.com repo: https://github.com/unki2aut/go-mpd
- godoc.org: https://godoc.org/github.com/unki2aut/go-mpd
- goreportcard.com: https://goreportcard.com/report/github.com/unki2aut/go-mpd
- coverage service link [gocover](https://gocover.io/github.com/unki2aut/go-mpd/)

Add go-mpd

---

README.md

- github.com repo: https://github.com/hibiken/asynq
- godoc.org: https://godoc.org/github.com/hibiken/asynq
- goreportcard.com: https://goreportcard.com/report/github.com/hibiken/asynq
- coverage service link ([gocover](http://gocover.io/), [coveralls](https://coveralls.io/) etc.) https://codecov.io/gh/hibiken/asynq

Add Asynq package.

---

README.md

- github.com repo: https://github.com/posener/compare
- pkg.go.dev: https://pkg.go.dev/github.com/posener/compare
- goreportcard.com: https://goreportcard.com/report/github.com/posener/compare
- coverage service link: https://codecov.io/gh/posener/compare

Add posener/compare

---

README.md

* https://github.com/n0madic/google-play-scraper
* https://godoc.org/github.com/n0madic/google-play-scraper/pkg
* https://coveralls.io/github/n0madic/google-play-scraper
* [![Go Report Card](https://goreportcard.com/badge/github.com/n0madic/google-play-scraper)](https://goreportcard.com/report/github.com/n0madic/google-play-scraper)

google-play-scraper

---

README.md

- github.com repo: https://github.com/jfcg/sorty
- godoc.org: https://godoc.org/github.com/jfcg/sorty
- goreportcard.com: https://goreportcard.com/report/github.com/jfcg/sorty
On coverage: Please see *Parameter Tuning* part in sorty repo readme file. Tests take a long time and most files are identical, differeing in the data type of a slice to sort.

add jfcg/sorty

---

README.md

- github.com repo: https://github.com/rekby/lets-proxy2
- godoc.org: https://godoc.org/github.com/rekby/lets-proxy2/ (it is software, not library and has no global export any).
- goreportcard.com: [![Go Report Card](https://goreportcard.com/badge/github.com/rekby/lets-proxy2)](https://goreportcard.com/report/github.com/rekby/lets-proxy2)
- coverage service link ([cover.run](https://cover.run/), [gocover](http://gocover.io/), [coveralls](https://coveralls.io/) etc.), : [![Coverage Status](https://coveralls.io/repos/github/rekby/lets-proxy2/badge.svg?bra …

Add lets proxy2

---

README.md

- github.com repo: https://github.com/xaionaro-go/secureio
- godoc.org: https://pkg.go.dev/github.com/xaionaro-go/secureio?tab=doc
- goreportcard.com: https://goreportcard.com/report/github.com/xaionaro-go/secureio
- coverage service link: https://coveralls.io/github/xaionaro-go/secureio

Add https://github.com/xaionaro-go/secureio

---

README.md

Added Golang Estonia to the  meetup list 🇪🇪

Added Golang Estonia

---

README.md

- github.com repo: https://github.com/jirenius/go-res
- godoc.org: https://godoc.org/github.com/jirenius/go-res
- pkg.go.dev: https://pkg.go.dev/github.com/jirenius/go-res
- goreportcard.com: https://goreportcard.com/report/github.com/jirenius/go-res
- coverage service link: https://coveralls.io/github/jirenius/go-res?branch=master

Add go-res to Messaging section

---

README.md

- github.com repo: https://github.com/ewohltman/ephemeral-roles
- godoc.org: https://godoc.org/github.com/ewohltman/ephemeral-roles
- Note: the code is packaged under an `internal/` directory because it's not intended to be imported by other projects but is otherwise open-source
- goreportcard.com: https://goreportcard.com/report/github.com/ewohltman/ephemeral-roles
- coverage service link ([gocover](http://gocover.io/), [coveralls](https://coveralls.io/) etc.): https://coveralls.io/github/ewohltman/ephemeral-roles
**Note**: that …

Add https://github.com/ewohltman/ephemeral-roles

---

README.md

- github.com repo: https://github.com/BoRuDar/configuration
- godoc.org: https://godoc.org/github.com/BoRuDar/configuration
- goreportcard.com: https://goreportcard.com/report/github.com/borudar/configuration
- coverage service link: https://codecov.io/gh/BoRuDar/configuration

Added configuration library (https://github.com/BoRuDar/configuration) 

---

README.md

- github.com repo: https://github.com/bozd4g/go-http-client
- godoc.org: https://godoc.org/github.com/bozd4g/go-http-client/client
- goreportcard.com: https://goreportcard.com/report/github.com/bozd4g/go-http-client
- coverage service link: https://codecov.io/gh/bozd4g/go-http-client

Add go-http-client package

---

README.md

- github.com repo: https://github.com/wlbr/mule
- godoc.org: https://godoc.org/github.com/wlbr/mule
- goreportcard.com: https://goreportcard.com/report/github.com/wlbr/mule
- coverage service link ([gocover](http://gocover.io/), [coveralls](https://coveralls.io/) etc.): https://coveralls.io/github/wlbr/mule?branch=master
Actually there is a full table of links in the end of the repos readme. …

Added Mule (https://github.com/wlbr/mule)

---

README.md

Yet Another CLi Spinner
- github.com repo: https://github.com/theckman/yacspin
- pkg.go.dev: https://godoc.org/github.com/theckman/yacspin
- goreportcard.com: https://goreportcard.com/report/github.com/theckman/yacspin
- coverage service link: https://codecov.io/gh/theckman/yacspin

Add yacspin

---

README.md

Add Tutorial for Gorilla Mux 

---

README.md

- github.com repo: https://github.com/elgohr/go-localstack
- pkg.go.dev: https://godoc.org/github.com/elgohr/go-localstack
- goreportcard.com: https://goreportcard.com/report/github.com/elgohr/go-localstack
- coverage service link: https://codecov.io/gh/elgohr/go-localstack

Add go-localstack

---

README.md

- github.com repo: https://github.com/Eun/go-convert
- godoc.org: https://godoc.org/github.com/Eun/go-convert
- goreportcard.com: https://goreportcard.com/report/github.com/Eun/go-convert
- coverage service link: https://codecov.io/gh/Eun/go-convert

add github.com/Eun/go-convert

---

README.md

- github.com repo: https://github.com/appist/appy
- pkg.go.dev: [![Go Doc](http://img.shields.io/badge/godoc-reference-5272B4.svg)](https://pkg.go.dev/github.com/appist/appy?tab=doc)
- goreportcard.com: [![Go Report Card](https://goreportcard.com/badge/github.com/appist/appy)](https://goreportcard.com/report/github.com/appist/appy)
- coverage service link: [![Coverage Status](https://img.shields.io/codecov/c/gh/appist/appy.svg?logo=codecov)](https://codecov.io/gh/appist/appy)
Very good coverage (93%)
**Note**: that new categories can be added only …

Add `appy` web framework

---

README.md

- github.com repo:https://github.com/monaco-io/request
- pkg.go.dev:https://pkg.go.dev/github.com/monaco-io/request?tab=doc
- goreportcard.com:https://goreportcard.com/report/github.com/monaco-io/request
- coverage service link: https://codecov.io/gh/monaco-io/request
Very good coverage: 100%
- [ √] I have added my package in alphabetical order.
- [√ ] I have an appropriate description with correct …

add module [https://github.com/monaco-io/request]

---

README.md

Add [Olivia](https://github.com/olivia-ai/olivia) chatbot to the list.
- github.com repo: https://github.com/olivia-ai/olivia
- pkg.go.dev: https://pkg.go.dev/github.com/olivia-ai/olivia?tab=doc
- goreportcard.com: https://goreportcard.com/report/github.com/olivia-ai/olivia
- coverage service link: https://codecov.io/gh/olivia-ai/olivia

add olivia-ai/olivia to the bot building section

---

README.md

[![Go Report Card](https://goreportcard.com/badge/github.com/arthurkushman/buildsqlx)](https://goreportcard.com/report/github.com/arthurkushman/buildsqlx)
[![Build and run](https://github.com/arthurkushman/buildsqlx/workflows/Build%20and%20run/badge.svg)](https://github.com/arthurkushman/buildsqlx/actions)
[![GoDoc](https://github.com/golang/gddo/blob/c782c79e0a3c3282dacdaaebeff9e6fd99cb2919/gddo-server/assets/status.svg)](https://godoc.org/github.com/arthurkushman/buildsqlx)
[![codecov](https://codecov.io/gh/arthurkushman/buildsqlx/branch/master/graph/badge.svg)](https://codecov.io/gh/arthurkushman/buildsqlx)
[![License: MIT](https://img.shields.io/badge/License-MIT-blue.svg)](https://opensource.org/licenses/MIT)
- github.com repo: https://github.com/arthurkushman/buildsqlx
- godoc.org: …

Add Go database query builder library for PostgreSQL

---

README.md

[google/uuid](https://github.com/google/uuid) is the most starred UUID project in go except [satori/go.uuid](https://github.com/satori/go.uuid) which has critical flaw (see https://github.com/satori/go.uuid/issues/73). [1]
satori/go.uuid was deleted by https://github.com/avelino/awesome-go/pull/2224, but google/uuid mentioned was not added.
However, google/uuid doesn't have coverage service. So I ran `go test -cover` on my own laptop and found that it has 88.4% coverage.
```
uuid % go test  -cover
PASS
coverage: 88.4% of statements
ok  	github.com/google/uuid	0.366s
``` 
[1] https://libs.garden/go/search?q=uuid&sort=popular
---
Please check if what you want to add to `awesome-go` list meets [quality standards](https://github.com/avelino/awesome-go/blob/master/CONTRIBUTING.md#quality-standa …

Add google/uuid

---

README.md

add tutorial 'How to Deploy a Go Web Application with Docker'

---

README.md

- github.com repo: https://github.com/pantrif/s2-geojson
- pkg.go.dev:  https://godoc.org/github.com/pantrif/s2-geojson
- goreportcard.com: https://goreportcard.com/report/github.com/pantrif/s2-geojson
- coverage service link https://codecov.io/gh/pantrif/s2-geojson

Add s2-geojson

---

README.md

- github.com repo: https://github.com/gurkankaymak/hocon
- godoc.org: https://godoc.org/github.com/gurkankaymak/hocon
- goreportcard.com: https://goreportcard.com/report/github.com/gurkankaymak/hocon
- coverage service link: https://codecov.io/gh/gurkankaymak/hocon
Note: that new categories can be added only when there are 3 packages or more.
Thanks for your PR, you're awesome! 👍

added gurkankaymak/hocon to configuration category

---

README.md

- [github.com repo]( https://github.com/andskur/argon2-hashing)
- [pkg.go.dev](https://pkg.go.dev/github.com/andskur/argon2-hashing?tab=doc)
- [ goreportcard.com:](https://goreportcard.com/report/github.com/andskur/argon2-hashing)
- [coverage service link](https://codecov.io/gh/andskur/argon2-hashing)

added argon2-hashing package

---

README.md

- github.com repo: [prototype](https://github.com/gonutz/prototype)
- godoc.org: [godoc](https://godoc.org/github.com/gonutz/prototype/draw)
- goreportcard.com: [report](https://goreportcard.com/report/github.com/gonutz/prototype)
This has some issues but they are only in the samples.
[gocover](https://gocover.io/github.com/gonutz/prototype/draw) This site seems broken. It compains about an error for strconv.ParseFloat which is not called anywhere in the …

Add prototype game library

---

README.md

- github.com repo: https://github.com/alitto/pond
- pkg.go.dev: https://pkg.go.dev/github.com/alitto/pond
- goreportcard.com: https://goreportcard.com/report/github.com/alitto/pond
- coverage service link ([codecov](https://codecov.io/), [coveralls](https://coveralls.io/), [gocover](http://gocover.io/) etc.): https://codecov.io/gh/alitto/pond …

Add pond library

---

README.md

- github.com repo: https://github.com/arunsworld/nursery
- pkg.go.dev: https://pkg.go.dev/github.com/arunsworld/nursery?tab=doc
- goreportcard.com: https://goreportcard.com/report/github.com/arunsworld/nursery
- coverage service link ([codecov](https://codecov.io/), [coveralls](https://coveralls.io/), [gocover](http://gocover.io/) etc.): https://gocover.io/github.com/arunsworld/nursery
Very good coverage (100% coverage) …

Add nursery - structured concurrency library

---

README.md

- github.com repo: https://github.com/peak/s5cmd
- pkg.go.dev: https://pkg.go.dev/github.com/peak/s5cmd?tab=doc
- goreportcard.com: https://goreportcard.com/report/github.com/peak/s5cmd
- coverage service link ([codecov](https://codecov.io/), [coveralls](https://coveralls.io/), [gocover](http://gocover.io/) etc.): https://gocover.io/github.com/peak/s5cmd …

Add s5cmd - Blazing fast S3 and local filesystem execution tool

---

README.md

Removed unmaintained (5+ years inactive) gamedev libraries

---

README.md

- github.com repo: https://github.com/sherifabdlnaby/configuro
- pkg.go.dev: https://godoc.org/github.com/sherifabdlnaby/configuro
- goreportcard.com: https://goreportcard.com/report/github.com/sherifabdlnaby/configuro
- coverage service link: [coveralls](https://coveralls.io/github/sherifabdlnaby/configuro)

Add sherifabdlnaby/configuro

---

README.md

- github.com repo: https://github.com/pokanop/nostromo
- pkg.go.dev:
- goreportcard.com: https://goreportcard.com/report/github.com/pokanop/nostromo
- coverage service link ([codecov](https://codecov.io/), [coveralls](https://coveralls.io/), [gocover](http://gocover.io/) etc.): https://coveralls.io/github/pokanop/nostromo

Add nostromo

---

README.md

- github.com repo: https://github.com/ccbrown/api-fu
- pkg.go.dev: https://pkg.go.dev/github.com/ccbrown/api-fu
- goreportcard.com: https://goreportcard.com/report/github.com/ccbrown/api-fu (A+)
- coverage service link: https://codecov.io/gh/ccbrown/api-fu (83%)

add ccbrown/api-fu

---

README.md

- github.com repo: https://github.com/logur/logur
- pkg.go.dev: https://pkg.go.dev/logur.dev/logur
- goreportcard.com: https://goreportcard.com/report/logur.dev/logur
- coverage service link: https://codecov.io/gh/logur/logur

Add logur library

---

README.md

also add a `uncategorized` category to make it clearer that it's not a continuation of the `strings` category.
- [github.com repo](https://github.com/containrrr/shoutrrr)
- [pkg.go.dev](https://pkg.go.dev/github.com/containrrr/shoutrrr?tab=doc)
- [goreportcard.com](https://goreportcard.com/report/github.com/containrrr/shoutrrr)
- [coverage service link](https://codecov.io/github/containrrr/shoutrrr/)

add shoutrrr

---

README.md

Hi there  👋,  we've launched our community beta this week and would be great to add to share with community. I'd call out that our backend is in go but it is not on this repo as it houses our community scripts and documentations. I noticed other similar projects on the list so hope that is ok. 
Thanks!
Ishan
- github.com repo: n/a
- pkg.go.dev: n/a
**Note**: that new categories can …

Add Pixie to performance sectionn

---

README.md

- github.com repo: https://github.com/alexsergivan/transliterator
- pkg.go.dev: https://pkg.go.dev/github.com/alexsergivan/transliterator
- goreportcard.com: https://goreportcard.com/report/github.com/alexsergivan/transliterator
- coverage service link: https://coveralls.io/github/alexsergivan/transliterator

Added golang transliterator

---

README.md

- github.com repo: https://github.com/gobeam/Stringy
- pkg.go.dev: https://pkg.go.dev/github.com/gobeam/Stringy
- goreportcard.com: https://goreportcard.com/report/github.com/gobeam/Stringy
- coverage service link [coveralls](https://coveralls.io/github/gobeam/Stringy)

Add Stringy a string manipulation library

---

README.md

- github.com repo: https://github.com/simukti/sqldb-logger
- pkg.go.dev: https://pkg.go.dev/github.com/simukti/sqldb-logger
- goreportcard.com: https://goreportcard.com/report/github.com/simukti/sqldb-logger
- coveralls.io code coverage: https://coveralls.io/github/simukti/sqldb-logger

add sqldb-logger

---

README.md

- github.com repo: https://github.com/subpop/go-ini
- godoc.org: https://godoc.org/github.com/subpop/go-ini
- goreportcard.com: https://goreportcard.com/report/github.com/subpop/go-ini
- coveralls.io: https://coveralls.io/github/subpop/go-ini
I am creating a new PR as I cannot reopen the old PR (#3011).

Add go-ini

---

README.md

- github.com repo: https://github.com/bogem/id3v2
- pkg.go.dev: https://pkg.go.dev/github.com/bogem/id3v2
- goreportcard.com: https://goreportcard.com/report/github.com/bogem/id3v2
- coverage service link: https://gocover.io/github.com/bogem/id3v2

Change id3v2 description

---

README.md

Sprbox package ( https://github.com/oblq/sprbox ) has been archived and entirely revised / simplified in a new project ( swap, https://github.com/oblq/swap ), it does basically the same things, just in a more intuitive way.
- github.com repo: https://github.com/oblq/swap
- pkg.go.dev: https://pkg.go.dev/github.com/oblq/swap?tab=doc
- goreportcard.com: https://goreportcard.com/report/github.com/oblq/swap
- coverage service link: https://codecov.io/gh/oblq/swap
**Note**: that new categories can be added only when there are 3 packages …

Remove `sprbox` package (which has been archived) in favor of `swap` package which replace it.

---

README.md

Hi, pogreb is an embedded key-value store for read-heavy workloads.
- github.com repo: https://github.com/akrylysov/pogreb
- pkg.go.dev: https://pkg.go.dev/github.com/akrylysov/pogreb?tab=doc
- goreportcard.com: https://goreportcard.com/report/github.com/akrylysov/pogreb
- coverage service link: https://codecov.io/gh/akrylysov/pogreb

Add pogreb to Database section

---

README.md

- github.com repo: https://github.com/foolin/pagser
- pkg.go.dev: https://pkg.go.dev/github.com/foolin/pagser
- goreportcard.com: https://goreportcard.com/report/github.com/foolin/pagser
- coverage service link ([codecov](https://codecov.io/), [coveralls](https://coveralls.io/), [gocover](http://gocover.io/) etc.) : https://codecov.io/gh/foolin/pagser …

Add [pagser] project to Text Processing

---

README.md

- github.com repo: https://github.com/abahmed/gearbox
- pkg.go.dev: https://pkg.go.dev/github.com/abahmed/gearbox?tab=doc
- goreportcard.com: https://goreportcard.com/report/github.com/abahmed/gearbox
- coverage service link https://codecov.io/gh/abahmed/gearbox

add gearbox

---

README.md

- github.com repo: https://github.com/viney-shih/go-lock
- pkg.go.dev: https://pkg.go.dev/github.com/viney-shih/go-lock?tab=doc
- goreportcard.com: https://goreportcard.com/report/github.com/viney-shih/go-lock
- coverage service link ([codecov](https://codecov.io/gh/viney-shih/go-lock), [coveralls](https://coveralls.io/github/viney-shih/go-lock?branch=master) ) …

request to add go-lock to awesome-go

---

README.md

- github.com repo: https://github.com/shomali11/gridder
- pkg.go.dev: https://pkg.go.dev/github.com/shomali11/gridder?tab=doc
- goreportcard.com: https://goreportcard.com/report/github.com/shomali11/gridder
- gocover.io: https://gocover.io/github.com/shomali11/gridder

Add Gridder

---

README.md

- github.com repo: https://github.com/mbrostami/consistenthash
- pkg.go.dev: https://pkg.go.dev/github.com/mbrostami/consistenthash
- goreportcard.com: https://goreportcard.com/report/github.com/mbrostami/consistenthash
- coverage service link: https://gocover.io/github.com/mbrostami/consistenthash

Add consistenthash repository

---

README.md

Rename tracedb to unitdb as tracedb is archived and replaced with unitdb.
- github.com repo: https://github.com/unit-io/unitdb
- pkg.go.dev: https://pkg.go.dev/github.com/unit-io/unitdb
- goreportcard.com: https://goreportcard.com/report/github.com/unit-io/unitdb
- coverage service link ([codecov](https://codecov.io/), [coveralls](https://coveralls.io/), [gocover](http://gocover.io/) etc.): [coveralls](https://coveralls.io/github/unit-io/unitdb) …

Rename tracedb to unitdb

---

README.md

- github.com repo: https://github.com/psampaz/gophersnippets
- pkg.go.dev:
- goreportcard.com: https://goreportcard.com/report/github.com/psampaz/gophersnippets
- coverage service link 

add gophersnippets.com

---

README.md

- github.com repo: https://github.com/kkyr/fig
- pkg.go.dev: https://pkg.go.dev/github.com/kkyr/fig
- goreportcard.com: https://goreportcard.com/report/github.com/kkyr/fig
- coverage service link: https://coveralls.io/github/kkyr/fig

Add fig - a configuration library

---

README.md

add an orm :gosql
- github.com repo:  https://github.com/rushteam/gosql
- pkg.go.dev: https://pkg.go.dev/github.com/rushteam/gosql
- goreportcard.com: https://goreportcard.com/report/github.com/rushteam/gosql
- coverage service link: https://codecov.io/gh/rushteam/gosql

add an orm: gosql

---

README.md

Update URL for Go Playground App

---

README.md

`iuliia` is the port of the incredible python library [iuliia](https://github.com/nalgeon/iuliia-py) made by @nalgeon.
Transliteration means representing Cyrillic data (mainly names and geographic locations) with Latin letters. It is used for international passports, visas, green cards, driving licenses, mail and goods delivery etc.
Why use Iuliia:
* 20 transliteration schemas (rule sets), including all main international and Russian standards.
* Correctly implements not only the base mapping, but all the special rules for letter combinations and word endings (AFAIK, Iuliia is the only library which does so).
* Simple API and zero third-party dependencies.
- [github.com repo](https://github.com/mehanizm/iuliia-go)
- …

Add iuliia-go to Natural Language Processing

---

README.md

- github.com repo: https://github.com/timsolov/rest-query-parser
- pkg.go.dev: https://pkg.go.dev/github.com/timsolov/rest-query-parser
- goreportcard.com: https://goreportcard.com/report/github.com/timsolov/rest-query-parser
- coverage service link: [coveralls](https://coveralls.io/github/timsolov/rest-query-parser?branch=master)

add rqp package to README.md

---

README.md

- github.com repo: https://github.com/github/go-fault
- pkg.go.dev: https://pkg.go.dev/github.com/github/go-fault?tab=doc
- goreportcard.com: https://goreportcard.com/report/github.com/github/go-fault
- coverage service link: https://github.com/github/go-fault/runs/679016162?check_suite_focus=true#step:7:365 (coverage is enforced using github actions and uploaded as an artifact on each run)

Add go-fault

---

README.md

- github.com repo: https://github.com/taskctl/taskctl
- pkg.go.dev: https://pkg.go.dev/github.com/taskctl/taskctl?tab=overview
- goreportcard.com: https://goreportcard.com/report/github.com/taskctl/taskctl
- coverage service link: [codecov](https://codecov.io/gh/taskctl/taskctl/tree/master/pkg)

Adds taskctl to list

---

README.md

- github.com repo: https://github.com/cheshir/go-mq
- pkg.go.dev: https://pkg.go.dev/github.com/cheshir/go-mq
- goreportcard.com: https://goreportcard.com/report/github.com/cheshir/go-mq
- coverage service link: https://codecov.io/gh/cheshir/go-mq

Added go-mq

---

README.md

- github.com repo: https://github.com/sbourlon/go-lctree
- pkg.go.dev: https://pkg.go.dev/github.com/sbourlon/go-lctree?tab=doc
- goreportcard.com: https://goreportcard.com/report/github.com/sbourlon/go-lctree
- coverage service link: https://coveralls.io/github/sbourlon/go-lctree

Add go-lctree

---

README.md

- github.com repo: https://github.com/micro/go-micro
- pkg.go.dev: https://pkg.go.dev/github.com/micro/go-micro/v2
- goreportcard.com: https://goreportcard.com/report/github.com/micro/go-micro
- gocover: https://gocover.io/github.com/micro/go-micro

Update the description of micro and add go-micro

---

README.md

- github.com repo: https://github.com/rogerwelin/cassowary
- pkg.go.dev: https://pkg.go.dev/github.com/rogerwelin/cassowary@v0.10.0/pkg/client?tab=doc
- goreportcard.com: https://goreportcard.com/report/github.com/rogerwelin/cassowary
- coverage service link:  [gocover](https://gocover.io/github.com/rogerwelin/cassowary/pkg/client)

add cassowary

---

README.md

- github.com repo: https://github.com/cvilsmeier/sqinn-go
- pkg.go.dev: https://pkg.go.dev/github.com/cvilsmeier/sqinn-go@v1.0.0/sqinn?tab=doc
- goreportcard.com: https://goreportcard.com/report/github.com/cvilsmeier/sqinn-go
I did not setup a coverage service. The reason is: Sqinn-Go has a runtime dependency on a C program that has to be downloaded separately for the target platform. A description how to run all tests, with …

add Sqinn-Go to Database Drivers

---

README.md

- github.com repo: https://github.com/shaj13/go-guardian
- pkg.go.dev: https://pkg.go.dev/github.com/shaj13/go-guardian?tab=doc
- goreportcard.com: https://goreportcard.com/report/github.com/shaj13/go-guardian 
- coverage service link ([codecov](https://codecov.io/), [coveralls](https://coveralls.io/), [gocover](http://gocover.io/) etc.) [coveralls](https://coveralls.io/github/shaj13/go-guardian?branch=master)
[circleci](https://circleci.com/gh/shaj13/go-guardian/tree/master)

add go-guardian

---

README.md

This PR updates the Organization/URL for Trickster from `Comcast` to `tricksterproxy`, where the project was recently transferred. Thanks!
- github.com repo: https://github.com/tricksterproxy/trickster
- pkg.go.dev: https://pkg.go.dev/github.com/tricksterproxy/trickster@v1.1.2
- goreportcard.com: https://goreportcard.com/report/github.com/tricksterproxy/trickster
- coverage service link https://coveralls.io/github/tricksterproxy/trickster
**Make sure …

update trickster organization

---

README.md

- github.com repo: https://github.com/confluentinc/confluent-kafka-go
- pkg.go.dev: https://pkg.go.dev/github.com/confluentinc/confluent-kafka-go/kafka?tab=doc
- goreportcard.com: https://goreportcard.com/report/github.com/confluentinc/confluent-kafka-go …

Added Confluent Kafka Golang client

---

README.md

- github.com repo: https://github.com/PaddleHQ/go-aws-ssm
- pkg.go.dev: https://pkg.go.dev/github.com/PaddleHQ/go-aws-ssm@v0.4.0?tab=doc
- goreportcard.com: https://goreportcard.com/report/github.com/PaddleHQ/go-aws-ssm
- coverage service link https://codecov.io/gh/PaddleHQ/go-aws-ssm/branch/master

Add go-aws-ssm package

---

README.md

- github.com repo: https://github.com/blasrodri/spaceship-go
- pkg.go.dev:

Add E-Book Spaceship Go

---

README.md

- github.com repo: https://github.com/goioc/di
- pkg.go.dev: https://pkg.go.dev/github.com/goioc/di/?tab=doc
- goreportcard.com: https://goreportcard.com/report/github.com/goioc/di
- coverage service link ([codecov](https://codecov.io/), [coveralls](https://coveralls.io/), [gocover](http://gocover.io/) etc.): https://codecov.io/gh/goioc/di

Add goioc/di

---

README.md

- github.com repo: https://github.com/HereMobilityDevelopers/mediary
- pkg.go.dev: https://pkg.go.dev/github.com/HereMobilityDevelopers/mediary?tab=doc
- goreportcard.com: https://goreportcard.com/report/github.com/HereMobilityDevelopers/mediary
- coverage service link [coveralls](https://coveralls.io/github/HereMobilityDevelopers/mediary)

add mediary a middleware for http.Client

---

README.md

- github.com repo: https://github.com/sanketplus/go-mysql-lock
- pkg.go.dev: https://godoc.org/github.com/sanketplus/go-mysql-lock
- goreportcard.com: https://goreportcard.com/report/github.com/sanketplus/go-mysql-lock
- coverage service link: https://dev.azure.com/sanketplus/go-mysql-lock/_build/results?buildId=32&view=codecoverage-tab

Adding go-mysql-lock

---

README.md

- github.com repo: https://github.com/dtgorski/typex
- pkg.go.dev: https://pkg.go.dev/github.com/dtgorski/typex (not a library, a CLI tool)
- goreportcard.com: https://goreportcard.com/report/github.com/dtgorski/typex
- coverage service link: https://coveralls.io/github/dtgorski/typex

Added typex

---

README.md

- github.com repo: https://github.com/reugn/equalizer
- pkg.go.dev: https://pkg.go.dev/github.com/reugn/equalizer?tab=doc
- goreportcard.com: https://goreportcard.com/report/github.com/reugn/equalizer
- coverage service link: [codecov](https://codecov.io/gh/reugn/equalizer)

add equalizer library

---

README.md

We migrated the project from personal namespace to the organization namespace.

Update the link address and description of rod

---

README.md

Article: https://medium.com/@rocketlaunchr.cloud/how-to-benchmark-dbq-vs-sqlx-vs-gorm-e814caacecb5

- add how to benchmark

---

README.md

- github.com repo: [github.com/Zaba505/gws](https://github.com/Zaba505/gws)
- pkg.go.dev: [docs](https://pkg.go.dev/github.com/zaba505/gws?tab=doc)
- goreportcard.com: [![Go Report Card](https://goreportcard.com/badge/github.com/zaba505/gws)](https://goreportcard.com/report/github.com/zaba505/gws)
- coverage service link: [![codecov](https://codecov.io/gh/Zaba505/gws/branch/master/graph/badge.svg)](https://codecov.io/gh/Zaba505/gws)
**Note**: A fair bit of the uncovered code pertains to either error implementations or a private interface which is …

feat: add github.com/Zaba505/gws

---

README.md

✨ `Create-Go-App` it's a powerful CLI for create a new production-ready project with backend (Golang), frontend (JavaScript, TypeScript) and deploy automation (Ansible, Docker) by running one CLI command! 
- github.com repo: [create-go-app](https://github.com/create-go-app/cli)
- pkg.go.dev: [godoc](https://pkg.go.dev/github.com/create-go-app/cli/pkg/cgapp?tab=doc)
- goreportcard.com: [goreportcard](https://goreportcard.com/report/github.com/create-go-app/cli)
- coverage service link [gocover](https://gocover.io/github.com/create-go-app/cli/pkg/cgapp) …

Add create-go-app/cli project to Utilities section

---

README.md

- github.com repo: https://github.com/nikolaydubina/calendarheatmap
- pkg.go.dev: https://pkg.go.dev/github.com/nikolaydubina/calendarheatmap@v1.0.0/charts
- goreportcard.com: https://goreportcard.com/report/github.com/nikolaydubina/calendarheatmap
- coverage service link: https://codecov.io/gh/nikolaydubina/calendarheatmap

Added github.com/nikolaydubina/calendarheatmap

---

README.md

- github.com repo: https://github.com/prashantgupta24/firewalld-rest
- pkg.go.dev: https://pkg.go.dev/github.com/prashantgupta24/firewalld-rest
- goreportcard.com: https://goreportcard.com/report/github.com/prashantgupta24/firewalld-rest
- coverage service link: https://codecov.io/gh/prashantgupta24/firewalld-rest (83% coverage)

add firewalld-rest library

---

README.md

- github.com repo: https://github.com/jexia/maestro
- pkg.go.dev: https://pkg.go.dev/mod/github.com/jexia/maestro
- goreportcard.com: https://goreportcard.com/report/github.com/jexia/maestro
- coverage service link: https://codecov.io/gh/jexia/maestro

Added Maestro

---

README.md

- github.com repo: https://github.com/lqs/sqlingo
- pkg.go.dev: https://pkg.go.dev/github.com/lqs/sqlingo?tab=doc
- goreportcard.com: https://goreportcard.com/report/github.com/lqs/sqlingo
- coverage service link: https://codecov.io/gh/lqs/sqlingo

Add github.com/lqs/sqlingo

---

README.md

- github.com repo: https://github.com/technohippy/go-glmatrix
- pkg.go.dev: https://pkg.go.dev/github.com/technohippy/go-glmatrix
- goreportcard.com: https://goreportcard.com/report/github.com/technohippy/go-glmatrix
- coverage service link: https://coveralls.io/github/technohippy/go-glmatrix

add go-glmatrix in opengl section

---

README.md

- github.com repo: https://github.com/facebookincubator/ent
- pkg.go.dev: https://pkg.go.dev/github.com/facebookincubator/ent
- goreportcard.com: https://goreportcard.com/report/github.com/facebookincubator/ent
- coverage service link: https://gocover.io/github.com/facebookincubator/ent

Add facebookincubator/ent

---

README.md

fix a wrong link

---

README.md

- github.com repo: https://github.com/xitonix/trubka
- pkg.go.dev: N/A since it's a CLI tool
- goreportcard.com: https://goreportcard.com/report/github.com/xitonix/trubka
- coverage service link: Not very unit testable I'm afraid, since it's a CLI tool
Thanks for reviewing the PR, you're awesome! 😉

Added trubka: A CLI tool for Apache Kafka

---

README.md

- github.com repo: https://github.com/db47h/decimal
- pkg.go.dev:  https://pkg.go.dev/github.com/db47h/decimal
- goreportcard.com: https://goreportcard.com/report/github.com/db47h/decimal
- coverage service link: https://coveralls.io/github/db47h/decimal?branch=master

Add github.com/db47h/decimal

---

README.md

- github.com repo: https://github.com/bnkamalesh/goapp
- pkg.go.dev: Not applicable since this is not a Go package
- goreportcard.com: https://goreportcard.com/badge/github.com/bnkamalesh/goapp
- coverage service link: https://codecov.io/gh/bnkamalesh/goapp

- added github.com/bnkamalesh/goapp

---

README.md

- github.com repo: https://github.com/xis/baraka
- pkg.go.dev: https://pkg.go.dev/github.com/xis/baraka
- goreportcard.com: https://goreportcard.com/report/github.com/xis/baraka
- coverage service link https://codecov.io/gh/xis/baraka

add baraka

---

README.md

- github.com repo: https://github.com/henvic/httpretty
- pkg.go.dev: https://pkg.go.dev/github.com/henvic/httpretty
- goreportcard.com: https://goreportcard.com/report/github.com/henvic/httpretty
- coverage service link: https://coveralls.io/github/henvic/httpretty
- [ x I have an appropriate description with correct grammar.
It's been a …

Adding github.com/henvic/httpretty HTTP debugging package.

---

README.md

- github.com repo: https://github.com/lrita/cmap
- pkg.go.dev: https://pkg.go.dev/github.com/lrita/cmap
- goreportcard.com: [![Go Report Card](https://goreportcard.com/badge/github.com/lrita/cmap)](https://goreportcard.com/report/github.com/lrita/cmap)
- coverage service link: [![codecov](https://codecov.io/gh/lrita/cmap/branch/master/graph/badge.svg)](https://codecov.io/gh/lrita/cmap)

add cmap in datastructure

---

README.md

- github.com repo: https://github.com/bnkamalesh/errors
- pkg.go.dev: https://pkg.go.dev/github.com/bnkamalesh/errors
- goreportcard.com: https://goreportcard.com/report/github.com/bnkamalesh/errors
- coverage service link [![codecov](https://codecov.io/gh/bnkamalesh/errors/branch/master/graph/badge.svg)](https://codecov.io/gh/bnkamalesh/errors) …

[patch] added github.com/bnkamalesh/errors

---

README.md

- github.com repo: https://github.com/jexia/semaphore
- pkg.go.dev: https://pkg.go.dev/mod/github.com/jexia/semaphore
- goreportcard.com: https://goreportcard.com/report/github.com/jexia/semaphore
- coverage service link: https://codecov.io/gh/jexia/semaphore

Renamed project Maestro to Semaphore

---

README.md

As discussed, the style guides from dgryski/awesome-go-style.

Style Guides: add section from dgryski/awesome-go-style

---

README.md

- github.com repo: https://github.com/qiniu/goc
- pkg.go.dev: https://pkg.go.dev/github.com/qiniu/goc
- goreportcard.com: https://goreportcard.com/report/github.com/qiniu/goc
- coverage service link: https://codecov.io/gh/qiniu/goc

Add qiniu goc

---

README.md

- github.com repo: https://github.com/cristalhq/jwt
- pkg.go.dev: https://pkg.go.dev/github.com/cristalhq/jwt/v3
- goreportcard.com: https://goreportcard.com/report/github.com/cristalhq/jwt
- coverage service link: https://codecov.io/gh/cristalhq/jwt

add cristalhq/jwt

---

README.md

- github.com repo: https://github.com/cristalhq/aconfig
- pkg.go.dev: https://pkg.go.dev/github.com/cristalhq/aconfig
- goreportcard.com: https://goreportcard.com/report/github.com/cristalhq/aconfig
- coverage service link: https://codecov.io/gh/cristalhq/aconfig

add cristalhq/aconfig

---

README.md

- github.com repo: [https://github.com/incu6us/goimports-reviser](https://github.com/incu6us/goimports-reviser)
- pkg.go.dev: https://pkg.go.dev/github.com/incu6us/goimports-reviser/v2?tab=doc
- goreportcard.com: [https://goreportcard.com/report/github.com/incu6us/goimports-reviser](https://goreportcard.com/report/github.com/incu6us/goimports-reviser)
- coverage service link ([codecov](https://codecov.io/), [coveralls](https://coveralls.io/), [gocover](http://gocover.io/) etc.): [https://codecov.io/gh/incu6us/goimports-reviser](https://codecov.io/gh/i …

Add goimports-reviser

---

README.md

- github.com repo: https://github.com/kenkyu392/go-safe
- pkg.go.dev: https://pkg.go.dev/github.com/kenkyu392/go-safe
- goreportcard.com: https://goreportcard.com/report/github.com/kenkyu392/go-safe
- coverage service link ([codecov](https://codecov.io/), [coveralls](https://coveralls.io/), [gocover](http://gocover.io/) etc.): https://codecov.io/gh/kenkyu392/go-safe
Thanks for …

Add go-safe

---

README.md

- github.com repo: https://github.com/JohannesKaufmann/html-to-markdown
- pkg.go.dev: https://godoc.org/github.com/JohannesKaufmann/html-to-markdown
- goreportcard.com: https://goreportcard.com/report/github.com/JohannesKaufmann/html-to-markdown
- coverage service link: https://codecov.io/gh/JohannesKaufmann/html-to-markdown
Very good coverage, through an extensive [golden file](https://github.com/JohannesKaufmann/html-to-markdown/tree/master/testdata) test suite. …

add html-to-markdown

---

README.md

Remove not found library https://github.com/txgruppi/werr.

Remove not found library

---

README.md

- github.com repo: https://github.com/reugn/go-quartz
- pkg.go.dev: https://godoc.org/github.com/reugn/go-quartz/quartz
- goreportcard.com: https://goreportcard.com/report/github.com/reugn/go-quartz
- coverage service link: https://codecov.io/gh/reugn/go-quartz

add go-quartz

---

README.md

- github.com repo: https://github.com/x1unix/go-playground
- pkg.go.dev: https://pkg.go.dev/github.com/x1unix/go-playground
- goreportcard.com: https://goreportcard.com/report/github.com/x1unix/go-playground
- coverage service link: https://coveralls.io/github/x1unix/go-playground

Add "Better Go Playground" service

---

README.md

https://github.com/drakkan/sftpgo
- pkg.go.dev:
https://pkg.go.dev/github.com/drakkan/sftpgo?tab=doc
https://goreportcard.com/report/github.com/drakkan/sftpgo
- coverage service link 
https://codecov.io/gh/drakkan/sftpgo/branch/master
This is an update for SFTPGo, many new features have been added since the initial submission, so the current description is no longer appropriate

update SFTPGo description

---

README.md

Themis is a popular cryptographic library, that supports 14 languages, including Go. Themis is a best fit for securing data in multi-platform apps and building apps with end-to-end encryption. It hides cryptographic details, so developers don't need to know the difference between AES CBC mode and AES GCM mode to encrypt the data. 
Themis has unit-tests for each language ([including Go](https://github.com/cossacklabs/themis/tree/master/gothemis)), cross-platform tests between languages, cross-version tests, etc (because crypto needs a lot of testing!). 
- github.com repo: https://github.com/cossacklabs/themis
- pkg.go.dev: https://pkg.go.dev/mod/github.com/cossacklabs/themis/gothemis …

Add Themis crypto library to Security

---

README.md

- github.com repo: https://github.com/georgysavva/scany
- pkg.go.dev: 
https://pkg.go.dev/github.com/georgysavva/scany - it's an empty landing package, that combines 3 sub-packages (listed below) that will be actually in use
https://pkg.go.dev/github.com/georgysavva/scany/pgxscan - 1st sub-package 
https://pkg.go.dev/github.com/georgysavva/scany/sqlscan - 2nd sub-package
https://pkg.go.dev/github.com/georgysavva/scany/dbscan- 3rd sub-package
- goreportcard.com: https://goreportcard.com/report/github.com/georgysavva/scany …

Add scany to utilities section

---

README.md

- github.com repo: https://github.com/neilotoole/errgroup
- pkg.go.dev: https://pkg.go.dev/github.com/neilotoole/errgroup
- goreportcard.com: https://goreportcard.com/report/github.com/neilotoole/errgroup
- coverage service link ([codecov](https://codecov.io/), [coveralls](https://coveralls.io/), [gocover](http://gocover.io/) etc.): https://gocover.io/github.com/neilotoole/errgroup …

Add neilotoole/errgroup to Goroutines section

---

README.md

just updating the link to the new home of this repo

update marlow reference

---

README.md

- github.com repo: https://github.com/yaa110/goterator
- pkg.go.dev: https://pkg.go.dev/github.com/yaa110/goterator?tab=doc
- goreportcard.com: https://goreportcard.com/report/github.com/yaa110/goterator
- coverage service link ([codecov](https://codecov.io/), [coveralls](https://coveralls.io/), [gocover](http://gocover.io/) etc.) https://gocover.io/github.com/yaa110/goterator …

Add goterator

---

README.md

Remove Dead Links

---

README.md

- github.com repo: https://github.com/bojanz/currency
- pkg.go.dev: https://pkg.go.dev/github.com/bojanz/currency?tab=doc
- goreportcard.com: https://goreportcard.com/report/github.com/bojanz/currency
- coverage service link ([coveralls](https://coveralls.io/): https://coveralls.io/github/bojanz/currency?branch=master
- [*] I …

Add bojanz/currency.

---

README.md

- github.com repo: https://github.com/facebook/ent
- pkg.go.dev: https://pkg.go.dev/github.com/facebook/ent
- goreportcard.com: https://goreportcard.com/report/github.com/facebook/ent
- coverage service link: https://gocover.io/github.com/facebook/ent

Update from facebookincubator/ent to facebook/ent

---

README.md

**Required links to:**
- github.com repo: https://github.com/covergates/covergates
- pkg.go.dev: https://pkg.go.dev/github.com/covergates/covergates
- goreportcard.com: https://goreportcard.com/report/github.com/covergates/covergates
- coverage service link : https://covergates.com/report/github/covergates/covergates
[![card](https://covergates.com/api/v1/reports/bsi5dvi23akg00a0tgl0/card)](https://covergates.com/report/github/covergates/covergates)
> I'm a new coverage service =)

Add covergates - Self-hosted code coverage report review and management service

---

README.md

vscode-go moved from /Microsoft to /golang
- github.com repo: https://github.com/golang/vscode-go
- pkg.go.dev: n/a
- coverage service link n/a
Very good coverage: n/a

Updated vscode-go link

---

README.md

updated baraka description
- github.com repo: https://github.com/xis/baraka
- pkg.go.dev: https://pkg.go.dev/github.com/xis/baraka
- goreportcard.com: https://goreportcard.com/report/github.com/xis/baraka
- coverage service link https://codecov.io/gh/xis/baraka

update baraka description

---

README.md

- github.com repo: https://github.com/hbollon/go-edlib
- pkg.go.dev: https://pkg.go.dev/github.com/hbollon/go-edlib
- goreportcard.com: https://goreportcard.com/report/github.com/hbollon/go-edlib
- coverage service link: https://codecov.io/gh/hbollon/go-edlib
- license: [MIT](https://github.com/hbollon/go-edlib/blob/master/LICENSE.md)
100% test covered
Thanks for this awesome libraries list ! :smile:

Add hbollon/go-edlib library link

---

README.md

Github repo: https://github.com/cybertec-postgresql/pg_timetable
License: [MIT](https://github.com/cybertec-postgresql/pg_timetable/blob/master/LICENSE)
Coverage: https://coveralls.io/github/cybertec-postgresql/pg_timetable?branch=master
Goreport: https://goreportcard.com/report/github.com/cybertec-postgresql/pg_timetable

Add pg_timetable to Database tools

---

README.md

- github.com repo: [https://github.com/dimuska139/go-email-normalizer](https://github.com/dimuska139/go-email-normalizer)
- pkg.go.dev: [https://pkg.go.dev/github.com/dimuska139/go-email-normalizer?tab=doc](https://pkg.go.dev/github.com/dimuska139/go-email-normalizer?tab=doc)
- goreportcard.com: [https://goreportcard.com/report/github.com/dimuska139/go-email-normalizer](https://goreportcard.com/report/github.com/dimuska139/go-email-normalizer)
- coverage service link: [https://codecov.io/gh/dimuska139/go-email-normalizer/branch/master](https://codecov …

Update README file to add go-email-normalizer library

---

README.md

- github.com repo: https://github.com/Fs02/go-todo-backend
- pkg.go.dev: https://pkg.go.dev/mod/github.com/Fs02/go-todo-backend
- goreportcard.com: https://goreportcard.com/report/github.com/Fs02/go-todo-backend
- coverage service link: https://codeclimate.com/github/Fs02/go-todo-backend

add go-todo-backend-example

---

README.md

- github.com repo: https://github.com/jltorresm/otpgo
- pkg.go.dev: https://pkg.go.dev/github.com/jltorresm/otpgo
- goreportcard.com: https://goreportcard.com/report/github.com/jltorresm/otpgo
- coverage service link: https://coveralls.io/github/jltorresm/otpgo?branch=main

Add otpgo library

---

README.md

- github.com repo: https://github.com/pioz/faker
- pkg.go.dev: https://pkg.go.dev/github.com/pioz/faker
- goreportcard.com: https://goreportcard.com/report/github.com/pioz/faker
- coverage service link: https://codecov.io/gh/pioz/faker

Add github.com/pioz/faker package

---

README.md

Hi folks,
Here's one more tool for people to hopefully make more games in Go (and not only games).  This is a general-purpose library for 2D grids with few algorithms implemented such as BFS, A* pathfinding, internal mini pub-sub for Observer pattern, and even some import/export functions. 
- github.com repo: https://github.com/kelindar/tile
- pkg.go.dev: https://pkg.go.dev/github.com/kelindar/tile
- goreportcard.com: https://goreportcard.com/report/github.com/kelindar/tile
- coverage service link: https://coveralls.io/github/kelindar/tile (**96% coverage**)
Thanks for reviewing this!

Adding kelindar/tile

---

README.md

otto, more than 2 years unmaintained.
- github.com repo: https://github.com/dop251/goja
- pkg.go.dev: https://pkg.go.dev/github.com/dop251/goja
- goreportcard.com: https://goreportcard.com/report/github.com/dop251/goja
- gocover: https://gocover.io/github.com/dop251/goja …

Replace otto to goja

---

README.md

Fix link to original GORM repository

---

README.md

Update to supported fork
- github.com repo: https://github.com/pressly/goose
- pkg.go.dev: https://pkg.go.dev/github.com/pressly/goose
- goreportcard: https://goreportcard.com/report/github.com/pressly/goose

Update goose migration tool

---

README.md

- github.com repo: https://github.com/lucasepe/modgv
- pkg.go.dev: https://pkg.go.dev/github.com/lucasepe/modgv?tab=doc
- goreportcard.com: https://goreportcard.com/report/github.com/lucasepe/modgv
- coverage service link: https://gocover.io/github.com/lucasepe/modgv

Add modgv - Converts 'go mod graph' output into GraphViz's DOT language

---

README.md

Arpc is a high-performance rpc package and more effective network communication support two-way-calling, notify, broadcast.
- github.com repo: https://github.com/lesismal/arpc
- pkg.go.dev: https://pkg.go.dev/github.com/lesismal/arpc?tab=doc
- goreportcard.com: https://goreportcard.com/report/github.com/lesismal/arpc
- coverage service link: https://codecov.io/gh/lesismal/arpc

Add lesismal/arpc

---

README.md

goreportcard.com: https://goreportcard.com/report/xorm.io/xorm
new location: https://gitea.com/xorm/xorm
website: https://xorm.io/

Update XORM: Link & Description

---

README.md

- github.com repo: https://github.com/shubhamzanwar/design-patterns
- goreportcard.com: https://goreportcard.com/report/github.com/shubhamzanwar/design-patterns

adding go design patterns repo to tutorials list

---

README.md

- github.com repo: https://github.com/oriser/regroup
- pkg.go.dev: https://pkg.go.dev/github.com/oriser/regroup
- goreportcard.com: https://goreportcard.com/report/github.com/oriser/regroup
- coverage service link ([codecov](https://codecov.io/), [coveralls](https://coveralls.io/), [gocover](http://gocover.io/) etc.): https://codecov.io/gh/oriser/regroup …

Add regroup to the project listing

---

README.md

- github.com repo: https://github.com/aplescia-chwy/lets-go
- pkg.go.dev: https://pkg.go.dev/github.com/aplescia-chwy/lets-go@v1.9.4
- goreportcard.com: https://goreportcard.com/report/github.com/Chewy-Inc/lets-go
- coverage service link ([codecov](https://codecov.io/), [coveralls](https://coveralls.io/), [gocover](http://gocover.io/) etc.) https://codecov.io/github/aplescia-chwy/lets-go/ …

Add lets-go, a library with various AWS and REST utility packages.

---

README.md

- github.com repo: https://github.com/zerosnake0/go-json-benchmark
- pkg.go.dev: *this is a benchmark*
- goreportcard.com: *this is a benchmark*
- coverage service link ([codecov](https://codecov.io/), [coveralls](https://coveralls.io/), [gocover](http://gocover.io/) etc.) *this is a benchmark*

add json benchmark

---

README.md

- github.com repo: https://github.com/DylanMeeus/GoAudio
- pkg.go.dev: https://pkg.go.dev/github.com/DylanMeeus/GoAudio
- goreportcard.com: https://goreportcard.com/report/github.com/DylanMeeus/GoAudio
- coverage service link ([codecov](https://codecov.io/), [coveralls](https://coveralls.io/), [gocover](http://gocover.io/) etc.): 
- https://gocover.io/github.com/DylanMeeus/GoAudio/breakpoint
- https://gocover.io/github.com/DylanMeeus/GoAudio/wave …

Add GoAudio - Native Audio Processing Library

---

README.md

Add Lille Gophers to website list

---

CONTRIBUTING.md

set contributing guide, /!\ warnning balance expectations

---

README.md

- github.com repo: https://github.com/bokwoon95/go-structured-query
- pkg.go.dev: https://pkg.go.dev/github.com/bokwoon95/go-structured-query/postgres https://pkg.go.dev/github.com/bokwoon95/go-structured-query/mysql
- goreportcard.com: https://goreportcard.com/report/github.com/bokwoon95/go-structured-query
- coverage service link: https://coveralls.io/github/bokwoon95/go-structured-query?branch=master …

add bokwoon95/go-structured-query to SQL query builder

---

README.md

- github.com repo: https://github.com/janiltonmaciel/statiks
- pkg.go.dev: https://pkg.go.dev/github.com/janiltonmaciel/statiks?tab=overview
- goreportcard.com: https://goreportcard.com/report/github.com/janiltonmaciel/statiks
- coverage service link ([codecov](https://codecov.io/), [coveralls](https://coveralls.io/), [gocover](http://gocover.io/) etc.): https://codecov.io/gh/janiltonmaciel/statiks
Very good coverage: 88%

add janiltonmaciel/statiks

---

README.md

This repos has been deleted and should be removed from the list.

Remove gostore from list (abandoned)

---

README.md

Add chanelify
- github.com repo: https://github.com/ddelizia/channelify/
- pkg.go.dev: https://pkg.go.dev/github.com/ddelizia/channelify
- goreportcard.com: https://goreportcard.com/report/github.com/ddelizia/channelify
- coverage service link ([gocover](https://gocover.io/github.com/ddelizia/channelify))

Add channelify

---

README.md

- github.com repo: https://github.com/vtopc/epoch
- pkg.go.dev: https://pkg.go.dev/github.com/vtopc/epoch
- goreportcard.com: https://goreportcard.com/report/github.com/vtopc/epoch
- coverage service link: https://codecov.io/gh/vtopc/epoch

Add vtopc/epoch

---

README.md

fixed description typo on id3v2

---

README.md

- github.com repo: https://github.com/tomwright/dasel
- pkg.go.dev: https://pkg.go.dev/github.com/tomwright/dasel
- goreportcard.com: https://goreportcard.com/report/github.com/TomWright/dasel
- coverage service link ([codecov](https://codecov.io/), [coveralls](https://coveralls.io/), [gocover](http://gocover.io/) etc.): https://codecov.io/gh/TomWright/dasel
All important querying/update functionality is covered. Cobra commands have not got tests yet but have been tested manually by myself. I will be adding tests for these in the future.
Very good …

Add Dasel.

---

README.md

Changed link to limetext
Refer to [issue 54 in limetext repo](https://github.com/limetext/limetext.github.io/issues/54)

Update link for limetext

---

README.md

- github.com repo: https://github.com/jonreiter/govader
- pkg.go.dev: https://pkg.go.dev/github.com/jonreiter/govader
- goreportcard.com: https://goreportcard.com/report/github.com/jonreiter/govader 
- coverage service link: https://codecov.io/gh/jonreiter/govader

added govader

---

README.md

- github.com repo: https://github.com/sonh/qs
- pkg.go.dev: https://pkg.go.dev/github.com/sonh/qs
- goreportcard.com: https://goreportcard.com/report/github.com/sonh/qs
- coverage service link: https://codecov.io/gh/sonh/qs
100% test covered
Thanks for this awesome libraries list ! :+1:

Add sonh/qs

---

README.md

- github.com repo: https://github.com/dinopuguh
- pkg.go.dev: https://pkg.go.dev/github.com/dinopuguh/gosentiwordnet/v2
- goreportcard.com: https://goreportcard.com/report/github.com/dinopuguh/gosentiwordnet
- coverage service link ([codecov](https://codecov.io/), [coveralls](https://coveralls.io/), [gocover](http://gocover.io/) etc.): https://codecov.io/gh/dinopuguh/gosentiwordnet …

📝 Add gosentiwordnet library

---

README.md

- github.com repo: https://github.com/camgraff/protoxy
- pkg.go.dev: https://pkg.go.dev/github.com/camgraff/protoxy?tab=overview
- goreportcard.com: https://goreportcard.com/report/github.com/camgraff/protoxy
- coverage service link: https://codecov.io/gh/camgraff/protoxy

Add protoxy

---

README.md

- github.com repo: [https://github.com/dimuska139/rawg-sdk-go](https://github.com/dimuska139/rawg-sdk-go)
- pkg.go.dev: [https://pkg.go.dev/github.com/dimuska139/rawg-sdk-go?tab=doc](https://pkg.go.dev/github.com/dimuska139/rawg-sdk-go?tab=doc)
- goreportcard.com: [https://goreportcard.com/report/github.com/dimuska139/rawg-sdk-go](https://goreportcard.com/report/github.com/dimuska139/rawg-sdk-go)
- coverage service link: [https://codecov.io/gh/dimuska139/rawg-sdk-go/branch/master](https://codecov.io/gh/dimuska139/rawg-sdk-go/branch/master)
Very good …

Update README to add rawg-sdk-go library

---

README.md

- github.com repo: https://github.com/phuslu/log
- pkg.go.dev: https://pkg.go.dev/github.com/phuslu/log
- goreportcard.com: https://goreportcard.com/report/github.com/phuslu/log
- coverage service link: https://gocover.io/github.com/phuslu/log

Add phuslu/log

---

README.md

fixed: #3295
- pkg.go.dev:
this is a removal of repos that have not been active as noted in #3295 in the last year here is the summary of what i found for each one:
note …

removed repositories due to inactivity issue # #3295

---

README.md

Hey @avelino 
just improving the readability a bit by adding missing spaces etc.
Cheers!

Add missing spaces

---

README.md

Hey @avelino 
just a typo...
Cheers!

Typo: dirver -> driver

---

README.md

- pkg.go.dev:
Here is the report for these repos, suprisingly only one seemed not really maintained. this is for [issue # …

got rid of one repository that did not appear to be maintained anymore

---

README.md

Update dasel description and change category

---

README.md

- github.com repo: https://github.com/mikekonan/go-countries
- pkg.go.dev: https://pkg.go.dev/github.com/mikekonan/go-countries
- goreportcard.com: https://goreportcard.com/report/github.com/mikekonan/go-countries
- gocover: https://gocover.io/github.com/mikekonan/go-countries

added go-countries

---

README.md

Add [Belfast Gophers](https://www.meetup.com/Belfast-Gophers/) meetup.

Add Belfast Gophers meetup

---

README.md

Readability: Adding missing space

---

README.md

- github.com repo: https://github.com/yahoo/panoptes-stream
- pkg.go.dev: https://pkg.go.dev/github.com/yahoo/panoptes-stream
- goreportcard.com: https://goreportcard.com/report/github.com/yahoo/panoptes-stream
- coverage service link [coveralls](https://coveralls.io/github/yahoo/panoptes-stream)

add panoptes-stream streaming network telemetry

---

README.md

Add Vienna, Austria Meetup

---

README.md

- github.com repo: https://github.com/gotidy/copy
- pkg.go.dev: https://pkg.go.dev/github.com/gotidy/copy
- goreportcard.com: https://goreportcard.com/report/github.com/gotidy/copy
- coverage service: link https://gocover.io/github.com/gotidy/copy 

Added «copy» package

---

README.md

- github.com repo: github.com/arl/statsviz
- pkg.go.dev: https://pkg.go.dev/github.com/arl/statsviz
- goreportcard.com: https://goreportcard.com/report/github.com/arl/statsviz
- coverage service link: there is no automated coverage, there are some tests but the Go code part is relatively tiny, most of the code is a single page application served by the Go package.

Add statsviz

---

README.md

- github.com repo: https://github.com/Eun/go-hit
- pkg.go.dev: https://pkg.go.dev/github.com/Eun/go-hit
- goreportcard.com: https://goreportcard.com/report/github.com/Eun/go-hit
- coverage service link: https://codecov.io/gh/Eun/go-hit

add go-hit

---

README.md

- github.com repo: https://github.com/newity/fastme
- pkg.go.dev: https://pkg.go.dev/github.com/newity/fastme
- goreportcard.com: https://goreportcard.com/report/github.com/newity/fastme
- gocover.io: https://gocover.io/github.com/newity/fastme

Add fastme library

---

README.md

Requested links:
- github.com repo: [gohooks](https://github.com/averageflow/gohooks)
- pkg.go.dev: [pkg.go.dev documentation](https://pkg.go.dev/github.com/averageflow/gohooks/gohooks)
- goreportcard.com: [goreportcard.com](https://goreportcard.com/report/github.com/averageflow/gohooks)
- coverage service link [codecov](https://codecov.io/gh/averageflow/gohooks)
Accepted conditions:
- [ x ] I have added my package in alphabetical order.
- [ x ] I have an appropriate description with correct grammar.
- [ x ] I know that this package was not listed before.
- [ x ] I have added pkg.go.dev link to the repo and to my pull request.
- [ x ] I have added coverage service link to the repo and to my pull request.
- [ x ] I have added goreportcard link to the repo and to my pull request.
- [ x ] I …

add GoHooks

---

README.md

Typo: implemeted -> implemented

---

README.md

This PR adds go-aws-news to awesome-go. go-aws-news is both a configurable application and Go library to fetch, manipulate and post the latest product announcements from AWS news.
Signed-off-by: circa10a <caleblemoine@gmail.com>
- github.com repo: https://github.com/circa10a/go-aws-news
- godoc.org: https://godoc.org/github.com/circa10a/go-aws-news/news
- pkg.go.dev: https://pkg.go.dev/github.com/circa10a/go-aws-news?tab=overview
- goreportcard.com: https://goreportcard.com/report/github.com/circa10a/go-aws-news
- coverage service link …

Add go-aws-news

---

README.md

- github.com repo: https://github.com/lane-c-wagner/go-password-validator
- pkg.go.dev: https://pkg.go.dev/github.com/lane-c-wagner/go-password-validator
- goreportcard.com: https://goreportcard.com/report/github.com/lane-c-wagner/go-password-validator
- coverage service link ([codecov](https://codecov.io/), [coveralls](https://coveralls.io/), [gocover](http://gocover.io/) etc.): https://gocover.io/github.com/lane-c-wagner/go-password-validator …

add go-password-validator

---

README.md

- github.com repo: https://github.com/elgohr/stop-and-go
- pkg.go.dev: https://pkg.go.dev/github.com/elgohr/stop-and-go?tab=overview
- goreportcard.com: https://goreportcard.com/report/github.com/elgohr/stop-and-go
- coverage service link: https://codecov.io/gh/elgohr/stop-and-go

Add stop-and-go

---

README.md

Hey @avelino,
just improving the readability a bit...
Cheers!

Fixing plural

---

README.md

- github.com repo: https://github.com/codenotary/immudb
- pkg.go.dev: https://pkg.go.dev/github.com/codenotary/immudb?tab=doc
- goreportcard.com: https://goreportcard.com/report/github.com/codenotary/immudb
- coverage service link ([codecov](https://codecov.io/), [coveralls](https://coveralls.io/), [gocover](http://gocover.io/) etc.) https://coveralls.io/github/codenotary/immudb?branch=master
Very good coverage [Go Report Card](https://goreportcard.com/report/github.com/codenotary/immudb) [coveralls](https://coveralls.io/github/codenotary/immudb?branc …

Add immudb

---

README.md

Added package `slices`
- github.com repo: https://github.com/srfrog/slices
- pkg.go.dev: https://pkg.go.dev/github.com/srfrog/slices
- goreportcard.com: https://goreportcard.com/report/github.com/srfrog/slices
- coverage service link: https://codecov.io/gh/srfrog/slices/

Add package slices

---

README.md

add `github.com/youthlin/stream`
- github.com repo: https://github.com/youthlin/stream
- pkg.go.dev: https://pkg.go.dev/github.com/youthlin/stream
- goreportcard.com: https://goreportcard.com/report/github.com/youthlin/stream
- coverage service link ([codecov](https://codecov.io/), [coveralls](https://coveralls.io/), [gocover](http://gocover.io/) etc.): https://codecov.io/gh/youthlin/stream …

add `github.com/youthlin/stream`

---

README.md

- github.com repo: https://github.com/mehrdadrad/tcpprobe
- pkg.go.dev: https://pkg.go.dev/github.com/mehrdadrad/tcpprobe
- goreportcard.com: https://goreportcard.com/report/github.com/mehrdadrad/tcpprobe
- coverage service link [coveralls](https://coveralls.io/github/mehrdadrad/tcpprobe?branch=main)

add tcpprobe

---

README.md

- github.com repo: https://github.com/leberKleber/simple-jwt-provider
- pkg.go.dev: https://pkg.go.dev/github.com/leberKleber/simple-jwt-provider
- goreportcard.com: https://goreportcard.com/report/github.com/leberKleber/simple-jwt-provider
- coverage service link ([codecov](https://codecov.io/), [coveralls](https://coveralls.io/), [gocover](http://gocover.io/) etc.): https://codecov.io/gh/leberKleber/simple-jwt-provider …

Add simple-jwt-provider (https://github.com/leberKleber/simple-jwt-provider)

---

README.md

- github.com repo: https://github.com/jf-tech/omniparser
- pkg.go.dev: https://pkg.go.dev/github.com/jf-tech/omniparser
- goreportcard.com: https://goreportcard.com/report/github.com/jf-tech/omniparser
- coverage service link: https://codecov.io/gh/jf-tech/omniparser

Add omniparser

---

README.md

- github.com repo: https://github.com/1set/todotxt
- pkg.go.dev: https://pkg.go.dev/github.com/1set/todotxt
- goreportcard.com: https://goreportcard.com/report/github.com/1set/todotxt
- coverage service link: https://codecov.io/gh/1set/todotxt

Add todotxt in file handling section

---

README.md

- github.com repo: https://github.com/go-git/go-git
- pkg.go.dev: https://pkg.go.dev/github.com/go-git/go-git/v5
- goreportcard.com: https://goreportcard.com/report/github.com/go-git/go-git
- coverage service link ([codecov](https://codecov.io/), [coveralls](https://coveralls.io/), [gocover](http://gocover.io/) etc.): https://github.com/go-git/go-git/actions?query=workflow%3ATest …

Update link go-git

---

README.md

- github.com repo: https://github.com/yandex/go-hasql
- pkg.go.dev: https://pkg.go.dev/golang.yandex/hasql
- goreportcard.com: https://goreportcard.com/report/golang.yandex/hasql
- coverage service link ([codecov](https://codecov.io/), [coveralls](https://coveralls.io/), [gocover](http://gocover.io/) etc.): https://codecov.io/gh/yandex/go-hasql …

Add golang.yandex/hasql

---

README.md

- github.com repo: https://github.com/whitaker-io/machine
- pkg.go.dev: https://pkg.go.dev/github.com/whitaker-io/machine
- goreportcard.com: https://goreportcard.com/report/github.com/whitaker-io/machine
- coverage service link ([codecov](https://codecov.io/), [coveralls](https://coveralls.io/), [gocover](http://gocover.io/) etc.): https://app.codacy.com/gh/whitaker-io/machine …

Add github.com/whitaker-io/machine

---

README.md

- github.com repo: https://github.com/vivek-ng/concurrency-limiter
- pkg.go.dev: https://pkg.go.dev/github.com/vivek-ng/concurrency-limiter
- goreportcard.com: https://goreportcard.com/report/github.com/vivek-ng/concurrency-limiter
- coverage service link ([codecov](https://codecov.io/gh/vivek-ng/concurrency-limiter))

Add concurrency limiter

---

README.md

- github.com repo: https://github.com/go-co-op/gocron
- pkg.go.dev: https://pkg.go.dev/github.com/go-co-op/gocron
- goreportcard.com: https://goreportcard.com/report/github.com/go-co-op/gocron
- coverage service link ([codecov](https://codecov.io/), [coveralls](https://coveralls.io/), [gocover](http://gocover.io/) etc.) https://gocover.io/github.com/go-co-op/gocron
Thanks for …

Add go-co-op/gocron to Job Scheduler

---

README.md

- github.com repo: https://github.com/fabiocicerchia/go-proxy-cache
- pkg.go.dev: https://pkg.go.dev/github.com/fabiocicerchia/go-proxy-cache
- goreportcard.com: https://goreportcard.com/report/github.com/fabiocicerchia/go-proxy-cache
- coverage service link ([codecov](https://codecov.io/), [coveralls](https://coveralls.io/), [gocover](http://gocover.io/) etc.): https://codecov.io/gh/fabiocicerchia/go-proxy-cache …

added go-proxy-cache as server application

---

README.md

- github.com repo: https://github.com/nikolaydubina/go-featureprocessing
- pkg.go.dev: https://pkg.go.dev/github.com/nikolaydubina/go-featureprocessing
- goreportcard.com: https://goreportcard.com/report/github.com/nikolaydubina/go-featureprocessing
- coverage service link: https://codecov.io/gh/nikolaydubina/go-featureprocessing
Very good coverage: 97%, key code is 100% …

added go-featureprocessing

---

README.md

- github.com repo: https://github.com/wI2L/jsondiff
- pkg.go.dev: https://pkg.go.dev/github.com/wI2L/jsondiff?tab=doc
- goreportcard.com: https://goreportcard.com/report/wI2L/jsondiff
- coverage service link ([codecov](https://codecov.io/), [coveralls](https://coveralls.io/), [gocover](http://gocover.io/) etc.): https://codecov.io/gh/wI2L/jsondiff …

feat: add github.com/wI2L/jsondiff

---

README.md

This is simply an update of the description of an existing project: https://github.com/wI2L/jettison

fix: update github.com/wI2L/jettison description

---

README.md

- github.com repo: https://github.com/krotik/ecal
- pkg.go.dev: https://pkg.go.dev/devt.de/krotik/ecal
- goreportcard.com: https://goreportcard.com/report/devt.de/krotik/ecal
https://gocover.io/github.com/krotik/ecal/cli
https://gocover.io/github.com/krotik/ecal/config
https://gocover.io/github.com/krotik/ecal/engine
https://gocover.io/github.com/krotik/ecal/interpreter
https://gocover.io/github.com/krotik/ecal/parser …

Adding ECAL language interpreter

---

README.md

Hey @avelino 
just improving the readability a bit..
Cheers!

Improving readabilitiy

---

README.md

Added [hare](https://github.com/leozz37/hare) to #messaging category
- github.com repo: https://github.com/leozz37/hare
- pkg.go.dev: https://pkg.go.dev/github.com/leozz37/hare
- goreportcard.com: https://goreportcard.com/report/github.com/leozz37/hare
- coverage service link: https://codecov.io/gh/leozz37/hare

Added hare repo

---

README.md

- github.com repo: https://github.com/dnnrly/abbreviate
- pkg.go.dev: https://pkg.go.dev/github.com/dnnrly/abbreviate
- goreportcard.com: https://goreportcard.com/report/github.com/dnnrly/abbreviate
- coverage service link: https://codecov.io/gh/dnnrly/abbreviate

Add abbreviate

---

README.md

- github.com repo: https://github.com/AfterShip/email-verifier
- pkg.go.dev: https://pkg.go.dev/github.com/AfterShip/email-verifier
- goreportcard.com: https://goreportcard.com/report/github.com/AfterShip/email-verifier
https://gocover.io/github.com/AfterShip/email-verifier …

Add email-verifier repo

---

README.md

https://github.com/noraesae/orange-cat - doesn't exist
https://github.com/LyricalSecurity/gigo - doesn't exist
https://github.com/Obaied/RAKE.go - was moved
https://github.com/mholt/caddy - was moved

Remove and update 4 repos

---

README.md

- github.com repo: https://github.com/sinhashubham95/bleep
- pkg.go.dev: https://pkg.go.dev/github.com/sinhashubham95/bleep
- goreportcard.com: https://goreportcard.com/report/github.com/sinhashubham95/bleep
- coverage service link ([codecov](https://codecov.io/), [coveralls](https://coveralls.io/), [gocover](http://gocover.io/) etc.) https://coveralls.io/github/sinhashubham95/bleep?branch=master …

Adding Bleep

---

README.md

- github.com repo: https://github.com/miniscruff/changie
- pkg.go.dev: https://pkg.go.dev/github.com/miniscruff/changie
- goreportcard.com: https://goreportcard.com/report/github.com/miniscruff/changie
- coverage service link ([codecov](https://codecov.io/), [coveralls](https://coveralls.io/), [gocover](http://gocover.io/) etc.): https://codecov.io/gh/miniscruff/changie
No, you're awesome 👍

add changie

---

README.md

Quality standards:
- github.com repo: https://github.com/Masterminds/sprig
- pkg.go.dev: https://pkg.go.dev/github.com/Masterminds/sprig/v3
- goreportcard.com: https://goreportcard.com/report/github.com/Masterminds/sprig
- coverage service link ([codecov](https://codecov.io/), [coveralls](https://coveralls.io/), [gocover](http://gocover.io/) etc.): https://gocover.io/github.com/Masterminds/sprig
PR requirements:

Add the sprig template functions library

---

README.md

- github.com repo: https://github.com/golang-templates/seed
- pkg.go.dev: https://pkg.go.dev/github.com/golang-templates/seed
- goreportcard.com: https://goreportcard.com/report/github.com/golang-templates/seed
- coverage service link: https://codecov.io/gh/golang-templates/seed

Add golang-templates/seed

---

README.md

github.com repo: https://github.com/nlpodyssey/spago
pkg.go.dev: https://pkg.go.dev/github.com/nlpodyssey/spago?tab=overview
goreportcard.com: https://goreportcard.com/report/github.com/nlpodyssey/spago
coverage service link: https://codecov.io/gh/nlpodyssey/spago
Additional info:

Add https://github.com/nlpodyssey/spago

---

README.md

- github.com repo: [https://github.com/pasdam/mockit](https://github.com/pasdam/mockit)
- pkg.go.dev: [https://pkg.go.dev/github.com/pasdam/mockit/mockit](https://pkg.go.dev/github.com/pasdam/mockit/mockit?status.svg)
- goreportcard.com: [https://goreportcard.com/report/github.com/pasdam/mockit](https://goreportcard.com/report/github.com/pasdam/mockit)
- coverage service link ([codecov](https://codecov.io/), [coveralls](https://coveralls.io/), [gocover](http://gocover.io/) etc.): [https://github.com/pasdam/mockit/runs/1579075353?check_suite_focus=true …

Add mockito to testing section

---

README.md

- github.com repo: [https://github.com/edoger/zkits-logger](https://github.com/edoger/zkits-logger)
- pkg.go.dev: [https://pkg.go.dev/github.com/edoger/zkits-logger](https://pkg.go.dev/github.com/edoger/zkits-logger)
- goreportcard.com: [https://goreportcard.com/report/github.com/edoger/zkits-logger](https://goreportcard.com/report/github.com/edoger/zkits-logger)
- coverage service link ([codecov](https://codecov.io/), [coveralls](https://coveralls.io/), [gocover](http://gocover.io/) etc.): [https://coveralls.io/github/edoger/zkits-logger](https://cov …

Add zkits logger library.

---

README.md

- github.com repo: https://github.com/krayzpipes/cronticker
- pkg.go.dev: https://pkg.go.dev/github.com/krayzpipes/cronticker
- goreportcard.com: https://goreportcard.com/report/github.com/krayzpipes/cronticker
- coverage service link ([codecov](https://codecov.io/), [coveralls](https://coveralls.io/), [gocover](http://gocover.io/) etc.): https://codecov.io/gh/krayzpipes/cronticker …

added cronticker

---

README.md

- github.com repo: https://github.com/rinchsan/device-check-go
- pkg.go.dev: https://pkg.go.dev/github.com/rinchsan/device-check-go
- goreportcard.com: https://goreportcard.com/report/github.com/rinchsan/device-check-go
- coverage service link: https://codecov.io/github/rinchsan/device-check-go?branch=master

Add device-check-go

---

README.md

- github.com repo: https://github.com/bojanz/address
- pkg.go.dev: https://pkg.go.dev/github.com/bojanz/address?tab=doc
- goreportcard.com: https://goreportcard.com/report/github.com/bojanz/address
- coverage service link ([coveralls](https://coveralls.io/)) https://coveralls.io/github/bojanz/address?branch=master

Add bojanz/address

---

README.md

- github.com repo: https://github.com/sinhashubham95/jsonic
- pkg.go.dev: https://pkg.go.dev/github.com/sinhashubham95/jsonic
- goreportcard.com: https://goreportcard.com/report/github.com/sinhashubham95/jsonic
- coverage service link ([codecov](https://codecov.io/), [coveralls](https://coveralls.io/), [gocover](http://gocover.io/) etc.) https://coveralls.io/github/sinhashubham95/jsonic?branch=master …

Adding Jsonic

---

README.md

- github.com repo: https://github.com/thomaspoignant/go-feature-flag
- pkg.go.dev: https://pkg.go.dev/github.com/thomaspoignant/go-feature-flag
- goreportcard.com: https://goreportcard.com/report/github.com/thomaspoignant/go-feature-flag
- coverage service link: https://coveralls.io/github/thomaspoignant/go-feature-flag

Add thomaspoignant/go-feature-flag

---

README.md

- github.com repo: -
- pkg.go.dev: -
- goreportcard.com: -
- coverage service link ([codecov](https://codecov.io/), [coveralls](https://coveralls.io/), [gocover](http://gocover.io/) etc.) -
- [X ] I have read [Contribution guidelines](https://github.com/avelino/awesome-go/blob/master/CONTRIBUTING.md#contribution-guidelines), [maintainers …

Added golangresources.com

---

README.md

- github.com repo: https://github.com/valyala/fastjson
- pkg.go.dev: https://pkg.go.dev/github.com/valyala/fastjson
- goreportcard.com: https://goreportcard.com/report/github.com/valyala/fastjson
- coverage service link: https://codecov.io/gh/valyala/fastjson

Add fastjson

---

README.md

- github.com repo: https://github.com/go-email-validator/go-email-validator
- pkg.go.dev: https://pkg.go.dev/github.com/go-email-validator/go-email-validator
- goreportcard.com: https://goreportcard.com/report/github.com/go-email-validator/go-email-validator
- coverage service link ([codecov](https://codecov.io/), [coveralls](https://coveralls.io/), [gocover](http://gocover.io/) etc.) https://codecov.io/gh/go-email-validator/go-email-validator

Add go-email-validator

---

README.md

- github.com repo: https://github.com/mxschmitt/playwright-go
- pkg.go.dev: https://pkg.go.dev/github.com/mxschmitt/playwright-go
- goreportcard.com: https://goreportcard.com/report/github.com/mxschmitt/playwright-go
- coverage service link: https://coveralls.io/github/mxschmitt/playwright-go?branch=master - adding more upstream tests will follow in the next weeks. The "magic" and logic happens in the main project, so checking the main functionality is enough.
**Make …

Add Playwright

---

README.md

- github.com repo: https://github.com/pellared/taskflow
- pkg.go.dev: https://pkg.go.dev/github.com/pellared/taskflow
- goreportcard.com: https://goreportcard.com/report/github.com/pellared/taskflow
- coverage service links: https://gocover.io/github.com/pellared/taskflow , https://codecov.io/gh/pellared/taskflow 

Create Build Automation category and add taskflow

---

README.md

- github.com repo: [https://github.com/mehdipourfar/webp-server](https://github.com/mehdipourfar/webp-server)
- pkg.go.dev: [https://pkg.go.dev/github.com/mehdipourfar/webp-server](https://pkg.go.dev/github.com/mehdipourfar/webp-server)
- goreportcard.com: [https://goreportcard.com/report/github.com/mehdipourfar/webp-server](https://goreportcard.com/report/github.com/mehdipourfar/webp-server) …

Add webp-server

---

README.md

- github.com repo: https://github.com/lawzava/go-pg-migrate
- pkg.go.dev: https://pkg.go.dev/github.com/lawzava/go-pg-migrate
- goreportcard.com: https://goreportcard.com/report/github.com/lawzava/go-pg-migrate
- coverage service link: https://coveralls.io/github/lawzava/go-pg-migrate?branch=main
91% Coverage

Add go-pg-migrate

---

README.md

- github.com repo: https://github.com/AsaiYusuke/jsonpath
- pkg.go.dev: https://pkg.go.dev/github.com/AsaiYusuke/jsonpath
- goreportcard.com: https://goreportcard.com/report/github.com/AsaiYusuke/jsonpath
- coverage service link: https://coveralls.io/github/AsaiYusuke/jsonpath?branch=main
Very good coverage 97%

Add AsaiYusuke/jsonpath

---

README.md

- github.com repo: https://github.com/wajox/gobase
- pkg.go.dev: https://pkg.go.dev/github.com/wajox/gobase
- goreportcard.com: https://goreportcard.com/report/github.com/wajox/gobase
- coverage service link: https://codecov.io/gh/wajox/gobase/

add wajox/gobase

---

README.md

Add httpref

---

README.md

- github.com repo: https://github.com/recolude/unitpacking
- pkg.go.dev: https://pkg.go.dev/github.com/recolude/unitpacking/unitpacking
- goreportcard.com: https://goreportcard.com/report/github.com/recolude/unitpacking
- coverage service link: https://codecov.io/gh/recolude/unitpacking

Added Unitpacking (#1)

---

README.md

- github.com repo: https://github.com/catmullet/go-workers
- pkg.go.dev: https://pkg.go.dev/github.com/catmullet/go-workers
- goreportcard.com: https://goreportcard.com/report/github.com/catmullet/go-workers
- coverage service link ([codecov](https://codecov.io/), [coveralls](https://coveralls.io/), [gocover](http://gocover.io/) etc.) https://gocover.io/github.com/catmullet/go-workers …

Adding go-workers to README.md

---

README.md

- github.com repo: https://github.com/blind-oracle/cortex-tenant
- pkg.go.dev: Not applicable (service, not library)
- goreportcard.com: https://goreportcard.com/report/github.com/blind-oracle/cortex-tenant
- coverage service link: https://coveralls.io/github/blind-oracle/cortex-tenant?branch=main

Add Cortex-Tenant to Server Applications

---

README.md

- github.com repo: https://github.com/prashantgupta24/go-clip
- pkg.go.dev: https://pkg.go.dev/github.com/prashantgupta24/go-clip
- goreportcard.com: https://goreportcard.com/report/github.com/prashantgupta24/go-clip
- coverage service link: https://codecov.io/gh/prashantgupta24/go-clip/ (~76% coverage~ 80.87% coverage)

Added go-clip repo

---

README.md

- github.com repo: https://github.com/Delta456/box-cli-maker
- pkg.go.dev: https://pkg.go.dev/github.com/Delta456/box-cli-maker/v2
- goreportcard.com: https://goreportcard.com/report/github.com/Delta456/box-cli-maker
- coverage service link ([codecov](https://codecov.io/), [coveralls](https://coveralls.io/), [gocover](http://gocover.io/) etc.): https://golangci.com/r/github.com/Delta456/box-cli-maker …

add box-cli-maker

---

README.md

- github.com repo: [https://github.com/sgrodriguez/ddt](https://github.com/sgrodriguez/ddt)
- pkg.go.dev: [https://pkg.go.dev/github.com/sgrodriguez/ddt](https://pkg.go.dev/github.com/sgrodriguez/ddt)
- goreportcard.com: [https://goreportcard.com/report/github.com/sgrodriguez/ddt](https://goreportcard.com/report/github.com/sgrodriguez/ddt)
- coverage service link: [https://codecov.io/gh/sgrodriguez/ddt](https://codecov.io/gh/sgrodriguez/ddt)
**Make …

README.md: add ddt lib

---

README.md

- github.com repo: https://github.com/99designs/gqlgen
- pkg.go.dev: https://pkg.go.dev/github.com/99designs/gqlgen
- goreportcard.com: https://goreportcard.com/report/github.com/99designs/gqlgen
- coverage service link: https://gocover.io/github.com/99designs/gqlgen
- website: https://gqlgen.com
**Additional notes:**
This projects is really awesome and is 5500 stars on GitHub.
- previous PR: https://github.com/avelino/awesome-go/pull/2347
- previous PR: https://github.com/avelino/awesome-go/pull/2566

Add gqlgen

---

README.md

- github.com repo: https://github.com/BlueOwlOpenSource/nject
- pkg.go.dev: https://pkg.go.dev/github.com/BlueOwlOpenSource/nject
- goreportcard.com: https://goreportcard.com/report/github.com/BlueOwlOpenSource/nject
- coverage service link ([codecov](https://codecov.io/), [coveralls](https://coveralls.io/), [gocover](http://gocover.io/) etc.): https://gocover.io/github.com/BlueOwlOpenSource/nject/nject & https://gocover.io/github.com/BlueOwlOpenSource/nject/npoint
Npoint has a bunch of one-line wrapper functions that bring down its coverge numbers …

Add nject/npoint dependency injection frameworks

---

README.md

- github.com repo: [gonfig](https://github.com/milad-abbasi/gonfig)
- pkg.go.dev: [docs](https://pkg.go.dev/github.com/milad-abbasi/gonfig)
- goreportcard.com: [goreportcard](https://goreportcard.com/report/github.com/milad-abbasi/gonfig)
- coverage service link: [codecov](https://codecov.io/gh/milad-abbasi/gonfig), [gocover](https://gocover.io/github.com/milad-abbasi/gonfig) …

Add gonfig to configuration libs

---

README.md

- github.com repo: [github.com/go-kata/kinit](https://github.com/go-kata/kinit)
- pkg.go.dev: [pkg.go.dev/github.com/go-kata/kinit](https://pkg.go.dev/github.com/go-kata/kinit)
- goreportcard.com: [goreportcard.com/report/github.com/go-kata/kinit](https://goreportcard.com/report/github.com/go-kata/kinit)
- coverage service link: [codecov.io/gh/go-kata/kinit](https://codecov.io/gh/go-kata/kinit)
Mostly obvious `Must` cases are not covered. …

Add github.com/go-kata/kinit

---

README.md

- github.com repo: [repo => go-oas/docs](https://github.com/go-oas/docs)
- pkg.go.dev: [pkg.go.dev => go-oas/docs](https://pkg.go.dev/github.com/go-oas/docs)
- goreportcard.com: [report card => go-oas/docs](https://goreportcard.com/report/github.com/go-oas/docs)
- coverage service link: [coveralls](https://coveralls.io/github/go-oas/docs)
Very good coverage - currently ~94% => but planning to add a few more _QuickCheck_ tests to cover more edge cases. …

Add go-OAS/docs

---

README.md

- github.com repo: https://github.com/mehrdadrad/tcpdog
- pkg.go.dev: https://pkg.go.dev/github.com/mehrdadrad/tcpdog
- goreportcard.com: https://goreportcard.com/report/github.com/mehrdadrad/tcpdog
- coverage service link [![Coverage Status](https://coveralls.io/repos/github/mehrdadrad/tcpdog/badge.svg?branch=main)](https://coveralls.io/github/mehrdadrad/tcpdog?branch=main) …

add tcpdog

---

README.md

**Links**
- github.com repo: https://github.com/simonnilsson/ask
- pkg.go.dev: https://pkg.go.dev/github.com/simonnilsson/ask
- goreportcard.com: https://goreportcard.com/report/github.com/simonnilsson/ask
- coverage service link: https://gocover.io/github.com/simonnilsson/ask
**Checkboxes**

Add ask to JSON category

---

README.md

- github.com repo: [https://github.com/milosgajdos/go-estimate](https://github.com/milosgajdos/go-estimate)
- pkg.go.dev: [https://pkg.go.dev/github.com/milosgajdos/go-estimate](https://pkg.go.dev/github.com/milosgajdos/go-estimate)
- goreportcard.com: [https://goreportcard.com/report/github.com/milosgajdos/go-estimate](https://goreportcard.com/report/github.com/milosgajdos/go-estimate)
- coverage service link: [https://codecov.io/gh/milosgajdos/go-estimate](https://codecov.io/gh/milosgajdos/go-estimate)

Add go-estimate

---

README.md

- github.com repo: https://github.com/inancgumus/learngo
- pkg.go.dev: https://pkg.go.dev/github.com/inancgumus/learngo
- goreportcard.com: https://goreportcard.com/report/github.com/inancgumus/learngo
- coverage service link: It's a tutorial repository, so the coverage is not available.

Add learngo

---

README.md

- github.com repo: https://github.com/Kachit/appstore-sdk-go
- pkg.go.dev: https://pkg.go.dev/github.com/kachit/appstore-sdk-go
- goreportcard.com: https://goreportcard.com/report/github.com/kachit/appstore-sdk-go
- coverage service link https://app.codecov.io/gh/Kachit/appstore-sdk-go/branch/master

Add appstore-sdk-go

---

README.md

- github.com repo: https://github.com/maja42/goval
- pkg.go.dev: [![GoDoc](https://godoc.org/github.com/maja42/goval?status.svg)](https://pkg.go.dev/github.com/maja42/goval) 
- goreportcard.com: [![Go Report Card](https://goreportcard.com/badge/github.com/maja42/goval)](https://goreportcard.com/report/github.com/maja42/goval)
- coverage service link [![Coverage Status](https://coveralls.io/repos/github/maja42/goval/badge.svg?branch=master)](https://coveralls.io/github/maja42/goval?branch=master)
Note: Low coverage is caused by auto-generated, …

add maja42/goval

---

README.md

Now nlopes/slack is transferred to slack-go/slack.
See also: https://github.com/slack-go/slack/issues/642
---
- github.com repo: https://github.com/slack-go/slack
- pkg.go.dev: https://pkg.go.dev/github.com/slack-go/slack
- goreportcard.com: https://goreportcard.com/report/github.com/slack-go/slack …

Fix link to slack API client

---

README.md

- github.com repo: https://github.com/0xERR0R/blocky
- pkg.go.dev:
- goreportcard.com: https://goreportcard.com/report/github.com/0xERR0R/blocky
- coverage service link: https://app.codecov.io/gh/0xERR0R/blocky/branch/development

add blocky to other software

---

README.md

- github.com repo: https://github.com/tal-tech/go-zero
- pkg.go.dev: https://pkg.go.dev/github.com/tal-tech/go-zero
- goreportcard.com: https://goreportcard.com/report/github.com/tal-tech/go-zero
https://codecov.io/gh/tal-tech/go-zero …

add go-zero (https://github.com/tal-tech/go-zero)

---

README.md

- github.com repo: https://github.com/innogames/slack-bot
- pkg.go.dev: https://pkg.go.dev/github.com/innogames/slack-bot/
- goreportcard.com: https://goreportcard.com/report/github.com/innogames/slack-bot
- coverage service: https://codecov.io/gh/innogames/slack-bot
[![Go Report Card](https://goreportcard.com/badge/github.com/innogames/slack-bot)](https://goreportcard.com/report/github.com/innogames/slack-bot)
[![codecov](https://codecov.io/gh/innogames/slack-bot/branch/master/graph/badge.svg)](https://codecov.io/gh/innogames/slack-bot)
**Note**: …

Added "slack-bot"

---

README.md

- github.com repo: https://github.com/jameycribbs/hare
- pkg.go.dev: https://pkg.go.dev/github.com/jameycribbs/hare
- goreportcard.com: https://goreportcard.com/report/github.com/jameycribbs/hare
- coverage service link: https://gocover.io/github.com/jameycribbs/hare

Add link to hare under Databases.

---

README.md

- github.com repo: https://github.com/lesismal/nbio
- pkg.go.dev: https://pkg.go.dev/github.com/lesismal/nbio?tab=doc
- goreportcard.com: https://goreportcard.com/report/github.com/lesismal/nbio
- coverage service link: https://codecov.io/gh/lesismal/nbio

Add lesismal/nbio

---

README.md

- github.com repo:[https://github.com/linvon/cuckoo-filter](https://github.com/linvon/cuckoo-filter)
- pkg.go.dev:[https://pkg.go.dev/github.com/linvon/cuckoo-filter](https://pkg.go.dev/github.com/linvon/cuckoo-filter)
- goreportcard.com:[https://goreportcard.com/report/github.com/linvon/cuckoo-filter](https://goreportcard.com/report/github.com/linvon/cuckoo-filter)
- coverage service link [gocover](https://gocover.io/github.com/linvon/cuckoo-filter) …

Add a more comprehensive cuckoo filter

---

README.md

- github.com repo: https://github.com/tejzpr/ordered-concurrently
- pkg.go.dev: https://pkg.go.dev/github.com/tejzpr/ordered-concurrently
- goreportcard.com: https://goreportcard.com/report/github.com/tejzpr/ordered-concurrently
- coverage service link [gocover](https://gocover.io/github.com/tejzpr/ordered-concurrently)

Added ordered-concurrently

---

README.md

ref: #3522 - more than 1 year without update

remove github.com/krig/go-sox

---

README.md

ref: #3522 more than 1 year without update
sad to have to remove libraries

remove github.com/tcolgate/mp3
