avelino/awesome-go

README.md

Lime Text is a powerful and elegant text editor primarily developed in Go that aims to be a Free and open-source software successor to Sublime Text. See http://limetext.org/

add Editor: limetext

---

README.md

* Add additional logging plugins	 a93e117
* Add go-amz library	 d526760
* Add goamz fork from Hashiecorp

Add additional packages

---

README.md

Fuzzing is in general the generation of data e.g. For testing functions with random values.
Delta-debugging/reducing/shrinking (all three names describe the same thing but the scientific community does not agree to one) describe techniques to reduce data systematically e.g. An input X leads to an error. Give me the minimal version of X which still reproduces the error.
These two areas come normally hand in hand since the same rules for generating can be used to reduce data. I would also like to add a symbolic execution and dynamic symbolic exuction section but I do not know any tool (yet) which is written in Go and does that.

Add section for fuzzing and delta-debugging/reducing/shrinking

---

README.md

I think that Square's recently released Go library for the JOSE standards merits inclusion. It is, I think, nearly the most complete implementation those specs have seen in any language at this point...

github.com/square/go-jose: a library for JWT, JWS, and JWE

---

README.md

add Leaf framework: A lightweight game server framework

update the game development list

---

README.md

Subject as discussed here https://github.com/avelino/awesome-go/pull/268

FastLz library

---

README.md

Adding Resoursea, a new and powerful REST framework.

Adding Resoursea framework.

---

README.md

add: golang-sql-benchmark

---

README.md

* useful lib if you write web apps
* actively maintained
* full test suite with tests on travis

Adding link to https://github.com/tomazk/envcfg

---

README.md

https://github.com/ivpusic/neo - http://ivpusic.github.io/neo/

Added neo web framework

---

README.md

easyssh added

---

README.md

hello, is the library I've used for quite some time and worked very well.

add gami, client asterisk manager interface

---

README.md

missing Bing

---

README.md

Miscellaneous section had 4 packages dedicated to configuration
management and parsing. New configuration section created with this
packages:
* envcfg
* envconf
* gofigure
* viper

Added configuration section

---

README.md

JSON or YAML configuration wrapper with environment variables and flags parsing

Config tool added

---

README.md

Add gonum/matrix, which is the best matrix package I've seen in go currently.
Also, I update the development status of some other matrix related packages.

Add gonum/matrix

---

README.md

Added Validation section for application data validation

Add Validation section

---

README.md

Pull request as requested in issue #307

Added go-json-rest web framework

---

README.md

Adds exponential backoff package.

Add package goback

---

README.md

Added bolt to the list of web frameworks.

---

README.md

Renamed bolt to echo in web frameworks

---

README.md

Ref: https://developer.valvesoftware.com/wiki/Source_RCON_Protocol

Add go-steam, library to interact with Steam servers

---

README.md

Reference:
* http://embd.io
* http://kidoman.io/framework/embd.html

Add embd, framework for hardware

---

README.md

Added two projects:
* [permissions2](https://github.com/xyproto/permissions2)
* [algernon](https://github.com/xyproto/algernon)

Added two projects

---

README.md

- under *database* chapter
- [repo link](https://github.com/rounds/go-bqstreamer)
- [release blog post](http://rounds.com/blog/collecting-user-data-and-usage/)

added BigQuery stream insert package: go-bqstreamer

---

README.md

* Also adjusted the placement of "Server Applications" slightly, since
it's neither a library or resource, nor a tool.
* Also tried to make the line spacing more regular.
Accept or reject at will (or ask me to make further changes).
Thanks for maintaining!

Added a missing headline in the overview.

---

README.md

shell2http  - executing shell commands via http server

Added shell2http

---

README.md

Resolves #266.
/cc @jlaffaye @davecheney @koofr

Add packages for FTP, SFTP protocols.

---

README.md

Added tail package. A Go package striving to emulate the features of the BSD tail program. Tail comes with full support for truncation/move detection as it is designed to work with log rotation tools.

Added tail package

---

README.md

A Nintendo Entertainment System (NES) emulator written in Go.

Added NES package

---

README.md

Add levigo, which use cgo to build wrapper for leveldb

Add levigo, Go wrapper for LevelDB.

---

README.md

Hi :smile: 
Please let me know if you have any questions.
Best regards

Added ServeMux to the list of Web Frameworks

---

README.md

This PR adds two new links:
* [picfit](https://github.com/thoas/picfit) - An image resizing server written in Go
* [stats](https://github.com/thoas/stats) - A Go middleware that stores various information about your web application
They are both: 
* Useful to the community
* Functional
* Actively maintained
* Stable
* Documented
* Tested
Thanks for this awesome awesome Go.

Add picfit and stats.

---

repo_test.go

Add Test to catch duplicated links

---

README.md

Imprements Hystrix patterns of programmer-defined fallbacks aka circuit breaker.

Add hystrix-go to Utilities

---

README.md

Added gofreetds to database drivers.

Adding gofreetds, MSSQL database driver.

---

README.md

Add caddy, a web server

---

README.md

go-multierror by hashicorp - put it to miscellaneous because the other categories don't fit for me

Added go-multierror to Miscellaneous

---

README.md

This project is incomplete and not maintained since may 2013.

remove go-pgsql as its incomplete and not actively maintained

---

README.md

Just adding a package that I wrote a while ago.

added genex package

---

README.md

Very nice library to handle OAuth, OAuth2.
Multiple providers supporter out of the box and custom providers can be added by implementing interface

Add markbates/goth auth library

---

README.md

Though it is not exactly an ORM, it does function similarly. I see other ORM-like libraries in this category so I believe it is the appropriate place. Happy to move it somewhere else if you think it would be more appropriate.
Cheers!

Add albrow/zoom

---

README.md

Add gommon/gytes to the list

---

README.md

This library is rapidly progressing toward a stable release.

Add brewerydb under Third-party APIs

---

README.md

Resolves #409.
Please review, does this look good to everyone? /cc @avelino @rakyll

Replace own hardware section with go-hardware link.

---

README.md

It's a little bit more popular than surge/bloom.

Add willf/bloom - bloom filters implementation.

---

README.md

A better implementation of skiplist in go.

Add ryszard/goskiplist.

---

README.md

Hi,
I created this package to help me building REST APIs more easily and would like to add it here.
It is fully tested, documented and functional.
Thanks!

Add structomap package to Serializer category.

---

README.md

Although I'm not sure if this project meets your quality standard, I hope it could be useful for the community and this is the way to let them know it exists. I don't know of any other existing tool for finding  code clones out there. Also, I would appreciate some help from anybody to improve it.

add dupl, a code clone detection tool

---

README.md

Adding of [GCache](https://github.com/bluele/gcache) library

Added GCache

---

README.md

added liner package and naclpipe, both packages written purely in Go.

added 2 packages

---

README.md

Library is not actively maintained

Remove go-porterstemmer

---

README.md

Please let me know if any are categorized incorrectly.

Add a few of VividCortex's projects

---

README.md

I have found this API to be very developer friendly, well maintained and stable and use it quite a lot in my private projects so maybe its worth the entry in awesome-go ?

Add kingpin to Standard CLI section

---

README.md

I'm the author of this package. 
The package is with 100% test coverage.

Added diegobernardes/ttlcache under DataStructures

---

README.md

Sorry about that. That's twice this week I have neglected a fork then tried to pull!

Added vdobber's chart

---

README.md

cucumber (ruby) or behat(php) like BDD framework reference

new bdd testing framework reference

---

README.md

Removes ServeMux from list of frameworks

---

README.md

This librairie adds the possibilities to deal with Google Adwords API

Third-party APIs - Google Adwords Unofficial API

---

README.md

Add panicparse.

---

README.md

Machinery is an asynchronous task queue/job queue based on distributed
message passing. Think of it as Celery for Golang.
So called tasks (or jobs if you like) are executed concurrently either
by many workers on many servers or multiple worker processes on a single
server using Golang's goroutines.
See the repository here: https://github.com/RichardKnop/machinery
Hacker News post: https://news.ycombinator.com/item?id=9520712

Added Machinery to Messaging section.

---

README.md

> UNMAINTAINED: A Go implementation of the Raft distributed consensus protocol.

goraft is unmaintained

---

README.md

Added mattcunningham/gumblr to the list of third-party APIs

Added mattcunningham/gumblr

---

README.md

Add https://github.com/bluesuncorp/assert - A Basic Assertion Library used along side native go testing, with building blocks for custom assertions

Add Basic Assertion Library

---

CONTRIBUTING.md

Proposed clarifications to the quality standards, to help avoid confusion.
The previous wording has existed since I put something together real quick before the project became widely known; it's time to be a little clearer about what is expected. I also changed some ordering that seems to flow better as you read it.

Clarifications to quality standards

---

README.md

I added timeutil.
Timeutil is a set of useful extensions (Timedelta, Strftime, ...) to the golang's time package.
Thanks :)

Add timeutil.

---

README.md

Add kingshard to Database tools

---

README.md

BeeDB deprecated in favor of beego orm

---

README.md

Add goveralls & overalls libraries.
https://github.com/mattn/goveralls
https://github.com/bluesuncorp/overalls

Add Continuous Integration Section

---

README.md

just another env to struct parser

adding env

---

README.md

Report about this conference: https://blog.golang.org/gopherchina

GopherChina

---

README.md

I added accounting.
accounting is a library for money and currency formatting.
Thanks :)

Add accounting

---

README.md

Adds some networking libraries that I feel are high quality and mostly complete.
Also removes a trailing whitespace character (my editor does this automatically).

Add github.com/mdlayher networking libraries

---

README.md

Pushover is a service to send and receive push notifications.

Add pushover, a wrapper for the Pushover API

---

README.md

As in title. Lib has set of algorithms to use

Add machine learning package - goml

---

README.md

The flowgraph package provides a mechanism to augment goroutines and channels with a ready-send MPI-style protocol that gives the developer tools to manage deadlock and congestion, while ensuring low-latency responses.  It incorporates a novel method for recursive use of goroutines with a self-managing pool.  It is actively developed and supported by myself.  Thanks for your consideration in adding this to the awesome-go list.
Scott Johnston
johnston@vectaport.com
Documentation:  https://godoc.org/github.com/vectaport/flowgraph
Wiki: https://github.com/vectaport/flowgraph/wiki
Testing:  https://github.com/vectaport/flowgraph_test

Add github.com/vectaport/flowgraph to Distributed Systems

---

README.md

Adds [logger](http://github.com/azer/logger)

Add logger

---

README.md

update repos addresses / fix some trailing whitespace

---

README.md

Remove `plubi` as I no longer maintain it and much better alternatives are available (I think).

remove unmaintained package

---

README.md

CockroachDB - A Scalable, Geo-Replicated, Transactional Datastore

Add cockroach to databases

---

README.md

I've personally used it and it's really awesome. Have a look at the games made in one weekend (mostly by newbies): https://codelympics.io/projects/2/gallery

Add termloop under Game Development

---

README.md

Add gcfg to Configuration

---

README.md

Stats package with many common functions and complete code coverage.

Add stats package

---

README.md

sciter is a cross platform GUI toolkit which is easy to deploy to Linux,Windows and OSX. Though not open sourced, but the sicter libraries are free to use for commercial or non-commercial applications.
I think it's a good choice for Golang GUI programming and hope you will like it. :)

 add Go bindings for Sciter: a desktop GUI development SDK

---

README.md

Added go-peerflix under torrent in the _Distributed Systems_ category

Add go-peerflix

---

README.md

Go Trigger is an event trigger package.
Link : [go-trigger](https://github.com/sadlil/go-trigger)

added go-trigger in utilities.

---

README.md

Added Hectane to the Email section

Added Hectane to the Email section

---

README.md

https://github.com/hlandau/passlib

Add hlandau/passlib

---

README.md

Added the following:
* [grpool](https://github.com/ivpusic/grpool) - Lightweight Goroutine pool.
* [pool](https://github.com/go-playground/pool) - Go consumer goroutine pool for easy goroutine handling + time saving.
* [tunny](https://github.com/Jeffail/tunny) - A goroutine pool for golang.
* [statics](https://github.com/go-playground/statics) - Embeds static resources into go files for single binary compilation + works with http.FileSystem + symlinks.
* [generate](https://github.com/go-playground/generate) - runs go generate recursively on a specified path or environment variable and can filter by regex.
* [stats](https://github.com/go-playground/stats) - Monitors Go MemStats + System stats such as Memory, Swap and CPU and sends via UDP anywhere you want for logging etc...

Add Category Goroutines + Add some packages

---

README.md

https://github.com/tucnak/climax
https://github.com/tucnak/store

Added some public libraries of mine

---

README.md

Demo: http://sentences.erock.io/
Docs: https://godoc.org/gopkg.in/neurosnap/sentences.v1

sentences package

---

README.md

```shell
% go test
PASS
ok  	_/Users/sijad/github/awesome-go	0.033s
```

add systray to gui section

---

README.md

Add github.com/feyeleanor/GoSpeed to benchmarks

---

README.md

added it to 'other software' , but i don't know if this is the correct place/section for snap - other suggesstions are welcome.

add snap - a powerful telemetry framework by intel

---

README.md

The previous #617 pull request failed to merge, I recreated the same one with asked changes. Sorry for the noise.

Add consul tool, official website

---

README.md

add drone - ci platform

---

README.md

Add dynago, a DynamoDB client for Go

Add dynago

---

README.md

This PR adds two new packages:
* [Limiter](https://github.com/ulule/limiter)
* [Deepcopier](https://github.com/ulule/deepcopier)
Thanks.

Add Limiter and Deepcopier packages.

---

README.md

Adds [boilr](https://github.com/tmrts/boilr) to the list

Include boilr

---

README.md

Go counters for reader/writer/http.

Add project Datacounter.

---

README.md

I've added the following projects to the Web Frameworks category
* gizmo
* go-kit
* goa

Added go-kit, goa and gizmo

---

README.md

APM is a Process Manager created at a company called TopFreeGames. It has been working for almost a month with a 100% uptime. Tests are being implemented as I write this.

Adding APM (Aguia Process Manager) to awesome-go README

---

README.md

ozzo-dbx is a Go package that enhances the standard database/sql package by providing powerful data retrieval methods as well as DB-agnostic query building capabilities.

added ozzo-dbx to SQL query builder

---

README.md

Add Skizze - A probabilistic data-structures service and storage.

Add Skizze

---

README.md

Adds `sqrl` - fork of Squirrel with different approach to memory management, thus better performance for 95% needs.

One more SQL query builder

---

README.md

> Emits events using Go way, with wildcard, predicates, cancellation
possibilities and many other good wins.
See: https://github.com/olebedev/emitter

Add event emitter

---

README.md

Hi there is new Golang conference http://www.gophercon.ae/ in Dubai!

Add GopherCon Dubai to conferences list

---

README.md

[Latest commit](https://github.com/eaigner/hood) is 3 years old. There are several [issues](https://github.com/eaigner/hood/issues) waiting for answer / patch for a long time.

Remove unmaintained repository - hood

---

README.md

Fine logging lib, for more details see
https://github.com/apex/log
https://medium.com/@tjholowaychuk/apex-log-e8d9627f4a9a#.vbun9sh69

added apex/log logging lib

---

README.md

I added two JSON related libraries for review. `gojq` is a `jq` like implementation in Golang. `jsonql` is an SQL WHERE clause like query expression language in Golang to filter JSON data.

Added jsonql in Query Language and gojq in Utilities

---

README.md

Hey @avelino!
Adding a package and command line tool for generating interface definitions for any Go type.

add interfaces to the generation section

---

README.md

Information about [goweek](https://github.com/grsmv/goweek) added.

Goweek added

---

README.md

Kindly have a look and add to the list, thanks.

Add go-resty library under Utilities.

---

README.md

Kubernetes is a Container Cluster Manager from Google.

Add kubernetes

---

README.md

Added fileb0x to the list, inserTed it in alphabetical order according to rules.
http://goreportcard.com/report/unnoted/fileb0x
https://github.com/UnnoTed/fileb0x

added fileb0x to Resource Embedding

---

README.md

Add banshee to devops

---

README.md

I use it, thought it might be pretty awesome to add another resource to discuss Go.
https://forum.golangbridge.org/t/welcome-to-the-go-forum/8

Add Go Forum

---

README.md

- adds [conform](https://github.com/leebenson/conform) to "Forms" section

adds `conform` to `Forms`

---

README.md

nanomsg scalability protocols in go

---

README.md

Go package for managing file downloads

Added grab

---

README.md

Updated echo and gommon/bytes

---

README.md

My MD editor found unnecessary whitespaces, so i removed them.

Added github.com/pariz/gountries to Miscellaneous

---

README.md

Refer to the gitter conversation for [background discussion](https://gitter.im/avelino/awesome-go?at=56a42113586242210adf2971). Further discussions may take place in the comment section of this pull request.
Cheers /u

Add FLAC decoder.

---

README.md

Real-time messaging (Websockets or SockJS) server in Go

Add Centrifugo

---

README.md

Record and replay your HTTP interactions for fast, deterministic and accurate tests with go-vcr.

Add go-vcr

---

README.md

go-atomix was renamed to ontomix

---

README.md

* https://github.com/dghubble/go-twitter
* https://dev.twitter.com/overview/api/twitter-libraries#go

Add go-twitter to third-party APIs

---

README.md

Add a command-line package based on golang tag and support command tree.

	add command-line package mkideal/cli

---

README.md

Repo: https://github.com/h2non/gentleman

feat: add gentleman package

---

README.md

A genetic algorithm I just published, it's quite popular and well documented.

Added gago

---

README.md

Adding an alternative to the default encoding/asn1 package.

Add ASN.1 alternative library.

---

README.md

gock - https://github.com/h2non/gock

Add gock package

---

README.md

Just adding a new messaging software to the previous collection.

Add github.com/rafael-santiago/cherry

---

README.md

Extensions to Go's testing/iotest package

Added BadIO

---

README.md

Hi,
I've created another Go web framework named Golf.
We have discussed it at #826 , and I have improved it after that:
https://goreportcard.com/report/github.com/dinever/golf
I am still working on the test coverage, so it would be great if you can add my project.
Thanks

Added Golf to Go web frameworks.

---

README.md

Please check if what you want to add to `awesome-go` list meets 
[quality standards](https://github.com/avelino/awesome-go/blob/master/CONTRIBUTING.md#quality-standard) 
before sending pull request. Thanks!
Link to [godoc.org](https://godoc.org/): https://godoc.org/github.com/alioygur/gores
Link to [goreportcard.com](https://goreportcard.com): https://goreportcard.com/report/github.com/alioygur/gores
Link to [gocover.io](https://gocover.io/): https://gocover.io/github.com/alioygur/gores

added alioygur/gores

---

README.md

Link to [godoc.org](https://godoc.org/): 
Link to [goreportcard.com](https://goreportcard.com/): 
Link to [gocover.io](https://gocover.io/):

converted GO to Go

---

README.md

https://godoc.org/github.com/dimiro1/health
https://goreportcard.com/report/github.com/dimiro1/health
https://gocover.io/github.com/dimiro1/health

[Miscellaneous] Added health check library

---

README.md

- godoc.org: https://godoc.org/github.com/kataras/iris
- goreportcard.com: https://goreportcard.com/report/github.com/kataras/iris
- gocover.io: https://gocover.io/github.com/kataras/iris

Update README.md - Add Iris to the Web Frameworks

---

README.md

- Source: https://github.com/go-testfixtures/testfixtures
- godoc.org: https://godoc.org/github.com/go-testfixtures/testfixtures
- goreportcard.com: https://goreportcard.com/report/github.com/go-testfixtures/testfixtures

Add testfixtures

---

README.md

Adding the xo command line database schema/query code generation tool to Database section of README.md.

Adding xo to Database section of README.md

---

README.md

Adding Vestigo - implements a performant, stand-alone, HTTP compliant URL Router for go web applications.

 Adding Vestigo URL Router

---

README.md

go-ontomix/ontomix moved to go-mix/mix

---

README.md

https://goreportcard.com/report/github.com/dimiro1/banner
https://godoc.org/github.com/dimiro1/banner
https://travis-ci.org/dimiro1/banner
https://gocover.io/github.com/dimiro1/banner
https://github.com/dimiro1/banner

Added lib banner

---

README.md

Everything covered as requested, docs, tests, vetting etc.

Added Structured Log Facade (SLF) and a reference implementation

---

README.md

- godoc.org: 
* https://godoc.org/gopkg.in/authboss.v0
* [![Go Report Card](https://godoc.org/gopkg.in/authboss.v0?status.svg)](https://godoc.org/gopkg.in/authboss.v0)
* https://goreportcard.com/report/github.com/go-authboss/authboss
* [![Go Report Card](https://goreportcard.com/badge/go-authboss/authboss)](https://goreportcard.com/report/github.com/go-authboss/authboss)
- gocover.io:

Authboss added to Authentication & OAuth

---

README.md

Adding [igor](https://github.com/galeone/igor):
- godoc.org: https://godoc.org/github.com/galeone/igor
- goreportcard.com: https://goreportcard.com/report/github.com/galeone/igor

Add igor: https://github.com/galeone/igor

---

README.md

Add https://github.com/galeone/rts
- godoc.org: https://godoc.org/github.com/galeone/rts
- goreportcard.com: https://goreportcard.com/report/github.com/galeone/rts
- gocover.io: https://gocover.io/github.com/galeone/rts

Add rts: https://github.com/galeone/rts

---

README.md

- godoc.org: https://godoc.org/github.com/quii/mockingjay-server
- goreportcard.com: https://goreportcard.com/report/github.com/quii/mockingjay-server
- gocover.io: https://gocover.io/github.com/quii/mockingjay-server
Thanks for your PR, you're awesome :+1:

adding mockingjay

---

README.md

Add `gofight` API handler testing tool
- Github: https://github.com/appleboy/gofight
- godoc.org: https://godoc.org/github.com/appleboy/gofight
- goreportcard.com: https://goreportcard.com/report/github.com/appleboy/gofight
- gocover.io: https://gocover.io/github.com/appleboy/gofight
Check list
Signed-off-by: Bo-Yi Wu <appleboy.tw@gmail.com>

Add gofight package in testing section.

---

README.md

Submitting a request to add [gofeed](https://github.com/mmcdole/gofeed), a feed parser, to awesome-go.
- godoc.org: https://godoc.org/github.com/mmcdole/gofeed
- goreportcard.com: https://goreportcard.com/report/github.com/mmcdole/gofeed
- gocover.io: https://gocover.io/github.com/mmcdole/gofeed
Make shure that you've checked the boxes below before you submit PR:

Add gofeed

---

README.md

- https://godoc.org/github.com/plar/go-adaptive-radix-tree
- https://goreportcard.com/report/github.com/plar/go-adaptive-radix-tree
- https://gocover.io/github.com/plar/go-adaptive-radix-tree
Make shure that you've checked the boxes below before you submit PR:
Thanks for your PR, you're awesome :+1:

Add data structure: adaptive radix tree

---

README.md

- godoc.org:  https://godoc.org/github.com/RoaringBitmap/roaring
- goreportcard.com: https://goreportcard.com/report/github.com/RoaringBitmap/roaring
- gocover.io: https://gocover.io/github.com/RoaringBitmap/roaring
- travis : https://travis-ci.org/RoaringBitmap/roaring
Make shure that you've checked the boxes below before you submit PR:
Thanks for your PR, you're awesome :+1:

adding the roaring library (compressed bitset format)

---

README.md

https://github.com/appleboy/gorush
- godoc.org: https://godoc.org/github.com/appleboy/gorush
- goreportcard.com: https://goreportcard.com/report/github.com/appleboy/gorush
- gocover.io: https://coveralls.io/github/appleboy/gorush?branch=master
Make shure that you've checked the boxes below before you submit PR:
Thanks for your PR, you're awesome :+1:
A push notification server using Gin framework written in Go (Golang).
* Support Google Cloud Message using go-gcm library for Android.
* Support HTTP/2 Apple Push Notification Service using apns2 library.
* Support YAML configuration.
* Support command line to send single Android or iOS notification.
* Support Web API to send push notification.
* Support zero downtime restarts for go servers using endless.
* …

Add a push notification server (gorush).

---

README.md

- godoc.org: https://godoc.org/github.com/asdine/storm
- goreportcard.com: https://goreportcard.com/report/github.com/asdine/storm
- gocover.io: https://gocover.io/github.com/asdine/storm

Add Storm ORM

---

README.md

- [log](https://github.com/go-playground/log) - a simple, configurable and scalable Structured Logging library for Go
- [godoc](https://godoc.org/github.com/go-playground/log)
- [goreportcard.com](https://goreportcard.com/report/github.com/go-playground/log)
- [gocover.io](https://gocover.io/github.com/go-playground/log)

Add log - a simple, configurable and scalable Structured Logging library for Go

---

README.md

- godoc.org - wlog: https://godoc.org/github.com/dixonwille/wlog
- godoc.org - wmenu: https://godoc.org/github.com/dixonwille/wmenu
- goreportcard.com - wlog: https://goreportcard.com/report/github.com/dixonwille/wlog
- goreportcard.com - wmenu: https://goreportcard.com/report/github.com/dixonwille/wmenu
- gocover.io - wlog: https://gocover.io/github.com/dixonwille/wlog
- gocover.io - wmenu: https://gocover.io/github.com/dixonwille/wmenu 
Make sure that you've checked the boxes …

Add WLog and WMenu

---

README.md

The repo for this system has changed.

The repo for rqlite has changed

---

README.md

- godoc.org: https://godoc.org/github.com/koffeinsource/go-imgur
- goreportcard.com: https://goreportcard.com/report/github.com/koffeinsource/go-imgur
- gocover.io: https://gocover.io/github.com/koffeinsource/go-imgur
- coveralls.io: https://coveralls.io/github/koffeinsource/go-imgur?branch=master

Added go-imgur.

---

README.md

https://godoc.org/github.com/xtaci/kcp-go
https://goreportcard.com/report/github.com/xtaci/kcp-go
https://gocover.io/github.com/xtaci/kcp-go

add kcp-go

---

README.md

- godoc.org: https://godoc.org/github.com/pascaldekloe/colfer/cmd/colf (not a library
- goreportcard.com: https://goreportcard.com/report/github.com/pascaldekloe/colfer
- gocover.io: https://gocover.io/github.com/pascaldekloe/colfer (unit and fuzz tests cover the generated code, not the compiler itself)
- [ x ] I know that this package was not listed before
- [ x ] I have added godoc link
- [ x ] I have added …

Add Colfer to serialization

---

README.md

- godoc.org: https://godoc.org/github.com/monmohan/xferspdy
- goreportcard.com: https://goreportcard.com/report/github.com/monmohan/xferspdy
NOTE: The go report card is wrong. Its shows non-existent lint and misspell issue. They were corrected but it continues to show them as problems.
- gocover.io: https://gocover.io/github.com/monmohan/xferspdy
- [Y] I have added my package in alphabetical order
- [Y] I know …

Added xferspdy to Utilities section

---

README.md

- godoc.org: https://godoc.org/github.com/hako/durafmt
- goreportcard.com: https://goreportcard.com/report/github.com/hako/durafmt
- gocover.io: https://gocover.io/github.com/hako/durafmt
- codecov.io (In case gocover.io does not work) https://codecov.io/gh/hako/durafmt

Add durafmt

---

README.md

- godoc.org: https://godoc.org/github.com/heroku/hk
- goreportcard.com: https://goreportcard.com/report/github.com/heroku/hk
- gocover.io: https://gocover.io/github.com/heroku/hk

hk is deprecated

---

README.md

- godoc.org: https://godoc.org/github.com/mjibson/esc
- goreportcard.com: https://goreportcard.com/report/github.com/mjibson/esc
- gocover.io: No tests now

esc - resource embedding package

---

README.md

- godoc.org: https://godoc.org/github.com/hajimehoshi/ebiten
- goreportcard.com: https://goreportcard.com/report/github.com/hajimehoshi/ebiten
- gocover.io: n/a

Add Ebiten

---

README.md

- godoc.org:
- https://godoc.org/github.com/luxengine/math
- https://godoc.org/github.com/luxengine/glm
- https://godoc.org/github.com/luxengine/lux
- https://godoc.org/github.com/luxengine/tornago
- https://goreportcard.com/report/github.com/luxengine/math
- https://goreportcard.com/report/github.com/luxengine/glm
- https://goreportcard.com/report/github.com/luxengine/lux
- https://goreportcard.com/report/github.com/luxengine/tornago
- gocover.io: 
- https://gocover.io/github.com/luxengine/math
- …

Add lux and it's utilities

---

README.md

Added the router Bxog to the section Web Frameworks
- https://godoc.org/github.com/claygod/Bxog
- https://goreportcard.com/report/github.com/claygod/Bxog
- https://gocover.io/github.com/claygod/Bxog

Added router Bxog

---

README.md

- godoc.org: 
- gocover.io: 
Added zap logger package from Uber

Added zap logger package from Uber

---

README.md

- godoc.org: https://godoc.org/github.com/melihmucuk/geocache
- goreportcard.com: https://goreportcard.com/report/github.com/melihmucuk/geocache
- gocover.io: https://gocover.io/github.com/melihmucuk/geocache

geocache package added to database section

---

README.md

- godoc.org: https://godoc.org/github.com/dannyvankooten/vat
- goreportcard.com: https://goreportcard.com/report/github.com/dannyvankooten/vat
- gocover.io: https://gocover.io/github.com/dannyvankooten/vat
---
---
Thanks for your repository, you're awesome! :+1:

Add dannyvankooten/vat to Financial.

---

README.md

Add sleuth to "Distributed Systems" section.

---

README.md

This is the "Awesome Go" list with some additions like popularity ordering, visualised dev activity, some metadata and the ability to compare different libs. It's been well received by the community at reddit.com/r/golang.

Add 'Awesome Go @LibHunt' to the Websites section

---

README.md

- godoc.org: https://godoc.org/github.com/AlekSi/reform
- goreportcard.com: https://goreportcard.com/report/github.com/AlekSi/reform
- gocover.io: can't be tested on gocover.io, here is an alternative: https://coveralls.io/github/AlekSi/reform

Add reform

---

README.md

- godoc.org: https://godoc.org/github.com/abo/rerate
- goreportcard.com: https://goreportcard.com/report/github.com/abo/rerate
- gocover.io: https://gocover.io/github.com/abo/rerate

Add rerate(redis-based ratecounter & ratelimiter) to utilities

---

README.md

`reform` package moved to the another repository.

Update reform repository

---

README.md

- godoc.org: https://godoc.org/github.com/go-ozzo/ozzo-validation
- goreportcard.com: https://goreportcard.com/report/github.com/go-ozzo/ozzo-validation
- gocover.io or coveralls: https://gocover.io/github.com/go-ozzo/ozzo-validation

added ozzo-validation to data validation section

---

README.md

- godoc.org: 
- gocover.io or coveralls: 

Adding govendor, a go package manager.

---

README.md

- godoc.org: 
- gocover.io or coveralls: 

Updating goreturns URL

---

README.md

add kcptun
an extremely simple & fast udp tunnel based on kcp protocol

add kcptun

---

README.md

- source: https://github.com/editorconfig/editorconfig-core-go
- godoc.org: https://godoc.org/gopkg.in/editorconfig/editorconfig-core-go.v1
- goreportcard.com: https://goreportcard.com/report/gopkg.in/editorconfig/editorconfig-core-go.v1

Add editorconfig-core-go

---

README.md

- godoc.org: http://godoc.org/github.com/agnivade/levenshtein
- goreportcard.com: https://goreportcard.com/report/agnivade/levenshtein
- gocover.io: https://gocover.io/github.com/agnivade/levenshtein

Added levenshtein to Data Structures

---

README.md

Hi, this PR add [go-slugify](https://github.com/mozillazg/go-slugify) .
- godoc.org: https://godoc.org/github.com/mozillazg/go-slugify
- goreportcard.com: https://goreportcard.com/report/github.com/mozillazg/go-slugify
- gocover.io or coveralls: https://coveralls.io/github/mozillazg/go-slugify
Check list:

add go-slugify

---

README.md

- godoc.org:  http://godoc.org/github.com/mustafaakin/gongular
- goreportcard.com:  https://goreportcard.com/report/github.com/mustafaakin/gongular
- gocover.io or coveralls:  https://coveralls.io/github/mustafaakin/gongular?branch=master

Added Gongular web framework

---

README.md

Nothing really to check here, not adding a new package

Removing unmaintained bmizerany/assert

---

README.md

https://github.com/mehrdadrad/mylg
Goreportcard : https://goreportcard.com/report/github.com/mehrdadrad/mylg
Travis-CI : https://travis-ci.org/mehrdadrad/mylg
Thanks in advance!

added mylg repo

---

README.md

- godoc.org: 
- [✓ ] I have added my package in alphabetical order
- [✓ ] I know that this package was not listed before
- [✓ ] I have added godoc link to the repo and to my pull request
- [✓ ] I have added coverage service link to the repo and to my pull request
- [✓ ] I have added goreportcard link to the …

Add: Implementation of the "Bailey-Borwein-Plouffe"

---

README.md

update [form](https://github.com/go-playground/form) description for new functionality added.

update form description for new functionality added.

---

README.md

- github.com repo: https://github.com/qntfy/kazaam
- godoc.org: https://godoc.org/github.com/qntfy/kazaam
- goreportcard.com: https://goreportcard.com/report/github.com/qntfy/kazaam
- coverage service link (gocover, coveralls etc.): https://coveralls.io/github/qntfy/kazaam?branch=master

Add Kazaam JSON transformation project

---

README.md

- github.com repo: https://github.com/CalebQ42/bbConvert
- godoc.org: https://godoc.org/github.com/CalebQ42/bbConvert
- goreportcard.com: https://goreportcard.com/report/github.com/CalebQ42/bbConvert
- coverage service link (gocover, coveralls etc.): https://coveralls.io/github/CalebQ42/bbConvert

Added bbConvert

---

README.md

- github.com repo: https://github.com/tidwall/buntdb
- godoc.org: https://godoc.org/github.com/tidwall/buntdb
- goreportcard.com: https://goreportcard.com/report/github.com/tidwall/buntdb
- coverage service link (gocover, coveralls etc.): http://gocover.io/github.com/tidwall/buntdb

Adding BuntDB

---

README.md

- https://github.com/alexflint/go-arg
- https://godoc.org/github.com/alexflint/go-arg
- https://goreportcard.com/report/alexflint/go-arg
- https://coveralls.io/github/alexflint/go-arg?branch=master

add go-arg under CLI

---

README.md

- github.com repo: https://github.com/leonelquinteros/gotext https://github.com/yarf-framework/yarf
- godoc.org: https://godoc.org/github.com/leonelquinteros/gotext https://godoc.org/github.com/yarf-framework/yarf
- goreportcard.com: https://goreportcard.com/report/github.com/leonelquinteros/gotext https://goreportcard.com/report/github.com/yarf-framework/yarf
- coverage service link (gocover, coveralls etc.): https://gocover.io/github.com/leonelquinteros/gotext https://gocover.io/github.com/yarf-framework/yarf  …

Add YARF and gotext

---

README.md

https://github.com/fogleman/gg
https://github.com/fogleman/ln
https://github.com/fogleman/pt
- godoc.org: 
https://godoc.org/github.com/fogleman/gg
https://godoc.org/github.com/fogleman/ln/ln
https://godoc.org/github.com/fogleman/pt/pt
https://goreportcard.com/report/github.com/fogleman/gg
https://goreportcard.com/report/github.com/fogleman/ln
https://goreportcard.com/report/github.com/fogleman/pt …

Add gg, ln, pt graphics libraries.

---

README.md

- github.com repo: https://github.com/anthonynsimon/bild
- godoc.org: https://godoc.org/github.com/anthonynsimon/bild
- goreportcard.com: https://goreportcard.com/report/github.com/anthonynsimon/bild
- coverage service link (gocover, coveralls etc.): https://gocover.io/github.com/anthonynsimon/bild

added bild

---

README.md

- github.com repo: https://github.com/seborama/govcr
- godoc.org: https://godoc.org/github.com/seborama/govcr
- goreportcard.com: https://goreportcard.com/report/github.com/seborama/govcr
- coverage service link (gocover, coveralls etc.): https://gocover.io/github.com/seborama/govcr
[govcr](https://github.com/seborama/govcr) - HTTP mock for Golang: record and …

[govcr] Add govcr

---

README.md

- github.com repo: https://github.com/db47h/ngaro
- godoc.org: https://godoc.org/github.com/db47h/ngaro/vm
- goreportcard.com: https://goreportcard.com/report/github.com/db47h/ngaro
- coverage service link: https://coveralls.io/github/db47h/ngaro
[ngaro](https://github.com/db47h/ngaro) - Embeddable Ngaro VM implementation enabling scripting in Retro

Add Ngaro to Embeddable Scripting Languages

---

README.md

- godoc.org: 
It`s a conference: https://gopherconbr.org

Add GopherCon Brazil

---

README.md

My library now can parse tags!
- github.com repo: https://github.com/bogem/id3v2
- godoc.org: https://godoc.org/github.com/bogem/id3v2
- goreportcard.com: https://goreportcard.com/report/github.com/bogem/id3v2

Complete description about id3v2

---

README.md

- github.com repo: https://github.com/distatus/battery
- godoc.org: https://godoc.org/github.com/distatus/battery
- goreportcard.com: https://goreportcard.com/report/github.com/distatus/battery
- coverage service link (gocover, coveralls etc.): http://gocover.io/github.com/distatus/battery

Add battery

---

README.md

- github.com repo: https://github.com/uniplaces/carbon
- godoc.org: https://godoc.org/github.com/uniplaces/carbon
- goreportcard.com: https://goreportcard.com/report/github.com/uniplaces/carbon
- coverage service link (gocover, coveralls etc.): https://codecov.io/gh/uniplaces/carbon

Add Carbon, a simple time extension

---

README.md

Added new go projects

---

README.md

Add grapes - distribute commands over ssh.
- github.com repo:  https://github.com/yaronsumel/grapes
- godoc.org:  https://godoc.org/github.com/yaronsumel/grapes
- goreportcard.com: https://goreportcard.com/report/github.com/yaronsumel/grapes
- coverage service link (gocover, coveralls etc.): http://gocover.io/github.com/yaronsumel/grapes
Thanks! :+1:

Add grapes

---

README.md

- github.com repo: https://github.com/ninedraft/gocryforhelp
- ~~godoc.org:~~ not a go library 
- ~~goreportcard.com:~~ not a go library
- ~~coverage service link (gocover, coveralls etc.):~~ not a go library
~~- [ ] I have added godoc link to the repo and to my pull request~~
~~- [ ] I have added coverage service link to the repo and to my pull request~~
~~- [ ] I have added goreportcard link to …

add gocryforhelp

---

README.md

- github.com repo: https://github.com/headwindfly/clevergo
- godoc.org: https://godoc.org/github.com/headwindfly/clevergo
- goreportcard.com: https://goreportcard.com/report/github.com/headwindfly/clevergo
- coverage service link (gocover, coveralls etc.): https://gocover.io/github.com/headwindfly/clevergo

Added CleverGo web framework

---

README.md

- github.com repo: https://github.com/kataras/go-events
- godoc.org: https://godoc.org/github.com/kataras/go-events
- goreportcard.com: https://goreportcard.com/report/github.com/kataras/go-events
- coverage service link (gocover, coveralls etc.): http://gocover.io/github.com/kataras/go-events
Thanks, the community is awesome! :+1:

Add go-events

---

README.md

- github.com repo: https://github.com/icza/bitio
- godoc.org: https://godoc.org/github.com/icza/bitio
- goreportcard.com: https://goreportcard.com/report/github.com/icza/bitio
- coverage service link (gocover, coveralls etc.): https://gocover.io/github.com/icza/bitio

Added bitio.

---

README.md

- github.com repo: https://github.com/vattle/sqlboiler
- godoc.org: https://godoc.org/github.com/vattle/sqlboiler
- goreportcard.com: https://goreportcard.com/report/github.com/vattle/sqlboiler
- coverage service link (gocover, coveralls etc.): http://gocover.io/github.com/vattle/sqlboiler

Add SQLBoiler to ORM section

---

README.md

- github.com repo: https://github.com/kataras/go-serializer
- godoc.org: https://godoc.org/github.com/kataras/go-serializer
- goreportcard.com: https://goreportcard.com/report/github.com/kataras/go-serializer
- coverage service link (gocover, coveralls etc.): http://gocover.io/github.com/kataras/go-serializer

Add simple go-serializer

---

README.md

- github.com repo: https://github.com/icza/session
- godoc.org: https://godoc.org/github.com/icza/session
- goreportcard.com: https://goreportcard.com/report/github.com/icza/session
- coverage service link (gocover, coveralls etc.): https://gocover.io/github.com/icza/session

Added session.

---

README.md

- github.com repo: https://github.com/kataras/go-options
- godoc.org: https://godoc.org/github.com/kataras/go-options
- goreportcard.com: https://goreportcard.com/report/github.com/kataras/go-options
- coverage service link (gocover, coveralls etc.): http://gocover.io/github.com/kataras/go-options

Add go-options

---

README.md

- github.com repo: https://github.com/coreos/etcd/tree/master/raft
- godoc.org: https://godoc.org/github.com/coreos/etcd/raft
- goreportcard.com: https://goreportcard.com/report/github.com/coreos/etcd

CoreOS raft implementation

---

README.md

- github.com repo: https://github.com/jszwedko/go-circleci
- godoc.org: http://godoc.org/github.com/jszwedko/go-circleci
- goreportcard.com: https://goreportcard.com/report/github.com/jszwedko/go-circleci
- coverage service link (gocover, coveralls etc.): http://gocover.io/github.com/jszwedko/go-circleci

Add go-circleci

---

README.md

- godoc.org: 
- [ X] I have read [Contribution guidelines](https://github.com/avelino/awesome-go/blob/master/CONTRIBUTING.md#contribution-guidelines) and [Quality standard](https://github.com/avelino/awesome-go/blob/master/CONTRIBUTING.md#quality-standard). …

Removed heka

---

README.md

- github.com repo: https://github.com/One-com/gone
- godoc.org: https://godoc.org/github.com/One-com/gone/log
- goreportcard.com: https://goreportcard.com/report/github.com/One-com/gone/log
- coverage service link (gocover, coveralls etc.): http://gocover.io/github.com/One-com/gone/log

Added gone/log std-lib compatible log library

---

README.md

- github.com repo: github.com/bradleyfalzon/apicompat
- godoc.org: https://godoc.org/github.com/bradleyfalzon/apicompat
- goreportcard.com: https://goreportcard.com/report/github.com/bradleyfalzon/apicompat
- coverage service link (gocover, coveralls etc.): https://coveralls.io/github/bradleyfalzon/apicompat?branch=master

Add apicompat

---

README.md

- github.com repo: https://github.com/pkg/errors
- godoc.org: https://godoc.org/github.com/pkg/errors
- goreportcard.com: https://goreportcard.com/report/github.com/pkg/errors
- coverage service link (gocover, coveralls etc.): https://gocover.io/github.com/pkg/errors

Add pkg/errors

---

README.md

- github.com repo: https://github.com/krotik/eliasdb/
- godoc.org: https://godoc.org/devt.de/eliasdb
Also self-hosted: http://devt.de/docs/pkg/devt.de/eliasdb/
- goreportcard.com: https://goreportcard.com/report/github.com/krotik/eliasdb
- coverage service link (gocover, coveralls etc.): https://devt.de/nightly/test.eliasdb.html#file0

Adding EliasDB

---

README.md

- godoc.org: 
High performance workflow based REST API Framework
Repo: https://github.com/jabong/florest-core
Godoc: https://godoc.org/github.com/jabong/florest-core/src
GoreportCard: https://goreportcard.com/report/github.com/jabong/florest-core
Coverage: …

add florest library

---

README.md

- github.com repo: https://github.com/tendermint/tendermint
- godoc.org: https://godoc.org/github.com/tendermint/tendermint
- goreportcard.com: https://goreportcard.com/report/github.com/tendermint/tendermint
- coverage service link (gocover, coveralls etc.): https://codecov.io/gh/tendermint/tendermint

Add Tendermint (consensus/blockchain middleware) to Distributed Systems 

---

README.md

- github.com repo: https://github.com/dveselov/go-mystem
- godoc.org: https://godoc.org/github.com/dveselov/go-mystem
- goreportcard.com: https://goreportcard.com/report/github.com/dveselov/go-mystem
- coverage service link (gocover, coveralls etc.): https://coveralls.io/github/dveselov/go-mystem

Add go-mystem

---

README.md

The Go Challenge is a monthly programming challenge for Go developers.

Add the Go Challenge website

---

README.md

- github.com repo: https://github.com/go-gormigrate/gormigrate
- godoc.org: https://godoc.org/gopkg.in/gormigrate.v1
- goreportcard.com: https://goreportcard.com/report/gopkg.in/gormigrate.v1
- coverage service link (gocover, coveralls etc.): http://gocover.io/gopkg.in/gormigrate.v1

Add gormigrate

---

README.md

- github.com repo: https://github.com/zpatrick/fireball
- godoc.org: https://godoc.org/github.com/zpatrick/fireball
- goreportcard.com: https://goreportcard.com/report/github.com/zpatrick/fireball
- coverage service link (gocover, coveralls etc.): https://gocover.io/github.com/zpatrick/fireball

add fireball

---

README.md

Repo - https://github.com/robbert229/jwt
Coverage - https://coveralls.io/github/robbert229/jwt?branch=master
Report Card - https://goreportcard.com/report/github.com/robbert229/jwt
Godoc - https://godoc.org/github.com/robbert229/jwt
Added my jwt library to the list.

Added github.com/robbert229/jwt

---

README.md

- github.com repo: https://github.com/tockins/realize
- godoc.org: https://godoc.org/github.com/tockins/realize/realize
- goreportcard.com: https://goreportcard.com/report/github.com/tockins/realize
- coverage service link (gocover, coveralls etc.): http://gocover.io/github.com/tockins/realize/realize
Realize is a Go build system with file watchers and live …

Added Realize - Go build system with file watchers and live reload

---

README.md

- github.com repo:   https://github.com/osrg/gobgp
- godoc.org:  https://godoc.org/github.com/osrg/gobgp
- goreportcard.com: https://goreportcard.com/report/github.com/osrg/gobgp
- coverage service link (gocover, coveralls etc.): http://gocover.io/github.com/osrg/gobgp
Signed-off-by: Peng Xiao <xiaoquwl@gmail.com>

add gobgp to networking

---

README.md

- github.com repo: https://github.com/allegro/bigcache
- godoc.org: https://godoc.org/github.com/allegro/bigcache
- goreportcard.com: https://goreportcard.com/report/github.com/allegro/bigcache
- coverage service link (gocover, coveralls etc.):  https://coveralls.io/github/allegro/bigcache?branch=master

Add allegro/bigcache

---

README.md

- github.com repo: https://github.com/fanux/lhttp
- godoc.org:  http://godoc.org/github.com/fanux/lhttp
- goreportcard.com:  https://goreportcard.com/report/github.com/fanux/lhttp
- coverage service link (gocover, coveralls etc.): http://gocover.io/github.com/fanux/lhttp
websoker -> websocket, sorry about that.

A word mistaken

---

README.md

- github.com repo: https://github.com/osamingo/indigo
- godoc.org: https://godoc.org/github.com/osamingo/indigo
- goreportcard.com: https://goreportcard.com/report/github.com/osamingo/indigo
- coverage service link (gocover, coveralls etc.): https://codecov.io/gh/osamingo/indigo

Add indigo

---

README.md

- github.com repo: https://github.com/pavlo/gosuite
- godoc.org: https://godoc.org/github.com/pavlo/gosuite
- goreportcard.com: https://goreportcard.com/report/github.com/pavlo/gosuite
- coverage service link (gocover, coveralls etc.): https://codecov.io/gh/pavlo/gosuite

adds the "gosuite" library

---

README.md

- github.com repo: https://github.com/documize/community
- godoc.org: https://godoc.org/github.com/documize/community
- goreportcard.com: https://goreportcard.com/report/github.com/documize/community
- [] I have added coverage service link to the repo and to my pull request

Add Documize

---

README.md

- github.com repo: https://github.com/sbstjn/hanu
- godoc.org: https://godoc.org/github.com/sbstjn/hanu
- goreportcard.com: https://goreportcard.com/report/github.com/sbstjn/hanu
- coverage service link (gocover, coveralls etc.): https://coveralls.io/github/sbstjn/hanu

Add github.com/sbstjn/hanu

---

README.md

- github.com repo: https://github.com/sbstjn/allot
- godoc.org: https://godoc.org/github.com/sbstjn/allot
- goreportcard.com: https://goreportcard.com/report/github.com/sbstjn/allot
- coverage service link (gocover, coveralls etc.): https://coveralls.io/github/sbstjn/allot

Add github.com/sbstjn/allot

---

README.md

- github.com repo: https://github.com/ngs/go-google-email-audit-api
- godoc.org: https://godoc.org/github.com/ngs/go-google-email-audit-api/emailaudit
- goreportcard.com: https://goreportcard.com/report/github.com/ngs/go-google-email-audit-api
- coverage service link (gocover, coveralls etc.): https://coveralls.io/github/ngs/go-google-email-audit-api?branch=master …

Add ngs/go-google-email-audit-api

---

README.md

- github.com repo: https://github.com/therecipe/qt
- godoc.org: https://godoc.org/github.com/therecipe/qt
- goreportcard.com: https://goreportcard.com/report/github.com/therecipe/qt
Semaphore CI - https://semaphoreci.com/therecipe/qt
Appveyor - https://ci.appveyor.com/project/therecipe/qt
Circle CI -  https://circleci.com/gh/therecipe/qt/tree/master …

add therecipe/qt - Qt binding for Go.

---

README.md

- github.com repo: https://github.com/buaazp/fasthttprouter
- godoc.org: https://godoc.org/github.com/buaazp/fasthttprouter
- goreportcard.com: https://goreportcard.com/report/github.com/buaazp/fasthttprouter
- coverage service link (gocover, coveralls etc.): https://coveralls.io/github/buaazp/fasthttprouter?branch=master

Add buaazp/fasthttprouter

---

README.md

- github.com repo: https://github.com/emersion/go-imap
- godoc.org: https://godoc.org/github.com/emersion/go-imap
- goreportcard.com: https://goreportcard.com/report/github.com/emersion/go-imap
- coverage service link (gocover, coveralls etc.): https://codecov.io/gh/emersion/go-imap

Adds go-imap

---

README.md

- github.com repo: https://github.com/ChristopherRabotin/sg
- godoc.org: https://godoc.org/github.com/ChristopherRabotin/sg
- goreportcard.com: https://goreportcard.com/report/github.com/ChristopherRabotin/sg
- coverage service link (gocover, coveralls etc.): https://travis-ci.org/ChristopherRabotin/sg
Note that Travis-ci image says "build failing" but the …

Add sg ([HTTP server] stress gauge)

---

README.md

- github.com repo: https://github.com/osamingo/jsonrpc
- godoc.org: https://godoc.org/github.com/osamingo/jsonrpc
- goreportcard.com: https://goreportcard.com/report/github.com/osamingo/jsonrpc
- coverage service link (gocover, coveralls etc.): https://codecov.io/gh/osamingo/jsonrpc

Add osamingo/jsonrpc

---

README.md

Reverts avelino/awesome-go#1091

Revert "Add go-options"

---

README.md

Reverts avelino/awesome-go#1090

Revert "Add simple go-serializer"

---

README.md

Reverts avelino/awesome-go#1084

Revert "Add go-events"

---

README.md

- github.com repo:  http://github.com/hprose/hprose-golang
- godoc.org: https://godoc.org/github.com/hprose/hprose-golang
- goreportcard.com: https://goreportcard.com/report/github.com/hprose/hprose-golang
- coverage service link (gocover, coveralls etc.): https://coveralls.io/github/hprose/hprose-golang?branch=master

Added hprose

---

README.md

Adding 2 TDD/BDD tutorials

---

README.md

- github.com repo: https://github.com/gernest/alien
- godoc.org: https://godoc.org/github.com/gernest/alien
- goreportcard.com: https://goreportcard.com/report/github.com/gernest/alien
- coverage service link (gocover, coveralls etc.): https://coveralls.io/github/gernest/alien?branch=master

Add gernest/alien

---

README.md

- github.com repo: https://github.com/smancke/guble
- godoc.org: https://godoc.org/github.com/smancke/guble
- goreportcard.com: https://goreportcard.com/report/github.com/smancke/guble
- coverage service link (gocover, coveralls etc.): https://coveralls.io/github/smancke/guble?branch=master

add guble [ https://github.com/smancke/guble ]

---

README.md

- github.com repo: https://github.com/zegl/goriak
- godoc.org: https://godoc.org/gopkg.in/zegl/goriak.v2
- goreportcard.com: https://goreportcard.com/report/gopkg.in/zegl/goriak.v2
- coverage service link (gocover, coveralls etc.): https://codecov.io/gh/zegl/goriak/branch/v2

Add goriak

---

README.md

- [github.com repo](https://github.com/chewxy/gorgonia)
- [godoc.org](https://godoc.org/github.com/chewxy/gorgonia)
- [goreportcard.com](https://goreportcard.com/report/github.com/chewxy/gorgonia)
- [coverage service link](http://gocover.io/github.com/chewxy/gorgonia)

Added Gorgonia

---

README.md

- github.com repo: https://github.com/wendigo/go-bind-plugin
- godoc.org: https://godoc.org/github.com/wendigo/go-bind-plugin/cli
- goreportcard.com: https://goreportcard.com/report/github.com/wendigo/go-bind-plugin
- coverage service link (gocover, coveralls etc.): https://coveralls.io/github/wendigo/go-bind-plugin?branch=master
Add …

add go-bind-plugin

---

README.md

"Scalable, fault-tolerant application-layer sharding for Go applications"

Add ringpop-go from Uber

---

README.md

- github.com repo: https://github.com/ChristopherRabotin/ode
- godoc.org: https://godoc.org/github.com/ChristopherRabotin/ode
- goreportcard.com: https://goreportcard.com/report/github.com/ChristopherRabotin/ode
- coverage service link (gocover, coveralls etc.): https://coveralls.io/github/ChristopherRabotin/ode?branch=master

Add ODE solver

---

README.md

- github.com repo: https://github.com/git-time-metric/gtm
- godoc.org: https://godoc.org/github.com/git-time-metric/gtm
- goreportcard.com: https://goreportcard.com/report/github.com/git-time-metric/gtm
- coverage service link (gocover, coveralls etc.): https://coveralls.io/github/git-time-metric/gtm

Add Git Time Metric utility

---

README.md

- github.com repo: https://github.com/AmuzaTkts/jsonapi-errors
- godoc.org: https://godoc.org/github.com/AmuzaTkts/jsonapi-errors
- goreportcard.com: https://goreportcard.com/report/github.com/AmuzaTkts/jsonapi-errors
- coverage service link (gocover, coveralls etc.): https://coveralls.io/github/AmuzaTkts/jsonapi-errors

Add jsonapi-errors to the list

---

README.md

- github.com repo: [https://github.com/surullabs/lint](https://github.com/surullabs/lint)
- godoc.org: [https://godoc.org/github.com/surullabs/lint](https://godoc.org/github.com/surullabs/lint)
- goreportcard.com: [https://goreportcard.com/report/github.com/surullabs/lint](https://goreportcard.com/report/github.com/surullabs/lint)
- coverage service link (gocover, coveralls etc.): [https://coveralls.io/github/surullabs/lint?branch=master](https://coveralls.io/github/surullabs/lint?branch=master)

Add github.com/surullabs/lint

---

README.md

That package is no longer maintained, and will be delete in a few weeks.
Thanks you :)

Removed clevergo

---

README.md

- github.com repo: https://github.com/t0pep0/efaceconv
- godoc.org: https://godoc.org/github.com/t0pep0/efaceconv/ecutils
- goreportcard.com: https://goreportcard.com/report/github.com/t0pep0/efaceconv
- coverage service link (gocover, coveralls etc.): https://coveralls.io/github/t0pep0/efaceconv?branch=master
- [*] I have added my package in alphabetical order
- [*] I know that this package was not …

Efaceconv - High performance conversion from interface{} to immutable types without additional allocations

---

README.md

- github.com repo: https://github.com/kamildrazkiewicz/go-flow
- godoc.org: https://godoc.org/github.com/kamildrazkiewicz/go-flow
- goreportcard.com: https://goreportcard.com/report/github.com/kamildrazkiewicz/go-flow
- coverage service link (gocover, coveralls etc.): https://coveralls.io/github/kamildrazkiewicz/go-flow?branch=master

Add go-flow to Goroutines section

---

README.md

- github.com repo: https://github.com/ybbus/jsonrpc
- godoc.org: https://godoc.org/github.com/ybbus/jsonrpc
- goreportcard.com: https://goreportcard.com/report/github.com/ybbus/jsonrpc
- coverage service link (gocover, coveralls etc.): http://gocover.io/github.com/ybbus/jsonrpc

add jsonrpc 2.0 client library

---

README.md

- github.com repo: https://github.com/cstockton/go-conv
- godoc.org: https://godoc.org/github.com/cstockton/go-conv (Fully documented)
- goreportcard.com: https://goreportcard.com/report/github.com/cstockton/go-conv (A+)
- coverage service link (gocover, coveralls etc.): https://codecov.io/github/cstockton/go-conv?branch=master (100% Code coverage)

Add package conv to Miscellaneous category.

---

README.md

[![Build Status](https://travis-ci.org/mamal72/golyrics.svg?branch=master)](https://travis-ci.org/mamal72/golyrics)
[![Go Report Card](https://goreportcard.com/badge/github.com/mamal72/golyrics)](https://goreportcard.com/report/github.com/mamal72/golyrics)
[![Coverage Status](https://coveralls.io/repos/github/mamal72/golyrics/badge.svg?branch=master)](https://coveralls.io/github/mamal72/golyrics?branch=master)
[![GoDoc](https://godoc.org/github.com/mamal72/golyrics?status.svg)](https://godoc.org/github.com/mamal72/golyrics)
[![license](https://img.shields.io/github/license/mamal72/golyrics.svg)](https://github.com/mamal72/golyrics/blob/master/LICENSE)

Add Golyrics

---

README.md

https://godoc.org/github.com/tdewolff/minify
https://goreportcard.com/report/github.com/tdewolff/minify
https://travis-ci.org/tdewolff/minify
http://gocover.io/github.com/tdewolff/minify all subpackages and dependencies have coverage of ~100% too

Added github.com/tdewolff/minify

---

README.md

- godoc.org: 
- gocover.io: 
I have a book, so there isn't a godoc path for it

Added a new Book

---

README.md

Added Gitea

---

README.md

Change owner repo name
@codegangsta to @urfave

update negroni path

---

README.md

- github.com repo: https://github.com/korandiz/v4l
- godoc.org: https://godoc.org/github.com/korandiz/v4l
- goreportcard.com: https://goreportcard.com/report/github.com/korandiz/v4l
- coverage service link (gocover, coveralls etc.): http://gocover.io/github.com/korandiz/v4l

Add v4l to Video section

---

README.md

BTW, Everything is linked in the repo. Thanks!!!
- Github: https://github.com/InVisionApp/rye
- GoDoc: https://godoc.org/github.com/InVisionApp/rye
- GoReportCard: https://goreportcard.com/report/github.com/InVisionApp/rye
- CodeCov: https://codecov.io/gh/InVisionApp/rye

Add Rye middleware library

---

README.md

Updated description for Echo

---

README.md

- github.com repo: https://github.com/azul3d/engine
- godoc.org: https://godoc.org/github.com/azul3d/engine
- goreportcard.com: https://goreportcard.com/report/github.com/azul3d/engine
- coverage service link (gocover, coveralls etc.): https://gocover.io/github.com/azul3d/engine (gocover.io fails on this repo for some reason)

Added Azul3D in section gamedev.

---

README.md

- github.com repo: https://github.com/xml-comp/xml-comp
- godoc.org: https://godoc.org/github.com/XML-Comp/xml-comp
- goreportcard.com: https://goreportcard.com/report/github.com/XML-Comp/XML-Comp
- coverage service link (gocover, coveralls etc.): https://coveralls.io/github/XML-Comp/XML-Comp?branch=master
Thanks for your time, you're awesome! :+1:

add xml-comp

---

README.md

- github.com repo: https://github.com/GuiaBolso/darwin
- godoc.org: https://godoc.org/github.com/GuiaBolso/darwin
- goreportcard.com:  https://goreportcard.com/report/github.com/GuiaBolso/darwin
- coverage service link (gocover, coveralls etc.): https://gocover.io/github.com/GuiaBolso/darwin

Adding Darwin

---

README.md

- github.com repo: https://github.com/gliderlabs/ssh
- godoc.org: https://godoc.org/github.com/gliderlabs/ssh
- goreportcard.com: https://goreportcard.com/report/github.com/gliderlabs/ssh
- coverage service link (gocover, coveralls etc.): -

add github.com/gliderlabs/ssh

---

README.md

A Go implementation of the Rapid Automatic Keyword Extraction (RAKE) algorithm as described in: Rose, S., Engel, D., Cramer, N., & Cowley, W. (2010). Automatic Keyword Extraction from Individual Documents. In M. W. Berry & J. Kogan (Eds.), Text Mining: Theory and Applications: John Wiley & Sons.
Originally implemented in Python and available at: https://github.com/aneesha/RAKE
The source code is released under the MIT License.
- github.com repo: https://github.com/Obaied/RAKE.Go
- godoc.org: https://godoc.org/github.com/Obaied/RAKE.Go
- goreportcard.com: https://goreportcard.com/report/github.com/Obaied/RAKE.Go
- coverage service link (gocover, coveralls etc.): None
Thank you, team …

Add RAKE.Go to NLP section

---

README.md

- github.com repo: https://github.com/fern4lvarez/piladb
- godoc.org: https://godoc.org/github.com/fern4lvarez/piladb — https://docs.piladb.org/
- goreportcard.com: https://goreportcard.com/report/github.com/fern4lvarez/piladb
- coverage service link (gocover, coveralls etc.): https://codecov.io/gh/fern4lvarez/piladb

Add piladb database

---

README.md

- github.com repo: [https://github.com/Luxurioust/excelize](https://github.com/Luxurioust/excelize)
- godoc.org: [https://godoc.org/github.com/Luxurioust/excelize](https://godoc.org/github.com/Luxurioust/excelize)
- goreportcard.com: [https://goreportcard.com/report/github.com/Luxurioust/excelize](https://goreportcard.com/report/github.com/Luxurioust/excelize)
- coverage service link (gocover, coveralls etc.): [https://codecov.io/gh/Luxurioust/excelize](https://codecov.io/gh/Luxurioust/excelize) …

Add excelize

---

README.md

- github.com repo: https://github.com/yanzay/tbot
- godoc.org: https://godoc.org/github.com/yanzay/tbot
- goreportcard.com: https://goreportcard.com/report/github.com/yanzay/tbot
- coverage service link (gocover, coveralls etc.): https://gocover.io/github.com/yanzay/tbot

Add tbot - Telegram Bot Server

---

README.md

- github.com repo: https://github.com/octago/sflags
- godoc.org: https://godoc.org/github.com/octago/sflags
- goreportcard.com: https://goreportcard.com/report/github.com/octago/sflags
- coverage service link (gocover, coveralls etc.): https://codecov.io/gh/octago/sflags

Add sflags library

---

README.md

please check if what you want to add to `awesome-go` list meets [quality standards](https://github.com/avelino/awesome-go/blob/master/CONTRIBUTING.md#quality-standard) before sending pull request. Thanks!
- github.com repo: https://github.com/dh1tw/gosamplerate
- godoc.org: https://godoc.org/github.com/dh1tw/gosamplerate
- goreportcard.com: https://goreportcard.com/report/github.com/dh1tw/gosamplerate
- coverage service link (gocover, coveralls etc.): https://coveralls.io/github/dh1tw/gosamplerate?branch=master

added gosamplerate

---

README.md

Fix a word in Ebiten explanation

---

README.md

- github.com repo: https://github.com/knspriggs/go-twitch
- godoc.org: https://godoc.org/github.com/knspriggs/go-twitch
- goreportcard.com:  https://goreportcard.com/report/github.com/knspriggs/go-twitch
- coverage service link (gocover, coveralls etc.): https://coveralls.io/github/knspriggs/go-twitch

Add go-twitch library

---

README.md

Repo:  https://github.com/polera/publicip
GoDoc:  https://godoc.org/github.com/polera/publicip
Go Report Card:  https://goreportcard.com/report/github.com/polera/publicip

Add polera/publicip

---

README.md

Adding a framework for the creation of microservices
https://github.com/claygod/microservice
https://godoc.org/github.com/claygod/temp/microservice-doc
https://goreportcard.com/report/github.com/claygod/microservice
- [ ✔] I have added my package in alphabetical order
- [✔ ] I know that this package was not listed before
- [✔ ] I have added godoc link to the repo and to my pull request
- [✔ ] I have …

Added framework `Microservice`

---

README.md

- github.com repo: [github.com/Luxurioust/aurora](https://github.com/Luxurioust/aurora)
- godoc.org: [godoc.org/github.com/Luxurioust/aurora](https://godoc.org/github.com/Luxurioust/aurora)
- goreportcard.com: [goreportcard.com/report/github.com/Luxurioust/aurora](https://goreportcard.com/report/github.com/Luxurioust/aurora)
- coverage service link (gocover, coveralls etc.): [codecov.io/gh/Luxurioust/aurora](https://codecov.io/gh/Luxurioust/aurora) …

Add new: aurora

---

README.md

- github.com repo: https://github.com/emersion/go-message
- godoc.org: https://godoc.org/github.com/emersion/go-message
- goreportcard.com: https://goreportcard.com/report/github.com/emersion/go-message
- coverage service link (gocover, coveralls etc.): https://codecov.io/gh/emersion/go-message

Adds go-message

---

README.md

Added fcm library

---

README.md

- github.com repo:  http://github.com/rakyll/statik
- godoc.org: https://godoc.org/github.com/rakyll/statik
- goreportcard.com: https://goreportcard.com/report/github.com/rakyll/statik A+

Add rakyll/statik

---

README.md

- github.com repo:  https://github.com/xfxdev/xlog
- godoc.org: https://godoc.org/github.com/xfxdev/xlog
- goreportcard.com: https://goreportcard.com/report/github.com/xfxdev/xlog
- coverage service link (gocover, coveralls etc.):  https://gocover.io/github.com/xfxdev/xlog
- [ x] I have added my package in alphabetical order
- [ x] I know that this package was not listed before
- [ x] I have added …

add xlog library.

---

README.md

- github.com repo: https://github.com/xfxdev/xtcp
- godoc.org: https://godoc.org/github.com/xfxdev/xtcp
- goreportcard.com: https://goreportcard.com/report/github.com/xfxdev/xtcp
- coverage service link (gocover, coveralls etc.):  https://gocover.io/github.com/xfxdev/xtcp

add xtcp library.

---

README.md

Added buffalo, pop, soda, and velvet to the list

---

README.md

- github.com repo: https://github.com/kamilsk/semaphore
- godoc.org: https://godoc.org/github.com/kamilsk/semaphore
- goreportcard.com: https://goreportcard.com/report/github.com/kamilsk/semaphore
- coverage service link (gocover, coveralls etc.): https://coveralls.io/github/kamilsk/semaphore, https://gocover.io/github.com/kamilsk/semaphore

add semaphore pattern implementation

---

README.md

- github.com repo: https://github.com/spf13/pflag
- godoc.org: https://godoc.org/github.com/spf13/pflag
- goreportcard.com: https://goreportcard.com/report/github.com/spf13/pflag
- coverage service link (gocover, coveralls etc.): https://gocover.io/github.com/spf13/pflag

Add spf13's pflag library

---

README.md

- github.com repo: https://github.com/olebedev/when
- godoc.org: https://godoc.org/github.com/olebedev/when
- goreportcard.com: https://goreportcard.com/report/github.com/olebedev/when
- coverage service link (gocover, coveralls etc.):  
- https://gocover.io/github.com/olebedev/when/rules/en
- https://gocover.io/github.com/olebedev/when/rules/ru
- https://gocover.io/github.com/olebedev/when/rules/common …

Add `when` NLP library

---

README.md

- github.com repo: https://github.com/olebedev/go-tgbot
- godoc.org: https://godoc.org/github.com/olebedev/go-tgbot
- goreportcard.com: https://goreportcard.com/report/github.com/olebedev/go-tgbot
- coverage service link (gocover, coveralls etc.):  https://gocover.io/github.com/olebedev/go-tgbot

Add go-tgbot api/router library

---

README.md

- github.com repo: https://github.com/ewwwwwqm/logdump
- godoc.org: https://godoc.org/github.com/ewwwwwqm/logdump
- goreportcard.com: https://goreportcard.com/report/github.com/ewwwwwqm/logdump
- coverage service link (gocover, coveralls etc.): https://gocover.io/github.com/ewwwwwqm/logdump

Add logdump package

---

README.md

- github.com repo: https://github.com/containous/traefik
- godoc.org: https://godoc.org/github.com/containous/traefik
- goreportcard.com: https://goreportcard.com/report/github.com/containous/traefik

Add traefik, reverse-proxy and load balancer

---

README.md

- github.com repo: https://github.com/nikepan/govkbot
- godoc.org: https://godoc.org/github.com/nikepan/govkbot
- goreportcard.com: https://goreportcard.com/report/github.com/nikepan/govkbot
- coverage service link (gocover, coveralls etc.): https://gocover.io/github.com/nikepan/govkbot

add govkbot

---

README.md

- github.com repo: https://github.com/thoas/go-funk
- godoc.org: https://godoc.org/github.com/thoas/go-funk
- goreportcard.com: https://goreportcard.com/report/github.com/thoas/go-funk
- coverage service link (gocover, coveralls etc.): https://gocover.io/github.com/thoas/go-funk

Add go-funk utility library

---

README.md

- github.com repo: https://github.com/couchbase/moss
- godoc.org: https://godoc.org/github.com/couchbase/moss
- goreportcard.com: https://goreportcard.com/report/github.com/couchbase/moss
- coverage service link (gocover, coveralls etc.): https://coveralls.io/github/couchbase/moss
- [y ] I have added my package in alphabetical order
- [y] I know that this package was not listed before
- [y] I have added godoc link to the repo and to my pull request
- [y] I have added coverage service link to the repo and to my pull request
- [y] I have added goreportcard link to the repo and to my pull request
- [y] I have read [Contribution guidelines](https://github.com/avelino/awesome-go/blob/master/CONTRIBUTING.md#contribution-guidelines) and [Quality …

added https://github.com/couchbase/moss

---

README.md

* [gota](https://github.com/kniren/gota/) is an implementation of dataframes in Go. Its goreportcard is https://goreportcard.com/report/github.com/kniren/gota
* Go Cheat Sheet is a reference card of Go
- github.com repo: https://github.com/kniren/gota
- godoc.org: https://godoc.org/github.com/kniren/gota
- goreportcard.com: https://goreportcard.com/report/github.com/kniren/gota
- coverage service link (gocover, coveralls etc.):  https://gocover.io/github.com/kniren/gota/dataframe and https://gocover.io/github.com/kniren/gota/series …

Include gota and Go Cheat Sheet

---

README.md

- github.com repo: https://github.com/aandryashin/ggr
- godoc.org: https://godoc.org/github.com/aandryashin/ggr
- goreportcard.com: https://goreportcard.com/report/github.com/aandryashin/ggr
- coverage service link (gocover, coveralls etc.): https://codecov.io/gh/aandryashin/ggr

Added link to ggr server

---

README.md

- github.com repo: https://github.com/davelondon/jennifer/
- godoc.org: https://godoc.org/github.com/davelondon/jennifer
- goreportcard.com: https://goreportcard.com/report/github.com/davelondon/jennifer
- coverage service link (gocover, coveralls etc.): https://codecov.io/gh/davelondon/jennifer

Add Jennifer to code generation category

---

README.md

- github.com repo: https://github.com/goreleaser/releaser
- godoc.org: https://godoc.org/github.com/goreleaser/goreleaser
- goreportcard.com: https://goreportcard.com/report/github.com/goreleaser/goreleaser
- coverage service link (gocover, coveralls etc.): https://coveralls.io/github/goreleaser/goreleaser

added goreleaser

---

README.md

- github.com repo: https://github.com/aandryashin/selenoid
- godoc.org: http://godoc.org/github.com/aandryashin/selenoid
- goreportcard.com: https://goreportcard.com/report/github.com/aandryashin/selenoid
- coverage service link (gocover, coveralls etc.): https://codecov.io/gh/aandryashin/selenoid

Added selenoid entry

---

README.md

- github.com repo: https://github.com/dominikh/go-mode.el 
- godoc.org: 

Add go-mode into Editor Plugins

---

README.md

- github.com repo: https://github.com/agext/levenshtein
- godoc.org: https://godoc.org/github.com/agext/levenshtein
- goreportcard.com: https://goreportcard.com/report/github.com/agext/levenshtein
- coverage service link (gocover, coveralls etc.): https://coveralls.io/github/agext/levenshtein
**Note:** a trailing white-space was automatically removed on an …

Add agext/levenshtein to 'Data Structures'

---

README.md

- github.com repo: https://github.com/go-vgo/robotgo
- godoc.org: https://godoc.org/github.com/go-vgo/robotgo
- goreportcard.com: https://goreportcard.com/report/github.com/go-vgo/robotgo
- coverage service link (gocover, coveralls etc.): http://gocover.io/github.com/go-vgo/robotgo

Add Robotgo

---

README.md

- github.com repo: https://github.com/unrolled/secure
- godoc.org: https://godoc.org/github.com/unrolled/secure
- goreportcard.com: https://goreportcard.com/report/github.com/unrolled/secure
- coverage service link (gocover, coveralls etc.): http://gocover.io/github.com/unrolled/secure

Added github.com/unrolled/secure

---

README.md

/cc @neelance FYI.
github.com repo: https://github.com/neelance/graphql-go
godoc.org: https://godoc.org/github.com/neelance/graphql-go 
goreportcard.com: https://goreportcard.com/report/github.com/neelance/graphql-go
coverage service link: https://gocover.io/github.com/neelance/graphql-go

Add https://github.com/neelance/graphql-go

---

README.md

github.com repo: [https://github.com/codesenberg/bombardier](https://github.com/codesenberg/bombardier)
godoc.org: [https://godoc.org/github.com/codesenberg/bombardier](https://godoc.org/github.com/codesenberg/bombardier)
goreportcard.com: [https://goreportcard.com/report/github.com/codesenberg/bombardier](https://goreportcard.com/report/github.com/codesenberg/bombardier)
coverage service link: [https://gocover.io/github.com/codesenberg/bombardier](https://gocover.io/github.com/codesenberg/bombardier)
I humbly request you to consider adding my little tool to your list of awesome Go software.

Add https://github.com/codesenberg/bombardier

---

README.md

- github.com repo: https://github.com/shiyanhui/hero
- godoc.org: https://godoc.org/github.com/shiyanhui/hero
- goreportcard.com: https://goreportcard.com/report/github.com/shiyanhui/hero
- coverage service link (gocover, coveralls etc.): https://gocover.io/github.com/shiyanhui/hero

add hero template engine

---

README.md

- github.com repo: https://github.com/agext/uuid
- godoc.org: https://godoc.org/github.com/agext/uuid
- goreportcard.com: https://goreportcard.com/report/github.com/agext/uuid
- coverage service link (gocover, coveralls etc.): https://coveralls.io/github/agext/uuid

Add agext/uuid to Miscellaneous

---

README.md

- github.com repo: https://github.com/gen2brain/raylib-go
- godoc.org: https://godoc.org/github.com/gen2brain/raylib-go/raylib
- goreportcard.com: https://goreportcard.com/report/github.com/gen2brain/raylib-go
- coverage service link (gocover, coveralls etc.): n/a

Add raylib-go

---

README.md

- github.com repo: [github.com/cosiner/argv](https://github.com/cosiner/argv)
- godoc.org: [godoc.org/github.com/cosiner/argv](https://godoc.org/github.com/cosiner/argv)
- goreportcard.com: [goreportcard.com/report/github.com/cosiner/argv](https://goreportcard.com/report/github.com/cosiner/argv)
- coverage service link (gocover, coveralls etc.): [coveralls.io/github/cosiner/argv](https://coveralls.io/github/cosiner/argv) …

add argv library.

---

README.md

- github.com repo: https://github.com/maxatome/go-vitotrol
- godoc.org: https://godoc.org/github.com/maxatome/go-vitotrol
- goreportcard.com: https://goreportcard.com/report/github.com/maxatome/go-vitotrol
- coverage service link (gocover, coveralls etc.): https://gocover.io/github.com/maxatome/go-vitotrol

Add go-vitotrol, Viessmann Vitotrol ws client

---

README.md

Nothing significant, just updates the `go-sciter` project link.

Update go-sciter project link

---

README.md

add go-colorable and go-isatty

---

README.md

- github.com repo: https://github.com/jutkko/copy-pasta
- godoc.org: https://godoc.org/github.com/jutkko/copy-pasta
- goreportcard.com: https://goreportcard.com/report/github.com/jutkko/copy-pasta
- coverage service link (gocover, coveralls etc.): Sorry can't find a way to do coverage, but the repo has lots of integration tests!
- [x ] I have added my package in alphabetical order
- [x ] I know that …

Add copy-pasta

---

README.md

* Github: https://github.com/zpatrick/rclient
* Godoc: https://godoc.org/github.com/zpatrick/rclient
* Go Report Card: https://goreportcard.com/report/github.com/zpatrick/rclient
* GoCover: https://gocover.io/github.com/zpatrick/rclient

add rclient

---

README.md

- github.com repo: [https://github.com/cosiner/flag](https://github.com/cosiner/flag)
- godoc.org: [https://godoc.org/github.com/cosiner/flag](https://godoc.org/github.com/cosiner/flag)
- goreportcard.com: [https://goreportcard.com/report/github.com/cosiner/flag](https://goreportcard.com/report/github.com/cosiner/flag)
- coverage service link (gocover, coveralls etc.): [https://coveralls.io/github/cosiner/flag](https://coveralls.io/github/cosiner/flag) …

add flag library.

---

README.md

- github.com repo: https://github.com/gen2brain/go-unarr
- godoc.org: https://godoc.org/github.com/gen2brain/go-unarr
- goreportcard.com: https://goreportcard.com/report/github.com/gen2brain/go-unarr
- coverage service link (gocover, coveralls etc.): http://gocover.io/github.com/gen2brain/go-unarr

Add go-unarr

---

README.md

- github.com repo: https://github.com/nstratos/go-myanimelist
- godoc.org: https://godoc.org/github.com/nstratos/go-myanimelist/mal
- goreportcard.com: https://goreportcard.com/report/github.com/nstratos/go-myanimelist
- coverage service link (gocover, coveralls etc.): [gocover.io](http://gocover.io/github.com/nstratos/go-myanimelist/mal), [coveralls.io](https://coveralls.io/github/nstratos/go-myanimelist), [latest coveralls.io build](https://coveralls.io/builds/10544797)
**Note**: that new categories can be added only when there are 3 packages or …

Add go-myanimelist to third-party APIs

---

README.md

Updated username davelondon to dave

---

README.md

- github.com repo: https://github.com/KyleBanks/depth
- godoc.org: https://godoc.org/github.com/KyleBanks/depth
- goreportcard.com: https://goreportcard.com/report/github.com/KyleBanks/depth
- coverage service link (gocover, coveralls etc.): https://coveralls.io/github/KyleBanks/depth?branch=master

Add 'depth' package

---

README.md

Added DDNS
- github.com repo: https://github.com/skibish/ddns
- godoc.org: https://godoc.org/github.com/skibish/ddns
- goreportcard.com: https://goreportcard.com/report/github.com/skibish/ddns
- coverage service link (gocover, coveralls etc.): https://gocover.io/github.com/skibish/ddns (detailed coverage can be seen here: https://travis-ci.org/skibish/ddns/jobs/211124109) …

Add DDNS (software)

---

README.md

- github.com repo: https://github.com/nicklaw5/go-respond
- godoc.org: https://godoc.org/github.com/nicklaw5/go-respond
- goreportcard.com: https://goreportcard.com/report/github.com/nicklaw5/go-respond
- coverage service link (gocover, coveralls etc.): https://coveralls.io/github/nicklaw5/go-respond

Add go-respond

---

README.md

- github.com repo: https://github.com/rafaeljesus/tempdb
- godoc.org: https://godoc.org/github.com/rafaeljesus/tempdb
- goreportcard.com: https://goreportcard.com/report/github.com/rafaeljesus/tempdb
- coverage service link (gocover, coveralls etc.): https://gocover.io/github.com/rafaeljesus/tempdb

Add tempdb to database list

---

README.md

- github.com repo: https://github.com/appleboy/easyssh-proxy
- godoc.org: https://godoc.org/github.com/appleboy/easyssh-proxy
- goreportcard.com: https://goreportcard.com/report/github.com/appleboy/easyssh-proxy
- coverage service link (gocover, coveralls etc.): https://codecov.io/gh/appleboy/easyssh-proxy
[![GoDoc](https://godoc.org/github.com/appleboy/easyssh-proxy?status.svg)](https://godoc.org/github.com/appleboy/easyssh-proxy) [![Build Status](http://drone.wu-boy.com/api/badges/appleboy/easyssh-proxy/status.svg)](http://drone.wu-boy.com/appleboy/easyssh-proxy) [![codecov](https://codecov.io/gh/appleboy/easyssh-proxy/branch/master/graph/badge.svg)](https://codecov.io/gh/appleboy/easyssh-proxy) [![Go Report Card](https://goreportcard.com/badge/github.com/appleboy/easyssh-proxy)](https:/ …

Add esayssh-proxy package.

---

README.md

Thanks in advance!
- github.com repo: https://github.com/VerizonDigital/vflow
- godoc.org: https://godoc.org/github.com/VerizonDigital/vflow/vflow
- goreportcard.com: https://goreportcard.com/report/github.com/VerizonDigital/vflow
- [ x] I have added my package in alphabetical order
- [ x] I know that this package was not listed before
- [ x] I …

added vflow

---

README.md

- github.com repo: https://github.com/pkg/profile
- godoc.org: https://godoc.org/github.com/pkg/profile
- goreportcard.com: https://goreportcard.com/report/github.com/pkg/profile
- coverage service link (gocover, coveralls etc.): https://gocover.io/github.com/pkg/profile

Change repo for profile package

---

README.md

- github.com repo: https://github.com/rafaeljesus/nsq-event-bus
- godoc.org: https://godoc.org/github.com/rafaeljesus/nsq-event-bus
- goreportcard.com: https://goreportcard.com/report/github.com/rafaeljesus/nsq-event-bus
- coverage service link (gocover, coveralls etc.): https://gocover.io/github.com/rafaeljesus/nsq-event-bus

Add nsq-event-bus

---

README.md

- github.com repo: https://github.com/adlio/trello
- godoc.org: https://godoc.org/github.com/adlio/trello
- goreportcard.com: https://goreportcard.com/report/github.com/adlio/trello
- coverage service link (gocover, coveralls etc.): https://coveralls.io/github/adlio/trello?branch=master

Adds Trello library to README.md

---

README.md

I have created Hermes, a Golang package that generates clean, responsive HTML e-mails for sending transactional mail.
Here are the needed info:
- github.com repo: https://github.com/matcornic/hermes
- godoc.org: https://godoc.org/github.com/matcornic/hermes
- goreportcard.com: https://goreportcard.com/report/github.com/matcornic/hermes
- coverage service link (gocover, coveralls etc.): https://codecov.io/github/matcornic/hermes/
And checklist:
Thank you for this repo. It helped me a lot in the past ❤️

Hermes - Golang package that generates clean, responsive HTML e-mails

---

README.md

- github.com repo: https://github.com/Rhymond/go-money
- godoc.org: https://godoc.org/github.com/Rhymond/go-money
- goreportcard.com: https://goreportcard.com/report/github.com/rhymond/go-money
- coverage service link (gocover, coveralls etc.): https://coveralls.io/github/Rhymond/go-money?branch=master

Add go-money

---

README.md

- github.com repo: https://github.com/bengadbois/pewpew
- godoc.org: https://godoc.org/github.com/bengadbois/pewpew/lib
- goreportcard.com: https://goreportcard.com/report/github.com/bengadbois/pewpew
- coverage service link (gocover, coveralls etc.): https://coveralls.io/github/bengadbois/pewpew?branch=master Note: the coverage is 99% for the lib, but 75% for the entire repo, as non-lib is mostly just wrappers that parse command line options for the runnable program. …

Adding github.com/bengadbois/pewpew

---

repo_test.go

Signed-off-by: Kirill Danshin <k@guava.by>
fixes #1336

tests: fix dup links test

---

README.md

- github.com repo: https://github.com/abadojack/whatlanggo
- godoc.org: https://godoc.org/github.com/abadojack/whatlanggo
- goreportcard.com: https://goreportcard.com/report/github.com/abadojack/whatlanggo
- coverage service link (gocover, coveralls etc.): https://gocover.io/github.com/abadojack/whatlanggo

Add whatlanggo

---

README.md

Updating go-money link

---

README.md

- github.com repo: https://github.com/tidwall/gjson
- godoc.org: https://godoc.org/github.com/tidwall/gjson
- goreportcard.com: https://goreportcard.com/report/github.com/tidwall/gjson
- coverage service link (gocover, coveralls etc.): https://gocover.io/github.com/tidwall/gjson

Add GJSON.

---

README.md

- github.com repo: [https://github.com/asdine/storm](https://github.com/asdine/storm)
- godoc.org: [https://godoc.org/github.com/asdine/storm](https://godoc.org/github.com/asdine/storm)
- goreportcard.com: [https://goreportcard.com/report/github.com/asdine/storm](https://goreportcard.com/report/github.com/asdine/storm) …

Update Storm phrase and category

---

README.md

- github.com repo: https://github.com/astaxie/build-web-application-with-golang
- godoc.org: N/A
- goreportcard.com: N/A 
- coverage service link (gocover, coveralls etc.): N/A

Add web app golang tutorial

---

README.md

- github.com repo: https://github.com/hsluoyz/casbin
- godoc.org: https://godoc.org/github.com/hsluoyz/casbin
- goreportcard.com: https://goreportcard.com/report/github.com/hsluoyz/casbin
- coverage service link (gocover, coveralls etc.): https://coveralls.io/github/hsluoyz/casbin?branch=master

Add casbin

---

.travis.yml
repo.go

Signed-off-by: Kirill Danshin <k@guava.by>
helps #1224

working on gfm compat (helps #1224)

---

README.md

- github.com repo: https://github.com/go-playground/pure
- godoc.org: https://godoc.org/github.com/go-playground/pure
- goreportcard.com: https://goreportcard.com/report/github.com/go-playground/pure
- coverage service link (gocover, coveralls etc.): https://gocover.io/github.com/go-playground/pure

Add pure http router

---

README.md

- github.com repo: https://github.com/faiface/pixel
- godoc.org: https://godoc.org/github.com/faiface/pixel
- goreportcard.com: https://goreportcard.com/report/github.com/faiface/pixel
- coverage service link (gocover, coveralls etc.): _Pixel doesn't have tests (yet), see explanation at the end_
**Note about tests: Pixel doesn't have tests yet. Being a game …

add Pixel (Game Development) package to awesome-go

---

README.md

https://github.com/yourbasic/graph
https://godoc.org/github.com/yourbasic/graph
https://goreportcard.com/report/github.com/yourbasic/graph
https://gocover.io/github.com/yourbasic/graph

Add githut.com/yourbasic/graph

---

.github/PULL_REQUEST_TEMPLATE.md

Shows how many percent that covered the package

recommendation new coverage runner cover.run

---

README.md

- godoc.org:
- [NA] I have added my package in alphabetical order
- [NA] I know that this package was not listed before
- [NA] I have …

Add Capital Go conference

---

README.md

I just updated the vFlow description as I added new protocol (Netflow) recently.
Thanks in advance!
------------------
- godoc.org: …

vFlow updated, I added netflow protocol feature to vFlow.

---

README.md

- github.com repo: https://github.com/ChimeraCoder/gojson
- godoc.org: https://godoc.org/github.com/ChimeraCoder/gojson
- goreportcard.com: https://goreportcard.com/report/github.com/ChimeraCoder/gojson
- coverage service link (gocover, coveralls etc.): https://gocover.io/github.com/ChimeraCoder/gojson

Add gojson

---

README.md

- github.com repo: https://github.com/wgliang/goreporter
- godoc.org: https://godoc.org/github.com/wgliang/goreporter
- goreportcard.com: https://goreportcard.com/report/github.com/wgliang/goreporter
- coverage service link (gocover, coveralls etc.): https://gocover.io/github.com/wgliang/goreporter

Add goreporter

---

README.md

- github.com repo: [repo](https://github.com/adam-hanna/sessions)
- godoc.org:  [![GoDoc](https://godoc.org/github.com/adam-hanna/sessions?status.svg)](https://godoc.org/github.com/adam-hanna/sessions)
- goreportcard.com:  [![Go Report Card](https://goreportcard.com/badge/github.com/adam-hanna/sessions)](https://goreportcard.com/report/github.com/adam-hanna/sessions)
- coverage service link ([cover.run](https://cover.run/), [gocover](http://gocover.io/), [coveralls](https://coveralls.io/) etc.), example: `![cover.run …

added github.com/adam-hanna/sessions

---

README.md

- github.com repo: https://github.com/devopsfaith/krakend
- godoc.org: https://godoc.org/github.com/devopsfaith/krakend
- goreportcard.com: https://goreportcard.com/report/github.com/devopsfaith/krakend
- coverage service link (gocover, coveralls etc.): https://coveralls.io/github/devopsfaith/krakend

Add KrakenD framework

---

README.md

- github.com repo: https://github.com/yazgazan/jaydiff
- godoc.org: https://godoc.org/github.com/yazgazan/jaydiff
- goreportcard.com: https://goreportcard.com/report/github.com/yazgazan/jaydiff
- coverage service link:  https://coveralls.io/repos/github/yazgazan/jaydiff/badge.svg?branch=master

add JayDiff

---

README.md

- github.com repo: https://github.com/asticode/go-astilectron
- godoc.org: https://godoc.org/github.com/asticode/go-astilectron
- goreportcard.com: http://goreportcard.com/report/github.com/asticode/go-astilectron
- coverage service link: https://gocover.io/github.com/asticode/go-astilectron

Add go-astilectron

---

README.md

Links:
- github.com repo: https://github.com/dannyvankooten/grender
- godoc.org: https://godoc.org/github.com/dannyvankooten/grender
- goreportcard.com: https://goreportcard.com/report/github.com/dannyvankooten/grender
- coverage service link (gocover, coveralls etc.): https://coveralls.io/github/dannyvankooten/grender
Checklist:
> Thanks for your PR, you're awesome! :+1:
No, *YOU'RE* awesome!

add grender

---

README.md

Add section about Go packages for the IoT.

---

README.md

- github.com repo: https://github.com/antchfx/xquery
- godoc.org: https://godoc.org/github.com/antchfx/xquery
- goreportcard.com: https://goreportcard.com/report/github.com/antchfx/xquery
- coverage service link (gocover, coveralls etc.): https://coveralls.io/github/antchfx/xquery?branch=master

add xquery package

---

README.md

- github.com repo: https://github.com/mrLSD/go-benchmark-app
- godoc.org: https://godoc.org/github.com/mrLSD/go-benchmark-app
- goreportcard.com: https://goreportcard.com/report/github.com/mrLSD/go-benchmark-app
- coverage service link (gocover, coveralls etc.): https://codecov.io/gh/mrLSD/go-benchmark-app
- [v ] I have added my package in alphabetical order
- [v ] I know that this package was not …

add go-benchmark-app - HTTP benchmark tool

---

README.md

Current Test Cov: 79%
Report Card: A+ (7/7 100%)
Build Passing: true
Awesome Badge: true
- github.com repo: https://github.com/esemplastic/unis
- godoc.org: https://godoc.org/github.com/esemplastic/unis
- goreportcard.com: https://goreportcard.com/report/github.com/esemplastic/unis
- coverage service link:  https://coveralls.io/github/esemplastic/unis

Add UNIS, the modern architecture pattern for string utilities

---

README.md

- github.com repo: https://github.com/adelowo/onecache
- godoc.org: https://godoc.org/github.com/adelowo/onecache
- goreportcard.com: https://goreportcard.com/report/github.com/adelowo/onecache
- coverage service link ([cover.run](https://cover.run/), [gocover](http://gocover.io/), [coveralls](https://coveralls.io/) etc.), example: [![Coverage Status](https://coveralls.io/repos/github/adelowo/onecache/badge.svg?branch=master)](https://coveralls.io/github/adelowo/onecache?branch=master)
**Note**: that new categories can be added only …

Added onecache, a caching library

---

README.md

- github.com repo: https://github.com/khaiql/dbcleaner
- godoc.org: https://godoc.org/github.com/khaiql/dbcleaner
- goreportcard.com: https://goreportcard.com/report/github.com/khaiql/dbcleaner
- coverage service link: [![Coverage Status](https://coveralls.io/repos/github/khaiql/dbcleaner/badge.svg)](https://coveralls.io/github/khaiql/dbcleaner) …

Add dbcleaner

---

README.md

- github.com repo: https://github.com/joshbetz/config
- godoc.org: [![](https://godoc.org/github.com/joshbetz/config?status.svg)](http://godoc.org/github.com/joshbetz/config)
- goreportcard.com: [![Go Report Card](https://goreportcard.com/badge/github.com/joshbetz/config)](https://goreportcard.com/report/github.com/joshbetz/config)
- coverage service link ([cover.run](https://cover.run/), [gocover](http://gocover.io/), [coveralls](https://coveralls.io/) etc.), example: https://gocover.io/github.com/joshbetz/config …

Add joshbetz/config

---

README.md

- github.com repo: https://github.com/posener/complete
- godoc.org: http://godoc.org/github.com/posener/complete
- goreportcard.com: https://goreportcard.com/report/github.com/posener/complete
- coverage service link: https://codecov.io/gh/posener/complete

Add complete

---

README.md

- github.com repo: https://github.com/antchfx/xpath
- godoc.org: https://godoc.org/github.com/antchfx/xpath
- goreportcard.com: https://goreportcard.com/report/github.com/antchfx/xpath
- coverage service link ([cover.run](https://cover.run/), [gocover](http://gocover.io/), [coveralls](https://coveralls.io/) etc.), example: `![cover.run go](https://cover.run/go/github.com/user/repository.svg)`: https://coveralls.io/github/antchfx/xpath?branch=master …

add xpath package

---

README.md

Hey, would be cool, if you add loginsrv:
https://github.com/tarent/loginsrv
https://goreportcard.com/badge/github.com/tarent/loginsrv
https://coveralls.io/repos/github/tarent/loginsrv/
https://godoc.org/github.com/tarent/loginsrv

Added loginsrv - JWT login microservice

---

README.md

- github.com repo: https://github.com/rs/zerolog
- godoc.org: https://godoc.org/github.com/rs/zerolog
- goreportcard.com: [![Go Report Card](https://goreportcard.com/badge/github.com/rs/zerolog)](https://goreportcard.com/report/github.com/rs/zerolog)
- coverage: ![cover.run go](https://cover.run/go/github.com/rs/zerolog.svg)

Add zerolog

---

README.md

Go-rquad: Region quadtrees in Go [![Build Status](https://travis-ci.org/aurelien-rainone/go-rquad.svg?branch=master)](https://travis-ci.org/aurelien-rainone/go-rquad)
- github.com repo: [aurelien-rainone/go-rquad](https://github.com/aurelien-rainone/go-rquad) 
- godoc.org: [![GoDoc](http://img.shields.io/badge/go-documentation-blue.svg?style=flat-square)](http://godoc.org/github.com/aurelien-rainone/go-rquad)
- goreportcard.com: [![Go Report Card](https://goreportcard.com/badge/github.com/aurelien-rainone/go-rquad)](https://goreportcard.com/report/github.com/aurelien-rainone/go-rquad)
- coverage service link [![Coverage Status](https://coveralls.io/repos/github/aurelien-rainone/go-rquad/badge.svg?branch=master)](https://coveralls.io/github/aurelien-rainone/go-rquad?branch=master)
**Make …

Add go-rquad - efficient region quadtrees

---

README.md

https://github.com/yourbasic/bit
https://godoc.org/github.com/yourbasic/bit
https://goreportcard.com/report/github.com/yourbasic/bit
http://gocover.io/github.com/yourbasic/bit

Add github.com/yourbasic/bit

---

README.md

- github.com repo: https://github.com/shomali11/slacker
- godoc.org: https://godoc.org/github.com/shomali11/slacker
- goreportcard.com: https://goreportcard.com/report/github.com/shomali11/slacker
http://gocover.io/github.com/shomali11/slacker/expression
http://gocover.io/github.com/shomali11/slacker/parser …

Added [slacker] A framework to create Slack bots

---

README.md

Add Gogland & deprecate the idea plug-in

---

README.md

- github.com repo: https://github.com/shabbyrobe/xmlwriter
- godoc.org: https://godoc.org/github.com/shabbyrobe/xmlwriter
- goreportcard.com: https://goreportcard.com/report/github.com/shabbyrobe/xmlwriter
- coverage service link ![cover.run go](https://cover.run/go/github.com/shabbyrobe/xmlwriter.svg)
Very good coverage: the unit test coverage is about 85%, but there is a separate tester in the repo which absolutely smashes the library with a huge corpus of test cases - every xml file on your hard drive can be used to drive the tester (about 80,000 …

Add shabbyrobe/xmlwriter, create XML section

---

README.md

- github.com repo: https://github.com/workanator/go-ataman
- godoc.org: https://godoc.org/gopkg.in/workanator/go-ataman.v1
- goreportcard.com: https://goreportcard.com/report/github.com/workanator/go-ataman
- coverage service link: https://coveralls.io/github/workanator/go-ataman?branch=master

Add go-ataman

---

README.md

- github.com repo: http://github.com/cch123/elasticsql
- godoc.org: https://godoc.org/github.com/cch123/elasticsql
- goreportcard.com: https://goreportcard.com/report/github.com/cch123/elasticsql
- coverage service link: https://coveralls.io/github/cch123/elasticsql?branch=master

Add elasticsql

---

README.md

Clean up whitespace, full stop header consistency

---

README.md

- github.com repo:  https://github.com/immortal/immortal/
- godoc.org: https://godoc.org/github.com/immortal/immortal
- goreportcard.com: https://goreportcard.com/report/github.com/immortal/immortal
- coverage service link: https://codecov.io/gh/immortal/immortal
- github.com repo: https://github.com/nbari/violetear/
- godoc.org: https://godoc.org/github.com/nbari/violetear
- goreportcard.com: https://goreportcard.com/report/github.com/nbari/violetear
- coverage service link: https://coveralls.io/github/nbari/violetear?branch=master …

immortal, ssh-vault, violetear

---

README.md

- github.com repo: https://github.com/rubyist/circuitbreaker
- godoc.org: https://godoc.org/github.com/rubyist/circuitbreaker
- goreportcard.com: https://goreportcard.com/report/github.com/rubyist/circuitbreaker
- coverage service link: https://cover.run/go/github.com/rubyist/circuitbreaker

Add rubyist/circuitbreaker

---

README.md

- github.com repo:https://github.com/tenntenn/gpath
- godoc.org:https://godoc.org/github.com/tenntenn/gpath
- goreportcard.com:https://goreportcard.com/report/github.com/tenntenn/gpath
- coverage service link:https://codecov.io/gh/tenntenn/gpath

Add tenntenn/gpath

---

README.md

- github.com repo: https://github.com/eapache/go-resiliency
- godoc.org: https://godoc.org/github.com/eapache/go-resiliency
- goreportcard.com: https://goreportcard.com/report/github.com/eapache/go-resiliency
- Coverages:
- github.com/eapache/go-resiliency/batcher: ![cover.run go](https://cover.run/go/github.com/eapache/go-resiliency/batcher.svg)
- github.com/eapache/go-resiliency/breaker: ![cover.run go](https://cover.run/go/github.com/eapache/go-resiliency/breaker.svg)
- github.com/eapache/go-resiliency/deadline: ![cover.run go](https://cover.run/go/github.com/eapache/go-resiliency/deadline.svg)
- github.com/eapache/go-resiliency/retrier: ![cover.run go](https://cover.run/go/github.com/eapache/go-resiliency/retrier.svg)
- github.com/eapache/go-resiliency/semaphore: ![cover.run …

Add go-resiliency

---

README.md

- godoc.org:
- [NA] I have added my package in alphabetical order
- [NA] I know that this package was not listed before
- [NA] I have …

Add GopherCon Singapore

---

README.md

- github.com repo: https://github.com/vardius/gorouter
- godoc.org: [![](https://godoc.org/github.com/vardius/gorouter?status.svg)](http://godoc.org/github.com/vardius/gorouter)
- goreportcard.com: [![Go Report Card](https://goreportcard.com/badge/github.com/vardius/gorouter)](https://goreportcard.com/report/github.com/vardius/gorouter)
- coverage: [![codecov](https://codecov.io/gh/vardius/gorouter/branch/master/graph/badge.svg)](https://codecov.io/gh/vardius/gorouter)

Add gorouter package

---

README.md

- github.com repo: https://github.com/roblaszczak/go-cleanarch
- godoc.org: https://godoc.org/github.com/roblaszczak/go-cleanarch/cleanarch
- goreportcard.com: https://goreportcard.com/report/github.com/roblaszczak/go-cleanarch
- coverage service link: http://gocover.io/github.com/roblaszczak/go-cleanarch/cleanarch

Add go-cleanarch

---

README.md

- github.com repo: github.com/shomali11/util
- godoc.org: https://godoc.org/github.com/shomali11/util
- goreportcard.com: https://goreportcard.com/report/github.com/shomali11/util
- coverage service link: http://gocover.io/github.com/shomali11/util/strings

Added github.com/shomali11/util

---

README.md

- github.com repo: http://github.com/jakehl/goid
- godoc.org: https://godoc.org/github.com/jakehl/goid
- goreportcard.com: https://goreportcard.com/badge/github.com/JakeHL/goid
- coverage service link: https://cover.run/go/github.com/jakehl/goid

Added goid

---

README.md

- github.com repo: https://github.com/dtylman/gowd
- godoc.org: https://godoc.org/github.com/dtylman/gowd
- goreportcard.com: https://goreportcard.com/report/github.com/dtylman/gowd
- coverage service link: http://gocover.io/github.com/dtylman/gowd
- [X ] I have added coverage service link to the repo and to my pull request
- [X ] I have added goreportcard link to the repo and to …

Adding gowd

---

README.md

Add gowww/router

---

README.md

- github.com repo: https://github.com/LawrenceWoodman/roveralls
- godoc.org: https://godoc.org/github.com/LawrenceWoodman/roveralls
- goreportcard.com: https://goreportcard.com/report/github.com/LawrenceWoodman/roveralls
- coverage service link (gocover, coveralls etc.):  https://coveralls.io/r/LawrenceWoodman/roveralls?branch=master
- [ x] I have added my package in alphabetical order
- [ x] I know …

Add roveralls to continuous integration section

---

README.md

- github.com repo: https://github.com/yourbasic/radix
- godoc.org: https://godoc.org/github.com/yourbasic/radix
- goreportcard.com: https://goreportcard.com/report/github.com/yourbasic/radix
- coverage service link: http://gocover.io/github.com/yourbasic/radix

Add github.com/yourbasic/radix

---

README.md

- github.com repo: https://github.com/vbauerster/mpb
- godoc.org: https://godoc.org/github.com/vbauerster/mpb
- goreportcard.com: https://goreportcard.com/report/github.com/vbauerster/mpb
- coverage service link ([cover.run](https://cover.run/), [gocover](http://gocover.io/), [coveralls](https://coveralls.io/) etc.), example: `![cover.run go](https://cover.run/go/github.com/user/repository.svg)` https://cover.run/go/github.com/vbauerster/mpb
**Make …

github.com/vbauerster/mpb - Multi progress bar for terminal applications

---

README.md

…of Augmenting Topologies (NEAT).
- github.com repo: https://github.com/jinyeom/neat
- godoc.org: https://godoc.org/github.com/jinyeom/neat
- goreportcard.com: https://goreportcard.com/report/github.com/jinyeom/neat
- coverage service link: https://cover.run/go/github.com/jinyeom/neat

Added neat - Plug-and-play, parallel Go framework for NeuroEvolution of Augmenting Topologies (NEAT)

---

README.md

Hi,
This pull request adds [Golangbot](https://golangbot.com/learn-golang-series/) to the Tutorials section.
This website contains tutorials to get started with programming in Go.
- I have added my website in alphabetical order
- I know that this website was not listed before
- I have read [Contribution guidelines](https://github.com/avelino/awesome-go/blob/master/CONTRIBUTING.md#contribution-guidelines), [maintainers note](https://github.com/avelino/awesome-go/blob/master/CONTRIBUTING.md#maintainers) and [Quality standard](https://github.com/avelino/awesome-go/blob/master/CONTRIBUTING.md#quality-standard).
Thanks.

Added new tutorial

---

README.md

- github.com repo: https://github.com/artonge/go-csv-tag
- godoc.org: https://godoc.org/github.com/artonge/go-csv-tag
- goreportcard.com: https://goreportcard.com/report/github.com/artonge/go-csv-tag
- coverage service link: https://cover.run/go/github.com/artonge/go-csv-tag

Add github.com/artonge/go-csv-tag

---

README.md

- github.com repo: https://github.com/cbergoon/merkletree
- godoc.org: https://godoc.org/github.com/cbergoon/merkletree
- goreportcard.com: https://goreportcard.com/report/github.com/cbergoon/merkletree
- coverage service link: http://gocover.io/github.com/cbergoon/merkletree

Adding cbergoon/merkletree to DS section

---

README.md

- github.com repo: https://github.com/One-com/gone/tree/master/jconf#readme
- godoc.org: https://godoc.org/github.com/One-com/gone/jconf
- goreportcard.com: https://goreportcard.com/report/github.com/One-com/gone
- coverage service link: http://gocover.io/github.com/One-com/gone/jconf
you're welcome...

Added gone/jconf modular JSON configuration lib

---

README.md

- github.com repo: https://github.com/mozillazg/go-httpheader
- godoc.org: https://godoc.org/github.com/mozillazg/go-httpheader
- goreportcard.com: https://goreportcard.com/report/github.com/mozillazg/go-httpheader
- coverage service link ([cover.run](https://cover.run/), [gocover](http://gocover.io/), [coveralls](https://coveralls.io/) etc.): https://coveralls.io/r/mozillazg/go-httpheader …

Add go-httpheader

---

README.md

- github.com repo: https://github.com/osamingo/gaurun-client
- godoc.org: https://godoc.org/github.com/osamingo/gaurun-client
- goreportcard.com: https://goreportcard.com/report/github.com/osamingo/gaurun-client
- coverage service link ([cover.run](https://cover.run/), [gocover](http://gocover.io/), [coveralls](https://coveralls.io/) etc.): https://codecov.io/gh/osamingo/gaurun-client …

Add osamingo/gaurun-client

---

README.md

Moved GoDotEnv from Utilities to Configuration

---

README.md

- github.com repo: https://github.com/shomali11/xredis
- godoc.org: https://godoc.org/github.com/shomali11/xredis
- goreportcard.com: https://goreportcard.com/report/github.com/shomali11/xredis
- coverage service link ([cover.run](https://cover.run/), [gocover](http://gocover.io/), [coveralls](https://coveralls.io/) etc.), example: http://gocover.io/github.com/shomali11/xredis …

Added github.com/shomali11/xredis

---

README.md

- godoc.org: https://godoc.org/github.com/Boostport/avatica
- goreportcard.com: https://goreportcard.com/report/github.com/Boostport/avatica
- gocover.io: https://coveralls.io/github/Boostport/avatica

Add Apache Phoenix/Avatica database/sql driver.

---

README.md

- github.com repo: https://github.com/oklahomer/go-sarah
- godoc.org: https://godoc.org/github.com/oklahomer/go-sarah
- goreportcard.com: https://goreportcard.com/report/github.com/oklahomer/go-sarah
- coverage service link ([cover.run](https://cover.run/), [gocover](http://gocover.io/), [coveralls](https://coveralls.io/) etc.): https://coveralls.io/github/oklahomer/go-sarah …

Add oklahomer/go-sarah

---

README.md

- https://godoc.org/astuart.co/goq
- https://github.com/andrewstuart/goq
- https://goreportcard.com/report/astuart.co/goq
- https://coveralls.io/github/andrewstuart/goq?branch=master

Add goq - html unmarshaling with jquery struct tags

---

README.md

Second most used editor for Go https://blog.golang.org/survey2016-results#TOC_4.
---
- github.com repo: n/a
- godoc.org: n/a
- coverage service link: n/a
Very good coverage: n/a

add vscode-go

---

README.md

I've placed this package in the `Video` category since it allow manipulating subtitles in GO. However if you think there's a better category for it, I'd be happy to move it.
---
- github.com repo: https://github.com/asticode/go-astisub
- godoc.org: https://godoc.org/github.com/asticode/go-astisub
- goreportcard.com: http://goreportcard.com/report/github.com/asticode/go-astisub
- coverage service link: https://cover.run/go/github.com/asticode/go-astisub …

add astisub

---

README.md

- github.com repo: https://github.com/asticode/go-astitodo
- godoc.org: https://godoc.org/github.com/asticode/go-astitodo
- goreportcard.com: http://goreportcard.com/report/github.com/asticode/go-astitodo
- coverage service link: https://cover.run/go/github.com/asticode/go-astitodo

Add astitodo

---

README.md

- github.com repo: https://github.com/fterrag/goxlsxwriter
- godoc.org: http://godoc.org/github.com/fterrag/goxlsxwriter
- goreportcard.com: https://goreportcard.com/report/github.com/fterrag/goxlsxwriter
- coverage service link: https://coveralls.io/github/fterrag/goxlsxwriter

Add goxlsxwriter

---

README.md

- github.com repo: https://github.com/artonge/go-gtfs
- godoc.org: https://godoc.org/github.com/artonge/go-gtfs
- goreportcard.com: https://goreportcard.com/report/github.com/artonge/go-gtfs
- coverage service link: https://cover.run/go/github.com/artonge/go-gtfs

Add github.com/artonge/go-gtfs

---

README.md

- github.com repo: https://github.com/json-iterator/go
- godoc.org: http://godoc.org/github.com/json-iterator/go
- goreportcard.com: https://goreportcard.com/report/github.com/json-iterator/go
- coverage service link: [![codecov](https://codecov.io/gh/json-iterator/go/branch/master/graph/badge.svg)](https://codecov.io/gh/json-iterator/go)

add jsoniter, A high-performance 100% compatible drop-in replacement of "encoding/json"

---

README.md

Links:
- github.com repo: [https://github.com/Jeffail/leaps](https://github.com/Jeffail/leaps)
- godoc.org: [![godoc for jeffail/leaps](https://godoc.org/github.com/jeffail/leaps?status.svg)](http://godoc.org/github.com/jeffail/leaps)
- goreportcard.com: [![goreportcard for jeffail/leaps](https://goreportcard.com/badge/github.com/jeffail/leaps)](https://goreportcard.com/report/jeffail/leaps)
- coverage service links:
- [![cover.run for jeffail/leaps/lib/binder](https://cover.run/go/github.com/jeffail/leaps/lib/binder.svg)](https://cover.run/go/github.com/jeffail/leaps/lib/binder)
- [![cover.run for jeffail/leaps/lib/curator](https://cover.run/go/github.com/jeffail/leaps/lib/curator.svg)](https://cover.run/go/github.com/jeffail/leaps/lib/curator)
- [![cover.run for …

Add github.com/jeffail/leaps

---

README.md

- github.com repo: https://github.com/gojuno/go-zooz
- godoc.org: http://godoc.org/github.com/gojuno/go-zooz
- goreportcard.com: https://goreportcard.com/report/github.com/gojuno/go-zooz
- coverage service link [gocover](http://gocover.io/): https://gocover.io/github.com/gojuno/go-zooz

Add Go client for the Zooz API

---

README.md

- github.com repo: https://github.com/go-aah/aah
- godoc.org: https://godoc.org/aahframework.org/aah.v0
- goreportcard.com: https://goreportcard.com/report/aahframework.org/aah.v0
- coverage service link: [![codecov](https://codecov.io/gh/go-aah/aah/branch/master/graph/badge.svg)](https://codecov.io/gh/go-aah/aah/branch/master)

Adding aah web framework under Web Framework section

---

README.md

- github.com repo: https://github.com/moby/moby
- godoc.org: https://godoc.org/github.com/moby/moby
- goreportcard.com: https://goreportcard.com/report/github.com/moby/moby …

Added moby project

---

README.md

Add to Websites section
- godoc.org:

Add Golangflow.io

---

README.md

Added Golangflow to Twitter section

---

README.md

Change pRest section from "database made by go"  to  "database tools"

pRest is not a database, but a tool

---

README.md

- github.com repo: <https://github.com/osteele/liquid>
- godoc.org: <https://godoc.org/github.com/osteele/liquid>
- goreportcard.com: <https://goreportcard.com/report/github.com/osteele/liquid> – note that `expressions/scanner.go` and `expressions/y.go` are generated by [Ragel](https://en.wikipedia.org/wiki/Ragel) and [goyacc](https://godoc.org/golang.org/x/tools/cmd/goyacc), respectively. Fixing golint errors in those files would require updates to those tools, not the source files in this repo. …

Add github.com/osteele/liquid to Template Engines

---

README.md

- github.com repo: https://github.com/osamingo/shamoji
- godoc.org: https://godoc.org/github.com/osamingo/shamoji
- goreportcard.com: https://goreportcard.com/report/github.com/osamingo/shamoji
- coverage service link: https://codecov.io/gh/osamingo/shamoji

Add osamingo/shamoji library

---

README.md

- github.com repo: https://github.com/utahta/go-cronowriter
- godoc.org: http://godoc.org/github.com/utahta/go-cronowriter
- goreportcard.com: https://goreportcard.com/report/github.com/utahta/go-cronowriter
- coverage service link: https://codecov.io/gh/utahta/go-cronowriter

Add github.com/utahta/go-cronowriter

---

README.md

Add `workanator/go-floc` package in **Goroutines** Category
- github.com repo: https://github.com/workanator/go-floc
- godoc.org: https://godoc.org/gopkg.in/workanator/go-floc.v1
- goreportcard.com: https://goreportcard.com/report/github.com/workanator/go-floc
- coverage service link: https://coveralls.io/github/workanator/go-floc

Add go-floc

---

README.md

- github.com repo: https://github.com/dixonwille/skywalker
- godoc.org: [![GoDoc](https://godoc.org/github.com/dixonwille/skywalker?status.svg)](https://godoc.org/github.com/dixonwille/skywalker)
- goreportcard.com: [![Go Report Card](https://goreportcard.com/badge/github.com/dixonwille/skywalker)](https://goreportcard.com/report/github.com/dixonwille/skywalker)
- coverage service link: [![codecov](https://codecov.io/gh/dixonwille/skywalker/branch/master/graph/badge.svg)](https://codecov.io/gh/dixonwille/skywalker)
**Note**: that …

Adding skywalker to the list

---

README.md

- github.com repo: https://github.com/linxGnu/mssqlx
- godoc.org: https://godoc.org/github.com/linxGnu/mssqlx
- goreportcard.com: https://goreportcard.com/report/github.com/linxGnu/mssqlx
- coverage service link: https://gocover.io/github.com/linxGnu/mssqlx

Adding mssqlx (production library at iparking.vn)

---

README.md

- github.com repo: https://github.com/OpenPeeDeeP/xdg
- godoc.org: [![GoDoc](https://godoc.org/github.com/OpenPeeDeeP/xdg?status.svg)](https://godoc.org/github.com/OpenPeeDeeP/xdg)
- goreportcard.com: [![Go Report Card](https://goreportcard.com/badge/github.com/OpenPeeDeeP/xdg)](https://goreportcard.com/report/github.com/OpenPeeDeeP/xdg)
- coverage service link: [![codecov](https://codecov.io/gh/OpenPeeDeeP/xdg/branch/master/graph/badge.svg)](https://codecov.io/gh/OpenPeeDeeP/xdg) …

Add OpenPeeDeeP/xdg package to the list

---

README.md

* [repo](https://github.com/Shixzie/nlp)
* [![GoDoc](https://godoc.org/github.com/Shixzie/nlp?status.svg)](https://godoc.org/github.com/Shixzie/nlp) 
* [![Go Report Card](https://goreportcard.com/badge/github.com/Shixzie/nlp)](https://goreportcard.com/report/github.com/Shixzie/nlp)
* [![Build Status](https://travis-ci.org/Shixzie/nlp.svg?branch=master)](https://travis-ci.org/Shixzie/nlp) [![codecov](https://codecov.io/gh/Shixzie/nlp/branch/master/graph/badge.svg)](https://codecov.io/gh/Shixzie/nlp)

Add Shixzie/nlp to Natural Language Processing

---

README.md

- github.com repo: https://github.com/linxGnu/goseaweedfs
- godoc.org: https://godoc.org/github.com/linxGnu/goseaweedfs
- goreportcard.com: https://goreportcard.com/report/github.com/linxGnu/goseaweedfs
- coverage service link: https://coveralls.io/github/linxGnu/goseaweedfs?branch=master

Add goseaweedfs (a SeaweedFS client)

---

README.md

- github.com repo: https://github.com/linxGnu/goseaweedfs
- godoc.org: https://godoc.org/github.com/linxGnu/goseaweedfs
- goreportcard.com: https://goreportcard.com/report/github.com/linxGnu/goseaweedfs
- coverage service link: https://coveralls.io/github/linxGnu/goseaweedfs?branch=master

Update goseaweedfs url

---

README.md

Signed-off-by: Kirill Danshin <k@guava.by>
- github.com repo: [link](https://github.com/kirillDanshin/avgRating)
- godoc.org: [link](https://godoc.org/github.com/kirillDanshin/avgRating)
- goreportcard.com: [link](https://goreportcard.com/report/github.com/kirillDanshin/avgRating)
- coverage service: [link 1](https://gocover.io/github.com/kirillDanshin/avgRating) [link 2](https://cover.run/go/github.com/kirillDanshin/avgRating) ![cover.run go](https://cover.run/go/github.com/kirillDanshin/avgRating.svg)
**Note**: that new categories …

add avgRating

---

README.md

To be compliant with [official Awesome guidelines](https://github.com/sindresorhus/awesome/blob/master/pull_request_template.md)
`Drop all the A / An prefixes in the descriptions.`
It looks really messy if some have the prefix and its a waste of a word for the description

Removed A/An prefixes

---

README.md

Updated link to authboss

---

README.md

- github.com repo: https://github.com/mxpv/patreon-go
- godoc.org: [![GoDoc](https://godoc.org/github.com/mxpv/patreon-go?status.svg)](https://godoc.org/github.com/mxpv/patreon-go/)
- goreportcard.com: [![Go Report Card](https://goreportcard.com/badge/github.com/mxpv/patreon-go)](https://goreportcard.com/report/github.com/mxpv/patreon-go)
- coverage service link: [![codecov](https://codecov.io/gh/mxpv/patreon-go/branch/master/graph/badge.svg)](https://codecov.io/gh/mxpv/patreon-go)

Add patreon-go (Patreon API client)

---

README.md

fix error link sawsij

---

README.md

- github.com repo: https://github.com/trivago/gollum
- godoc.org: https://godoc.org/github.com/trivago/gollum
- readthedocs.io: http://gollum.readthedocs.io/en/latest/index.html
- goreportcard.com: https://goreportcard.com/report/github.com/trivago/gollum
- coverage service link: [![Coverage Status](https://coveralls.io/repos/github/trivago/gollum/badge.svg?branch=master)](https://coveralls.io/github/trivago/gollum?branch=master) …

added trivago/gollum to messaging category

---

README.md

- github.com repo: https://github.com/awnumar/memguard
- godoc.org: https://godoc.org/github.com/awnumar/memguard
- goreportcard.com: https://goreportcard.com/report/github.com/awnumar/memguard
- coverage service link: ![cover.run go](https://cover.run/go/github.com/awnumar/memguard.svg)

Add memguard.

---

README.md

- github.com repo: [github.com/bradleyjkemp/cupaloy](https://github.com/bradleyjkemp/cupaloy)
- godoc.org: [![GoDoc](https://godoc.org/github.com/bradleyjkemp/cupaloy?status.svg)](https://godoc.org/github.com/bradleyjkemp/cupaloy)
- goreportcard.com: [![Go Report Card](https://goreportcard.com/badge/github.com/bradleyjkemp/cupaloy)](https://goreportcard.com/report/github.com/bradleyjkemp/cupaloy)
- coverage service link: [![Coverage Status](https://coveralls.io/repos/github/bradleyjkemp/cupaloy/badge.svg)](https://coveralls.io/github/bradleyjkemp/cupal …

Add package: cupaloy

---

README.md

- github.com repo: https://github.com/agoalofalife/event
- godoc.org: http://godoc.org/github.com/agoalofalife/event
- goreportcard.com:https://goreportcard.com/report/github.com/agoalofalife/event
- coverage service link [![codecov](https://codecov.io/gh/agoalofalife/event/branch/master/graph/badge.svg)](https://codecov.io/gh/agoalofalife/event)

Add package

---

README.md

- github.com repo: https://www.github.com/oakmound/oak
- godoc.org: https://godoc.org/github.com/oakmound/oak
- goreportcard.com: https://goreportcard.com/report/github.com/oakmound/oak
- coverage service link: https://codecov.io/gh/oakmound/oak/branch/develop
Packages relating to drawing graphics and playing audio are not currently tested through travis CI / codecov, as the machines running said tests have no graphical / audio devices. These packages (the main package, oak, and oak/audio), have ~70% and ~100% code coverage respectively. 

Add package: oak

---

.github/PULL_REQUEST_TEMPLATE.md
CONTRIBUTING.md
README.md

To keep things more consistent and have all items end with periods instead of every other third one not having one. Keeps things a little more professional looking and keeping the Awesome standard high

Added periods to all missing lines

---

README.md

- github.com repo: https://github.com/osteele/tuesday
- godoc.org: https://godoc.org/github.com/osteele/tuesday
- goreportcard.com: https://goreportcard.com/report/github.com/osteele/tuesday
- coverage service link: https://coveralls.io/github/osteele/tuesday/

Add osteele/tuesday

---

README.md

remove hsync

---

README.md

- github.com repo:   https://github.com/araddon/dateparse
- godoc.org:  http://godoc.org/github.com/araddon/dateparse
- goreportcard.com: https://goreportcard.com/report/github.com/araddon/dateparse
- coverage: https://codecov.io/gh/araddon/dateparse

Add dateparse pkg

---

README.md

- github.com repo: https://github.com/PaulRosset/go-hacknews
- godoc.org: http://godoc.org/github.com/PaulRosset/go-hacknews
- goreportcard.com: https://goreportcard.com/report/github.com/PaulRosset/go-hacknews
- coverage service link: ![cover.run go](https://cover.run/go/github.com/PaulRosset/go-hacknews.svg)

Go hacknews

---

README.md

- github.com repo: https://github.com/hscells/doi
- godoc.org: https://godoc.org/github.com/hscells/doi
- goreportcard.com: https://goreportcard.com/report/github.com/hscells/doi
- coverage service link ([cover.run](https://cover.run/), [gocover](http://gocover.io/), [coveralls](https://coveralls.io/) etc.), example: `![cover.run go](https://cover.run/go/github.com/user/repository.svg)`: https://gocover.io/github.com/hscells/doi …

Add doi link.

---

README.md

- github.com repo: https://github.com/xiaonanln/goworld
- godoc.org: [![GoDoc](https://godoc.org/github.com/xiaonanln/goworld?status.png)](https://godoc.org/github.com/xiaonanln/goworld)
- goreportcard.com:[![Go Report Card](https://goreportcard.com/badge/github.com/xiaonanln/goworld)](https://goreportcard.com/report/github.com/xiaonanln/goworld)
- coverage service link: the server is not quite coverage-testable since it requires the coordinations of multiple components of server and clients, sorry. 
**Note**: that new categories …

add goworld - another game server engine

---

README.md

- github.com repo: https://github.com/abice/go-enum
- godoc.org: [![GoDoc](https://godoc.org/github.com/abice/go-enum?status.svg)](https://godoc.org/github.com/abice/go-enum)
- goreportcard.com: [![Go Report Card](https://goreportcard.com/badge/github.com/abice/go-enum)](https://goreportcard.com/report/github.com/abice/go-enum)
- coverage service link: [![Coverage Status](https://coveralls.io/repos/github/abice/go-enum/badge.svg)](https://coveralls.io/github/abice/go-enum)
**Note**: that new categories can be added only when there …

Added go-enum

---

README.md

- github.com repo:  https://github.com/codingconcepts/env
- godoc.org:  https://godoc.org/github.com/codingconcepts/env
- goreportcard.com:  https://goreportcard.com/report/github.com/codingconcepts/env
- coverage service link [gocover](https://gocover.io/github.com/codingconcepts/env)

Added 'env' struct configuration CLI library

---

README.md

- github.com repo: https://github.com/wargarblgarbl/libgosubs
- godoc.org: https://godoc.org/github.com/wargarblgarbl/libgosubs/ass https://godoc.org/github.com/wargarblgarbl/libgosubs/srt https://godoc.org/github.com/wargarblgarbl/libgosubs/ttml
- goreportcard.com: [![Go Report Card](https://goreportcard.com/badge/github.com/wargarblgarbl/libgosubs)](https://goreportcard.com/report/github.com/wargarblgarbl/libgosubs)
- coverage service links
**Make …

Add libgosubs

---

README.md

- github.com repo: https://github.com/digota/digota
- godoc.org: http://godoc.org/github.com/digota/digota?imports
- goreportcard.com: https://goreportcard.com/report/github.com/digota/digota
- coverage service link: https://coveralls.io/github/digota/digota
- [*] I …

Add digota

---

README.md

- github.com repo: https://github.com/gulien/orbit
- godoc.org: https://godoc.org/github.com/gulien/orbit
- goreportcard.com: https://goreportcard.com/report/github.com/gulien/orbit
- coverage service link: https://codecov.io/gh/gulien/orbit

Adding Orbit

---

README.md

github.com repo: https://github.com/lunny/gop
godoc.org: https://godoc.org/github.com/lunny/gop
goreportcard.com: https://goreportcard.com/report/github.com/lunny/gop
coverage service link (codecov): https://codecov.io/gh/lunny/gop

Add gop - Build and manage your Go applications out of GOPATH

---

README.md
repo_test.go

Fix all links failed the test.

Add test to find out malformed separators.

---

README.md

_nlp_
- github.com repo: https://github.com/james-bowman/nlp
- godoc.org: [![GoDoc](https://godoc.org/github.com/james-bowman/nlp?status.svg)](https://godoc.org/github.com/james-bowman/nlp)
- goreportcard.com: [![Go Report Card](https://goreportcard.com/badge/github.com/james-bowman/nlp)](https://goreportcard.com/report/github.com/james-bowman/nlp) 
- coverage service link ([cover.run](https://cover.run/), [gocover](http://gocover.io/), [coveralls](https://coveralls.io/) etc.), example: `![cover.run …

Added nlp and sparse libraries

---

README.md

github.com: https://github.com/awalterschulze/goderive
godoc.org: https://godoc.org/github.com/awalterschulze/goderive
goreportcard.com: https://goreportcard.com/report/github.com/awalterschulze/goderive
coverage service link: https://cover.run/go/github.com/awalterschulze/goderive/test/normal
- github.com repo: https://github.com/awalterschulze/goderive
- godoc.org: https://godoc.org/github.com/awalterschulze/goderive
- goreportcard.com: https://goreportcard.com/report/github.com/awalterschulze/goderive
- coverage service link …

add goderive

---

README.md

Update repo URL for excelize and aurora lib:
- github.com repo: [github.com/xuri/aurora](https://github.com/xuri/aurora)
- godoc.org: [godoc.org/github.com/xuri/aurora](https://godoc.org/github.com/xuri/aurora)
- goreportcard.com: [goreportcard.com/report/github.com/xuri/aurora](https://goreportcard.com/report/github.com/xuri/aurora)
- coverage service link (gocover, coveralls etc.): [codecov.io/gh/xuri/aurora](https://codecov.io/gh/xuri/aurora)
- github.com repo: [https://github.com/360EntSecGroup-Skylar/excelize](https://github.com/360EntSecGroup-Skylar/excelize)
- godoc.org: [https://godoc.org/github.com/360EntSecGroup-Skylar/excelize](https://godoc.org/github.com/360EntSecGroup-Skylar/excelize)
- goreportcard.com: [https://goreportcard.com/report/github.com/360EntSecGroup-Skylar/exceli …

Update repo URL for excelize and aurora lib.

---

README.md

Hello, I wanted to add my logging library to your list.
- github.com repo: https://github.com/mbndr/logo
- godoc.org: https://godoc.org/github.com/mbndr/logo
- goreportcard.com: https://goreportcard.com/report/github.com/mbndr/logo
- ![cover.run go](https://cover.run/go/github.com/mbndr/logo.svg)
- [![Coverage](https://gocover.io/_badge/github.com/mbndr/logo)](https://gocover.io/github.com/mbndr/logo)

Add mbndr/logo

---

README.md

- github.com repo: https://github.com/yl2chen/cidranger
- godoc.org: [![GoDoc Reference](https://img.shields.io/badge/godoc-reference-5272B4.svg?style=flat-square)](https://godoc.org/github.com/yl2chen/cidranger)
- goreportcard.com: [![Go Report Card](https://goreportcard.com/badge/github.com/yl2chen/cidranger?&style=flat-square)](https://goreportcard.com/report/github.com/yl2chen/cidranger)
- coverage service link: [![Coverage Status](https://img.shields.io/coveralls/yl2chen/cidranger.svg?branch=master&style=flat-square)](https://coveralls.io/github/y …

Add cidranger

---

README.md

- github.com repo: https://github.com/jirfag/go-queryset
- godoc.org: https://godoc.org/github.com/jirfag/go-queryset
- goreportcard.com: https://goreportcard.com/report/github.com/jirfag/go-queryset
- coverage service link: https://coveralls.io/github/jirfag/go-queryset?branch=master

add go-queryset

---

README.md

- github.com repo: [github.com/dgraph-io/badger](https://github.com/dgraph-io/badger)
- godoc.org: [godoc.org/github.com/dgraph-io/badger](https://godoc.org/github.com/dgraph-io/badger)
- goreportcard.com: [goreportcard.com/report/github.com/dgraph-io/badger](https://goreportcard.com/report/github.com/dgraph-io/badger)
- coveralls.io: [coveralls.io/github/dgraph-io/badger](https://coveralls.io/github/dgraph-io/badger?branch=master) …

Add dgraph-io/badger

---

README.md

- github.com repo: https://github.com/onrik/ethrpc
- godoc.org: https://godoc.org/github.com/onrik/ethrpc
- goreportcard.com: [![Go Report Card](https://goreportcard.com/badge/github.com/onrik/ethrpc)](https://goreportcard.com/report/github.com/onrik/ethrpc)
- coverage service link: [![Coverage Status](https://coveralls.io/repos/github/onrik/ethrpc/badge.svg?branch=master)](https://coveralls.io/github/onrik/ethrpc?branch=master) …

Add ethrpc

---

README.md

- github.com repo: https://github.com/inancgumus/myhttp
- godoc.org: https://godoc.org/github.com/inancgumus/myhttp
- goreportcard.com: https://goreportcard.com/report/github.com/inancgumus/myhttp
- coverage service link: https://coveralls.io/github/inancgumus/myhttp?branch=master

add myhttp

---

README.md

- github.com repo: https://github.com/asafschers/goscore
- godoc.org: https://godoc.org/github.com/asafschers/goscore
- goreportcard.com: https://goreportcard.com/report/github.com/asafschers/goscore
- coverage service link: https://coveralls.io/github/asafschers/goscore?branch=master

Added link to goscore

---

README.md

- github.com repo: https://github.com/linxGnu/mssqlx
- godoc.org: https://godoc.org/github.com/linxGnu/mssqlx
- goreportcard.com: https://goreportcard.com/report/github.com/linxGnu/mssqlx
- coverage service link: https://coveralls.io/github/linxGnu/mssqlx

Update intro to closet meaning for github.com/linxGnu/mssqlx

---

README.md

- github.com repo: https://github.com/themester/GoSlaves
- godoc.org: https://godoc.org/github.com/themester/GoSlaves
- goreportcard.com: https://goreportcard.com/report/github.com/themester/goslaves
- coverage service link ([cover.run](https://cover.run/), [gocover](http://gocover.io/), [coveralls](https://coveralls.io/) etc.), example: `![cover.run go](https://cover.run/go/github.com/user/repository.svg)` ![cover.run go](https://cover.run/go/github.com/themester/GoSlaves.svg) …

Added GoSlaves in Goroutines

---

README.md

- github.com repo: https://github.com/alin-sinpalean/concurrent-writer
- godoc.org: https://godoc.org/github.com/alin-sinpalean/concurrent-writer/concurrent
- goreportcard.com: https://goreportcard.com/report/github.com/alin-sinpalean/concurrent-writer
- coverage service link: https://gocover.io/github.com/alin-sinpalean/concurrent-writer/concurrent

Add concurrent-writer to Data Structures.

---

README.md

- github.com repo: https://github.com/chmike/securecookie
- godoc.org: https://godoc.org/github.com/chmike/securecookie
- goreportcard.com:  https://goreportcard.com/report/github.com/chmike/securecookie
- coverage service link:  https://coveralls.io/github/chmike/securecookie?branch=master

Add securecookie to the Authentication section

---

README.md

- github.com repo: https://github.com/amallia/go-ef
- godoc.org: https://godoc.org/github.com/amallia/go-ef
- goreportcard.com: https://goreportcard.com/report/github.com/amallia/go-ef

Added go-ef

---

README.md

- github.com repo: https://github.com/rickb777/date
- godoc.org: https://godoc.org/github.com/rickb777/date
- goreportcard.com: https://goreportcard.com/report/github.com/rickb777/date
- coverage service link: https://coveralls.io/github/rickb777/date?branch=master
- …

Added link to rickb777/date

---

README.md

| github | godoc | code coverage | report card |
| :--- | :--- | :--- | :--- |
| [github] | [godoc] | [coverage] | [report card] |
*PR Guidelines*
[github]: https://github.com/dadleyy/marlow
[godoc]: https://godoc.org/github.com/dadleyy/marlow/marlow
[coverage]: https://codecov.io/gh/dadleyy/marlow
[report card]: https://goreportcard.com/report/github.com/dadleyy/marlow

Adding marlow - typesafe orm interfaces generated at compile time

---

README.md

- github.com repo: https://github.com/sergioaugrod/go-sptrans
- godoc.org: [![GoDoc](https://godoc.org/github.com/sergioaugrod/go-sptrans?status.png)](https://godoc.org/github.com/sergioaugrod/go-sptrans)
- goreportcard.com: [![Go Report Card](https://goreportcard.com/badge/github.com/sergioaugrod/go-sptrans)](https://goreportcard.com/report/github.com/sergioaugrod/go-sptrans)
- coverage service link: [![codecov](https://codecov.io/gh/sergioaugrod/go-sptrans/branch/master/graph/badge.svg)](https://codecov.io/gh/sergioaugrod/go-sptrans)
Very good …

Add go-sptrans

---

README.md

- github.com repo: https://github.com/hackebrot/turtle
- godoc.org: https://godoc.org/github.com/hackebrot/turtle
- goreportcard.com: https://goreportcard.com/report/github.com/hackebrot/turtle
- coverage service link ([cover.run](https://cover.run/), [gocover](http://gocover.io/), [coveralls](https://coveralls.io/) etc.), example: `![cover.run go](https://cover.run/go/github.com/user/repository.svg)`  ![cover.run go](https://cover.run/go/github.com/hackebrot/turtle.svg)
**Note**: that new categories can be added only when there are …

Add turtle

---

README.md

- github.com repo: https://github.com/zserge/webview
- godoc.org: https://godoc.org/github.com/zserge/webview
- goreportcard.com: https://goreportcard.com/report/github.com/zserge/webview
- coverage is not applicable, because the library is Cgo bindings to the single-header library, and as a black-box GUI library I don't think it can be unit-tested easily.

Add webview library

---

README.md

- github.com repo: https://github.com/steambap/captcha
- godoc.org: https://godoc.org/github.com/steambap/captcha
- goreportcard.com: https://goreportcard.com/report/github.com/steambap/captcha …

Add captcha

---

README.md

add thestrukture/IDE

---

README.md

- github.com repo: https://github.com/vardius/worker-pool
- godoc.org: [![](https://godoc.org/github.com/vardius/worker-pool?status.svg)](http://godoc.org/github.com/vardius/worker-pool)
- goreportcard.com: [![Go Report Card](https://goreportcard.com/badge/github.com/vardius/worker-pool)](https://goreportcard.com/report/github.com/vardius/worker-pool)
- coverage: [![codecov](https://codecov.io/gh/vardius/worker-pool/branch/master/graph/badge.svg)](https://codecov.io/gh/vardius/worker-pool)
- github.com repo: https://github.com/vardius/message-bus
- godoc.org: [![](https://godoc.org/github.com/vardius/message-bus?status.svg)](http://godoc.org/github.com/vardius/message-bus)
- goreportcard.com: [![Go Report Card](https://goreportcard.com/badge/github.com/vardius/message-bus)](https://gorepor …

Add workerpool and messagebus package

---

README.md

[![Go Report Card](https://goreportcard.com/badge/github.com/Wing924/shellwords)](https://goreportcard.com/report/github.com/Wing924/shellwords)
[![codecov](https://codecov.io/gh/Wing924/shellwords/branch/master/graph/badge.svg)](https://codecov.io/gh/Wing924/shellwords)
[![GoDoc](https://godoc.org/github.com/Wing924/shellwords?status.svg)](https://godoc.org/github.com/Wing924/shellwords)
A Golang library to manipulate strings according to the word parsing rules of the UNIX Bourne shell.
[![Go Report Card](https://goreportcard.com/badge/github.com/Wing924/hostutils)](https://goreportcard.com/report/github.com/Wing924/hostutils)
[![codecov](https://codecov.io/gh/Wing924/hostutils/branch/master/graph/badge.svg)](https://codecov.io/gh/Wing924/hostutils) …

add shellwords and hostutils

---

README.md

Add go-cluster under Machine Learning.
> Please check if what you want to add to `awesome-go` list meets [quality standards](https://github.com/avelino/awesome-go/blob/master/CONTRIBUTING.md#quality-standard) before sending pull request. Thanks!
- github.com repo: https://github.com/e-XpertSolutions/go-cluster
- godoc.org: https://godoc.org/github.com/e-XpertSolutions/go-cluster/cluster
- goreportcard.com: https://goreportcard.com/report/github.com/e-XpertSolutions/go-cluster
- coverage service link ([cover.run](https://cover.run/), [gocover](http://gocover.io/), [coveralls](https://coveralls.io/) etc.), example: `![cover.run go](https://cover.run/go/github.com/user/repository.svg)`: https://cover.run/go/github.com/e-XpertSolutions/go-cluster/cluster …

Add go-cluster

---

README.md

- github.com repo: https://github.com/striker2000/petrovich
- godoc.org: https://godoc.org/github.com/striker2000/petrovich
- goreportcard.com: https://goreportcard.com/report/github.com/striker2000/petrovich
- coverage service link: https://cover.run/go/github.com/striker2000/petrovich

Add petrovich

---

README.md

https://github.com/usk81/generic
https://github.com/cheekybits/genny
https://github.com/cweill/gotests
https://github.com/bouk/gonerics
https://github.com/opennota/re2dfa
- godoc.org:
https://godoc.org/github.com/usk81/generic
https://godoc.org/github.com/cheekybits/genny
https://godoc.org/github.com/cweill/gotests
https://godoc.org/github.com/bouk/gonerics
https://godoc.org/github.com/opennota/re2dfa
https://goreportcard.com/report/github.com/usk81/generic …

Add "Go Generate Tools"

---

README.md

- github.com repo: https://github.com/o1egl/govatar
- godoc.org: [![GoDoc](https://godoc.org/github.com/o1egl/govatar?status.svg)](https://godoc.org/github.com/o1egl/govatar)
- goreportcard.com: [![Go Report Card](https://goreportcard.com/badge/github.com/o1egl/govatar)](https://goreportcard.com/report/github.com/o1egl/govatar)
- coverage service link: [![coveralls](http://img.shields.io/coveralls/o1egl/govatar.svg?style=flat-square)](https://coveralls.io/r/o1egl/govatar)

Add govatar library

---

README.md

- github.com repo: https://github.com/cpmech/gosl
- godoc.org: https://godoc.org/github.com/cpmech/gosl
- goreportcard.com: https://goreportcard.com/report/github.com/cpmech/gosl
- coverage service link: https://cover.run/go/github.com/cpmech/gosl/chk
**Thank you.**

Add gosl (Go Scientific Library)

---

README.md

Add workerpool utility.
- github.com repo: https://github.com/gammazero/workerpool
- godoc.org: [![GoDoc](https://godoc.org/github.com/gammazero/workerpool?status.svg)](https://godoc.org/github.com/gammazero/workerpool)
- goreportcard.com: [![Go Report Card](https://goreportcard.com/badge/github.com/gammazero/workerpool)](https://goreportcard.com/report/github.com/gammazero/workerpool)
- coverage service link: [![codecov](https://codecov.io/gh/gammazero/workerpool/branch/master/graph/badge.svg)](https://codecov.io/gh/gammazero/workerpool)
Very good …

Add workerpool utility

---

README.md

- github.com repo: https://github.com/mengzhuo/cookiestxt
- godoc.org: https://godoc.org/github.com/mengzhuo/cookiestxt
- goreportcard.com: https://goreportcard.com/report/github.com/mengzhuo/cookiestxt
- coverage service link https://cover.run/go/github.com/mengzhuo/cookiestxt

add cookiestxt

---

README.md

1.Godoc: https://godoc.org/github.com/thedevsaddam/govalidator
2.Goreport: https://goreportcard.com/report/github.com/thedevsaddam/govalidator
3.Go coverage: https://cover.run/go/github.com/thedevsaddam/govalidator
- godoc.org:
**Note**: that new categories can be added only when there …

Add govalidator package

---

README.md

https://godoc.org/github.com/f0rmiga/sessiongate-go
[![Build Status](https://travis-ci.org/f0rmiga/sessiongate-go.svg?branch=master)](http://travis-ci.org/f0rmiga/sessiongate-go)
[![Coverage Status](https://coveralls.io/repos/github/f0rmiga/sessiongate-go/badge.svg?branch=master)](https://coveralls.io/github/f0rmiga/sessiongate-go?branch=master)
[![Go Report Card](https://goreportcard.com/badge/github.com/f0rmiga/sessiongate-go)](https://goreportcard.com/report/github.com/f0rmiga/sessiongate-go)

Added the sessiongate-go package

---

README.md

- github.com repo: https://github.com/PumpkinSeed/structs
- godoc.org: https://godoc.org/github.com/PumpkinSeed/structs
- goreportcard.com: https://goreportcard.com/report/github.com/PumpkinSeed/structs
- coverage service link ([cover.run](https://cover.run/go/github.com/PumpkinSeed/structs), [gocover](https://gocover.io/github.com/PumpkinSeed/structs))

Add github.com/PumpkinSeed/structs

---

README.md

- github.com repo: https://github.com/dwin/goSecretBoxPassword
- godoc.org: https://godoc.org/github.com/dwin/goSecretBoxPassword
- goreportcard.com:  https://goreportcard.com/report/github.com/dwin/goSecretBoxPassword
- coverage service link: https://cover.run/go/github.com/dwin/goSecretBoxPassword

Added dwin/GoSecretBoxPassword

---

README.md

Add richgo plz.
- github.com repo: https://github.com/kyoh86/richgo
- godoc.org: https://godoc.org/github.com/kyoh86/richgo
- goreportcard.com: https://goreportcard.com/report/github.com/kyoh86/richgo
- coverage service link: [![Coverage Status](https://coveralls.io/repos/github/kyoh86/richgo/badge.svg?branch=HEAD)](https://coveralls.io/github/kyoh86/richgo?branch=HEAD)

Add richgo

---

tmpl/tmpl.html

Update tmpl.html with Open Graph data for better sharing.

---

README.md

- github.com repo: https://github.com/verygoodsoftwarenotvirus/tarp
- godoc.org: [![GoDoc](https://godoc.org/github.com/verygoodsoftwarenotvirus/tarp?status.svg)](https://godoc.org/github.com/verygoodsoftwarenotvirus/tarp)
- goreportcard.com: [![Go Report Card](https://goreportcard.com/badge/github.com/verygoodsoftwarenotvirus/tarp)](https://goreportcard.com/report/github.com/verygoodsoftwarenotvirus/tarp)
- coverage service link: [![Coverage Status](https://coveralls.io/repos/github/verygoodsoftwarenotvirus/tarp/badge.svg?branch=master)](https://coveralls.io/github/verygoodsoftwarenotvirus/tarp?branch=master)

Add tarp code analysis tool

---

README.md

Add Meetup List

---

README.md

- github.com repo: https://github.com/razonyang/fastrouter
- godoc.org: https://godoc.org/github.com/razonyang/fastrouter
- goreportcard.com: https://goreportcard.com/report/github.com/razonyang/fastrouter
- coverage: [![Coverage Status](https://coveralls.io/repos/github/razonyang/fastrouter/badge.svg?branch=master)](https://coveralls.io/github/razonyang/fastrouter?branch=master)

Add FastRouter

---

README.md

Hi, please add this package: [lk]( https://github.com/hyperboloide/lk)
- github.com repo: [https://github.com/hyperboloide/lk](https://github.com/hyperboloide/lk)
- godoc.org: [![GoDoc](https://godoc.org/github.com/hyperboloide/lk?status.svg)](https://godoc.org/github.com/hyperboloide/lk)
- goreportcard.com: [![Go Report Card](https://goreportcard.com/badge/github.com/hyperboloide/lk)](https://goreportcard.com/report/github.com/hyperboloide/lk)
- coverage service link ([cover.run](https://cover.run/), [gocover](http://gocover.io/), …

add https://github.com/hyperboloide/lk library

---

README.md

- github.com repo: https://github.com/andizzle/rwdb
- godoc.org: https://godoc.org/github.com/andizzle/rwdb
- goreportcard.com: https://goreportcard.com/report/github.com/andizzle/rwdb
- coverage service link [gocover](https://gocover.io/github.com/andizzle/rwdb)

add in rwdb

---

README.md

GO Implementation of Entropy Measures
- github.com repo: https://github.com/kzahedi/goent
- godoc.org: https://godoc.org/github.com/kzahedi/goent
- goreportcard.com: https://goreportcard.com/report/github.com/kzahedi/goent
- coverage service link [coveralls](https://coveralls.io/repos/github/kzahedi/goent/badge.svg?branch=master)
- [x ] I have added my package in alphabetical …

Added goent

---

README.md

- github.com repo: https://github.com/go-ego/riot
- godoc.org: https://godoc.org/github.com/go-ego/riot
- goreportcard.com: https://goreportcard.com/report/github.com/go-ego/riot
- coverage service link ([cover.run](https://cover.run/), [gocover](http://gocover.io/), [coveralls](https://coveralls.io/) etc.), example: https://gocover.io/github.com/go-ego/riot/engine …

add riot search

---

README.md

Hi, it's honor for me to send this pull-request
- github.com repo: https://github.com/otiai10/gosseract
- godoc.org: https://godoc.org/github.com/otiai10/gosseract
- goreportcard.com: https://goreportcard.com/report/github.com/otiai10/gosseract
- coverage service link: https://codecov.io/gh/otiai10/gosseract
Thanks

Add gosseract

---

README.md

Add golang response (JSON, JSONP, XML, YAML, HTML, File) rendering package
- github.com repo: https://github.com/thedevsaddam/renderer
- godoc.org: https://godoc.org/github.com/thedevsaddam/renderer
- goreportcard.com: https://goreportcard.com/report/github.com/thedevsaddam/renderer
- coverage service link ([cover.run](https://cover.run/), [gocover](http://gocover.io/), [coveralls](https://coveralls.io/) etc.), example: `![cover.run go](https://cover.run/go/github.com/user/repository.svg)` [![Coverage …

Add renderer package

---

README.md

* Adds new packages cli and log.
- https://github.com/teris-io/log ([travis](https://travis-ci.org/teris-io/log) | [codecov](https://codecov.io/github/teris-io/log?branch=master) | [goreportcard](http://goreportcard.com/report/teris-io/log) | [godoc](https://godoc.org/github.com/teris-io/log))
- https://github.com/teris-io/cli ([travis](https://travis-ci.org/teris-io/cli) | [codecov](https://codecov.io/github/teris-io/cli?branch=master) | [goreportcard](http://goreportcard.com/report/teris-io/cli) | [godoc](https://godoc.org/github.com/teris-io/cli))
* Drops go-longpoll as defunct, repo removed.
* Drops slf and slog (providing above log as the replacement) as defunct, repos removed.
* Migrates ventu-io/go-shortid to teris-io/shortid.
The committer is the author of all the packages, of the …

Adds 2 new packages, drops 3 old ones, migrates 1 to a new location

---

README.md

- github.com repo: https://github.com/Vertamedia/chproxy
- godoc.org: https://godoc.org/github.com/Vertamedia/chproxy
- goreportcard.com: https://goreportcard.com/report/github.com/Vertamedia/chproxy
- coverage service link ([cover.run](https://cover.run/), [gocover](http://gocover.io/), [coveralls](https://coveralls.io/) etc.): https://gocover.io/github.com/Vertamedia/chproxy?version=1.9
- [ x ] I have added my package in alphabetical order.
- [ x ] I have an appropriate description with correct grammar.
- [ x ] I know that this package was not listed before.
- [ x ] I have added godoc link to the …

Add chproxy

---

README.md

- github.com repo: https://github.com/schollz/progressbar
- godoc.org: https://godoc.org/github.com/schollz/progressbar
- goreportcard.com: https://goreportcard.com/report/github.com/schollz/progressbar
- coverage service link: https://gocover.io/github.com/schollz/progressbar

Add schollz/progressbar

---

README.md

- github.com repo: https://github.com/stackerzzq/xj2go
- godoc.org: https://godoc.org/github.com/stackerzzq/xj2go
- goreportcard.com: https://goreportcard.com/report/github.com/stackerzzq/xj2go
- coverage service link: https://codecov.io/gh/stackerzzq/xj2go

add xj2go pkg

---

README.md

- github.com repo: https://github.com/nullne/evaluator
- godoc.org: https://godoc.org/github.com/nullne/evaluator
- goreportcard.com: https://goreportcard.com/report/github.com/nullne/evaluator
- coverage service link ([cover.run](https://cover.run/), [gocover](http://gocover.io/), [coveralls](https://coveralls.io/) etc.) : [![Coverage Status](https://coveralls.io/repos/github/nullne/evaluator/badge.svg?branch=master)](https://coveralls.io/github/nullne/evaluator?branch=master) …

add repo evaluator which evaluates an expression dynamicly

---

README.md

- github.com repo: https://github.com/etherlabsio/healthcheck
- godoc.org: https://godoc.org/github.com/etherlabsio/healthcheck
- goreportcard.com: https://goreportcard.com/report/github.com/etherlabsio/healthcheck
- coverage service link: https://codecov.io/gh/etherlabsio/healthcheck

Add healthcheck

---

README.md

set awesome-go chat channel

---

README.md

- github.com repo: https://github.com/marcusolsson/tui-go
- godoc.org: https://godoc.org/github.com/marcusolsson/tui-go
- goreportcard.com: https://goreportcard.com/report/github.com/marcusolsson/tui-go
- coverage service link https://gocover.io/github.com/marcusolsson/tui-go

Add 'tui-go' to advanced console UIs

---

README.md

- github.com repo: https://github.com/xwjdsh/manssh
- godoc.org: https://godoc.org/github.com/xwjdsh/manssh
- goreportcard.com: https://goreportcard.com/report/github.com/xwjdsh/manssh
- coverage service link ([cover.run](https://cover.run/), [gocover](http://gocover.io/), [coveralls](https://coveralls.io/) etc.):
https://gocover.io/github.com/xwjdsh/manssh …

add manssh

---

README.md

- github.com repo: https://github.com/gen2brain/malgo
- godoc.org: https://godoc.org/github.com/gen2brain/malgo
- goreportcard.com: https://goreportcard.com/report/github.com/gen2brain/malgo
- coverage service link ([cover.run](https://cover.run/), [gocover](http://gocover.io/), [coveralls](https://coveralls.io/) etc.), example: `![cover.run go](https://cover.run/go/github.com/user/repository.svg)` 
http://gocover.io/github.com/gen2brain/malgo
**Make …

Add malgo (Mini audio library)

---

README.md

- github.com repo: https://github.com/go-ego/gse
- godoc.org: https://godoc.org/github.com/go-ego/gse
- goreportcard.com: https://goreportcard.com/report/github.com/go-ego/gse
- coverage service link ([cover.run](https://cover.run/), [gocover](http://gocover.io/), [coveralls](https://coveralls.io/) etc.), example: https://gocover.io/github.com/go-ego/gse …

add gse text segmentation

---

README.md

- github.com repo: https://github.com/ianlopshire/go-fixedwidth
- godoc.org: [![GoDoc](https://godoc.org/github.com/ianlopshire/go-fixedwidth?status.svg)](http://godoc.org/github.com/ianlopshire/go-fixedwidth)
- goreportcard.com: [![Report card](https://goreportcard.com/badge/github.com/ianlopshire/go-fixedwidth)](https://goreportcard.com/report/github.com/ianlopshire/go-fixedwidth)
- coverage service link: [![Go Cover](http://gocover.io/_badge/github.com/ianlopshire/go-fixedwidth)](http://gocover.io/github.com/ianlopshire/go-fixedwidth)
**Note**: …

Added go-fixedwidth

---

README.md

- github.com repo: https://github.com/lucasgomide/snitch
- godoc.org: http://godoc.org/github.com/lucasgomide/snitch
- goreportcard.com: https://goreportcard.com/report/github.com/lucasgomide/snitch
- coverage service link: https://coveralls.io/github/lucasgomide/snitch?branch=master

Add Snitch to list of other software

---

README.md

- github.com repo: https://github.com/emvicom/gondolier
- godoc.org: https://godoc.org/github.com/emvicom/gondolier
- goreportcard.com: https://goreportcard.com/report/github.com/emvicom/gondolier
- coverage service link: https://circleci.com/gh/emvicom/gondolier (go test -cover . step)
Coverage: 91.8%

Add Gondolier

---

README.md

- correct channel name
- smaller font
- godoc.org:

Fix link to Slack

---

README.md

- github.com repo: https://github.com/akamensky/argparse
- godoc.org: https://godoc.org/github.com/akamensky/argparse
- goreportcard.com: https://goreportcard.com/report/github.com/akamensky/argparse
- coverage service link [gocover](https://gocover.io/github.com/akamensky/argparse)

Add link to argparse

---

README.md

Package csvutil provides high performance, idiomatic encoding and decoding of CSV records to native Go structures
- github.com repo: https://github.com/jszwec/csvutil
- godoc.org: https://godoc.org/github.com/jszwec/csvutil
- goreportcard.com: https://goreportcard.com/report/github.com/jszwec/csvutil
- coverage service link: https://codecov.io/gh/jszwec/csvutil

Add csvutil

---

README.md

- github.com repo: https://github.com/amoghe/distillog
- godoc.org: https://godoc.org/github.com/amoghe/distillog
- goreportcard.com: https://goreportcard.com/report/github.com/amoghe/distillog
- coverage service link: [gocover](https://gocover.io/github.com/amoghe/distillog)
- [x ] I know that this package was not listed before.
- [x ] I have added godoc link to …

Add distillog to 'Logging' section

---

README.md

Better slack badge instead of raw text.

Better slack badge

---

README.md

- [github.com repo](https://github.com/ssgreg/repeat)
- [godoc.org](https://godoc.org/github.com/ssgreg/repeat)
- [goreportcard.com](https://goreportcard.com/report/github.com/ssgreg/repeat)
- [coverage service link](https://gocover.io/github.com/ssgreg/repeat)

Add repeat

---

README.md

- [github.com repo](https://github.com/ssgreg/journald)
- [godoc.org](https://godoc.org/github.com/ssgreg/journald)
- [goreportcard.com](https://goreportcard.com/badge/github.com/ssgreg/journald)
- [coverage service link](https://gocover.io/github.com/ssgreg/journald)

Add journald

---

README.md

Add gopher mascot resources

---

README.md

ref: https://github.com/avelino/awesome-go/pull/1716#issuecomment-349718222

docs(Gophers): add another gopher icon resource.

---

README.md

The library hasn't been updated in 2 years and [Casper](https://clients.casper.io/register.php) has been shut down for legal reasons, so the library no longer works.
- godoc.org: …

Remove github.com/neuegram/ghost

---

README.md

- github.com repo: https://github.com/Xamber/Varis
- godoc.org: https://godoc.org/github.com/Xamber/Varis
- goreportcard.com: https://goreportcard.com/report/github.com/Xamber/Varis
- coverage service link : https://codecov.io/gh/Xamber/Varis

Add github.com/Xamber/Varis

---

README.md

- github.com repo: https://github.com/jaegertracing/jaeger
- godoc.org: https://godoc.org/github.com/jaegertracing/jaeger
- goreportcard.com: https://goreportcard.com/report/github.com/jaegertracing/jaeger
- coverage service link: [coveralls.io](https://coveralls.io/repos/jaegertracing/jaeger/badge.svg?branch=master)

Add Jaeger

---

README.md

Add parallel-fn library
- github.com repo: https://github.com/rafaeljesus/parallel-fn
- godoc.org: https://godoc.org/github.com/rafaeljesus/parallel-fn
- goreportcard.com: https://goreportcard.com/report/github.com/rafaeljesus/parallel-fn
- coverage service link ([gocover](http://gocover.io/)): https://gocover.io/github.com/rafaeljesus/parallel-fn

Add parallel-fn library

---

README.md

Add github.com/marusama/semaphore
- github.com repo: https://github.com/marusama/semaphore
- godoc.org: https://godoc.org/github.com/marusama/semaphore
- goreportcard.com: https://goreportcard.com/report/github.com/marusama/semaphore
- coverage service link ![Coverage Status](https://coveralls.io/repos/github/marusama/semaphore/badge.svg?branch=master)(https://coveralls.io/github/marusama/semaphore?branch=master) …

Add github.com/marusama/semaphore

---

README.md

I have read the following but do not think I need to fill these for this PR. 
- godoc.org:  …

Rename Gogland to GoLand

---

README.md

Added theia-go-extension and go-language-server

---

README.md

- github.com repo: https://github.com/google/periph/
- godoc.org: https://godoc.org/periph.io/x/periph
- goreportcard.com: https://goreportcard.com/report/periph.io/x/periph
- coverage service link [![Coverage Status](https://codecov.io/gh/google/periph/graph/badge.svg)](https://codecov.io/gh/google/periph)

Add periph.io

---

README.md

- github.com repo: https://github.com/huandu/go-sqlbuilder
- godoc.org: https://godoc.org/github.com/huandu/go-sqlbuilder
- goreportcard.com: https://goreportcard.com/report/github.com/huandu/go-sqlbuilder
- coverage service link: https://coveralls.io/github/huandu/go-sqlbuilder?branch=master

add go-sqlbuilder

---

README.md

- github.com repo: [go-health](https://github.com/InVisionApp/go-health)
- godoc.org: [godoc](https://godoc.org/github.com/InVisionApp/go-health)
- goreportcard.com: [goreportcard](https://goreportcard.com/report/github.com/InVisionApp/go-health)
- coverage service link: [codecov](https://codecov.io/gh/InVisionApp/go-health)
Very good coverage: > 90%
- [ X ] I have added my package in alphabetical …

Adding the InVisionApp/go-health async health check lib

---

README.md

Add retry-go library
- github.com repo: https://github.com/rafaeljesus/retry-go
- godoc.org: https://godoc.org/github.com/rafaeljesus/retry-go
- goreportcard.com: https://goreportcard.com/report/github.com/rafaeljesus/retry-go
- coverage service link ([gocover](http://gocover.io/)): https://gocover.io/github.com/rafaeljesus/retry-go

Add retry-go library

---

README.md

- github.com repo: https://github.com/viant/endly
- godoc.org: https://godoc.org/github.com/viant/endly
- goreportcard.com: https://goreportcard.com/report/github.com/viant/endly
- coverage service link https://gocover.io/github.com/viant/endly (80.2%)

added endly declarative end to end testing

---

README.md

Hello,
Prep analyzes the source code in order to find string literals and constants that are passed to the sql.DB.* methods. In other words it finds all *static* SQL queries that are passed to the DB. Then you decorate your DB connection with the prep.NewConnection method which instruments the original connection with the prepared SQL staments for all queries found above. It allows you to squeeze a bit more perfomance out of your db and application, please see benchmark results at the bottom of the repo's README.
https://github.com/hexdigest/prep
https://godoc.org/github.com/hexdigest/prep
https://goreportcard.com/report/github.com/hexdigest/prep
https://coveralls.io/github/hexdigest/prep?branch=master
Hope you find it interesting.
Thank you!

Add github.com/hexdigest/prep

---

README.md

- github.com repo: https://github.com/Henry-Sarabia/igdb
- godoc.org: https://godoc.org/github.com/Henry-Sarabia/igdb
- goreportcard.com: https://goreportcard.com/report/github.com/Henry-Sarabia/igdb
- coverage service link: https://coveralls.io/github/Henry-Sarabia/igdb?branch=master

Add github.com/Henry-Sarabia/igdb

---

README.md

- github.com repo: https://github.com/mojocn/base64Captcha
- godoc.org: https://godoc.org/github.com/mojocn/base64Captcha
- goreportcard.com: https://goreportcard.com/report/github.com/mojocn/base64Captcha  ![Go Report Card](https://goreportcard.com/badge/github.com/mojocn/base64Captcha)
- coverage service link [gocover:90.5%](https://gocover.io/github.com/mojocn/base64Captcha), [![codecov](https://codecov.io/gh/mojocn/base64Captcha/branch/master/graph/badge.svg)](https://codecov.io/gh/mojocn/base64Captcha)

Update README.md add base64captcha

---

README.md

- github.com repo: https://github.com/antham/strumt
- godoc.org: https://godoc.org/github.com/antham/strumt
- goreportcard.com: https://goreportcard.com/report/github.com/antham/strumt
- coverage service link : https://codecov.io/gh/antham/strumt

Add strumt

---

README.md

- github.com repo: https://github.com/o1egl/fwencoder
- godoc.org: https://godoc.org/github.com/o1egl/fwencoder
- goreportcard.com: https://goreportcard.com/report/github.com/o1egl/fwencoder
- coverage service link: https://coveralls.io/github/o1egl/fwencoder

Add https://github.com/o1egl/fwencoder library

---

README.md

- github.com repo:https://github.com/jandelgado/rabtap
- godoc.org: n/a - it's not a lib
- goreportcard.com: https://goreportcard.com/report/github.com/jandelgado/rabtap
- coverage service link: https://coveralls.io/github/jandelgado/rabtap?branch=master

Added RabbitMQ/AMQP related libs and tools

---

README.md

- github.com repo: https://github.com/istio/fortio
- godoc.org: https://godoc.org/istio.io/fortio
- goreportcard.com:  https://goreportcard.com/report/istio.io/fortio
- coverage service link: https://codecov.io/gh/istio/fortio
Note: doc etc are good I think, so are tests for core functions and everything easily testable, but coverage for network and UI is not where I want it to be, yet I think it's still high quality and useful code and software. …

proposed addition of fortio

---

README.md

Hello,
I am Saurabh, co-founder of Hackr.io. Hackr.io is a programming community & a great place to find the best online programming courses and tutorials. It's a one stop solution for tutorial recommendations with 5000+ tutorial of more than 140 programming languages.
I was looking at your learning resources page and found it pretty useful. I believe that Hackr.io would be really useful to the developer community in finding the right programming course/tutorial and would make a nice addition to your resource page.
Hackr is also listed on other esteemed websites like Lehigh University's resource page and official Official Python wiki page to name a few.
Thanks for the list of great resources you have compiled. Enjoy your week:)
Please check if what you want to add to `awesome-go` list …

Suggestion for a Resource addition

---

README.md

- github.com repo: https://github.com/ddo/rq
- godoc.org: https://godoc.org/gopkg.in/ddo/rq.v0
- goreportcard.com: https://goreportcard.com/report/github.com/ddo/rq
- coverage: https://codecov.io/gh/ddo/rq
- test: https://semaphoreci.com/ddo/rq

add ddo/rq

---

README.md

- github.com repo: https://github.com/icza/minquery
- godoc.org: https://godoc.org/github.com/icza/minquery
- goreportcard.com: https://goreportcard.com/report/github.com/icza/minquery [![Go Report Card](https://goreportcard.com/badge/github.com/icza/minquery)](https://goreportcard.com/report/github.com/icza/minquery)
- coverage service link: [codecov.io/gh/icza/minquery](https://codecov.io/gh/icza/minquery) [![codecov](https://codecov.io/gh/icza/minquery/branch/master/graph/badge.svg)](https://codecov.io/gh/icza/minquery)
**Note**: …

Add minquery utility library

---

README.md

- github.com repo: https://github.com/icza/backscanner
- godoc.org: https://godoc.org/github.com/icza/backscanner
- goreportcard.com: https://goreportcard.com/report/github.com/icza/backscanner [![Go Report Card](https://goreportcard.com/badge/github.com/icza/backscanner)](https://goreportcard.com/report/github.com/icza/backscanner)
- coverage service link https://codecov.io/gh/icza/backscanner [![codecov](https://codecov.io/gh/icza/backscanner/branch/master/graph/badge.svg)](https://codecov.io/gh/icza/backscanner)
**Note**: that …

Add backscanner utility library

---

README.md

Updated GoSublime descirption

---

README.md

Add link to Codeship Go API client
Repo: https://github.com/codeship/codeship-go
Coverage: https://coveralls.io/github/codeship/codeship-go
Godoc: https://godoc.org/github.com/codeship/codeship-go
Go Report Card: https://goreportcard.com/report/github.com/codeship/codeship-go
- godoc.org:
Very good …

Add codeship-go link

---

README.md

- github.com repo: [conjungo](https://github.com/InVisionApp/conjungo)
- godoc.org: [godoc](https://godoc.org/github.com/InVisionApp/conjungo)
- goreportcard.com: [reportcard](https://goreportcard.com/report/github.com/InVisionApp/conjungo)
- coverage service link: https://codecov.io/gh/InVisionApp/conjungo
Very good coverage: 100%
- [ X ] I have added my package in alphabetical order.
- [ X ] I …

adding the conjungo merge library

---

README.md

Timespan is a Go library for interacting with intervals of time, defined as a start time and a duration.
- github.com repo: https://github.com/SaidinWoT/timespan
- godoc.org: https://godoc.org/github.com/SaidinWoT/timespan
- goreportcard.com: https://goreportcard.com/report/github.com/SaidinWoT/timespan
- coverage: [gocover](https://gocover.io/github.com/SaidinWoT/timespan) …

Add Timespan package

---

README.md

See author's last commit
https://github.com/go-mgo/mgo/commit/b86855e89b5a6a30ea0c31ef8bb16bf17179734d

go-mgo is unmaintained

---

README.md

This adds a library to interact with the [Chronos](https://mesos.github.io/chronos/) Job Scheduler for Mesos and a Yeoman generator for Go projects.
- github.com repo: https://github.com/axelspringer/go-chronos
- godoc.org: https://godoc.org/github.com/axelspringer/go-chronos
- goreportcard.com: https://goreportcard.com/report/github.com/axelspringer/go-chronos
- coverage service link: https://gocover.io/github.com/axelspringer/go-chronos
**Make sure …

Adding Chronos library and Yeoman generator

---

README.md

- github.com repo: https://github.com/oaStuff/clusteredBigCache
- godoc.org: https://github.com/oaStuff/clusteredBigCache/blob/master/README.md
- goreportcard.com: https://goreportcard.com/report/github.com/oastuff/clusteredBigCache
- coverage: [clusteredBigCache](https://gocover.io/github.com/oastuff/clusteredBigCache/Cluster)

added clusteredBigCache

---

README.md

- github.com repo: https://github.com/kapitan-k/gorocksdb
- godoc.org: https://godoc.org/github.com/kapitan-k/gorocksdb
- goreportcard.com: https://goreportcard.com/report/github.com/kapitan-k/gorocksdb
- coverage service link https://codecov.io/gh/kapitan-k/gorocksdb
- [ x ] I have added my package in alphabetical order.
- [ x ] I have an appropriate description with correct grammar.
- [ x ] I know …

Add gorocksdb

---

README.md

- github.com repo: https://github.com/rafaeljesus/rabbus
- godoc.org: https://godoc.org/github.com/rafaeljesus/rabbus
- goreportcard.com: https://goreportcard.com/report/github.com/rafaeljesus/rabbus
- coverage service link: https://gocover.io/github.com/rafaeljesus/rabbus

Add rabbus library

---

README.md

- github.com repo: https://github.com/campoy/justforfunc
- godoc.org:
- goreportcard.com: https://goreportcard.com/report/github.com/campoy/justforfunc
- coverage service link :

Justforfunc youtube channel hosted by @campoy

---

README.md

- github.com repo: [gendry](https://github.com/didi/gendry)
- godoc.org: https://www.godoc.org/github.com/didi/gendry
- goreportcard.com: https://goreportcard.com/report/github.com/didi/gendry
- coverage service link: 
- https://gocover.io/github.com/didi/gendry/builder
- https://gocover.io/github.com/didi/gendry/scanner
- https://gocover.io/github.com/didi/gendry/manager
Thanks …

Feature add gendry

---

README.md

- github.com repo: **https://github.com/mudler/anagent**
- godoc.org: https://godoc.org/github.com/mudler/anagent
- goreportcard.com: https://goreportcard.com/report/github.com/mudler/anagent
- coverage service link: https://codecov.io/gh/mudler/anagent

Add anagent library

---

README.md

- github.com repo: https://github.com/marusama/cyclicbarrier
- godoc.org: https://godoc.org/github.com/marusama/cyclicbarrier
- goreportcard.com: https://goreportcard.com/report/github.com/marusama/cyclicbarrier
- coverage service link ![Coverage Status](https://coveralls.io/repos/github/marusama/cyclicbarrier/badge.svg?branch=master) https://coveralls.io/github/marusama/cyclicbarrier
Thanks for …

Add CyclicBarrier

---

README.md

- github.com repo: https://github.com/claygod/transaction
- godoc.org: https://godoc.org/github.com/claygod/transaction
- goreportcard.com: https://goreportcard.com/report/github.com/claygod/transaction
- coverage service links: [travis](https://travis-ci.org/claygod/transaction) , [gocover](https://gocover.io/github.com/claygod/transaction)
- [x ] I know that this …

Added a link to the "transaction" library in the "Finance" section.

---

README.md

- github.com repo: https://github.com/edwingeng/wuid
- godoc.org: https://godoc.org/github.com/edwingeng/wuid
- goreportcard.com: https://goreportcard.com/report/github.com/edwingeng/wuid
- coverage:
ok  	github.com/edwingeng/wuid/callback	0.011s	coverage: 96.2% of statements
ok  	github.com/edwingeng/wuid/internal	1.026s	coverage: 97.1% of statements
ok  	github.com/edwingeng/wuid/mongo	3.084s	coverage: 94.9% of statements
ok  	github.com/edwingeng/wuid/mysql	4.074s	coverage: 92.3% of statements
ok  	github.com/edwingeng/wuid/redis	0.781s	coverage: …

add the WUID package

---

README.md

Add geographic tools and servers

---

README.md

Fix a word in the description of Ebiten

---

README.md

- godoc.org:
- [ x] I have added my package in alphabetical order.
- [ x] I have an appropriate description with correct grammar.
- [ …

Added go-finance

---

README.md

- github.com repo: https://github.com/jaffee/commandeer
- godoc.org: https://godoc.org/github.com/jaffee/commandeer
- goreportcard.com: https://goreportcard.com/report/github.com/jaffee/commandeer
- coverage service link [![Coverage](http://gocover.io/_badge/github.com/jaffee/commandeer)](https://gocover.io/github.com/jaffee/commandeer)

add commandeer to CLI libraries

---

README.md

- github.com repo: https://github.com/awoodbeck/strftime
- godoc.org: https://godoc.org/github.com/awoodbeck/strftime
- goreportcard.com: https://goreportcard.com/report/github.com/awoodbeck/strftime …

Add strftime

---

README.md

- github.com repo: https://github.com/nikogura/gomason
- godoc.org: https://godoc.org/github.com/nikogura/gomason
- goreportcard.com: https://goreportcard.com/report/github.com/nikogura/gomason
- coverage service link: https://coveralls.io/github/nikogura/gomason?branch=master
- [x ] I have an appropriate description with …

Submitting Gomason for consideration

---

README.md

Add link to https://github.com/cep21/circuit
https://travis-ci.org/cep21/circuit
https://godoc.org/github.com/cep21/circuit
https://gocover.io/github.com/cep21/circuit
https://goreportcard.com/report/github.com/cep21/circuit

Update README.md (add github.com/cep21/circuit)

---

README.md

(just a tiny fix so I figured the PR template didn't really apply to this situation!)

Fix go-finance bad markdown syntax

---

README.md

- github.com repo: https://github.com/crazcalm/term-quiz
- godoc.org: https://godoc.org/github.com/crazcalm/term-quiz
- goreportcard.com: https://goreportcard.com/report/github.com/crazcalm/term-quiz
- Coverage service link: [![Coverage Status](https://coveralls.io/repos/github/crazcalm/term-quiz/badge.svg?branch=master)](https://coveralls.io/gi …

Added term-quiz to the README

---

README.md

- github.com repo: https://github.com/patrikeh/go-deep
- godoc.org: https://godoc.org/github.com/patrikeh/go-deep
- goreportcard.com: https://goreportcard.com/report/github.com/patrikeh/go-deep
- coverage service link: https://coveralls.io/github/patrikeh/go-deep?branch=master

Add go-deep

---

README.md

This is a command line gui and doesn't really have tests, so I can't add links for some of the items.  It has a good README, however.
- github.com repo: https://github.com/cswank/kcli
- godoc.org: It is not a library, so no godoc.
- goreportcard.com: https://goreportcard.com/report/github.com/cswank/kcli …

Added kcli to devops tools

---

README.md

Add GoLab conference.

---

README.md

- github.com repo: https://github.com/Ullaakut/cameradar
- godoc.org: https://godoc.org/github.com/Ullaakut/cameradar
- goreportcard.com: https://goreportcard.com/report/github.com/Ullaakut/cameradar
- coverage service link [![Coverage Status](https://coveralls.io/repos/github/Ullaakut/cameradar/badge.svg?branch=master)](https://coveralls.io/github/Ullaakut/cameradar?branch=master) https://coveralls.io/github/Ullaakut/cameradar?branch=master
**The low coverage of 79% is due to the fact that the library is mostly using `os.exec` and an external …

Add Cameradar library

---

README.md

Added HTTPS scheme to Golangflow URL

---

README.md

- github.com repo: https://github.com/hyperboloide/pdfgen
- godoc.org: https://godoc.org/github.com/hyperboloide/pdfgen
- goreportcard.com: https://goreportcard.com/report/github.com/hyperboloide/pdfgen
- coverage service link: I don't know how to do it, the project as some non-go dependecies, but locally I have: `coverage: 82.3% of statements`

add pdfgen

---

README.md

- github.com repo: https://github.com/c-bata/go-prompt
- godoc.org: https://godoc.org/github.com/c-bata/go-promp
- goreportcard.com: https://goreportcard.com/report/github.com/c-bata/go-prompt
- coverage service link: [gocover](https://gocover.io/github.com/c-bata/go-prompt)

Add go-prompt

---

README.md

- github.com repo: https://github.com/o1egl/paseto
- godoc.org: https://godoc.org/github.com/o1egl/paseto
- goreportcard.com: https://goreportcard.com/report/github.com/o1egl/paseto
- coverage service link https://coveralls.io/github/o1egl/paseto

Add https://github.com/o1egl/paseto library

---

README.md

- github.com repo: https://github.com/mingrammer/commonregex
- godoc.org: https://godoc.org/github.com/mingrammer/commonregex
- goreportcard.com: https://goreportcard.com/report/github.com/mingrammer/commonregex
- coverage service link: [![codecov](https://codecov.io/gh/mingrammer/commonregex/branch/master/graph/badge.svg)](https://codecov.io/gh/mingrammer/commonregex)
Thanks for …

Add commonregex library

---

README.md

- github.com repo: [https://golangci.com](https://golangci.com)
- godoc.org:
- [ x] I have added my package in alphabetical order.
- [x ] I have an …

Add GolangCI

---

README.md

- github.com repo: https://github.com/xujiajun/gorouter
- godoc.org: https://godoc.org/github.com/xujiajun/gorouter
- goreportcard.com: https://goreportcard.com/report/github.com/xujiajun/gorouter
- coverage service link: https://coveralls.io/github/xujiajun/gorouter?branch=master
- [✔️] I have added my package in alphabetical order.
- [✔️] I have an appropriate description with …

add https://github.com/xujiajun/gorouter library

---

README.md

- github.com repo: https://github.com/DavidBelicza/TextRank
- godoc.org: https://godoc.org/github.com/DavidBelicza/TextRank
- goreportcard.com: https://goreportcard.com/report/github.com/DavidBelicza/TextRank
- coverage service link: [![Coverage Status](https://coveralls.io/repos/github/DavidBelicza/TextRank/badge.svg?branch=master)](https://coveralls.io/github/DavidBelicza/TextRank?branch=master) …

TextRank package - Update README.md

---

README.md

- github.com repo: https://github.com/aerokube/ggr
- godoc.org: http://aerokube.com/ggr/latest/
- goreportcard.com: https://goreportcard.com/report/github.com/aerokube/ggr
- coverage service link ([cover.run](https://codecov.io/gh/aerokube/ggr)
It closes #1816, I removed kallax(I've sent, but you don't accept, golint < 70% in goreportcard)

Change repo

---

README.md

- github.com repo: https://github.com/gojektech/heimdall/
- godoc.org: https://godoc.org/github.com/gojektech/heimdall
- goreportcard.com: https://goreportcard.com/report/github.com/gojektech/heimdall
- coverage service link: https://coveralls.io/github/gojektech/heimdall

Adding Heimdall HTTP client to the awesome list

---

README.md

- github.com repo: https://github.com/mitchellh/go-server-timing
- godoc.org: https://godoc.org/github.com/mitchellh/go-server-timing
- goreportcard.com: https://goreportcard.com/report/github.com/mitchellh/go-server-timing
- coverage service link ([cover.run](https://cover.run/go/github.com/mitchellh/go-server-timing?tag=golang-1.10)

Add go-server-timing

---

README.md

- github.com repo: https://github.com/posener/client-timing
- godoc.org: http://godoc.org/github.com/posener/client-timing
- goreportcard.com: https://goreportcard.com/report/github.com/posener/client-timing
- coverage service https://travis-ci.org/posener/client-timing

Add client-timing

---

README.md

Add package retry
- github.com repo: [retry](https://github.com/thedevsaddam/retry)
- godoc.org: https://godoc.org/github.com/thedevsaddam/retry
- goreportcard.com: https://goreportcard.com/report/github.com/thedevsaddam/retry
- coverage service link: [![Coverage Status](https://coveralls.io/repos/github/thedevsaddam/retry/badge.svg?branch=master)](https://coveralls.io/github/thedevsaddam/retry?branch=master) …

Add package retry

---

README.md

Added Gophercon Russia to the conferences

---

README.md

- github.com repo: https://github.com/albertito/chasquid
- godoc.org: [![GoDoc](https://godoc.org/blitiri.com.ar/go/chasquid?status.svg)](https://godoc.org/blitiri.com.ar/go/chasquid)
- goreportcard.com: [![Go Report Card](https://goreportcard.com/badge/github.com/albertito/chasquid)](https://goreportcard.com/report/github.com/albertito/chasquid)
- coverage service link: [![coveralls.io](https://coveralls.io/repos/github/albertito/chasquid/badge.svg)](https://coveralls.io/github/albertito/chasquid)
Thanks a lot!

Add chasquid, an SMTP (email) server

---

README.md

Please check if what you want to add to `awesome-go` list meets [quality standards](https://github.com/avelino/awesome-go/blob/master/CONTRIBUTING.md#quality-standard) before sending pull request.
- github.com repo: https://github.com/Jeffail/benthos
- godoc.org: https://godoc.org/github.com/Jeffail/benthos
- goreportcard.com: https://goreportcard.com/report/github.com/Jeffail/benthos
- coverage service links:
+ processor: ![cover.run go processor](https://cover.run/go/github.com/Jeffail/benthos/lib/processor.svg)
+ condition: ![cover.run go condition](https://cover.run/go/github.com/Jeffail/benthos/lib/processor/condition.svg)
+ pipeline: ![cover.run go pipeline](https://cover.run/go/github.com/Jeffail/benthos/lib/pipeline.svg)
+ broker: ![cover.run go …

Add github.com/Jeffail/benthos

---

README.md

- github.com repo: https://github.com/ufoscout/go-up
- godoc.org: https://godoc.org/github.com/ufoscout/go-up
- goreportcard.com: https://goreportcard.com/report/github.com/ufoscout/go-up
- coverage service link: https://codecov.io/gh/ufoscout/go-up

Add go-up library

---

README.md

[orb](https://github.com/paulmach/orb) is a package for working with 2d geometry. It is a successor to [go.geo](https://github.com/paulmach/go.geo) and [go.geojson](https://github.com/paulmach/go.geojson). There are major improvements to the API to make it must more usable and idiomatic along with added features.
[osm](https://github.com/paulmach/osm) is a package for working with OpenStreetMap data from all the sources using a shared set of types. It has the ability to:
* read data from the API
* read data and state from the minute/hour/day replication service
* Marshal small xml files and scan large xml files
* scan osm pbf files
* cover osm data to geojson for more straight forward viewing. 
https://github.com/paulmach/orb …

Add paulmach/(orb|osm) geometric libraries

---

README.md

- github.com repo: https://github.com/algoGuy/EasyMIDI
- godoc.org: [![GoDoc](https://godoc.org/github.com/algoGuy/EasyMIDI?status.svg)](https://godoc.org/github.com/algoGuy/EasyMIDI)
- goreportcard.com: [![Go Report Card](https://goreportcard.com/badge/github.com/algoGuy/EasyMIDI)](https://goreportcard.com/report/github.com/algoGuy/EasyMIDI)
- coverage service link: [![codecov](https://codecov.io/gh/algoGuy/EasyMIDI/branch/master/graph/badge.svg)](https://codecov.io/gh/algoGuy/EasyMIDI)
**Note**: that new categories can be added …

added EasyMIDI library to awesome-go list

---

README.md

- github.com repo: https://github.com/rylans/getlang
- godoc.org: https://godoc.org/github.com/rylans/getlang
- goreportcard.com: https://goreportcard.com/report/github.com/rylans/getlang
- coverage service link [cover.run go](https://cover.run/go/github.com/rylans/getlang.svg?tag=golang-1.10)

Add package getlang

---

README.md

- github.com repo: https://github.com/zhengchun/syndfeed
- godoc.org: https://godoc.org/github.com/zhengchun/syndfeed
- goreportcard.com: https://goreportcard.com/report/github.com/zhengchun/syndfeed
- coverage service link: https://coveralls.io/github/zhengchun/syndfeed?branch=master

Add syndfeed package

---

README.md

- github.com repo: https://github.com/ortuman/jackal
- godoc.org: https://godoc.org/github.com/ortuman/jackal
- goreportcard.com: https://goreportcard.com/report/github.com/ortuman/jackal
- coverage service link: [![codecov](https://codecov.io/gh/ortuman/jackal/branch/master/graph/badge.svg)](https://codecov.io/gh/ortuman/jackal)

Added jackal XMPP server.

---

README.md

Goat is deprecated by its author.

Remove Goat: deprecated

---

README.md

- github.com repo: https://github.com/nikepan/clickhouse-bulk
- godoc.org: https://godoc.org/github.com/nikepan/clickhouse-bulk
- goreportcard.com: https://goreportcard.com/report/github.com/nikepan/clickhouse-bulk
- coverage service link: https://codecov.io/gh/nikepan/clickhouse-bulk

added clickhouse-bulk

---

README.md

- github.com repo: https://github.com/mingrammer/cfmt
- godoc.org: https://godoc.org/github.com/mingrammer/cfmt
- goreportcard.com: https://goreportcard.com/report/github.com/mingrammer/cfmt
- coverage service link : [![codecov](https://codecov.io/gh/mingrammer/cfmt/branch/master/graph/badge.svg)](https://codecov.io/gh/mingrammer/cfmt)

Add cfmt library

---

README.md

- github.com repo: https://github.com/mongodb/mongo-go-driver
- godoc.org: https://godoc.org/github.com/mongodb/mongo-go-driver/mongo
- goreportcard.com: https://goreportcard.com/report/github.com/mongodb/mongo-go-driver
- ci: https://evergreen.mongodb.com/waterfall/mongo-go-driver

Add official MongoDB Go driver

---

README.md

Updated Naming

---

README.md

- github.com repo: https://github.com/b3log/pipe
- godoc.org: https://godoc.org/github.com/b3log/pipe
- goreportcard.com: https://goreportcard.com/report/github.com/b3log/pipe
- coverage service link: `![coveralls](https://coveralls.io/repos/github/b3log/pipe/badge.svg?branch=master)`

:sparkles: Add Pipe

---

README.md

Didn't believe the PR template is required as only adding a single meet-up link.
Thank you
Dan

added golang dorset meetup

---

README.md

- github.com repo: https://github.com/buraksezer/consistent
- godoc.org: [![GoDoc](http://img.shields.io/badge/godoc-reference-blue.svg?style=flat)](https://godoc.org/github.com/buraksezer/consistent)
- goreportcard.com: [![Go Report Card](https://goreportcard.com/badge/github.com/buraksezer/consistent)](https://goreportcard.com/report/github.com/buraksezer/consistent)
- coverage service link: [![Coverage](http://gocover.io/_badge/github.com/buraksezer/consistent)](http://gocover.io/github.com/buraksezer/consistent)
**Note**: that …

Add github.com/buraksezer/consistent package

---

README.md

- github.com repo: https://github.com/vaelen/iot
- godoc.org: [![Go Docs](https://godoc.org/github.com/vaelen/iot?status.svg)](https://godoc.org/github.com/vaelen/iot)
- goreportcard.com: [![Go Report Card](https://goreportcard.com/badge/github.com/vaelen/iot)](https://goreportcard.com/report/github.com/vaelen/iot)
- coverage service link: [![gocover.io](https://gocover.io/_badge/github.com/vaelen/iot)](https://gocover.io/github.com/vaelen/iot) …

Add the iot project for Google IoT Core.

---

README.md

- github.com repo: https://github.com/fatih/structs
- godoc.org: https://godoc.org/github.com/fatih/structs
- goreportcard.com: https://goreportcard.com/report/github.com/fatih/structs
- coverage service link https://coveralls.io/r/fatih/structs
100% coverage

Added github.com/fatih/structs to serialization

---

README.md

- github.com repo: https://github.com/gobuffalo/packr
- godoc.org: https://godoc.org/github.com/gobuffalo/packr
- goreportcard.com: https://goreportcard.com/report/github.com/gobuffalo/packr
- coverage service link: ![cover.run go](https://cover.run/go/github.com/gobuffalo/packr.svg?tag=golang-1.10)
- [*] I have an appropriate …

added https://github.com/gobuffalo/packr

---

README.md

- github.com repo: https://github.com/corona10/goimagehash
- godoc.org: https://godoc.org/github.com/corona10/goimagehash
- goreportcard.com: https://goreportcard.com/report/github.com/corona10/goimagehash
- coverage service link: [![Coverage Status](https://coveralls.io/repos/github/corona10/goimagehash/badge.svg)](https://coveralls.io/github/corona10/goimagehash) …

README.md: Add goimagehash

---

README.md

Fix typo in iot link

---

README.md

fix malformed link

---

README.md

- github.com repo: https://github.com/pascaldekloe/jwt
- godoc.org: [![API Documentation](https://godoc.org/github.com/pascaldekloe/jwt?status.svg)](https://godoc.org/github.com/pascaldekloe/jwt)
- goreportcard.com: [![Report Card](https://goreportcard.com/badge/github.com/pascaldekloe/jwt)](https://goreportcard.com/report/github.com/pascaldekloe/jwt)
- coverage service: [![Build Report](https://cover.run/go/github.com/pascaldekloe/jwt.svg)](https://cover.run/go/github.com/pascaldekloe/jwt)
- [* ] I have added my package in alphabetical order.
- [ *] I have an appropriate description with correct grammar.
- [ *] I know that this package was not listed before.
- [ *] I have added godoc link to the repo and to my pull request.
- [ *] I have added coverage service link to the repo and to my …

Add another JWT library.

---

README.md

Added link to Learn go with TDD

---

README.md

- github.com repo: https://github.com/sdcoffey/techan
- godoc.org: https://godoc.org/github.com/sdcoffey/techan
- goreportcard.com: https://goreportcard.com/report/github.com/sdcoffey/techan
- Code coverage: https://codecov.io/gh/sdcoffey/techan

Add techan package

---

README.md

hi,
add https://github.com/xujiajun/godbal
- github.com repo: https://github.com/xujiajun/godbal
- godoc.org: https://godoc.org/github.com/xujiajun/godbal
- goreportcard.com: https://goreportcard.com/report/github.com/xujiajun/godbal
- coverage service link: https://coveralls.io/github/xujiajun/godbal?branch=master
- [ ✔️] I have added my package in alphabetical order.
- [ ✔️] I have an appropriate …

add https://github.com/xujiajun/godbal

---

README.md

- github.com repo: https://github.com/Fs02/grimoire
- godoc.org: https://godoc.org/github.com/Fs02/grimoire
- goreportcard.com: https://goreportcard.com/report/github.com/Fs02/grimoire
- coverage service link: ![cover.run go](https://cover.run/go/github.com/Fs02/grimoire.svg?tag=golang-1.10) [![Test Coverage](https://api.codeclimate.com/v1/badges/d487e2be0ed7b0b1fed1/test_coverage)](https://codeclimate.com/github/Fs02/grimoire/test_coverage)
**Make …

add https://github.com/Fs02/grimoire

---

README.md

- github.com repo: https://github.com/heetch/confita
- godoc.org: https://godoc.org/github.com/heetch/confita
- goreportcard.com: https://goreportcard.com/report/github.com/heetch/confita
- coverage service link ([cover.run](https://cover.run/), [gocover](http://gocover.io/), [coveralls](https://coveralls.io/) etc.), example: `![cover.run go](https://cover.run/go/github.com/user/repository.svg)` : https://gocover.io/github.com/heetch/confita
**Make …

Add Confita

---

README.md

added golang bulgaria into the meetup list 🎏  🇧🇬

added golang bulgaria

---

README.md

- github.com repo: https://github.com/Talento90/go-health
- godoc.org: https://godoc.org/github.com/Talento90/go-health
- goreportcard.com: https://goreportcard.com/report/github.com/Talento90/go-health
- coverage service: https://codecov.io/gh/Talento90/go-health

Add Go Health Package

---

README.md

fix build fail

---

README.md

- github.com repo: https://github.com/InVisionApp/tabular
- godoc.org: https://godoc.org/github.com/InVisionApp/tabular
- goreportcard.com: https://goreportcard.com/report/github.com/InVisionApp/tabular
- coverage service link: https://codecov.io/gh/InVisionApp/tabular
Checklist:

adding InVisionApp/tabular library

---

README.md

- github.com repo: https://github.com/leandro-lugaresi/hub
- godoc.org: [![Go Doc](https://img.shields.io/badge/godoc-reference-blue.svg?style=flat-square)](http://godoc.org/github.com/leandro-lugaresi/hub)
- goreportcard.com:[![Go Report Card](https://goreportcard.com/badge/github.com/leandro-lugaresi/hub?style=flat-square)](https://goreportcard.com/report/github.com/leandro-lugaresi/hub)
- licence: [![Software License](https://img.shields.io/github/license/leandro-lugaresi/hub.svg?style=flat-square)](https://github.com/leandro-lugaresi/hub/blob/master/LICENSE)
- coverage: [![Coverage …

add leandro-lugaresi/hub

---

README.md

- github.com repo: https://github.com/hishamkaram/geoserver
- godoc.org: [![godoc](https://godoc.org/github.com/hishamkaram/geoserver?status.svg)](https://godoc.org/github.com/hishamkaram/geoserver?)
- goreportcard.com:[![Go Report Card](https://goreportcard.com/badge/github.com/hishamkaram/geoserver)](https://goreportcard.com/report/github.com/hishamkaram/geoserver)
- coverage service link: [![Coverage Status](https://coveralls.io/repos/github/hishamkaram/geoserver/badge.svg?branch=master)](https://coveralls.io/github/hishamkaram/geoserver?branch=mast …

add geoserver package

---

README.md

Add a go algorithms repo, including tree(bst, btree, vEB-tree...), heap(binary heap, leftist heap, fibonacci heap...), sort, hashmap, graph(more content will be soon) ...
[https://github.com/shady831213/algorithms](https://github.com/shady831213/algorithms)
[![Go Report Card](https://goreportcard.com/badge/github.com/shady831213/algorithms)](https://goreportcard.com/report/github.com/shady831213/algorithms)
- coverage service link ([cover.run](https://cover.run/), [gocover](http://gocover.io/), …

Add a go algorithms repo

---

README.md

add Go Copenhagen

---

README.md

fix typo about algorithms.
dat -> data
Sorry about that.

fix typo about algorithms

---

README.md

- github.com repo: https://github.com/recoilme/slowpoke
- godoc.org: https://godoc.org/github.com/recoilme/slowpoke
- goreportcard.com:https://goreportcard.com/report/github.com/recoilme/slowpoke
- coverage service link:![cover.run go](https://cover.run/go/github.com/recoilme/slowpoke.svg)
https://cover.run/go/github.com/recoilme/slowpoke?tag=golang-1.10

slowpoke - Key-value store with persistence

---

README.md

- github.com repo: https://github.com/francoispqt/onelog
- godoc.org: https://godoc.org/github.com/francoispqt/onelog
- goreportcard.com: https://goreportcard.com/report/github.com/francoispqt/onelog
- coverage service link https://codecov.io/gh/francoispqt/onelog

ADD: Onelog to logging section

---

README.md

- github.com repo: https://github.com/sheng/cameron
- godoc.org: https://godoc.org/github.com/sheng/cameron
- goreportcard.com: https://goreportcard.com/report/github.com/sheng/cameron
- coverage service link ([cover.run](https://cover.run/), [gocover](http://gocover.io/), [coveralls](https://coveralls.io/) etc.): [![Coverage Status](https://coveralls.io/repos/github/sheng/cameron/badge.svg?branch=master)](https://coveralls.io/github/sheng/cameron?branch=master)

Add Cameron

---

README.md

An simple and light excel file reader to read a standard excel as a table faster.
---
- github.com repo: https://github.com/szyhf/go-excel
- godoc.org: [![GoDoc](https://godoc.org/github.com/szyhf/go-excel?status.png)](https://godoc.org/github.com/szyhf/go-excel)
- goreportcard.com:[![Go Report Card](https://goreportcard.com/badge/github.com/szyhf/go-excel)](https://goreportcard.com/report/github.com/szyhf/go-excel)
- coverage service link ([cover.run](https://cover.run/), [gocover](http://gocover.io/), [coveralls](https://coveralls.io/) etc.): …

add go-excel

---

README.md

Really sorry for this mistake.

fix mistake in grammar of `go-excel` relate to #1937

---

README.md

- github.com repo: https://github.com/fulldump/biff
- godoc.org: https://godoc.org/github.com/fulldump/biff
- goreportcard.com: https://goreportcard.com/report/github.com/fulldump/biff
- coverage service link: https://gocover.io/github.com/fulldump/biff

Add https://github.com/fulldump/biff

---

README.md

- github.com repo: https://github.com/subchen/go-log
- godoc.org: https://godoc.org/github.com/subchen/go-log
- goreportcard.com: https://goreportcard.com/report/github.com/subchen/go-log
- coverage service link: [![Coverage Status](https://coveralls.io/repos/github/subchen/go-log/badge.svg?branch=master)](https://coveralls.io/github/subchen/go-log?branch=master)

add another go-log

---

README.md

> A collection of flag argument types for Go's standard `flag` package (simple structs that can be passed to `flag.Var()`). For example: enums, templates, URLs, slices.
- github.com repo: <https://github.com/sgreben/flagvar>
- godoc.org: <https://godoc.org/github.com/sgreben/flagvar>
- goreportcard.com: [![](https://goreportcard.com/badge/github.com/sgreben/flagvar/goreportcard)](https://goreportcard.com/report/github.com/sgreben/flagvar)
- coverage service link: [![cover.run](https://cover.run/go/github.com/sgreben/flagvar.svg?style=flat&tag=golang-1. …

Add sgreben/flagvar

---

README.md

Remove dpar

---

README.md

A wrapper around the Google Cloud Datastore Go package
that adds caching using memcached.
- github.com repo: https://github.com/defcronyke/godscache
- godoc.org: [![GoDoc](https://godoc.org/github.com/defcronyke/godscache?status.png)](https://godoc.org/github.com/defcronyke/godscache)
- goreportcard.com: [![Go Report Card](https://goreportcard.com/badge/github.com/defcronyke/godscache)](https://goreportcard.com/report/github.com/defcronyke/godscache)
- coverage service link: [![Coverage Status](https://coveralls.io/repos/github/defcronyke/godscache/bad …

add godscache a.k.a. Go DS Cache

---

README.md

- github.com repo: https://github.com/subchen/go-trylock
- godoc.org: https://godoc.org/github.com/subchen/go-trylock
- goreportcard.com: https://goreportcard.com/report/github.com/subchen/go-trylock
- coverage service link ([cover.run](https://cover.run/), [gocover](http://gocover.io/), [coveralls](https://coveralls.io/) etc.): [![Coverage Status](https://coveralls.io/repos/github/subchen/go-trylock/badge.svg?branch=master)](https://coveralls.io/github/subchen/go-trylock?branch=master)

Add go-trylock

---

README.md

- github.com repo: https://github.com/BlackRabbitt/mspm
- godoc.org: https://godoc.org/github.com/BlackRabbitt/mspm
- goreportcard.com: [![Go Report Card](https://goreportcard.com/badge/github.com/BlackRabbitt/mspm)](https://goreportcard.com/report/github.com/BlackRabbitt/mspm)
- coverage service link [gocover](https://gocover.io/github.com/blackrabbitt/mspm/ds/trie), [gocover](https://gocover.io/github.com/blackrabbitt/mspm/search) …

Adds mspm package name in DataStructure and Algorithm list.

---

README.md

- github.com repo: [https://github.com/whiteShtef/clockwork](https://github.com/whiteShtef/clockwork)
- godoc.org:  [![GoDoc](https://godoc.org/github.com/whiteshtef/clockwork?status.svg)](https://godoc.org/github.com/whiteshtef/clockwork)
- goreportcard.com: [![Go Report Card](https://goreportcard.com/badge/github.com/whiteshtef/clockwork)](https://goreportcard.com/report/github.com/whiteshtef/clockwork)
- coverage service link:  ![Coverage](http://gocover.io/_badge/github.com/whiteshtef/clockwork) - [https://gocover.io/github.com/whiteshtef/clockwork](https://gocover.io/github.com/whiteshtef/clockwork)
- [✔️] I have added my package in alphabetical order.
- [✔️] I have an appropriate description with correct grammar.
- [✔️] I know that this package was not listed before.
- [✔️] I have …

Add clockwork

---

README.md

- github.com repo: https://github.com/thedevsaddam/gojsonq
- godoc.org: https://godoc.org/github.com/thedevsaddam/gojsonq
- goreportcard.com: https://goreportcard.com/report/github.com/thedevsaddam/gojsonq
- coverage service link: [![Coverage Status](https://coveralls.io/repos/github/thedevsaddam/gojsonq/badge.svg?branch=master)](https://coveralls.io/github/thedevsaddam/gojsonq?branch=master) …

Add package gojsonq

---

README.md

- github.com repo: https://github.com/novalagung/gubrak
- godoc.org: https://godoc.org/github.com/novalagung/gubrak
- goreportcard.com: [![Go Report Card](https://goreportcard.com/badge/github.com/novalagung/gubrak?nocache=1)](https://goreportcard.com/report/github.com/novalagung/gubrak?nocache=1)
- coverage service link: [![cover.run](https://cover.run/go/github.com/novalagung/gubrak.svg?style=flat&tag=golang-1.10)](https://cover.run/go?tag=golang-1.10&repo=github.com%2Fnovalagung%2Fgubrak) …

update gubrak tagline

---

README.md

- github.com repo: https://github.com/osamingo/gosh
- godoc.org: https://godoc.org/github.com/osamingo/gosh
- goreportcard.com: https://goreportcard.com/report/github.com/osamingo/gosh
- coverage service link: [![codecov](https://codecov.io/gh/osamingo/gosh/branch/master/graph/badge.svg)](https://codecov.io/gh/osamingo/gosh)

Add osamingo/gosh

---

README.md

Add GopherCon India conference
