README.md

This is the only publicly available mutation tester for Go source code which is practial usable and not a prototype. I described other mutation testers and their flaws here https://github.com/zimmski/go-mutesting#other-projects

add go-mutesting

---

README.md

Package autoflags provides a convenient way of exposing struct fields as command line flags. Exposed fields should have flag tag attached: `flag:"flagName,usage string"`.

Add autoflags package

---

README.md

This isn't my package, it's by @GlenKelley, and it's either a fork or simply related to `github.com/go3d/go-collada` by @metaleap. However, it actually works (in my [testing](https://github.com/shurcooL/play/commit/bb12dd54f9d6b69523b695420b4cac9423bddd03#commitcomment-9134222)) and is useful for loading/parsing the Collada file format, unlike the go3d package which [isn't working/finished](https://github.com/go3d/go-collada/issues/1#issuecomment-68077857).
I'm willing to help maintain it if @GlenKelley doesn't want to, but I think adding it to this list is helpful because as far as I know, it's the only (working) Go package for dealing with the Collada file format.

Add go-collada, a Go package for working with the Collada file format.

---

README.md

Closes #169.
I didn't add the `gogits` pure Go library because I wasn't sure which is better, and I've never used it myself yet, so I can't speak for its quality. I'll let someone more familiar with them add it.
These 3 packages I rely on for a while and they're good. /cc @sqs @beyang @libgit2

Add version control libraries.

---

README.md

Curated by [Go Newsletter Issue 45](http://golangweekly.com/issues/45), it's a geocoding service developed in an idiomatically Go-style way. Works with Google Maps, MapQuest, OpenCage and HERE out of the box.

add geo-golang

---

README.md

- blevesearch/segment is a a Go library for performing Unicode Text
Segmentation as described in Unicode Standard Annex #29

Add blevesearch/segment to the NLP section

---

README.md

In mitchellh/mapstructure#24, the author said he wouldn't mind it here. It's a high quality Go library that serves a specific need.

Add github.com/mitchellh/mapstructure.

---

README.md

https://github.com/avelino/awesome-go/issues/282
Notes: It was not immediately clear whether I should move the command line email tool to Standard Command Line or leave as a utility (https://github.com/sanbornm/mp). I think the best option is to leave it as a utility because it isn't a tool for building command line apps, it is just a command line app itself.

divide CUI into std and advanced Command Line

---

README.md

> Fix lexicographical ordering of other packages in Images section too.
Renamed it after this discussion, http://git.io/geopattern-naming-discussion

Rename geo_pattern to geopattern

---

README.md

at Web Frameworks section.
current squiidz/bone seems just one of fork.

update Bone for preferable URL

---

README.md

I just moved my package from my user account to an organization account and renamed the repository so here's a pull request to update.

update package location for go-validate-yourself to bluesuncorp/validator

---

README.md

Hello,
Many people find this library useful: https://github.com/deckarep/gosx-notifier for building scripts, tools and systems that can generate Desktop Notifications on OSX.
Please consider adding it.
Thanks!

Adding gosx-notifier library which is desktop notifications for OSX

---

README.md

Accessing them using a browser makes github redirect you to the new home but using the github API these throw 404s, which is annoying to deal with.
I don't know the policy around old URLs, maybe such a check should be part of the guidelines and the test suite.

update the url of github projects that have moved

---

README.md

The OpenGL repos have had an overhaul earlier this year. This update is to reflect the changes.
- Update descriptions of go-gl/gl and go-gl/glfw repos.
- Remove `glow`. It is an internal generator tool used to generate the go-gl/gl bindings; most users will not need to know about it unless they are interested in generating custom bindings or fixing issues. But in that case they can find out about glow from the go-gl/gl repository, since it's described in the README.
/cc @errcw Since `glow` is your package, I want to check if removing it is okay with you. See rationale above. It was primarily here before the go-gl overhaul because it contained the glow-generated bindings inside; those are now in go-gl/gl. I think avoiding listing it here will help avoid confusion for new users.

Update OpenGL section.

---

README.md

It seems reasonable (from my point of view) to have logrus as a standalone library. If you do not know what is logrus and do not care about a plugin for something (which is logrusly), you will miss logrus itself.

add logrus as a standalone lib

---

README.md

Uses regex to extract urls from text. Can be used as a library via the regexp package and also has a command line utility.

Add xurls to the text processing category

---

README.md

It has moved out into a standalone repo. See shurcooL/go#19 for rationale.

Update import path of github_flavored_markdown package.

---

README.md

A more comprehensive bindings to the FFMPEG av* libraries: libavcodec, libavformat, libavutil, libavfilter, libavdevice, libswresample, libswscale.

Add giorgisio/goav

---

README.md

[Tollbooth](https://github.com/didip/tollbooth) is an HTTP rate limiter middleware.
We are using it internally at work for various internal services and I use it for some personal projects at home as well.

Add tollbooth to list of middlewares.

---

README.md

There is no other tga encoder/decoder package in the awesome-go list, so I think it would be beneficial to add it. This is the only and best tga package I know of.
> Supports RLE and raw TARGA images with 8/15/16/24/32 bits per pixel, monochrome, truecolor and colormapped images. Correctly handles origins and attribute type in extensions area. Passes TGA 2.0 conformance suite (http://googlesites.inequation.org/tgautilities).
I've opened https://github.com/ftrvxmtrx/tga/issues/4 to see if it's still well maintained, since it was last updated 3 years ago. But it's complete and functional, so I wouldn't hold it too much against it.
/cc @ftrvxmtrx

Add TARGA image format decoder/encoder package.

---

README.md

orchestrator is being used in production in major companies such as Booking.com, Outbrain, and more, and is under active development.

Added orchestrator under "database tools" section

---

README.md

Add link to Jsonf: Console tool for highlighted formatting and struct query fetching JSON.

Add link to Jsonf: Console tool for highlighted formatting and struct query fetching JSON

---

README.md

A few repositories appear like this on the website: `[SendGrid] (https://github.com/sendgrid/sendgrid-go) - SendGrid's Go library for sending email`. This fixes those

fix some markdown link spacing issues

---

README.md

- adding a link to the go api library for interacting with mesosphere's marathon PaaS

Go API for Marathon PaaS

---

README.md

Also list the conference cities to make it clearer where they are held, since it's not always evident from the conference name.

Add GoCon and GothamGo to the conference list

---

README.md

Since there is a Validations section `asaskevich/govalidator` fits there better then under "Text Processing/Utility"

govalidator belongs in Validation section

---

README.md

Add [anaconda](https://github.com/ChimeraCoder/anaconda) library for working with Twitter 1.1 API to `Third-party APIs` section

Add anaconda

---

README.md

Don't merge this [within 7 days](https://github.com/avelino/awesome-go/pull/484#issuecomment-127084329) of PR's open date to allow sufficient time for people to review.
The website appears to be down. As far as I can tell it's no longer active, but let me know if that's not the case.

Remove GoBuild (http://gobuild.io/), online compile Go projects to Windows, Linux and OS X.

---

README.md

The `go-stats` package, which is a command line parser, was in the `Miscellaneous` section. Instead, it should be in the `Standard CLI` section.

relocate go-stats to Standard CLI section

---

README.md

This commit adds a link to restic, a fast and secure backup program
that uses de-deuplication.
Disclaimer: I started the project and I'm the lead developer.
I was a bit unsure whether I should link to the restic GitHub repository or the restic website at https://restic.github.io, feedback here is appreciated.

Add restic

---

README.md

I recently migrated some code from one organization to another and am
just updating the links to point directly to the new location:
Repos affected:
* https://github.com/go-playground/validator
* https://github.com/go-playground/assert
* https://github.com/go-playground/overalls

Update repo links to a few packages

---

README.md

The upstream project has not been active for over a year. Update the URL
to point to an active fork.

Update gotk3 URL

---

README.md

Super handy tool for S3 access that's just a single `go get` away.

Add s3gof3r to list of devops tools.

---

README.md

Not sure if this library is best suited on this list or under this category, but go-getter has been pretty useful and is pretty actively developed.

Add go-getter to the network section.

---

README.md

* Add Github Webhook library, more service to come i.e. BitBucket..
https://github.com/go-playground/webhooks
Most other libraries only return part of the webhooks even, this returns the WHOLE posted event data.

Add webhooks library for GitHub

---

README.md

Adds the go-libsass lib for writing your own Sass tooling. The default
implementation, wellington, implements a tool for working on Sass
projects. Wellington adds the same spriting functions as available in Compass.
Signed-off-by: Drew Wells <drew.wells00@gmail.com>

add wellington and low level libsass wrapper

---

README.md

The previous Snapchat library is a year old and out of date. This library is up to date, progressing fast and is actively maintained.

Replace outdated Snapchat library with an updated one.

---

README.md

Adding grequests – An elegant and simple `net/http` wrapper that follows Python's requests library

Adding grequests

---

README.md

Package trayhost is a cross-platform Go library to place an icon in the host operating system's taskbar.
[`github.com/shurcooL/trayhost`](https://github.com/shurcooL/trayhost)
Here are some screenshots from [an app](https://github.com/pavben/InstantShare#readme) (/cc @pavben) that uses trayhost for its GUI.
The implementation status is fully implemented for OS X, but there's not a working implementation for Linux nor Windows yet. Contributors for those platforms are welcome.

Add trayhost package to GUI section.

---

README.md

Library is not being maintained (according to github page).

Removed gxui from GUI section. 

---

README.md

According to https://github.com/go-martini/martini/commit/15a47622d6a9b3e6a1eaca2681e4850f612471ea:
> The martini framework is no longer maintained.

Remove Martini.

---

README.md

I think we need a Query Language section to list `graphql` related libraries.
Adds: 
- Query Language section.
- `graphql-go` library within Query Language.

Adds query language section.

---

README.md

A [library](https://github.com/jawher/mow.cli) for building CLI applications.
mow.cli comes with support for what you would expect from any decent CLI library: posix syntax, option groups, commands and sub commands, contextual help, ...
What sets it apart is a sophisticated call validation, by providing a spec string to specify how exactly a command should be called.
For example, here's the spec string you can use with mow.cli to define the call syntax of a `cp` like command:
```
[-R [-H | -L | -P]] [-fi | -n] [-apvX] SRC... DST
```
I've written 2 articles to explain in more details the why and how: [1](https://jawher.me/2015/01/13/parsing-command-line-arguments-shameless-plug-mowcli/), [2](https://jawher.me/2015/01/18/parsing-command-line-arguments-finite-state-machine-backtracking/) …

Add mow.cli, a library for building CLIs

---

README.md

* Added `gorilla/csrf` 
* Modified Goji to point to the new "v2" library at `goji/goji`
* Added `simple-scrypt` - follows the API conventions of Go's `crypto/bcrypt` package.

Added gorilla/csrf, Goji v2 & simple-scrypt

---

README.md

Localization probably deserves its own (sub)section, but for now it fits reasonably well under NLP.

Add go-i18n, a localization package and tool

---

README.md

add Bitbucket support to [webhooks](https://github.com/go-playground/webhooks) library description.

Update webhooks library description

---

README.md

Add two project to the Natural Language Processing section:
* dpar, a transition-based dependency parser.
* go2vec, a reader for word2vec embeddings.

Add dpar and go2vec

---

README.md

Updated the AWS SDK for Go's comment line to reflect that it is now officially launched and ready for production use.

Update README.md's aws-sdk-go comment

---

README.md

checkstyle is a style check tool like java checkstyle. This tool inspired by [java checkstyle](https://github.com/checkstyle/checkstyle), [golint] (https://github.com/golang/lint). The style refered to some points in [Go Code Review Comments](https://code.google.com/p/go-wiki/wiki/CodeReviewComments).
I am the author.

add check style for go

---

README.md

[go-atomix](https://github.com/outrightmental/go-atomix) is a sequence-based Go-native audio mixer for Music apps.
Here is its A+ [go report card](http://goreportcard.com/report/outrightmental/go-atomix)
This is a library I've been working on for two months now, since first discovering `go-sdl2` through your awesome list. It now meets the criteria of being awesome. Please add!

Add go-atomix to the Audio & Music section.

---

README.md

Hi,
I just changed the Macaron url to point to the proper url after the owner moved the project.

changed macaron to proper repo

---

README.md

Added [ozzo-routing](https://github.com/go-ozzo/ozzo-routing) to the "Web frameworks" section.
ozzo-routing is a high-performance HTTP router and Web framework. It comes with full support for quickly building a RESTful API service.
The code is fully covered by unit tests.

Add ozzo-routing to Web frameworks

---

README.md

Added [ozzo-log](https://github.com/go-ozzo/ozzo-log) to the "Logging" section.
ozzo-log is a high-performance logging package that supports logging messages with severity levels and categories. It allows sending filtered log messages to various targets, such as console, mail, network, etc.

Add ozzo-log to Logging

---

README.md

`go-persian-calendar` was appended to `Date & Time` libraries

Add go-persian-calendar to Date & Time

---

README.md

geo-golang supports [Mapbox](https://www.mapbox.com/developers/api/geocoding/) geocoding service now.

update description of geo-golang

---

README.md

DGraph is a distributed graph database written entirely in Go.
Project Link: https://github.com/dgraph-io/dgraph
Demo link: http://dgraph.io

Add DGraph to Go Databases

---

README.md

ontomix moved to its own github.com/go-ontomix - now [gopkg.in/ontomix.v0](https://gopkg.in/ontomix.v0)
Please update. Thanks!

ontomix moved to its own github.com/go-ontomix - now gopkg.in/ontomix.v0

---

README.md

go-xkcd: [GitHub](https://github.com/nishanths/go-xkcd), [GoDoc](https://godoc.org/github.com/nishanths/go-xkcd)

Add xkcd API

---

README.md

Why the go-carpet better builtin tool?
The builtin Go coverage viewer:
- generates in two steps: "go test -coverprofile" and "go tool cover", go-carpet in one (just run)
- generates only html, your don't view coverage in terminal
- not able to show coverage outside of the GOPATH
- not able to show coverage for multiple Go packages (in sub-directories)
Screenshot:

Added go-carpet, tool for viewing test coverage

---

README.md

A Go implementation Count-Min-Log sketch: Approximately counting with approximate counters (Like Count-Min sketch but using waaay less memory)

Add count-min-log

---

README.md

go-commons-pool is a generic object pool for golang
1. test case coverage 90%
2. goreportcard A+  http://goreportcard.com/report/jolestar/go-commons-pool
I can not find a suitable category，so add to Miscellaneous

add go-commons-pool

---

README.md

Link to https://goreportcard.com/: https://goreportcard.com/report/github.com/kirillDanshin/nulltime
Link to https://gocover.io/: https://gocover.io/github.com/kirillDanshin/nulltime
Link to https://godoc.org/: https://godoc.org/github.com/kirillDanshin/nulltime
This library provides a modified version of nulltime from lib/pq as small library. So we don't need to `import github.com/lib/pq` when we don't need the whole library, just `import github.com/kirilldanshin/nulltime`.

Add kirilldanshin/nulltime

---

README.md

Link to [goreportcard](https://goreportcard.com/): https://goreportcard.com/report/github.com/alxrm/ugo
Link to [gocover](https://gocover.io/): https://gocover.io/github.com/alxrm/ugo
Link to [godoc](https://godoc.org/): https://godoc.org/github.com/alxrm/ugo
ugo is a set of slice helper methods, written in Go. It provides many different functions, mostly for slices though. Inspired by [underscore.js](underscorejs.org) and copies it's syntax and behaviour.

add alxrm/ugo

---

README.md

- godoc.org: https://godoc.org/github.com/valyala/quicktemplate
- goreportcard.com: http://goreportcard.com/report/valyala/quicktemplate
- gocover.io: https://gocover.io/github.com/valyala/quicktemplate

Added quicktemplate

---

README.md

See the README at https://github.com/ventu-io/go-log-interface

remove defunct go-log-interface

---

README.md

- godoc.org: https://godoc.org/github.com/azr/generators/varhandler
- goreportcard.com:  https://goreportcard.com/report/github.com/azr/generators
- gocover.io: Can't really, its a generator.
I'll be the maintainer.
I'd rather put it into web framework stuff, but it can put be in generation too, so I put it in both.
Is it fine ?
Cheers !

add link to VarHandler

---

README.md

[![GoDoc](https://godoc.org/github.com/go-playground/lars?status.svg)](https://godoc.org/github.com/go-playground/lars)
[![Go Report Card](https://goreportcard.com/badge/go-playground/lars)](https://goreportcard.com/report/go-playground/lars)
[![Coverage Status](https://coveralls.io/repos/github/go-playground/lars/badge.svg?branch=master)](https://coveralls.io/github/go-playground/lars?branch=master)
[gocover.io](https://gocover.io/github.com/go-playground/lars)

Add lars http router

---

README.md

[Tile38](https://github.com/tidwall/tile38) is a geolocation data store, spatial index, and realtime geofence. It supports a variety of object types including lat/lon points, bounding boxes, XYZ tiles, Geohashes, and GeoJSON.
It's like Redis but for GIS.
- website: http://tile38.com
- godoc.org: https://godoc.org/github.com/tidwall/tile38
- goreportcard.com: https://goreportcard.com/report/github.com/tidwall/tile38

Adding Tile38

---

README.md

I've been working on this and it is now at a point of having some decent utility. I am actively continuing work on it. Thanks!
https://github.com/go-music-theory/music-theory
https://godoc.org/github.com/go-music-theory/music-theory
https://goreportcard.com/report/github.com/go-music-theory/music-theory
* https://gocover.io/github.com/go-music-theory/music-theory/chord
* https://gocover.io/github.com/go-music-theory/music-theory/key
* https://gocover.io/github.com/go-music-theory/music-theory/note

add github.com/go-music-theory/music-theory

---

README.md

This diff is identical to the already-merged-and-closed [#869](https://github.com/avelino/awesome-go/pull/869/files) which my own subsequent  79cc8dc126c3f4fa3f764e351dfb32fe662f64d3 has accidentally reversed.
*To re-cap:*
I've been working on the `gopkg.in/music-theory.v0` library for a while and it is now at a point of having some decent utility. I am actively continuing work on it. Thanks!
https://github.com/go-music-theory/music-theory
https://godoc.org/github.com/go-music-theory/music-theory
https://goreportcard.com/report/github.com/go-music-theory/music-theory
* https://gocover.io/github.com/go-music-theory/music-theory/chord
* https://gocover.io/github.com/go-music-theory/music-theory/key
* https://gocover.io/github.com/go-music-theory/music-theory/note

re-add github.com/go-music-theory/music-theory

---

README.md

[Megos](https://github.com/andygrunwald/megos): [Go(lang)](https://golang.org/) client library for accessing an [Apache Mesos](http://mesos.apache.org/) cluster.
- godoc.org: https://godoc.org/github.com/andygrunwald/megos
- goreportcard.com: https://goreportcard.com/report/github.com/andygrunwald/megos
- coveralls.io: https://coveralls.io/github/andygrunwald/megos

Added megos: A client library for accessing an Apache Mesos Cluster

---

README.md

[go-jira](https://github.com/andygrunwald/go-jira): A [Go](https://golang.org/) client library for [Atlassian JIRA](https://www.atlassian.com/software/jira).
- godoc.org: https://godoc.org/github.com/andygrunwald/go-jira
- goreportcard.com: https://goreportcard.com/report/github.com/andygrunwald/go-jira
- coveralls.io: https://coveralls.io/github/andygrunwald/go-jira?branch=master

Add go-jira: Go client library for Atlassian JIRA

---

README.md

- godoc.org: https://godoc.org/github.com/spf13/afero
- goreportcard.com: https://goreportcard.com/report/github.com/spf13/afero
- gocover.io: https://gocover.io/github.com/spf13/afero

Add afero to miscellaneous category

---

README.md

`ether` is a cross-platform Go package for sending and receiving ethernet frames. Currently it supports Linux, Freebsd, and OS X.

Add ether (for sending/receiving ethernet frames)

---

README.md

httpware is a library for composing/creating http middleware. It also contains a collection of middleware packages. I was not sure whether to put it under "Actual Middlewares" or "Libraries for creating HTTP middlewares", so I went with the latter.
The old pull request is here: https://github.com/avelino/awesome-go/pull/830
Godoc:
https://godoc.org/github.com/nstogner/httpware
Go Report Card:
https://goreportcard.com/report/github.com/nstogner/httpware
Go Cover:
https://gocover.io/github.com/nstogner/httpware
https://gocover.io/github.com/nstogner/httpware/contentware
https://gocover.io/github.com/nstogner/httpware/corsware
https://gocover.io/github.com/nstogner/httpware/errorware
https://gocover.io/github.com/nstogner/httpware/httpctx (no testable code in this pkg) …

Add httpware - composable (net/context based) middleware

---

README.md

We've recently renamed the project and moved to an organisation.
I'm really sorry I haven't included the godoc, gocover, etc. links at the moment. I'll put this on my todo list.

Rename Engi to Engo

---

README.md

required links:
- [godoc.org](https://godoc.org/github.com/schachmat/ingo)
- [goreportcard.com](https://goreportcard.com/report/github.com/schachmat/ingo)
- [gocover.io](https://gocover.io/github.com/schachmat/ingo)
It distinguishes itself from the other choices by its simplicity. It just has around 100 lines of code only using standard library imports and only one exported function `ingo.Parse(appName string)` which is supposed to be used as a drop-in replacement for flags.Parse().

add ingo config utility

---

README.md

This is a really awesome package I found, and noticed it was not on the list.
Package links:
- [godoc.org](https://godoc.org/github.com/jung-kurt/gofpdf)
- [goreportcard.com](https://goreportcard.com/report/github.com/jung-kurt/gofpdf)
Thank you!

Add gofpdf

---

README.md

REST Layer is an API framework heavily inspired by the excellent Python Eve. It helps you create a comprehensive, customizable, and secure REST (graph) API on top of pluggable backend storages with no boiler plate code so you can focus on your business logic.
Godoc: https://godoc.org/github.com/rs/rest-layer
Report Card: https://goreportcard.com/report/github.com/rs/rest-layer
Cover:
http://gocover.io/github.com/rs/rest-layer/rest?version=1.6
http://gocover.io/github.com/rs/rest-layer/graphql
http://gocover.io/github.com/rs/rest-layer/schema
http://gocover.io/github.com/rs/rest-layer/resource

Add rest-layer

---

README.md

- godoc.org: https://godoc.org/github.com/xor-gate/secdl
- goreportcard.com: https://goreportcard.com/report/github.com/xor-gate/secdl
- gocover.io: https://gocover.io/github.com/xor-gate/secdl

Add secdl, Golang implementation of Lighttpd ModSecDownload algorithm

---

README.md

I created a Direct3D9 wrapper for Go because none existed. The API is complete, I created some samples, added a readme with build instructions and documentation, ran go vet and golint on the code and fixed the issues that needed to be fixed, tested the library on two different Windows systems with different compilers and now it is ready to be used by other people so I would like it to be added to this list so people can find it.
Here are the links:
[d3d9 library](https://github.com/gonutz/d3d9)
[godoc](https://godoc.org/github.com/gonutz/d3d9)
[goreportcard](https://goreportcard.com/report/github.com/gonutz/d3d9)
gocover is not able to build the project, I assume because it uses cgo on Windows.

Added d3d9 library.

---

README.md

Hi,
As the masterzen/winrm and masterzen/winrm-cli maintainer, I'd like this library and tool to be added
to the awesome-go list.
This (now mature) library is in used in Packer and some other Go projects.
As of this writing it is maintained, and relatively well tested.
Godoc:
https://godoc.org/github.com/masterzen/winrm
Go Report Card: A+
https://goreportcard.com/report/github.com/masterzen/winrm
Gocover: 86%
https://gocover.io/github.com/masterzen/winrm

Add Go WinRM client library and cli tool

---

README.md

Note that the gocover.io link is broken as I am using `testing.T.Run()` from tip. If you want to know the coverage:
```
ok      github.com/mvdan/sh     0.093s  coverage: 99.8% of statements
?       github.com/mvdan/sh/cmd/shfmt   [no test files]
```
- godoc.org: https://godoc.org/github.com/mvdan/sh
- goreportcard.com: https://goreportcard.com/report/github.com/mvdan/sh
- gocover.io: https://gocover.io/github.com/mvdan/sh

Add github.com/mvdan/sh to text processing

---

README.md

Previously https://github.com/chris-ramon/graphql-go, now https://github.com/graphql-go/graphql

Updated `graphql-go` package new repo URL

---

README.md

🚂  [form](https://github.com/go-playground/form) - decodes url.Values into struct, creating objects as necessary. Dual Array and Full map support.
- [![GoDoc](https://godoc.org/github.com/go-playground/form?status.svg)](https://godoc.org/github.com/go-playground/form)
- [![Go Report Card](https://goreportcard.com/badge/github.com/go-playground/form)](https://goreportcard.com/report/github.com/go-playground/form)
- [![Coverage Status](https://coveralls.io/repos/github/go-playground/form/badge.svg?branch=master)](https://coveralls.io/github/go-playground/form?branch=master)
- [gocover.io](https://gocover.io/github.com/go-playground/form)

Add form url.Values to struct decoder

---

README.md

Update description of https://github.com/go-playground/pool to `a limited consumer goroutine or unlimited goroutine pool for easier goroutine handling and cancellation` as new functionality has been added

update pool description

---

README.md

Update [go-playground/form's](https://github.com/go-playground/form) description as it now also supports Encoding url.Values from a struct along with Decoding.

update go-playground/form's description to include Encoder functionality

---

README.md

Hi, this PR adds [httpexpect](https://github.com/gavv/httpexpect) package.
- godoc.org: https://godoc.org/github.com/gavv/httpexpect
- goreportcard.com: https://goreportcard.com/report/github.com/gavv/httpexpect
- gocover.io or coveralls: https://coveralls.io/github/gavv/httpexpect?branch=master
Boxes:

Add httpexpect

---

README.md

Resolves #1016.
As I mentioned there, @nareix, please let us know if the package has moved and is still deserving to be listed here, then we can update the link and close this PR.
According to https://github.com/avelino/awesome-go/blob/master/CONTRIBUTING.md#reporting-issues, we should wait 1 week.
I'm not sure if that applies if the entire repo is missing and the link is 404. Any thoughts?

Remove aac/h264 package because of 404.

---

README.md

`gvt` was missing from the dependency management list.

Adding gvt to pkg management

---

README.md

Hi, this PR adds [go-unidecode](https://github.com/mozillazg/go-unidecode) package.
- godoc.org: https://godoc.org/github.com/mozillazg/go-unidecode
- goreportcard.com: https://goreportcard.com/report/github.com/mozillazg/go-unidecode
- gocover.io or coveralls: https://coveralls.io/github/mozillazg/go-unidecode
Check list:

add go-unidecode

---

README.md

[Go(lang)](https://golang.org/) client library for [Cachet (open source status page system)](https://cachethq.io/).
- godoc.org: https://godoc.org/github.com/andygrunwald/cachet
- goreportcard.com: https://goreportcard.com/report/github.com/andygrunwald/cachet
- coveralls.io: https://coveralls.io/github/andygrunwald/cachet

Added cachet client library

---

README.md

- github.com repo: https://github.com/crufter/borg
- godoc.org: https://godoc.org/github.com/crufter/borg
- goreportcard.com: https://goreportcard.com/report/github.com/crufter/borg
Gocover is down at the moment so I can't check

Add crufter/borg

---

README.md

Based on previous issues such as [1] and [2] as well as still not accepting
open-source contributions, flattening contributions, closing PRs from users,
editing issues, breaking changes very often and overall poor leadership of
the project this PR removes the iris as a project from this listing.
Thank you.
[1] https://github.com/julienschmidt/httprouter/issues/148
[2] https://github.com/julienschmidt/httprouter/issues/160

Remove iris from listing

---

README.md

[Boom](https://github.com/rakyll/boom) has been renamed to [Hey](https://github.com/rakyll/hey) because of a name conflict with another binary.
The old URL is still working but users are encouraged to change to the new one.
Not sure if it's better to keep both, Boom and Hey, in the list for reference..

Replace Boom with Hey

---

README.md

Hi,
This pull request adds [go-oauth2-server](https://github.com/RichardKnop/go-oauth2-server) to the Authentication & Oauth section.
It is a full and standalone OAuth2 server based on the [specification](http://tools.ietf.org/html/rfc6749#section-4.3).
As far as I know, it is the fullest server implementation of the spec (including all 4 grant types and introspect endpoint).
It is also used in production and very well tested.
- github.com repo: https://github.com/RichardKnop/go-oauth2-server
- godoc.org: https://godoc.org/github.com/RichardKnop/go-oauth2-server
- travis CI link: https://travis-ci.org/RichardKnop/go-oauth2-server

Adding RichardKnop/go-oauth2-server.

---

README.md

Hello. I wrote a library that provides ANSI-colors for output (for terminals). The library supports fmt.Printf/Sprintf functions. Check it out [aurora](https://github.com/logrusorgru/aurora)
[![GoDoc](https://godoc.org/github.com/logrusorgru/aurora?status.svg)](https://godoc.org/github.com/logrusorgru/aurora)
[![WTFPL License](https://img.shields.io/badge/license-wtfpl-blue.svg)](http://www.wtfpl.net/about/)
[![Build Status](https://travis-ci.org/logrusorgru/aurora.svg)](https://travis-ci.org/logrusorgru/aurora)
[![Coverage Status](https://coveralls.io/repos/logrusorgru/aurora/badge.svg?branch=master)](https://coveralls.io/r/logrusorgru/aurora?branch=master)
[![GoReportCard](https://goreportcard.com/badge/logrusorgru/aurora)](https://goreportcard.com/report/logrusorgru/aurora) …

Advanced Console UIs -> add logrusorgru/aurora package

---

README.md

Author of httpware here: go 1.7 introduced the net/context pkg into the http pkg... making the "httpware" unnecessary.

Remove httpware (no longer relevant after go 1.7)

---

README.md

- github.com repo: https://github.com/ngs/go-amazon-product-advertising-api
- godoc.org: https://godoc.org/github.com/ngs/go-amazon-product-advertising-api/amazon
- goreportcard.com: https://goreportcard.com/report/github.com/ngs/go-amazon-product-advertising-api
- coverage service link (gocover, coveralls etc.): https://coveralls.io/github/ngs/go-amazon-product-advertising-api?branch=master

Add amazon-product-advertising-api

---

.travis.yml
repo_test.go

Per discussion in #1217 updating the test to latest stable and adding a log for correct sorting order if a fail occurs.

Update test to 1.7 and display correct sorting order

---

README.md

- github.com repo: https://github.com/udhos/jazigo
- godoc.org: https://godoc.org/github.com/udhos/jazigo/jazigo
- goreportcard.com: https://goreportcard.com/report/github.com/udhos/jazigo
- coverage service link (gocover, coveralls etc.): http://gocover.io/github.com/udhos/jazigo/dev

Added github.com/udhos/jazigo

---

README.md

I can to squeeze into in awesome list? P-please? 😥
- github.com repo: https://github.com/toby3d/telegraph
- godoc.org: https://godoc.org/github.com/toby3d/telegraph
- goreportcard.com: https://goreportcard.com/report/github.com/toby3d/telegraph
- coverage service link (gocover, coveralls etc.): http://gocover.io/github.com/toby3d/telegraph

😶 Added telegraph library

---

README.md

- github.com repo: https://github.com/appleboy/drone-line
- godoc.org: https://godoc.org/github.com/appleboy/drone-line
- goreportcard.com: https://goreportcard.com/report/github.com/appleboy/drone-line
- coverage service link (gocover, coveralls etc.): https://codecov.io/gh/appleboy/drone-line
Please refer to [LINE Business Center](https://business.line.me/en/services/bot).

Add application of Line notification

---

README.md

Copy files and artifacts via SSH using a binary, docker or Drone CI.
- github.com repo: https://github.com/appleboy/drone-scp
- godoc.org: https://godoc.org/github.com/appleboy/drone-scp 
- goreportcard.com: https://goreportcard.com/report/github.com/appleboy/drone-scp
- coverage service link: [![codecov](https://codecov.io/gh/appleboy/drone-scp/branch/master/graph/badge.svg)](https://codecov.io/gh/appleboy/drone-scp)

Add drone-scp tool

---

README.md

Site | Link
---- | ----
github.com | https://github.com/TrueFurby/go-callvis
godoc.org | https://godoc.org/github.com/TrueFurby/go-callvis
goreportcard.com | https://goreportcard.com/report/github.com/TrueFurby/go-callvis
gocover.io | https://gocover.io/github.com/TrueFurby/go-callvis
✅ I have added my package in alphabetical order
✅ I know that this package was not listed before
✅ I have added godoc link to the repo and to my pull request
✅ I have added coverage service link to the repo and to my pull request
✅ I have added goreportcard link to the repo and to my pull request
✅ I have read [Contribution guidelines](https://github.com/avelino/awesome-go/blob/master/CONTRIBUTING.md#contribution-guidelines) and [Quality standard](https://github.com/avelino/awesome-go/blob/master/CONTRIBUTING …

Add "go-callvis" program to Go Tools section

---

README.md

You can trigger downstream Jenkins jobs from Drone CI server or command line.
- github.com repo: https://github.com/appleboy/drone-jenkins
- godoc.org: https://godoc.org/github.com/appleboy/drone-jenkins
- goreportcard.com: https://goreportcard.com/report/github.com/appleboy/drone-jenkins
- coverage service link (gocover, coveralls etc.): https://codecov.io/gh/appleboy/drone-jenkins
[![GoDoc](https://godoc.org/github.com/appleboy/drone-jenkins?status.svg)](https://godoc.org/github.com/appleboy/drone-jenkins) [![Build Status](http://drone.wu-boy.com/api/badges/appleboy/drone-jenkins/status.svg)](http://drone.wu-boy.com/appleboy/drone-jenkins) [![codecov](https://codecov.io/gh/appleboy/drone-jenkins/branch/master/graph/badge.svg)](https://codecov.io/gh/appleboy/drone-jenkins) [![Go Report …

Add trigger Jenkins job tool.

---

README.md

_staticcheck_ is go vet on steroids, applying a ton of static analysis checks you might be used to from tools like ReSharper for C#.
_gosimple_ is a linter for Go source code that specialises on simplifying code.
_unused_ checks Go code for unused constants, variables, functions and types.
github.com: https://github.com/dominikh/go-tools
godoc.org: https://godoc.org/honnef.co/go/tools/cmd
goreportcard.com: https://goreportcard.com/report/github.com/dominikh/go-tools
coverage service: https://gocover.io/github.com/dominikh/go-tools (fails with "Cannot get 'github.com/dominikh/go-tools'" error for some reason)

Add staticcheck, gosimple, unused code analysis tools.

---

README.md

The unconvert program analyzes Go packages to identify unnecessary type conversions; i.e., expressions `T(x)` where `x` already has type `T`.
/cc @mdempsky
github.com repo: https://github.com/mdempsky/unconvert
godoc.org: https://godoc.org/github.com/mdempsky/unconvert
goreportcard.com: https://goreportcard.com/report/github.com/mdempsky/unconvert
coverage service link (gocover, coveralls etc.): https://gocover.io/github.com/mdempsky/unconvert

Add unconvert tool.

---

README.md

This was listed as a nested item.  small fix to change

fix indentation for `github_flavored_markdown`

---

README.md

github.com repo: https://github.com/crgimenes/goConfig
godoc.org: https://godoc.org/github.com/crgimenes/goConfig
goreportcard.com: https://goreportcard.com/report/github.com/crgimenes/goConfig
coverage service link (gocover, coveralls etc.): https://codecov.io/gh/crgimenes/goConfig

Add goConfig in the Configuration category

---

README.md

Request to add https://github.com/knq/chromedp
While chromedp still doesn't have > 80% coverage, we are on track to finish the unit tests for those within the next couple weeks. The coverage that has yet to remaining are trivial lines such as testing all the various `if err != nil { ... }` blocks, as well as specific library / package functional options that only configure/set various system settings that are extremely difficult to generate error conditions for, as well as to do testing on.
- github.com repo:  https://github.com/knq/chromedp/
- godoc.org: https://godoc.org/github.com/knq/chromedp
- goreportcard.com: https://goreportcard.com/report/github.com/knq/chromedp
- coverage service link (gocover, coveralls etc.): …

Updating README.md with link to chromedp

---

README.md

- github.com repo: https://github.com/aphistic/gomol
- godoc.org: https://godoc.org/github.com/aphistic/gomol
- goreportcard.com: https://goreportcard.com/report/github.com/aphistic/gomol
- coverage service link (gocover, coveralls etc.): https://codecov.io/github/aphistic/gomol?branch=master
**Question**: I've only included gomol in this PR but I noticed there's a logrus plugin for Loggly added, does that mean for logging libraries that are extensible that the implementations for those libraries can be added to the list as well? gomol has a number of loggers it supports that are in separate repositories, so that's why I was wondering.  I do make a note of them in the readme, …

Add gomol to logging section

---

README.md

If you look at the README https://github.com/outbrain/orchestrator#orchestrator-upstream-has-moved, they mention it has a new location

Updating Orchestrator's new repo location

---

README.md

The extra space in the markdown prevented it from being rendered properly with [GitHub's new markdown engine](https://github.com/blog/2333-a-formal-spec-for-github-flavored-markdown).

Fix markdown (Vegeta)

---

README.md

I would love it if you would consider `cdp` for `awesome-go`! The project contains a lot of generated code, but I've managed to get the coverage up to ~90% by generating tests as well.
- github.com repo: https://github.com/mafredri/cdp
- godoc.org: https://godoc.org/github.com/mafredri/cdp
- goreportcard.com: https://goreportcard.com/report/github.com/mafredri/cdp
- coverage service link (gocover, coveralls etc.): https://coveralls.io/github/mafredri/cdp?branch=master

Add cdp to README

---

README.md

- github.com repo: https://github.com/posener/wstest
- godoc.org: https://godoc.org/github.com/posener/wstest
- goreportcard.com: https://goreportcard.com/report/github.com/posener/wstest
- coverage service link (gocover, coveralls etc.): https://codecov.io/gh/posener/wstest

Add wstest

---

README.md

Please add `retry` package to Utilities section. Previous request is https://github.com/avelino/awesome-go/pull/1360
- github.com repo: https://github.com/kamilsk/retry
- godoc.org: https://godoc.org/github.com/kamilsk/retry
- goreportcard.com: https://goreportcard.com/report/github.com/kamilsk/retry
- coverage service link (gocover, coveralls etc.): https://coveralls.io/github/kamilsk/retry

add retry to Utilities section

---

README.md

I renamed the package and moved it in the list in alphabetical order.

Rename telegraph to go-telegraph

---

README.md

Please add `clockwerk` package to Utilities category.
- github.com repo: https://github.com/onatm/clockwerk
- godoc.org: https://godoc.org/github.com/onatm/clockwerk
- goreportcard.com: https://goreportcard.com/report/github.com/onatm/clockwerk
- coverage service link (gocover, coveralls etc.): https://coveralls.io/github/onatm/clockwerk

add onatm/clockwerk to Utilities category

---

README.md

This omits the word 'SNES-style' from Ebiten explanation.

Fix a word in Ebiten explanation

---

README.md

The Web Framework section was becoming littered with libraries, routers etc. that should not be considered "Web Frameworks", to that end some libraries have been shuffled to their appropriate sections and a new "Routers" sub-section was created to distinguish URL routers and multiplexers.
I propose that some guidelines or a checklist should be created to help determine what should be considered a "Web Framework" vs "Something Else" to avoid the section becoming cluttered again, but that can be done at a later date.

Cleanup Web Frameworks section

---

README.md

The repo comment on https://github.com/hypersleep/easyssh is "unmaintained". Not sure if that's grounds for removing from the list.

Removing EasySSH

---

README.md

- github.com repo: https://github.com/emersion/go-vcard
- godoc.org: https://godoc.org/github.com/emersion/go-vcard
- goreportcard.com: https://goreportcard.com/report/github.com/emersion/go-vcard
- coverage service link (gocover, coveralls etc.): https://codecov.io/gh/emersion/go-vcard

Adds go-vcard

---

README.md

- github.com repo: https://github.com/hardikbagdi/go-unsplash
- godoc.org: https://godoc.org/github.com/hardikbagdi/go-unsplash/unsplash
- goreportcard.com: https://goreportcard.com/report/github.com/hardikbagdi/go-unsplash
- coverage service link https://coveralls.io/github/hardikbagdi/go-unsplash?branch=master

Adding go-unsplash for unsplash.com API

---

.github/PULL_REQUEST_TEMPLATE.md
CONTRIBUTING.md

We are trying to avoid having hundreds of open Pull Requests. By using
this rule we may close old PRs.
ref #1458

Add a deadline for new PR on CONTRIBUTION

---

README.md

Package links:
github.com:
https://github.com/roylee0704/gron
godoc.org:
https://godoc.org/github.com/roylee0704/gron
goreportcard.com:
https://goreportcard.com/report/github.com/roylee0704/gron
gocover.io:
https://gocover.io/github.com/roylee0704/gron

add gron package -- Cron Jobs in Go.

---

README.md

Thanks for considering. Please re-check. 100% now. Used in very large compute clusters in production.

Added DRMAA job submission library for cluster schedulers.

---

README.md

Package githubql is a client library for accessing GitHub GraphQL API v4 (https://developer.github.com/v4/).
Status: In active early research and development. The API will change when opportunities for improvement are discovered; it is not yet frozen.
[![Build Status](https://travis-ci.org/shurcooL/githubql.svg?branch=master)](https://travis-ci.org/shurcooL/githubql) [![GoDoc](https://godoc.org/github.com/shurcooL/githubql?status.svg)](https://godoc.org/github.com/shurcooL/githubql) [![](https://goreportcard.com/badge/github.com/shurcooL/githubql)](https://goreportcard.com/report/github.com/shurcooL/githubql)
- github.com repo: https://github.com/shurcooL/githubql
- godoc.org: https://godoc.org/github.com/shurcooL/githubql …

Add githubql package.

---

README.md

Here is my application for inclusion of my websocket framework [melody](https://github.com/olahol/melody) in `awsome-go`:
- godoc.org: https://godoc.org/github.com/olahol/melody
- goreportcard.com: https://goreportcard.com/report/github.com/olahol/melody
- gocover.io: https://gocover.io/github.com/olahol/melody

Add github.com/olahol/melody.

---

README.md

Hi,
This pull request adds [jsonhal](https://github.com/RichardKnop/jsonhal) to the utilities section.
It is a useful package to implement structs which JSON encode into HAL format which is one of emerging standards for hyperlinked API responses.
- github.com repo: https://github.com/RichardKnop/jsonhal
- godoc.org: https://godoc.org/github.com/RichardKnop/jsonhal
- goreportcard.com: https://goreportcard.com/report/github.com/RichardKnop/jsonhal
- coverage service link: https://codecov.io/gh/RichardKnop/jsonhal
- travis CI link: https://travis-ci.org/RichardKnop/jsonhal

Add github.com/RichardKnop/jsonhal

---

README.md

Hi,
This pull request adds [glg](https://github.com/kpango/glg) to the logging section.
It is a useful package can quickly output that are colored and leveled logs  with simple syntax
- github.com repo: https://github.com/kpango/glg
- godoc.org: http://godoc.org/github.com/kpango/glg
- goreportcard.com: https://goreportcard.com/report/github.com/kpango/glg
- coverage service link:  [gocover](http://gocover.io/github.com/kpango/glg), [codecov](https://codecov.io/gh/kpango/glg)

Add github.com/kpango/glg

---

README.md

Not the owner of the project.
Looking at the [project's `README`](https://github.com/denisenkom/go-mssqldb), I believe the driver is no longer considered a prototype.

Update description for go-mssqldb database driver

---

README.md

Voila!
* github.com repo: [http://github.com/axiomhq/hyperloglog](http://github.com/axiomhq/hyperloglog)
* godoc.org: [![GoDoc](https://godoc.org/github.com/axiomhq/hyperloglog?status.svg)](https://godoc.org/github.com/axiomhq/hyperloglog)
* goreportcard.com: [![Go Report Card](https://goreportcard.com/badge/github.com/axiomhq/hyperloglog)](https://goreportcard.com/report/github.com/axiomhq/hyperloglog)
* coverage service link: ![cover.run go](https://cover.run/go/github.com/axiomhq/hyperloglog.svg)

add axiomhq/hyperloglog

---

README.md

- github.com repo: https://github.com/mengzhuo/intrinsic
- godoc.org: https://godoc.org/github.com/mengzhuo/intrinsic
- goreportcard.com: https://goreportcard.com/report/github.com/mengzhuo/intrinsic
- coverage service link: http://gocover.io/github.com/mengzhuo/intrinsic/sse2
NOTE:  the coverage is not available due to the code is written in ASSEMBLY.  

add project intrinsic, Use x86 SIMD without writing any assembly code

---

README.md

Hi there,
Just fixing a URL due to an account rename.
Sorry for the trouble.

Update URL of go-unsplash to fix broken URL

---

README.md

Hi Guys!
Please take a look at this mock generator. The main feature is that it generates mocks that do not rely on reflection.
- github.com repo: https://github.com/gojuno/minimock
- godoc.org: http://godoc.org/github.com/gojuno/minimock
- goreportcard.com: https://goreportcard.com/report/github.com/gojuno/minimock
- coverage service link: https://cover.run/go/github.com/gojuno/minimock/tests.svg
Please find tests in the test subpackage, I've tested minimock via the generated code it produces.

Added link to minimock generator

---

README.md

A few anchor links were broken, likely since https://github.com/shurcooL/sanitized_anchor_name/commit/f105e6d6adf3fd73b316934472e2a3c0146fb3a9

Broken anchor links

---

README.md

The repo was transferred to volatiletech, then forked back to vattle with a "moved" message.
(I deleted the usual template, since this is just a rename and I'm not the author, but let me know.)

Update sqlboiler path

---

README.md

Hi again,
Adding a link to the YANFF - Yet Another Network Function Framework to the awesome-go. Framework for creating cloud native network scalable network functions.
- github.com repo: https://github.com/intel-go/yanff
- godoc.org: https://godoc.org/github.com/intel-go/yanff
- goreportcard.com: [![Go Report Card](https://goreportcard.com/badge/github.com/intel-go/yanff)](https://goreportcard.com/report/github.com/intel-go/yanff)
- coverage service link - This is a framework, it has external dependencies for the successful build, which cannot be done online. 

Adding YANFF

---

README.md

- github.com repo: https://github.com/asciimoo/colly
- godoc.org: https://godoc.org/github.com/asciimoo/colly
- goreportcard.com: https://goreportcard.com/report/github.com/asciimoo/colly
- test coverage service: https://cover.run/go/github.com/asciimoo/colly
- build status: https://travis-ci.org/asciimoo/colly

Add colly Scraping Framework

---

README.md

Add ergo proxy under Utilities. #1611
github.com repo: https://github.com/cristianoliveira/ergo
godoc.org: https://godoc.org/github.com/cristianoliveira/ergo
goreportcard.com:  https://goreportcard.com/report/github.com/cristianoliveira/ergo
coverage service link: https://cover.run/go/github.com/cristianoliveira/ergo

Add ergo proxy

---

README.md

https://github.com/bradrydzewski/go.auth says in the description that it is deprecated and it has not been updated since 2013.

Remove go.auth

---

README.md

Some utilities for Persian language in go.
- github.com repo: https://github.com/mavihq/persian
- godoc.org: https://godoc.org/github.com/mavihq/persian
- goreportcard.com: https://goreportcard.com/report/github.com/mavihq/persian 
- coverage service link: https://cover.run/go/github.com/mavihq/persian

added persian repo to list

---

README.md

This (fork of) go-bindata unfortunately is not awesome anymore.
The project is not maintained anymore and has a great bunch of issues.
Currently there are 50 unresolved issue tickets and 18 unmerge pull
requests. Many of the issues make this tool very annoying to use, but
would be easy to fix if it was maintained.
An example issue that is very easy to fix is jteeuwen/go-bindata/issues/148
which brought to make this PR.
See also jteeuwen/go-bindata/issues/165 
Apparently the maintainer has disappeared from earth's surface two years
ago. Let's hope that's not actually true!
(PR template omitted; doesn't seem to be applicable.)

Remove go-bindata

---

README.md

**Links to:**
- github.com repo: https://github.com/emitter-io/emitter
- godoc.org: https://godoc.org/github.com/emitter-io/emitter
- goreportcard.com: https://goreportcard.com/report/github.com/emitter-io/emitter
- coverage service link: https://coveralls.io/github/emitter-io/emitter?branch=master
[![Coverage Status](https://coveralls.io/repos/github/emitter-io/emitter/badge.svg?branch=master)](https://coveralls.io/github/emitter-io/emitter?branch=master)
Latest test coverage report:
```
?       github.com/emitter-io/emitter   [no test files]
ok      github.com/emitter-io/emitter/broker    1.142s  coverage: 57.3% of statements
ok …
```

Adding Emitter

---

README.md

This is simply an update to the URL of an existing package. I've changed my GitHub username and so I'm updating the GitHub link to match the new username.
The GoDoc, GoReportCard and GoCover links and badges in the README have all been already updated and they're all green.

Replace github username in concurrent-writer URL

---

README.md

Add the Joinville -Brazil Go meetup to the list.
@avelino i didn't follow the PR template because it's focused on go repo/packages and not make sense to a new meetup link. is it ok?

Add Joinville Go Meetup

---

README.md

Remove space in the link area. I mistakenly added it, sorry for the mess.
Thank you for merging.

Fix csvutil link

---

README.md

Autocert is a Go maintained project that facilitates provisioning TLS
certificates and starting a server using those certificates.
kevinburke/nacl implements all of the NaCL API's in Go, in a way
that's compatible with the C library offered here:
https://nacl.cr.yp.to.
- github.com repo: https://github.com/kevinburke/nacl
- godoc.org: https://godoc.org/github.com/kevinburke/nacl
- goreportcard.com: https://goreportcard.com/report/github.com/kevinburke/nacl
- coverage service link ([cover.run](https://cover.run/), [gocover](http://gocover.io/), …

Add autocert and nacl

---

README.md

Traefik was under `Authentication`, this PR transfers it under `DevOps Tools`. 
If you think it fits more in another category, do tell me and I'll update the PR.
Cheers

Transfer traefik to DevOps tools

---

README.md

Change slack badge url to be displayed in site, like README. fixes #1751

Change slack badge url, fixes #1751

---

README.md

Very basic update moving link for goes repo from the [unmaintained page](https://github.com/belogik/goes) to the [maintained one](https://github.com/OwnLocal/goes).

Updated goes link to maintained repo

---

README.md

*  github.com repo: https://github.com/tosone/minimp3
*  godoc.org: https://godoc.org/github.com/tosone/minimp3
*  goreportcard.com: https://goreportcard.com/report/github.com/tosone/minimp3
*  coverage service link: [![Coverage Status](https://coveralls.io/repos/github/tosone/minimp3/badge.svg)](https://coveralls.io/github/tosone/minimp3)

add minimp3

---

README.md

I stumbled across a link to a non-existent repo. I do not know if you should remove it or reach out to the owner of the repo. In any case, I thought I should make you aware of the link.
Thanks for all that you do!
- Marcus

Removed go-pkg-rss because the repo does not exist

---

README.md

Hello. I'd like to add my library to the list. For now, I am actively working on tests, and now it fully covered php5 and php7 parsing rules, fully tested creating and traversing nodes, and the lexer is basically tested.
- github.com repo: https://github.com/z7zmey/php-parser
- godoc.org: https://godoc.org/github.com/z7zmey/php-parser
- goreportcard.com: https://goreportcard.com/report/github.com/z7zmey/php-parser
- coverage service link: https://www.exago.io/project/github.com/z7zmey/php-parser

Add php-parser

---

README.md

v2.0 is advertised in the readme but is not open source and a commercial service

remove inconshreveable/ngrok - no longer developed

---

README.md

Removed go-gml, goqt; no activity since 2015, 2016, respectively.

Removed go-gml, goqt

---

README.md

Oracle driver for Go, using the ODPI-C driver
https://github.com/go-goracle/goracle
https://godoc.org/gopkg.in/goracle.v2
https://goreportcard.com/report/github.com/go-goracle/goracle

Added goracle

---

README.md

Package provides a generic interface to encoders and decoders
[![GoDoc](https://godoc.org/github.com/mickep76/encdec?status.svg)](https://godoc.org/github.com/mickep76/encdec)
[![codecov](https://codecov.io/gh/mickep76/encdec/branch/master/graph/badge.svg)](https://codecov.io/gh/mickep76/encdec)
[![Build Status](https://travis-ci.org/mickep76/encdec.svg?branch=master)](https://travis-ci.org/mickep76/encdec)
[![Go Report Card](https://goreportcard.com/badge/github.com/mickep76/encdec)](https://goreportcard.com/report/github.com/mickep76/encdec)
[![License](https://img.shields.io/badge/License-Apache%202.0-blue.svg)](https://github.com/mickep76/mlfmt/blob/master/LICENSE)

add encdec package

---

README.md

The original Boostport/avatica database/sql driver was donated to the Apache Calcite project (part of the Apache Foundation).
The code has been imported to github.com/apache/calcite-avatica-go and all new development will continue in that repository.
This PR changes the url from github.com/Boosport/avatica to github.com/apache/calcite-avatica

Update repository for avatica database driver

---

README.md

Cardiff (Wales) meetup added in accordance with formatting of other meetups on README.md
No package being added - only link to Meetup page

Add Cardiff meetup to README.md

---

README.md

Add `lstags`: Tool and API to sync Docker images across different registries. 
- github.com repo: https://github.com/ivanilves/lstags
- godoc.org:  https://godoc.org/github.com/ivanilves/lstags/api/v1
- goreportcard.com: https://goreportcard.com/report/github.com/ivanilves/lstags
- coverage service link: https://coveralls.io/github/ivanilves/lstags?branch=master

Add lstags

---

README.md

This is a pull request to add [kelseyhightower/envconfig](https://github.com/kelseyhightower/envconfig). I believe these meet the [quality standards](https://github.com/avelino/awesome-go/blob/master/CONTRIBUTING.md#quality-standard).
- github.com repo: https://github.com/kelseyhightower/envconfig
- godoc.org: https://godoc.org/github.com/kelseyhightower/envconfig
- goreportcard.com: [![Go Report Card](https://goreportcard.com/badge/github.com/kelseyhightower/envconfig)](https://goreportcard.com/report/github.com/kelseyhightower/envconfig)
- coverage service link: [cover.run](http://cover.run/go/github.com/kelseyhightower/envconfig?tag=golang-1.10)
Checklist:

Add kelseyhightower/envconfig to Configurations section

---

README.md

Add deque (fast ring-buffer double-ended queue) to README.
**Reason for Posting**
For a number of projects I needed a high-performance deque that is efficient with its use of memory.  There are many queue implementations, but few that the performance characteristics I needed in a double-ended queue.  After not finding what I needed I spent time carefully writing my own.  Since I have found it so highly useful in many of my own projects, I imagine there are others with a similar need, and I wanted to share the work I put into addressing that need.  Here is the deque implementation with thorough documentation and excellent test coverage.
**Package Links:**
- github.com repo: https://github.com/gammazero/deque
- godoc.org: [![GoDoc](https://godoc.org/github.com/gammazero/deque?status.svg)](ht …

Add deque to README.md

---

README.md

- github.com repo: https://github.com/novalagung/gubrak
- godoc.org: https://godoc.org/github.com/novalagung/gubrak
- goreportcard.com: [![Go Report Card](https://goreportcard.com/badge/github.com/novalagung/gubrak?nocache=1)](https://goreportcard.com/report/github.com/novalagung/gubrak?nocache=1)
- coverage service link: [![cover.run](https://cover.run/go/github.com/novalagung/gubrak.svg?style=flat&tag=golang-1.10)](https://cover.run/go?tag=golang-1.10&repo=github.com%2Fnovalagung%2Fgubrak) …

add gubrak

---

README.md

Add `go-critic` linter in Code Analysis.
- github.com repo: https://github.com/go-critic/go-critic
- godoc.org: 
- goreportcard.com: https://goreportcard.com/report/github.com/go-critic/go-critic

Add go-critic linter.

---

README.md

The satori UUID package is no longer maintained. The [gofrs](https://github.com/gofrs) organization is actively maintaining a fork of this package.
- github.com repo: https://github.com/gofrs/uuid
- godoc.org: https://godoc.org/github.com/gofrs/uuid
- goreportcard.com: https://goreportcard.com/report/github.com/gofrs/uuid
- coverage service link: https://coveralls.io/github/gofrs/uuid
Thanks for …

Add gofrs UUID package

---

README.md

Just escaping the `*` in the immortal description :)

Fix escaping on immortal/immortal package

---

README.md

Shameless self-promotion of my own books, but since the feedback was so positive so far, I thought someone would enjoy stumbling upon them in this list. Feel free to decline, though, if you don't want me to add my own links :)
**TODOs:**

Add two books to E-Books section

---

README.md

The new location for pop (and soda) repository is https://github.com/gobuffalo/pop. See https://github.com/markbates/pop#notice-this-repo-has-moved
**This is just an update, both packages are already listed**.

Update pop/soda repository location

---

README.md

[Acra](https://github.com/cossacklabs/acra) is not a single library, but a set of client-side and server-side services, working as network encryption proxy to protect database-based applications from data leaks, combining strong selective encryption, SQL injections prevention and intrusion detection system.
- github.com repo: https://github.com/cossacklabs/acra/
- godoc.org: [![](https://godoc.org/github.com/cossacklabs/acra?status.svg)](https://godoc.org/github.com/cossacklabs/acra)
- goreportcard.com: [![](https://goreportcard.com/badge/github.com/cossacklabs/acra)](https://goreportcard.com/report/github.com/cossacklabs/acra)
- coverage service link  [![](https://coveralls.io/repos/github/cossacklabs/themis/badge.svg?branch=master)](https://coveralls. …

add Acra, database protection suite [security]

---

README.md

there is a redirect which works already but might as well have the destination. added a few words to description too.
[edit: this is just an update of an existing entry]

fortio existing entry link update (new org)

---

README.md

Hi. I'd like to add my computational geometry library which does triangulation of lines and polygons. Below are the required things. Please let me know if you have some more requests or if something is missing.
Thanks for your time!
[triangolatte](https://github.com/tchayen/triangolatte) – 2D triangulation library. Allows translating lines and polygons (both based on points) to the language of GPUs.
[![](https://godoc.org/github.com/tchayen/triangolatte?status.svg)](https://godoc.org/github.com/tchayen/triangolatte)
[![](https://goreportcard.com/badge/github.com/tchayen/triangolatte)](https://goreportcard.com/report/github.com/tchayen/triangolatte)
[![](https://coveralls.io/repos/github/tchayen/triangolatte/badge.svg?branch=master)](https://coveralls.io/github/tchayen/triangolatte?branch=m …

Add triangolatte

---

README.md

According to #2100 and #2101 
from: https://github.com/coreos/fleet
> fleet is no longer developed or maintained by CoreOS. After February 1, 2018, a fleet container image will continue to be available from the CoreOS Quay registry, but will not be shipped as part of Container Linux. CoreOS instead recommends Kubernetes for all clustering needs.
from: https://github.com/rakyll/coop
> Note: This package became obsolete. I started it when I was learning Go a couple of years ago. I see so many better ways to implement them all now, so don't keep using this package as an ultimate reference.

Remove fleet and coop

---

CONTRIBUTING.md

Fixed the goreportcard URL by removing the "report" part which was leading to a 404 page. Now the URL points to the homepage, I assume this is what was intended.

Fix goreportcard URL

---

README.md

https://github.com/spate/vectormath
No docs, no tests, no #examples
closes #2044

Remove spate/vectormath

---

README.md

```
Update: I created tui-go as an experiment because I wanted a simpler way of creating terminal-based user interfaces. It has since then become a project, with all the work that comes with it. While it's been really fun, unfortunately I'm no longer able to maintain this project.
```
Removing tui, because it's no longer maintained. I am also adding a replacement. PR: https://github.com/avelino/awesome-go/pull/2163
- github.com repo: - 
- godoc.org: -
- goreportcard.com: -
- coverage service link: - …

Remove tui-go, because it's no longer maintained

---

README.md

Closes #2170 
No tests, latest commit May 8, 2016, no one watches issues and PRs.

remove websysd/websysd

---

README.md

closes #2047 
no docs, no README, no examples, many warnings and errors on goreport card.

remove go.matrix

---

README.md

Hello, these are the links to the `mimetype` package:
- github.com repo: https://github.com/gabriel-vasile/mimetype
- godoc.org: https://godoc.org/github.com/gabriel-vasile/mimetype
- goreportcard.com: https://goreportcard.com/report/github.com/gabriel-vasile/mimetype
- coverage service link: [coveralls.io/github/gabriel-vasile/mimetype](https://coveralls.io/github/gabriel-vasile/mimetype)
Thanks for your time!

Add mimetype package

---

README.md

> A tiny library for linear interpolation. O(log(N)) per evaluation for N control points.
- github.com repo: https://github.com/sgreben/piecewiselinear
- godoc.org: https://godoc.org/github.com/sgreben/piecewiselinear
- goreportcard.com: https://goreportcard.com/report/github.com/sgreben/piecewiselinear
- coverage service link [![cover.run](https://cover.run/go/github.com/sgreben/piecewiselinear/.svg?style=flat&tag=golang-1.10)](https://cover.run/go?tag=golang-1.10&repo=github.com%2Fsgreben%2Fpiecewiselinear%2F) …

Add piecewiselinear

---

README.md

- github.com repo: https://github.com/borderstech/logmatic
- godoc.org: http://godoc.org/github.com/borderstech/logmatic
- goreportcard.com: https://goreportcard.com/report/github.com/borderstech/logmatic
- coverage service link: https://codecov.io/gh/borderstech/logmatic

Add logmatic

---

CONTRIBUTING.md

Require english documentation

---

README.md

go.uuid is currently the most starred uuid repo for go. However, it is basically unmaintained and contained at least one critical security, which has been fixed by PR but took half a year to be merged, since the owner is not really active (satori/go.uuid#75). There is an actively maintained fork at https://github.com/gofrs/uuid which is already listed here already. go.uuid should be removed.
See 
satori/go.uuid#75
satori/go.uuid#73
https://github.com/gofrs/uuid#project-history

Remove go.uuid

---

README.md

While searching an oauth framework, i found osin pointing to https://github.com/RangelReale/osin which has been archived. It is a fork of https://github.com/openshift/osin which is even with the fork, so the link should be changed. 
However, it does not seem very active at all. So maybe it should be removed entirely? I am interested in other opinions here.

Change osin URL/Remove osin?

---

README.md

Adding the `github.com/JoshuaDoes/gofuckyourself` package to `Text Processing` -> `Utility`.
**Links**:
- github.com repo: https://github.com/JoshuaDoes/gofuckyourself
- godoc.org: https://godoc.org/github.com/JoshuaDoes/gofuckyourself
- goreportcard.com: https://goreportcard.com/report/github.com/JoshuaDoes/gofuckyourself
- coverage service link: [![cover.run](https://cover.run/go/github.com/JoshuaDoes/gofuckyourself.svg?style=flat&tag=golang-1.10)](https://cover.run/go?tag=golang-1.10&repo=github.com%2FJoshuaDoes%2Fgofuckyourself)
**I confirm that**:
- [✓] I have added my package in alphabetical order.
- [✓] I have an appropriate description with proper grammar.
- [✓] I know that this package was not listed before.
- [✓] I have added the godoc link to the repo and to my pull request.
- …

Add gofuckyourself

---

README.md

Go-AWS-Auth is deprecated and archived.
https://github.com/smartystreets/go-aws-auth

Deprecate Go-AWS-Auth

---

README.md

`github.com/franela/goreq` is archived. Should we remove it?

Deprecate github.com/franela/goreq

---

README.md

`github/facebookgo/httpcontrol` is archived. Should we remove it?

Deprecate github/facebookgo/httpcontrol

---

README.md

`github.com/markbates/validate` is archived. Should we remove it?

Deprecate github.com/markbates/validate

---

README.md

`github.com/codehack/go-relax` is archived. Should we remove it?

Deprecate github.com/codehack/go-relax

---

README.md

`github.com/volatile/core` is archived. Should we remove it?

Deprecate github.com/volatile/core

---

README.md

`github.com/daryl/zeus` is archived. Should we remove it?

Deprecate github.com/daryl/zeus

---

README.md

`github.com/mvdan/interfacer` is archived. Should we remove it?

Deprecate github.com/mvdan/interfacer

---

README.md

`github.com/GoClipse/goclipse` is archived. Should we remove it?

Deprecate github.com/GoClipse/goclipse

---

README.md

- github.com repo (gitea instance): https://git.jonasfranz.software/JonasFranzDEV/gitea-github-migrator
- godoc.org: https://godoc.org/git.jonasfranz.software/JonasFranzDEV/gitea-github-migrator
- goreportcard.com: https://goreportcard.com/report/git.jonasfranz.software/JonasFranzDEV/gitea-github-migrator
- coverage service link: https://coverage.jonasfranz.software/projects/1/ (not public, only badge available)

Add gitea-github-migrator

---

Dockerfile

ref: #1903 
stdout:
```
awesome-go ~/awesome-go > docker-compose up webhook
Starting awesomego_webhook_1
Attaching to awesomego_webhook_1
webhook_1  | repo.go:11:2: cannot find package "github.com/shurcooL/github_flavored_markdown" in any of:
webhook_1  |    /usr/local/go/src/github.com/shurcooL/github_flavored_markdown (from $GOROOT)
webhook_1  |    /go/src/github.com/shurcooL/github_flavored_markdown (from $GOPATH)
awesomego_webhook_1 exited with code 1
```

fixed install github_flavored_markdown package

---

README.md

I think the Google Drive client was added to the wrong place in the README. This PR fixes that.

Google Drive client is not a cli parser library

---

README.md

- Issue: the two listed flac libraries are named the same and have the same description
- Added a more detailed description that makes it clear the two libs do not have the same capabilities

Disambiguate listed flac libraries

---

README.md

- github.com repo: https://github.com/mum4k/termdash
- godoc.org: [![Doc Status](https://godoc.org/github.com/mum4k/termdash?status.png)](https://godoc.org/github.com/mum4k/termdash)
- goreportcard.com: [![Go Report Card](https://goreportcard.com/badge/github.com/mum4k/termdash)](https://goreportcard.com/report/github.com/mum4k/termdash)
- coverage service link: [![Coverage Status](https://coveralls.io/repos/github/mum4k/termdash/badge.svg?branch=master)](https://coveralls.io/github/mum4k/termdash?branch=master)

Adding termdash to Advanced Console UIs.

---

README.md

- github.com repo: https://github.com/socifi/jazz
- godoc.org: https://godoc.org/github.com/socifi/jazz
- goreportcard.com: https://goreportcard.com/report/github.com/socifi/jazz
- coverage service link: Coverage 70% (by running `go test -cover`). Must be tested manually. For obvious reasons, it needs RabbitMQ up and running.

Added socif/jazz

---

README.md

**github.com/emvi/hide**
- description: ID type with marshalling to/from hash to prevent sending IDs to clients.
- detailed article: https://medium.com/emvi/golang-transforming-ids-to-a-userfriendly-representation-in-web-applications-85bf2f7d71c5
- github.com repo: https://github.com/emvi/hide
- godoc.org: https://godoc.org/github.com/emvi/hide
- goreportcard.com: https://goreportcard.com/report/github.com/emvi/hide
- coverage service link: https://circleci.com/gh/emvi/hide (82.3%)
**github.com/emvi/null**
- description: Nullable Go types that can be marshalled/unmarshalled to/from JSON.
- github.com repo: https://github.com/emvi/null
- godoc.org: https://godoc.org/github.com/emvi/null
- goreportcard.com: https://goreportcard.com/report/github.com/emvi/null …

Removed gondolier, added 'hide' and 'null'.

---

README.md

Hello, I see uber-go/dig is missing.
- github.com repo: https://github.com/uber-go/dig
- godoc.org: https://godoc.org/go.uber.org/dig
- goreportcard.com: https://goreportcard.com/report/github.com/uber-go/dig
- coverage service link https://codecov.io/gh/uber-go/dig/branch/master

Adding uber/dig

---

README.md

Welcome to Taipei 101 in Taiwan and we also joined the GDN ([Go Developer Network](https://blog.golang.org/go-developer-network)).
See https://www.meetup.com/golang-taipei-meetup/

Add golang meetup in Taipei

---

README.md

- github.com repo: https://github.com/emvi/gondolier
- godoc.org: https://godoc.org/github.com/emvi/gondolier
- goreportcard.com: https://goreportcard.com/report/github.com/emvi/gondolier
- coverage service link: https://circleci.com/gh/emvi/gondolier (90.5%)
I've removed this library because I did not intend to support it anymore, but I changed my mind. So this PR re-adds Gondolier with updated link and some code quality improvements (100% on goreportcard + fixed CircleCI build).

Add gondolier database schema migration.

---

README.md

this pull request adds [crunch](https://github.com/superwhiskers/crunch), a library that provides buffers for handling various datatypes easily
- [repo](https://github.com/superwhiskers/crunch)
- [godoc](https://godoc.org/github.com/superwhiskers/crunch)
- [goreportcard](https://goreportcard.com/report/github.com/superwhiskers/crunch)
- [coverage](https://codecov.io/gh/superwhiskers/crunch)

add crunch

---

README.md

A high level wrapper around acme/autocert, hoping to get everyone to always use SSL even for trivial projects.
Links:
github.com repo: https://github.com/adrianosela/sslmgr
godoc.org: https://godoc.org/github.com/adrianosela/sslmgr
goreportcard.com: https://goreportcard.com/report/github.com/adrianosela/sslmgr
Coverage Service: https://gocover.io/github.com/adrianosela/sslmgr
(Edited coverage since PR was created)
```
09:44 $ go test --cover
.............................
29 total assertions
...
32 total assertions
...
36 total assertions
PASS
coverage: 81.4% of statements
ok  	github.com/adrianosela/sslmgr	0.070s
```
Tested all testable packages

Add sslmgr

---

README.md

#2433 
- github.com repo: https://github.com/pelletier/go-toml
- godoc.org: https://godoc.org/github.com/pelletier/go-toml
- goreportcard.com: https://goreportcard.com/report/github.com/pelletier/go-toml
- coverage service link: [![codecov](https://codecov.io/gh/pelletier/go-toml/branch/master/graph/badge.svg)](https://codecov.io/gh/pelletier/go-toml)

Add go-toml

---

README.md

- github.com repo: https://github.com/russoj88/stl
- godoc.org: https://godoc.org/github.com/russoj88/stl/stl
- goreportcard.com: https://goreportcard.com/report/github.com/russoj88/stl
- coverage service link: Didn't find one that supports go 1.12

Add STL library

---

README.md

As of Go v1.11, Go modules are the official, toolchain-supported mechanism for package and dependency management. They are available for use as of v1.11 and will be the default as of Go v1.13. See [this official blog post](https://blog.golang.org/modules2019) for further information.
Additionally, work on dep is now described as geared "primarily towards the development of an alternative prototype for versioning behavior in the toolchain" [_source_](https://github.com/golang/dep#dep).
As many users of Go will reference the awesome-go repo for suggestions and tooling, this PR is intended to guide users towards the official toolchain mechanism for package management.
**Links**
- github.com repo: https://github.com/golang/go/wiki/Modules
- godoc.org: N/A …

Go modules are the official package management going forward

---

README.md

MalShare is a free Malware repository providing researchers access to samples, malicous feeds, and Yara results.
- github.com repo: https://github.com/MonaxGT/gomalshare
- godoc.org: https://godoc.org/github.com/MonaxGT/gomalshare
- goreportcard.com: https://goreportcard.com/report/github.com/MonaxGT/gomalshare
- https://app.codacy.com/app/MonaxGT/gomalshare?utm_source=github.com&utm_medium=referral&utm_content=MonaxGT/gomalshare&utm_campaign=Badge_Grade_Dashboard
- coverage service link : https://gocover.io/github.com/MonaxGT/gomalshare

Added gomalshare package

---

README.md

- github.com repo: https://github.com/blind-oracle/riemann-relay
- godoc.org: Not applicable (server application)
- goreportcard.com: https://goreportcard.com/report/github.com/blind-oracle/riemann-relay
- coverage service link: https://coveralls.io/github/blind-oracle/riemann-relay
- [*] I know that this package was not listed before.
- [*] I have added coverage service link to the repo and to my pull request.
- [*] I have added goreportcard link to the repo and to my pull request.
- [*] I have read [Contribution …

Add riemann-relay to Server Applications

---

README.md

This patch adds the official Go client for Elasticsearch.
- github.com repo: https://github.com/elastic/go-elasticsearch
- godoc.org: https://godoc.org/github.com/elastic/go-elasticsearch
- goreportcard.com: https://goreportcard.com/report/github.com/elastic/go-elasticsearch
- coverage service link: https://codecov.io/gh/elastic/go-elasticsearch?branch=master

Add go-elasticsearch

---

README.md

The SA gometalinter is deprecated in favour of [GolangCI](https://github.com/golangci/golangci-lint) and the project is archived.

Removing gometalinter (deprecated)

---

README.md

Converter from SDDL-string to user-friendly JSON. SDDL consist of four part: Owner, Primary Group, DACL, SACL. 
- github.com repo: https://github.com/MonaxGT/gosddl
- godoc.org: https://godoc.org/github.com/MonaxGT/gosddl
- goreportcard.com: https://goreportcard.com/report/github.com/MonaxGT/gosddl
- https://codeclimate.com/github/MonaxGT/gosddl/maintainability
- coverage service link : https://gocover.io/github.com/MonaxGT/gosddl

Added gosddl package

---

README.md

- github.com repo: https://github.com/mvmaasakkers/go-problemdetails
- godoc.org: [![GoDoc](https://godoc.org/github.com/mvmaasakkers/go-problemdetails?status.svg)](https://godoc.org/github.com/mvmaasakkers/go-problemdetails)
- goreportcard.com: [![Go Report Card](https://goreportcard.com/badge/github.com/mvmaasakkers/go-problemdetails)](https://goreportcard.com/report/github.com/mvmaasakkers/go-problemdetails)
- coverage service link: [![Coverage Status](https://coveralls.io/repos/github/mvmaasakkers/go-problemdetails/badge.svg?branch=master)](https://coveralls.io/github/mvmaasakkers/go-problemdetails?branch=master)

Add go-problemdetails package

---

README.md

- github.com repo: https://github.com/adamluzsi/testcase
- godoc.org: http://godoc.org/github.com/adamluzsi/testcase
- goreportcard.com: https://goreportcard.com/report/github.com/adamluzsi/testcase
- coverage service link [![codecov](https://codecov.io/gh/adamluzsi/testcase/branch/master/graph/badge.svg)](https://codecov.io/gh/adamluzsi/testcase)

add testcase package to the testing section

---

README.md

- github.com repo: https://github.com/aerogo/codetree
- godoc.org: [![Godoc][godoc-image]][godoc-url]
- goreportcard.com: [![Report][report-image]][report-url]
- coverage service link: [![Coverage][coverage-image]][coverage-url]
[godoc-image]: https://godoc.org/github.com/aerogo/codetree?status.svg
[godoc-url]: https://godoc.org/github.com/aerogo/codetree
[report-image]: https://goreportcard.com/badge/github.com/aerogo/codetree
[report-url]: https://goreportcard.com/report/github.com/aerogo/codetree
[coverage-image]: https://codecov.io/gh/aerogo/codetree/graph/badge.svg
[coverage-url]: https://codecov.io/gh/aerogo/codetree

Add aerogo/codetree

---

README.md

`script` is a Go library for doing the kind of tasks that shell scripts are good at: reading files, executing subprocesses, counting lines, matching strings, and so on.
- [GitHub](https://github.com/bitfield/script)
- [GoDoc](http://godoc.org/github.com/bitfield/script)
- [Go Report Card](https://goreportcard.com/report/github.com/bitfield/script)
Test coverage (none of the suggested free coverage services are working right now):
go test -cover
PASS
coverage: 91.7% of statements
ok      github.com/bitfield/script      0.048s

Add 'script', a library for DevOps tasks

---

README.md

Good day!
This is tool for parse JSON-like logs for collecting unique fields. Main purpose to collect JSON-data with typical events and fields it is useful when you want to create mapping schema for database and you want to reduce the risks of forgotten fields.
- github.com repo: https://github.com/MonaxGT/parsefields
- godoc.org: https://godoc.org/github.com/MonaxGT/parsefields
- goreportcard.com: https://goreportcard.com/report/github.com/MonaxGT/parsefields
- coverage service link: https://gocover.io/github.com/MonaxGT/parsefields

Add parsefields package

---

README.md

Project called "Banshee" no longer exists, link goes to 404
Related to issue #2036

Remove Banshee

---

README.md

As requested by the author on slack, this is more descriptive for the Goa service.

Fix Goa name,url and description to more accurate

---

README.md

* Add onnx-go 
* github.com repo: https://github.com/owulveryck/onnx-go
* godoc.org: https://godoc.org/github.com/owulveryck/onnx-go
* goreportcard.com: https://goreportcard.com/report/github.com/owulveryck/onnx-go
* travis build: https://travis-ci.com/owulveryck/onnx-go
* coverage service: https://codecov.io/gh/owulveryck/onnx-go/
* Update README.md

Add onnx-go

---

README.md

`gotoprom` offers a type-safe metrics builder wrapper library for the official Prometheus client.
- github.com repo: https://github.com/cabify/gotoprom
- godoc.org: [![GoDoc](https://godoc.org/github.com/cabify/gotoprom?status.svg)](https://godoc.org/github.com/cabify/gotoprom)
- goreportcard.com: [![Go Report Card](https://goreportcard.com/badge/github.com/cabify/gotoprom)](https://goreportcard.com/report/github.com/cabify/gotoprom)
- coverage service link [![Coverage Status](https://coveralls.io/repos/github/cabify/gotoprom/badge.svg?branch=master)](https://coveralls.io/github/cabify/gotoprom?branch=master)

Add github.com/cabify/gotoprom library

---

README.md

Hasgo (A code generator for Go slices influenced by Haskell)
- github.com repo: https://github.com/DylanMeeus/hasgo
- godoc.org: https://godoc.org/github.com/DylanMeeus/hasgo
- goreportcard.com:https://goreportcard.com/report/github.com/DylanMeeus/hasgo
- coverage service link: https://gocover.io/github.com/DylanMeeus/hasgo/types
(I ran the coverage on hasgo/types because those are the actual functions that get generated rather than other folder such as examples).

Add hasgo to generate tools

---

README.md

- github.com repo: https://github.com/go-gilbert/gilbert
- godoc.org: https://godoc.org/github.com/go-gilbert/gilbert
- goreportcard.com: https://goreportcard.com/report/github.com/go-gilbert/gilbert
- coverage service link [![cover.run](https://cover.run/go/github.com/go-gilbert/gilbert.svg?style=flat&tag=golang-1.12)](https://cover.run/go?tag=golang-1.12&repo=github.com%2Fgo-gilbert%2Fgilbert) …

Add Gilbert task runner

---

README.md

- github.com repo: https://github.com/lalamove/konfig
- godoc.org: https://godoc.org/github.com/lalamove/konfig
- goreportcard.com: https://goreportcard.com/report/github.com/lalamove/konfig
- coverage service link [![codecov](https://codecov.io/gh/lalamove/konfig/branch/master/graph/badge.svg)](https://codecov.io/gh/lalamove/konfig)

Add github.com/lalamove/konfig

---

README.md

- github.com repo: https://github.com/alexedwards/scs
- godoc.org: https://godoc.org/github.com/alexedwards/scs
- goreportcard.com: https://goreportcard.com/report/github.com/alexedwards/scs
- coverage service link: https://gocover.io/github.com/alexedwards/scs (91.2%)

Add alexedwards/scs

---

README.md

- github.com repo: https://github.com/logrange/linker
- godoc.org: [![GoDoc](https://godoc.org/github.com/logrange/linker?status.png)](https://godoc.org/github.com/logrange/linker)
- goreportcard.com: [![Go Report Card](https://goreportcard.com/badge/github.com/logrange/linker)](https://goreportcard.com/report/github.com/logrange/linker)
- coverage service link [![codecov](https://codecov.io/gh/logrange/linker/branch/master/graph/badge.svg)](https://codecov.io/gh/logrange/linker) …

add linker to awesome-go misc section

---

README.md

- github.com repo: https://github.com/brianvoe/sjwt
- godoc.org: https://godoc.org/github.com/brianvoe/sjwt
- goreportcard.com: https://goreportcard.com/report/github.com/brianvoe/sjwt
- coverage service link: https://codecov.io/github/brianvoe/sjwt

Added to authentication

---

README.md

- github.com repo: https://github.com/thazelart/terraform-validator
- godoc.org: https://godoc.org/github.com/thazelart/terraform-validator
- goreportcard.com: https://goreportcard.com/report/github.com/thazelart/terraform-validator
- coverage service link: https://codecov.io/gh/thazelart/terraform-validator

Add thazelart/terraform-validator in validation

---

README.md

changes:
- moved jaeger, profile, and tracer to the new section Performance
- removed go-torch because it's archived
- removed netbug because it doesn't have any tests

add performance section

---

README.md

This is a sad day: `rkt` has been [officially archived by the CNCF](https://www.cncf.io/blog/2019/08/16/cncf-archives-the-rkt-project/). 
It probably makes sense to remove it from this list. 😢 This diff does exactly that.

Removing rkt: it has been archived by the CNCF :(

---

README.md

- github.com repo: https://github.com/mailgun/mailgun-go
- godoc.org: https://godoc.org/github.com/mailgun/mailgun-go
- goreportcard.com: https://goreportcard.com/report/github.com/mailgun/mailgun-go
- coverage service link: https://gocover.io/github.com/mailgun/mailgun-go

Added the mailgun-go library to the list.

---

README.md

Note: I don't use any online coverage services, except local tools. The coverage is either 100% or 0% where project is still in progress :-)
The godoc should update their indexes.
- github.com repo: https://github.com/isbm/textwrap
- goreportcard.com: https://goreportcard.com/report/github.com/isbm/textwrap

Add implementation of Python's module "textwrap"

---

README.md

- Last commit over 5 years ago
- Author doesn't respond to requests or PRs
- Also no OSS license (not strictly required for inclusion in awesome-go,
but legally, this code can't be used by anyone other than the author,
without some sort of license)

Remove go-couchdb: Unmantained

---

README.md

**gnet: A high-performance, lightweight, nonblocking, event-loop networking library written in pure Go.**
- github.com repo: https://github.com/panjf2000/gnet
- godoc.org: [![Doc for panjf2000/gnet](https://img.shields.io/badge/api-reference-blue.svg?style=flat-square)](https://gowalker.org/github.com/panjf2000/gnet?lang=en-US)
- goreportcard.com: [![Go Report Card](https://goreportcard.com/badge/github.com/panjf2000/gnet?style=flat-square)](https://goreportcard.com/report/github.com/panjf2000/gnet)
- coverage service link: [![codecov for panjf2000/gnet](https://img.shields.io/codecov/c/github/panjf2000/gnet?style=flat-square)](https://codecov.io/gh/panjf2000/gnet)

Add gnet to the networking section

---

README.md

Added https://m-zajac.github.io/json2go (fixed according to comment in #2671)
---
- github.com repo: https://github.com/m-zajac/json2go
- godoc.org: https://godoc.org/github.com/m-zajac/json2go
- goreportcard.com: https://goreportcard.com/report/github.com/m-zajac/json2go
- coverage service link: https://gocover.io/github.com/m-zajac/json2go
---
I'd like to propose adding this little utility that I think is pretty convenient for go community :)
It's a bit different than existing tools, especially works well when provided an array of docs that are not exactly the same.
Code is written purely in go, and web page uses webassembly created by go compiler.
I've tried my best to ensure good code quality and test coverage.
Few examples to show what this tool can do can be found here: …

Add m-zajac/json2go

---

README.md

In case it's useful to others, I thought I'd add a golang code website. Haven't added godoc/report card links as I didn't think they'd be applicable.
--
- godoc.org:

Add golangcode to tutorial links

---

README.md

When checking the frameworks in the list I saw at least 2 are marked as unmaintained by the "maintainer":
https://github.com/go-gem/gem
unmaintained
https://github.com/gravityblast/traffic
unmaintained

Remove frameworks flagged as unmaintained

---

README.md

Add Coursera Specialization  : Programming with Google Go in Tutorials section
- godoc.org:

Add Programming with Google Go Specialization

---

README.md

Hi there!
With this PR, I would like to remove the [Gomail](https://github.com/go-gomail/gomail/) package.
It's unmaintained since 2016. Several forks exist, but I wasn't able to identify one as a valid replacement fitting the requirements to be added to the awesome list.
I'd suggest that if one of the owners of a fork wants it to be added to the list they should create a separate PR for this.
Kind regards, 3stadt

Remove Gomail since it's unmaintained since 2016.

---

README.md

@kirillDanshin, I fixed the goreportcard issues which you mentioned in #2692.
- github.com repo: https://github.com/ansd/lastpass-go
- godoc.org: https://godoc.org/github.com/ansd/lastpass-go
- goreportcard.com: https://goreportcard.com/report/github.com/ansd/lastpass-go
- coverage service link ([gocover](http://gocover.io/), [coveralls](https://coveralls.io/) etc.): https://coveralls.io/github/ansd/lastpass-go?branch=master …

Add lastpass-go

---

README.md

abutil package is no longer maintained, so it should be deleted from the list.

Removed unmaintained abutil

---

README.md

Latest commit was 2 years ago.
Unanswered PR since 2015.
Low test coverage
`coverage: 23.6% of statements
ok  	github.com/eaburns/flac	0.002s
`

Removed unmaintained and untested flac

---

README.md

This is a library I wrote for executing shell commands on windows, linux and osx. 
- github.com repo: https://github.com/SimonBaeumer/cmd
- godoc.org: https://godoc.org/github.com/SimonBaeumer/cmd
- goreportcard.com: https://goreportcard.com/report/github.com/SimonBaeumer/cmd
- coverage service link: [codeclimate](https://codeclimate.com/github/SimonBaeumer/cmd) …

Add SimonBaeumer/cmd go package

---

README.md

- github.com repo: https://github.com/liftbridge-io/liftbridge
- godoc.org: https://godoc.org/github.com/liftbridge-io/liftbridge
- goreportcard.com: https://goreportcard.com/report/github.com/liftbridge-io/liftbridge
- coverage service link: https://coveralls.io/github/liftbridge-io/liftbridge

Add liftbridge to the Distributed Systems section

---

README.md

- github.com repo: https://github.com/goraz/onion
- godoc.org: https://godoc.org/github.com/goraz/onion
- goreportcard.com: https://goreportcard.com/report/github.com/goraz/onion
https://coveralls.io/github/goraz/onion?branch=master

add onion configuration library

---

README.md

https://github.com/mna/agora is archived.

Remove agora – not maintained anymore.

---

README.md

Added the [go.dev](https://go.dev/) website [introduced lately](https://blog.golang.org/go.dev)

Added go.dev

---

README.md

Links to https://github.com/apcera/termtables repo is dead now. Remove it.

Remove dead link to termtables, fix typo slash

---

README.md

- github.com repo: https://github.com/psampaz/gothanks
- godoc.org: https://godoc.org/github.com/psampaz/gothanks
- goreportcard.com: https://goreportcard.com/report/github.com/psampaz/gothanks

Add GoThanks

---

README.md

- github.com repo: https://github.com/stoewer/go-week
- godoc.org: https://godoc.org/github.com/stoewer/go-week
- goreportcard.com: https://goreportcard.com/report/github.com/stoewer/go-week
- coverage service link [codecov.io](https://codecov.io/gh/stoewer/go-week)
With this PR I furthermore suggest to remove a similar package [`goweek`](https://github.com/grsmv/goweek) from the list. The package provides less features and does not seem to be actively maintained. Furthermore it's implementation of the …

Add package go-week to section 'Date and Time'

---

README.md

- github.com repo: https://github.com/psampaz/slice
- godoc.org: https://godoc.org/github.com/psampaz/slice
- goreportcard.com: https://goreportcard.com/report/github.com/psampaz/slice
- coverage service link: https://codecov.io/gh/psampaz/slice

add psampaz/slice

---

README.md

- github.com repo: https://github.com/Rakeki/gosocsvr
- godoc.org: https://godoc.org/github.com/Rakeki/gosocsvr
- goreportcard.com: https://goreportcard.com/report/github.com/Rakeki/gosocsvr
- coverage service link: https://gocover.io/github.com/Rakeki/gosocsvr
- [*] …

Add gosocsvr

---

README.md

... a tool that surfaces TODO comments in a codebase and applies a git blame to identify the author
- github.com repo: https://github.com/augmentable-dev/tickgit
- godoc.org: https://godoc.org/github.com/augmentable-dev/tickgit
- goreportcard.com: https://goreportcard.com/report/github.com/augmentable-dev/tickgit
- coverage service link ([gocover](http://gocover.io/), [coveralls](https://coveralls.io/) etc.): https://gocover.io/github.com/augmentable-dev/tickgit
**Note**: that new categories can be added only when there are 3 …

add a link to tickgit

---

README.md

Hi,
All requested metrics / documentation as follows...
- github.com repo: https://github.com/fergusstrange/embedded-postgres
- godoc.org: https://godoc.org/github.com/fergusstrange/embedded-postgres
- goreportcard.com: https://goreportcard.com/report/github.com/fergusstrange/embedded-postgres
- coverage service link: https://coveralls.io/github/fergusstrange/embedded-postgres?branch=master
Thanks!

Add fergusstrange/embedded-postgres

---

README.md

- github.com repo: https://github.com/huydang284/fixedwidth
- godoc.org: https://godoc.org/github.com/huydang284/fixedwidth
- goreportcard.com: https://goreportcard.com/report/github.com/huydang284/fixedwidth
- coverage service link: https://codecov.io/gh/huydang284/fixedwidth

add fixedwidth package

---

README.md

- github.com repo: https://github.com/qiangxue/go-restful-api
- godoc.org: https://godoc.org/github.com/qiangxue/go-restful-api
- goreportcard.com: https://goreportcard.com/report/github.com/qiangxue/go-restful-api
- coverage service link ([gocover](http://gocover.io/), [coveralls](https://coveralls.io/) etc.): https://codecov.io/gh/qiangxue/go-restful-api …

Added go-restful-api project

---

README.md

Hi awesome folks :)
- github.com repo: https://github.com/rotisserie/eris
- godoc.org: https://godoc.org/github.com/rotisserie/eris
- goreportcard.com: https://goreportcard.com/report/github.com/rotisserie/eris
- coverage service link: https://codecov.io/gh/rotisserie/eris

Add rotisserie/eris to readme

---

README.md

This change adds [golines](https://github.com/segmentio/golines), a new formatter that automatically shortens long lines, to the awesome-go `Code Analysis` section. We've been using it inside Segment for a while, and it was just open-sourced.
- github.com repo: https://github.com/segmentio/golines
- godoc.org: https://godoc.org/github.com/segmentio/golines
- goreportcard.com: https://goreportcard.com/report/github.com/segmentio/golines
- coverage service link: https://gocover.io/github.com/segmentio/golines

Add golines

---

README.md

* [scaneo](https://github.com/variadico/scaneo) - Generate Go code to convert database rows into arbitrary structs.
* https://github.com/avelino/awesome-go/pull/458
* [go-restful-api](https://github.com/qiangxue/go-restful-api) - An idiomatic Go RESTful API starter kit following SOLID principles and Clean Architecture with a common project layout.
* https://github.com/avelino/awesome-go/pull/2869
* [sreq](https://github.com/winterssy/sreq) - A simple, user-friendly and concurrent safe HTTP request library for Go.
* https://github.com/avelino/awesome-go/pull/2755
* [sslice](https://github.com/yaa110/sslice) - Create a slice which is always sorted.
* https://github.com/avelino/awesome-go/pull/2232
I validate urls by [durl](https://github.com/suzuki-shunsuke/durl)
```
$ git ls-files | durl …
```

Remove tools which are not found

---

README.md

- github.com repo: https://github.com/xhit/go-str2duration
- godoc.org: https://godoc.org/github.com/xhit/go-str2duration
- goreportcard.com: https://goreportcard.com/report/github.com/xhit/go-str2duration
- coverage service link: https://gocover.io/github.com/xhit/go-str2duration

Add go-str2duration

---

README.md

- github.com repo: https://github.com/1set/gut
- godoc.org: https://godoc.org/github.com/1set/gut/yos
- goreportcard.com: https://goreportcard.com/report/github.com/1set/gut
- coverage service link: https://codecov.io/gh/1set/gut/branch/master

Add gut/yos in Files section

---

README.md

add httpretry to awesome go
- github.com repo: https://github.com/ybbus/httpretry
- godoc.org: https://godoc.org/github.com/ybbus/httpretry
- goreportcard.com: https://goreportcard.com/report/github.com/ybbus/httpretry
- coverage service link: http://gocover.io/github.com/ybbus/httpretry

add https://github.com/ybbus/httpretry

---

README.md

Hi! My library was moved. Thx!
- github.com repo: https://github.com/goava/di
- godoc.org: https://pkg.go.dev/github.com/goava/di
- goreportcard.com: https://goreportcard.com/report/github.com/goava/di
- coverage service link: https://codecov.io/gh/goava/di

Replace archived defval/inject to goava/di

---

CONTRIBUTING.md

The current amount of pending days for a PR is too long, which will easily produce lots of inactive open PRs on the list. I suggest reducing this amount for a cleaner PR list. Actually 15 days are enough for a PR owner to resolve requested changes and respond.

Renew the pending days for a PR

---

README.md

Close #2933
To be honest, I'm not sure if all projects here are awesome, even if they listed [in the official guide](https://github.com/golang/go/wiki/WebAssembly). My motivation is the same as (I guess) had authors of that guide: collect what is here right now and just works, since Go compilation into wasm is relatively new and has no ecosystem around. However, I'm a bit more selective and listed only projects that work right now and have some minimal support. Anyway, let's talk.
A few projects that I can be sure are awesome:
+ https://github.com/tinygo-org/tinygo is amazing. I was surprised that it's not here yet.
+ https://github.com/agnivade/wasmbrowsertest is a must-have tool without alternative solutions. I use it actively and it works.
About other tools:
+ …

Add WebAssembly category

---

README.md

- github.com repo: https://github.com/rocketlaunchr/igo
- coverage service link N/A
`igo` is a transpiler that converts igo files (go files with some new syntax and other language features) into standard go files which you can then compile.
**It is not a package for others to use.**
There is a unit test provided for converting a "sample" igo file to a standard go file which you can then then run. Peruse/run the 1 unit test in the parent directory.

- add igo (github.com/rocketlaunchr/igo)

---

README.md

`hostctl` is a developer CLI tool to manage `/etc/hosts` with simple commands. It has lots of features to simplify the hosts management like profile groups, enable/disable profiles, sync with docker and docker compose containers, etc.
- [github.com/guumaster/hostctl](https://github.com/guumaster/hostctl)
- [pkg.go.dev](https://pkg.go.dev/github.com/guumaster/hostctl?tab=doc)
- [goreportcard](https://goreportcard.com/report/github.com/guumaster/hostctl)
- [sonarcloud coverage](https://sonarcloud.io/dashboard?id=guumaster_hostctl)

Add hostctl to Utilities

---

README.md

`airtable` is a simple golang package to access the Airtable API. 
- [github.com repo](https://github.com/mehanizm/airtable)
- [pkg.go.dev](https://pkg.go.dev/github.com/mehanizm/airtable?tab=doc)
- [goreportcard.com](https://goreportcard.com/report/github.com/mehanizm/airtable)
- [codecov](https://codecov.io/gh/mehanizm/airtable)

Add Airtable to Third-party APIs

---

README.md

* Change the url https://github.com/xenolf/lego to https://github.com/go-acme/lego
* Remove the following tools which are not found
* [yakvs](https://git.sci4me.com/sci4me/yakvs) - Small, networked, in-memory key-value store.
* [compare](https://github.com/posener/compare) - Enables more readable and easier comparison tasks.

Remove not found tools and fix a link

---

README.md

Hi! Please add my package to the list. It's unofficial Google Trends API.
- github.com repo: https://github.com/groovili/gogtrends
- pkg.go.dev: https://pkg.go.dev/github.com/groovili/gogtrends
- goreportcard.com: https://goreportcard.com/report/github.com/groovili/gogtrends
- coverage service link ([codecov](https://codecov.io/), [coveralls](https://coveralls.io/), [gocover](http://gocover.io/) etc.) https://coveralls.io/github/groovili/gogtrends

add gogtrends unofficial google trends api

---

README.md

Typenv is a minimalistic, zero dependency, typed environment variables library.
- github.com repo: https://github.com/diegomarangoni/typenv
- pkg.go.dev: https://pkg.go.dev/diegomarangoni.dev/typenv
- goreportcard.com: https://goreportcard.com/report/diegomarangoni.dev/typenv
- coverage service link: https://codecov.io/gh/diegomarangoni/typenv

add typenv into configuration category

---

README.md

The URL for `go-guardian` was pointing to its [go-reportcard](https://goreportcard.com/report/github.com/shaj13/go-guardian). The attached PR fixes it, to point to its GitHub [repo](https://github.com/shaj13/go-guardian).

Fix URL of go-guardian

---

README.md

I was updating the link and description of the package since it changed owner a few years ago.
- github.com/ReneKroon/ttlcache 
- https://pkg.go.dev/github.com/ReneKroon/ttlcache/v2?tab=doc:
- https://goreportcard.com/report/github.com/ReneKroon/ttlcache 
- https://gocover.io/github.com/ReneKroon/ttlcache (100%)
- [X ] I have added my package in alphabetical order.
- [X ] I have an appropriate description with correct grammar.
- [N/A ] This is an update so N/A - I know that this package was not listed before.
- [X ] I have added pkg.go.dev link to the repo and to my pull request.
- [X ] I have added coverage service link to the repo and to my pull request.
- [X ] I have added …

Update main location and description of ttlcache

---

README.md

Thanos style guide link is broken - updated to the new location

Thanos style guide - Fix broken URL

---

README.md

- pkg.go.dev:
fixed: #3316 
This is a reponse to issue [#3316](https://github.com/avelino/awesome-go/issues/3316) i looked into these repositories and am giving a small …

removed 3 repositories that were falling out of maintenance #3316

---

README.md

Removing entry for golangci.com since this service is no longer supported. However `golangci-lint` is used in it's place as a CLI in CI pipelines
- github.com repo: https://github.com/golangci/golangci-lint
- pkg.go.dev: https://pkg.go.dev/github.com/golangci/golangci-lint
- goreportcard.com: https://goreportcard.com/report/github.com/golangci/golangci-lint

Remove golangci-lint reference (golangci.com out of service)

---

README.md

- github.com repo: https://github.com/orlangure/gnomock
- pkg.go.dev: https://pkg.go.dev/github.com/orlangure/gnomock
- goreportcard.com: https://goreportcard.com/report/github.com/orlangure/gnomock
- coverage service link ([codecov](https://codecov.io/), [coveralls](https://coveralls.io/), [gocover](http://gocover.io/) etc.): https://codecov.io/gh/orlangure/gnomock

Add gnomock to testing frameworks list

---

README.md

https://github.com/is5/r and https://github.com/is5 give 404
Removing a package `github.com/is5/r`.

remove 'r'

---

README.md

llgo is no longer actively maintained and was dropped from the
official LLVM source tree in February 2020.

Remove llgo

---

README.md

According to the [README](https://github.com/go-goracle/goracle/blob/master/README), project [go-oracle ](https://github.com/go-goracle) is deprecated in favour of [Godror](https://github.com/godror/godror). This PR switches these two drivers and fixes #3429
Some data:
- github.com repo: https://github.com/godror/godror
- pkg.go.dev: https://pkg.go.dev/github.com/godror/godror
- goreportcard.com: https://goreportcard.com/report/github.com/godror/godror
- coverage service link: https://codecov.io/gh/godror/godror

Switched Go Oracle ODPI-C Driver

---

README.md

Goyave moved from my personal account to the go-goyave organization. This PR updates the link.

Update goyave link

---

README.md

I just noticed that there is sub section called `Advanced Console UIs` under Command Line which fits my module more from PR https://github.com/avelino/awesome-go/pull/3439

readme: shift box-cli-maker from standard cli to adv. console ui

---

.travis.yml

- root: deprecated key sudo (The key `sudo` has no effect anymore.)
- deploy: deprecated key skip_cleanup (not supported in dpl v2, use cleanup)

fixed warnings on travisci config

---

.travis.yml

Reverts avelino/awesome-go#3562
Cleaning up git repository with `git stash --all`. If you need build artifacts for deployment, set `deploy.skip_cleanup: true`. See https://docs.travis-ci.com/user/deployment#Uploading-Files-and-skip_cleanup.
Saved working directory and index state WIP on (no branch): 2932cf1 fixed warnings on travisci config - root: deprecated key sudo (The key `sudo` has no effect anymore.) - deploy: deprecated key skip_cleanup (not supported in dpl v2, use cleanup)
```
Deploy path: /home/travis/gopath/src/github.com/avelino/awesome-go/tmpl
Deploying to main site URL...
- Hashing files...
✔ Finished hashing 49 files
- CDN diffing files...
✔ CDN requesting 0 files
- Uploading 0 files
✔ Finished uploading 0 assets
- Waiting for deploy to go live...
✔ Deploy is live!
Logs: …
```

Revert "fixed warnings on travisci config"

---

README.md

Package is unmaintained. Hasn't been updated in 5 years. https://github.com/melihmucuk/geocache

Remove Geocache

---

.github/PULL_REQUEST_TEMPLATE.md

While submitting the PR with my package I found that one of the links to the [Quality standard](https://github.com/avelino/awesome-go/blob/master/CONTRIBUTING.md#quality-standards) in the PR templates was incorrect, so I created this tiny PR to fix it.

Fix broken link to the contribution guidelines

---

README.md

- github.com repo: https://github.com/pyros2097/go-embed
- pkg.go.dev: https://pkg.go.dev/github.com/pyros2097/go-embed
- goreportcard.com: https://goreportcard.com/report/github.com/pyros2097/go-embed

Remove pyros2097/go-embed

---

README.md

Removed QBS (Query By Struct) ORM as QBS hasn't been updated for over 4 years.

Remove QBS

---

README.md

`balerter` is Script Based Alert Manager
- https://github.com/balerter/balerter
- https://goreportcard.com/report/github.com/balerter/balerter
- https://codecov.io/gh/balerter/balerter
- [x ] I know that this package was not listed before.
- [x ] I have added coverage service link to the repo and to my pull request.
- [x ] I have added goreportcard link to the repo and to my pull request.
- [x ] I have read [Contribution guidelines](https://github.com/avelino/awesome-go/blob/master/CONTRIBUTING.md#contribution-guidelines), [maintainers note](https://github.com/avelino/awesome-go/blob/master/CONTRIBUTING.md#maintainers) and [Quality …

add Balerter to the DevOps section

---

README.md

This is just a simple URL change of where source code is hosted for my projects:
`s|github.com/prologic|git.mills.io/prologic|g`
See [Why I no longer trust Github](https://twtxt.net/blog/prologic/2021/07/11/why-i-no-longer-trust-github) (backup link [here](https://www.prologic.blog/2021/07/11/why-i-no.html)) for why I moved my projects off Github.
Thank you! 🙇‍♂️

Fix the sourcecode URLs for many of my (prologic) Go libraries

---

README.md

So lately i have used this list to get another text color library for lazygit with support for RGB colors, sadly there seems to be only one library in here that is not a logger and has RGB text color support (https://github.com/gookit/color) sadly that library has a lot of problems for my use case:
- No single interface for switching between 16-color (4-bit), 256-color (8-bit) and true color (24-bit, RGB) (so i needed to write at least 100 lines for a general abstraction)
- A lot of chinese in it's docs and source code
- Seems to miss a lot of helper functions for advanced usage
Github just recommended https://github.com/muesli/termenv and if only that library was in this list because it solves all the problems from above and supports all the terminal color outputs just fine and thus …

Add muesli/termenv

---

README.md

Hi team,
I just saw that the link to beego seems incorrect or outdated. The link that is currently listed is `https://github.com/astaxie/beego/tree/master/orm` which is only a fork outdated by more than 100 commits of the original project `https://github.com/beego/beego`.
I have git-blamed all the commits back with all the transitions it has gone through, it seems that this was introduced with commit 96050f0d50ef3ffbfe0bb72cdda571720d24c08b.

correct beego orm link

---

README.md

Now the missing coverage > 80% is fullfilled -> Initial proposal #3633.
Links
- github.com repo: https://github.com/gabyx/githooks
- pkg.go.dev: https://pkg.go.dev/github.com/gabyx/githooks/githooks
- goreportcard.com: https://goreportcard.com/report/github.com/gabyx/githooks
- coverage service link: https://coveralls.io/github/gabyx/Githooks?branch=main
Checks

Add Githooks

---

README.md

Changelist:
* Added a 'back to top' hyperlink to the README.md, you can find at the end of every section that starts with ## and ###.
* Also the Hyperlinks for 'Authentication and OAuth' & 'Blockchain' were missing, I fixed those.
As I was browsing the README.md I found myself jumping between sections inefficiently, decided to add a hyperlink for "Go to top", more specifically to the Contents table.
I hope you find it useful.
Let me know if you want me to change anything.
Thank you,

Making 'README.md' a bit more efficient to read

---

README.md

Golang is very handy when working with hardware. It's trivial to write code that interacts with real objects by using simple protocols (like CANBUS, I2C, SPI, Mavlink), and it's also easy to write more complex libraries that handle most of the job of detecting and establishing communication with a device, sensor or actuator.
At the moment, the Hardware section of awesome-go redirects to an external repository (go-hardware) that has a couple of problems:
* it's unmaintained since 2019; no packages have been added or removed since 2 years
* listed packages are either already present in awesome-go, unmaintained, deprecated or undocumented, with the exception of some entries
I've checked every package listed in go-hardware, here's what i've found:
* [devices](https://github.com/goiot/devices) …

Replace unmaintained go-hardware link with a selected list of packages

---

README.md

[nbio](https://github.com/lesismal/nbio) is already on the list, just want to update its description, because we have implemented more features and so that:
1. Compared with other poller frameworks which does not support tls/http 1.x/websocket, [nbio](https://github.com/lesismal/nbio) has supported tls/http 1.x/websocket for both server and client sides.
2. Compared with other std-based frameworks, [nbio](https://github.com/lesismal/nbio) is the real 1000k+ connections solution without [HOLB](https://docs.solace.com/System-and-Software-Maintenance/HOL-blocking.htm) like problems.

update: nbio

---

README.md

Change alphabetical order for #3925

varint: fix alphabetical order

---

README.md

Created two new sections under 'E-books':
1. E-books for purchase
2. Free e-books
fixed: #3956

Split books into 'paid' and 'free' per #3956

---

README.md

ChainJacking is a tool to find which of your Go lang direct GitHub dependencies is susceptible to ChainJacking attack.

Add ChainJacking by Checkmarx

---

README.md
repo_test.go

- removing duplicate content menu
- enabling vscode editing with markdown lint on — previously it was automatically correcting the content menu swapping, messing up the order and making it fail the tests
- markdown lint

markdown structure improvements

---

README.md

The framework has been moved to GitHub pages without its own domain name.

Update Confetti Framework URL

---

README.md

https://github.com/igrmk/treemap
- pkg.go.dev:
https://pkg.go.dev/github.com/igrmk/treemap/v2
Unfortunately goreportcard doesn't support generics so current mark is D:
https://goreportcard.com/report/github.com/igrmk/treemap/v2
However previous version that was built around gotemplate has A+ mark:
https://goreportcard.com/report/github.com/igrmk/treemap
Once Go is updated to 1.18 on goreportcard side it should be fixed.
- coverage service link ([codecov](https://codecov.io/), …

add treemap

---

.github/PULL_REQUEST_TEMPLATE.md
CONTRIBUTING.md

Per the discussion at #4032, here are some updates to the contributions guidelines. This is to start the discussion among the maintainers.
I just went through the review process, and some of the changes here are to clarify some things I encountered going through the process.
I made some changes  that I think should be added related to modern Go, like:
- A project should have at least one official release so it can be tracked in go.mod
- A project should maintain compatibility with Go, if not the most recent version, at least a version before that.
I also gave specific directions on how to add an item, and how to remove.
The goal of all of this is to give clear directions for people who want to help maintain the project, and to ulitimately keep its quality high.

Updating contribution guidelines

---

README.md

[samber/lo](https://github.com/samber/lo)
- repo link (github.com, gitlab.com, etc): https://github.com/samber/lo
- pkg.go.dev: https://pkg.go.dev/github.com/samber/lo
- goreportcard.com: https://goreportcard.com/report/github.com/samber/lo (not applicable: go 1.18+)
- coverage service link ([codecov](https://codecov.io/), [coveralls](https://coveralls.io/), [gocover](http://gocover.io/) etc.): Not applicable (go 1.18)
Code coverage: 
Goreportcard or coverage services fail on generics, because it does not support go 1.18 yet.

adding github.com/samber/lo

---

README.md

Damsel appears to be abandoned. The most recent commit was 6 years ago.
While it appears stable, it does not correspond to current awesome-go standards. In particular, it does not have a go.mod file nor any published releases, no report card and no code coverage report.
@dskinner, please reply if you would like to keep Damsel on awesome-go.

Removing Damsel.

---

README.md

Velvet appears to be abandoned.
- Most recent commit was 5 years ago.
- It does not meet current awesome-go quality standards.
@markbates, please reply if you would like to keep Velvet on awesome-go.

Removing Velvet

---

README.md

Mustache appears to be abandoned.
- Most recent commit was 6 years ago.
- It does not have a go.mod file
- It does not conform to current awesome-go quality standards
@hoisie, please reply if you would like to keep mustache on awesome-go

Removing Mustache

---

README.md

Kasia appears to be abandoned.
- The most recent commit was 7 years ago.
- It does not have a go.mod file
- It does not conform to current awesome-go standards
@ziutek, please reply if you would like to keep kasia on awesome-go

Removing Kasia

---

CONTRIBUTING.md
COVERAGE.md

Adding an example of how to create code coverage reports from within github actions and workflows.

Example github workflow with code coverage badge production

---

README.md

- repo link (github.com, gitlab.com, etc): https://github.com/bitfield/gotestdox
- pkg.go.dev: https://pkg.go.dev/github.com/bitfield/gotestdox
- goreportcard.com: https://goreportcard.com/report/github.com/bitfield/gotestdox
- coverage: 96.4%

Add gotestdox

---

README.md

This is a reorganization of the Text Processing category into sub-categories to make it easier to peruse.
Also removed the "inject" package since the author officially archived the project and is no longer supporting it. All other packages remain.
I reviewed all of the packages in this category, and while most don't fit current quality standards, most of them are simply mature projects with 1 or 2 open issues, and are still quite useful.

Reorganizing text processors

---

README.md

Hero appears to be adandoned:
- The most recent commit was 2 years ago.
- It is not passing its continuous integration test.
- It is still at v0.0.2 and so is not progressing to release.
- There are many open issues.
- It does not conform to current awesome-go quality standards.
@shiyanhui, please respond if you would like to maintain hero on awesome-go.

Removing hero

---

README.md

Amber appears to be abandoned.
- Most recent commit is 5 years ago
- It has multiple open issues
Amber also does not conform to current awesome-go quality standards
@eknkc please respond if you would like to keep Amber on awesome-go.

Removing Amber

---

README.md

Ace appears to be abandoned:
- The most recent commit is 4 years ago
- It has multiple open issues.
Ace also does not conform to awesome-go current quality standards.
@yosssi Please respond if you would like to keep Ace on awesome-go.

Removing Ace:

---

README.md

Renaming the Generation and Generics category to just "Generators" since that seems to describe the category better, and Generics is now a native part of the language, and so it will move into many different types of libraries.

Renaming *Generation and Generics* category now that Go has native generics

---

README.md

The package has been transferred to other entity, it is still being maintained.

Update ttlcache package entity

---

README.md

- repo link (github.com, gitlab.com, etc): https://github.com/jellydator/newsapi-go
- pkg.go.dev:  https://pkg.go.dev/github.com/jellydator/newsapi-go
- goreportcard.com: https://goreportcard.com/report/github.com/jellydator/newsapi-go
- coverage service link: https://coveralls.io/github/jellydator/newsapi-go?branch=master

Add newsapi-go package

---

README.md

- Development is mostly over 2 years old
- Many open issues
- No report card
- No code coverage
Port-midi is scheduled to be removed by March 21, 2022. @rakyll, please respond with fixes to your repo that will bring the repo up to current awesome-go quality standards if you would like to keep portmidi on awesome-go.

Remove port-midi:

---

README.md

- Last update is over 2 years ago
- Many open issues including bug reports, that do not appear to have any activity
- Does not conform to current awesome-go guidelines
@clipperhouse: gen is scheduled to be removed from awesome-go. If you would like to keep it on awesome-go, please reply to this pull-request and update it so that it conforms to current quality standards.
gen will be removed on April 6, 2022

Removing gen:

---

README.md

- Last commit was 7 years ago
- There are open issues with bug reports
- Author appears to have abandoned the project
- Does not conform to current awesome-go standards
@ryszard, skiplist is scheduled to be removed on April 6, 2022. If you would like to keep skiplist on awesome-go, please update the code, addessing the issues mentioned above.

Removing skiplist:

---

README.md

- Last commit is 3 years ago
- Project is still in alpha and not progressing
- Open issues and pull requests are not being responded to
- Has no code coverage report
@cbergoon, merkletree is scheduled to be removed from awesome-go on April 6, 2022. If you would like to keep it on awesome-go, please update the code, addressing the issues mentioned above.

Removing merkletree:

---

README.md

- No official releases
- Last commit over 3 years ago
- Is a branch of another project that is diverging
- Does not conform to current awesome-go guidlines
@tylerflint, Scribble is scheduled to be removed from awesome-go on April 8, 2022. If you would like to keep Scribble on awesome-go, please respond to this request with fixes to the issues mentioned above.

Removing scribble:

---

README.md

Removing go-cache:
- No development for 3 years
- Does not conform to current awesome-go standards

Removing go-cache

---

README.md

- Last commit was 4 years ago
- There is a recent bug report that shows its not working with recent versions of Go, and there is no response from the author.
- It does not conform to current awesome-go standards

Removing encoding:

---

CONTRIBUTING.md

Making sure all public functions and types are documented now that GoReportCard is no longer checking for this.

Clarifying documentation

---

README.md

[efaceconv](https://github.com/t0pep0/efaceconv) is scheduled to be removed from awesome-go on May 12, 2022. If you would like it to remain, fix your repository such that it passes tests with a current version of Go and shows code coverage of 80% or more. In addition, your project is failing to meet the following criteria:
- The project has not made an official release within the last year and it has open issues.
- The project has an open-issue from 2016.
- The project does not use Go modules issued in `go 1.13`. Projects must be compatible with Go versions issued in the last year. See https://go.dev/doc/devel/release for release history.
Once completed, post here to confirm.
_Owner: @t0pep0_
_Submission: https://github.com/avelino/awesome-go/pull/1188_

remove efaceconv

---

README.md

[pkgreflect](https://github.com/ungerik/pkgreflect) is scheduled to be removed from awesome-go on May 12, 2022. If you would like it to remain, fix your repository such that it passes tests with a current version of Go and shows code coverage of 80% or more. In addition, your project is failing to meet the following criteria:
- The project does not use Go modules issued in `go 1.13`. Projects must be compatible with Go versions issued in the last year. See https://go.dev/doc/devel/release for release history.
Once completed, post here to confirm.
_Owner: @ungerik_
_Submission: https://github.com/avelino/awesome-go/pull/113_

remove pkgreflect

---

README.md

Project: https://github.com/samber/mo
- repo link (github.com, gitlab.com, etc): https://github.com/samber/mo
- pkg.go.dev: [pkg.go.dev/github.com/samber/mo](https://pkg.go.dev/github.com/samber/mo)
- goreportcard.com: https://goreportcard.com/report/github.com/samber/mo
- coverage service link ([codecov](https://codecov.io/), [coveralls](https://coveralls.io/), [gocover](http://gocover.io/) etc.): https://app.codecov.io/gh/samber/mo

Adding samber/mo

---

.github/workflows/run-check.yaml
.gitignore
stale_repositories_test.go

I think this fixes #4264. Instead of running the stale via `go run`, we can run it via `go test`.
I have run the workflow on my fork & it looks like it can work https://github.com/cglotr/awesome-go/actions.
What do you think @avelino?

run stale repo check as test instead

---

README.md

Rationale: go-email-normalizer is not implementing any of authentications schemes. So it can't be in "Authentication and OAuth" section

Library go-email-normalizer moved to the correct category

---

README.md

Add an extra line break to prevent the awesome-go.com website from rendering the "Caches" section incorrectly

Fix website rendering of Database/Caches section

---

README.md

Rationale:
* [`hasql`](https://github.com/yandex/go-hasql) is not a query builder, it's a library for working with multi-host (high availability) database clusters, so move to "Database Tools" section
* [`mpath`](https://github.com/spacetab-io/mpath-go) doesn't have anything to do with databases or SQL, so remove

Move hasql to correct section; remove mpath

---

README.md

Feat: add lancet in Utilities section
I find a good go utils function lib, it's lancet. May I add it to Utilities section? Please check blow info.
[lancet](https://github.com/duke-git/lancet)
[lancet-goreportcard](https://goreportcard.com/report/github.com/duke-git/lancet/v2)
[lancet-coverage](https://app.codecov.io/gh/duke-git/lancet)

Add lancet(A comprehensive, efficient, and reusable util function library of go) to Utilities section.

---

README.md

- repo link (github.com, gitlab.com, etc): https://github.com/cockroachdb/errors
- pkg.go.dev: https://pkg.go.dev/github.com/cockroachdb/errors
- goreportcard.com: https://goreportcard.com/report/github.com/cockroachdb/errors …

add cockroachdb/errors

---

README.md

`go-appindicator` was abandoned and eventually archived back on 2022. In February of this year I forked the project to bring it back to life. Now called AppIndicator Go, this project will continue under this new name and URL.

Replace go-appindicator with fork

---

README.md

Since this is a GitHub Action using tooling included in the Go standard library, the usual criteria for linking to the package documentation, coverage, and Go report card don't quite apply.
If this Action isn't appropriate for this repo, please feel free to close this PR.
---
- repo link (github.com, gitlab.com, etc): https://github.com/jidicula/go-fuzz-action …

feat: Add go-fuzz-action to CI resources

---

README.md

Remove [goflake](https://github.com/hart87/GoFlake) due to the repository being **inaccessible** or **deleted**.

Remove goflake

---

README.md

[rbac](https://github.com/zpatrick/rbac) is scheduled to be removed from awesome-go on August 20, 2022. If you would like it to remain, fix your repository such that it passes tests with a current version of Go and shows code coverage of 80% or more. In addition, your project is failing to meet the following criteria:
- Official releases should be at least once a year if the project is ongoing. The last release for `rbac` was **never** (last commit on Aug 29, 2018).
- The project does not use Go modules issued in go 1.13. Projects must be compatible with Go versions issued in the last year. See https://go.dev/doc/devel/release for release history.
- The project does not support generics issued in go 1.18. Projects must be compatible with Go versions issued in the last year. See …

remove rbac

---

README.md

- repo link (github.com, gitlab.com, etc): https://github.com/heartwilltell/log
- pkg.go.dev: https://pkg.go.dev/github.com/heartwilltell/log
- goreportcard.com: https://goreportcard.com/report/github.com/heartwilltell/log
- coverage service link ([codecov](https://codecov.io/), [coveralls](https://coveralls.io/), [gocover](http://gocover.io/) etc.): https://app.codecov.io/gh/heartwilltell/log

Add github.com/heartwilltell/log to Logging section

---

README.md

Package links:
repo link: http://github.com/Kwynto/gosession
pkg.go.dev: https://pkg.go.dev/github.com/Kwynto/gosession
goreportcard.com: https://goreportcard.com/report/github.com/Kwynto/gosession
coverage service link: https://gocover.io/github.com/Kwynto/gosession

Add github.com/Kwynto/gosession to "Authentication and OAuth"

---

README.md

This updates the glab entry to point to the new canonical repo on GitLab. Announcement was made in
https://github.com/profclems/glab/issues/983
- pkg.go.dev: …

glab moved to GitLab as the CLI

---

README.md

Update to gotestfmt originally submitted in #3681: this tool is moving to the [GoTestTools](https://github.com/GoTestTools/) organization, see the [announcement](https://github.com/GoTestTools/gotestfmt/discussions/46).

gotestfmt is moving to the GoTestTools org

---

README.md

[go-xray](https://github.com/pieterclaerhout/go-xray) is scheduled to be removed from awesome-go on August 11, 2022. If you would like it to remain, fix your repository such that it passes tests with a current version of Go and shows code coverage of 80% or more. In addition, your project is failing to meet the following criteria:
- Official releases should be at least once a year if the project is ongoing. The last release for `go-xray` was on Oct 04, 2019.
- The project does not support generics issued in `go 1.18`. Projects must be compatible with Go versions issued in the last year. See https://go.dev/doc/devel/release for release history.
Once completed, post here to confirm.
_Owner: @pieterclaerhout_
_Submission: https://github.com/avelino/awesome-go/pull/2818_
_NOTE: The project …

remove go-xray

---

stale_repositories_test.go

It's best to use the built-in library constants for status codes when possible as it improves readability, rather than having to look up status code definitions when otherwise changing behaviour.
---
Since this is a refactor to the repo's tests itself, I've removed the usual PR template that's meant for entries to the list.

refactor(tests): Use net/http constants for status codes

---

README.md

- repo link:  https://github.com/mszostok/version
- pkg.go.dev: https://pkg.go.dev/go.szostok.io/version
- goreportcard.com: https://goreportcard.com/report/go.szostok.io/version
- coverage service link: https://coveralls.io/github/mszostok/version
- More about testing: https://szostok.io/projects/version/community/testing/
Checklist:
Thanks!

Add `go.szostok.io/version` package

---

.github/workflows/run-check.yaml
.github/workflows/site-deploy.yaml
.github/workflows/tests.yaml

GitHub Workflows security hardening

---

README.md

- Last commit was 2 years ago.
- Last release was 3 years ago.
- No activity on open issues for over a year.
- Does not meet awesome-go standards.
- CI error for 2 years
- missing gopkg.in requirements
@charneykaye, @lamg, [music-theory](https://github.com/go-music-theory/music-theory) is scheduled to be removed from awesome-go. If you would like to keep it on awesome-go, please reply to this pull request and update it so that it conforms to current quality standards.

remove music-theory from Audio and Music

---

README.md

Add [Google's Go style guide](https://google.github.io/styleguide/go/), as mentioned [here](https://groups.google.com/g/golang-nuts/c/8_X8O3k62pI).

Add Google's Go style guide

---

README.md

- repo link (github.com, gitlab.com, etc): https://github.com/golang-jwt/jwt
- pkg.go.dev: https://pkg.go.dev/github.com/golang-jwt/jwt/v4
- goreportcard.com: https://goreportcard.com/report/github.com/golang-jwt/jwt
- coverage service link ([codecov](https://codecov.io/), [coveralls](https://coveralls.io/), [gocover](http://gocover.io/) etc.): https://github.com/golang-jwt/jwt/actions/workflows/build.yml …

Adding - jwt-go

---

README.md

I'm not maintaining `terraform-validator`anymore. We can remove it from that curated list.
Best.

remove: terraform-validator

---

README.md

- repo link (github.com, gitlab.com, etc): https://github.com/ThreeDotsLabs/watermill
- pkg.go.dev: https://pkg.go.dev/github.com/threedotslabs/watermill
- goreportcard.com: https://goreportcard.com/report/github.com/ThreeDotsLabs/watermill
- coverage service link ([codecov](https://codecov.io/), [coveralls](https://coveralls.io/), [gocover](http://gocover.io/) etc.): https://app.codecov.io/gh/ThreeDotsLabs/watermill …

Add Watermill

---

README.md

This PR simply moves the listing for Kivik (CouchDB SDK/driver) from the relational database section, to the NoSQL section, where it makes more sense, given that CouchDB is a NoSQL/document database.

Move Kivik from relational to NoSQL section

---

README.md

- repo link (github.com, gitlab.com, etc): https://github.com/Southclaws/fault
- pkg.go.dev: https://pkg.go.dev/github.com/Southclaws/fault
- goreportcard.com: https://goreportcard.com/report/github.com/Southclaws/fault
- coverage service link ([codecov](https://codecov.io/), [coveralls](https://coveralls.io/), etc.): https://app.codecov.io/github/Southclaws/fault/tree/master

add fault structured error wrapping library

---

README.md

- repo link (github.com, gitlab.com, etc): https://github.com/amacneil/dbmate
- pkg.go.dev: https://pkg.go.dev/github.com/amacneil/dbmate/v2/pkg/dbmate
- goreportcard.com: https://goreportcard.com/report/github.com/amacneil/dbmate
- coverage service link ([codecov](https://codecov.io/), [coveralls](https://coveralls.io/), etc.): n/a
**Manual code coverage results:**
```
ok  	github.com/amacneil/dbmate/v2/pkg/dbmate …
```

add dbmate

---

README.md

This PR fixes spell mistakes and removes trailing whitespace in README.

Correct typos and remove trailing whitespace

---

README.md

- https://pkg.go.dev/gitlab.com/verygoodsoftwarenotvirus/blanket
- https://goreportcard.com/report/gitlab.com/verygoodsoftwarenotvirus/blanket
The repo https://github.com/verygoodsoftwarenotvirus/tarp is archived and moved by the author to https://gitlab.com/verygoodsoftwarenotvirus/blanket. This PR updates its name, link, and description.

Change tarp to blanket, blanket is on GitLab

---

README.md

- repo link (github.com, gitlab.com, etc): https://github.com/ravsii/textra
- pkg.go.dev: https://pkg.go.dev/github.com/ravsii/textra
- goreportcard.com: https://goreportcard.com/report/github.com/ravsii/textra
- coverage service link: https://app.codecov.io/gh/ravsii/textra

Add Textra under Go Tools - struct info extractor package

---

.github/workflows/pull-request-first-comment.yaml

This fixes the error seen creating a new pull request.
Fixes https://github.com/avelino/awesome-go/issues/4868

build(ci): fix first comment github action

---

README.md

- repo link (github.com, gitlab.com, etc): [https://github.com/jamf/regatta](https://github.com/jamf/regatta)
- pkg.go.dev: [https://pkg.go.dev/github.com/jamf/regatta](https://pkg.go.dev/github.com/jamf/regatta)
- goreportcard.com: [https://goreportcard.com/report/github.com/jamf/regatta](https://goreportcard.com/report/github.com/jamf/regatta)
- code coverage: [https://coveralls.io/github/jamf/regatta](https://coveralls.io/github/jamf/regatta) …

Add regatta to DB section

---

README.md

- repo link (github.com, gitlab.com, etc): https://github.com/awterman/monkey
- pkg.go.dev:https://pkg.go.dev/github.com/awterman/monkey
- goreportcard.com:https://goreportcard.com/report/github.com/awterman/monkey
- coverage service link ([codecov](https://codecov.io/), [coveralls](https://coveralls.io/), etc.):https://raw.githack.com/wiki/awterman/monkey/coverage.html
_Not every …

Add monkey

---

README.md

- repo link (github.com, gitlab.com, etc): https://github.com/BooleanCat/go-functional
- pkg.go.dev: https://pkg.go.dev/github.com/BooleanCat/go-functional
- goreportcard.com: https://goreportcard.com/report/github.com/BooleanCat/go-functional
- coverage service link ([codecov](https://codecov.io/), [coveralls](https://coveralls.io/), etc.): https://app.codecov.io/gh/BooleanCat/go-functional …

Add go-functional to list

---

README.md

Hello maintainers,
This pr removes the package [resize](https://github.com/nfnt/resize), which as per the [author is no longer maintained](https://github.com/nfnt/resize/issues/63), and it is archived.
Thank you.

remove the package resize under images

---

README.md

https://github.com/pkg/errors is not maintained anymore and has been archived.
cc @davecheney

Removing github.com/pkg/errors

---

README.md

- repo link (github.com, gitlab.com, etc): https://github.com/mvrilo/go-redoc/
- pkg.go.dev: https://pkg.go.dev/github.com/mvrilo/go-redoc?utm_source=godoc
- goreportcard.com: https://goreportcard.com/report/github.com/mvrilo/go-redoc?_=1

Add go-redoc to Third-Party APIs

---

README.md

Useful utility to generate go models based on openapi spec
- repo link (github.com, gitlab.com, etc): https://github.com/deepmap/oapi-codegen
- pkg.go.dev: https://pkg.go.dev/github.com/deepmap/oapi-codegen/pkg/codegen
- goreportcard.com: https://goreportcard.com/report/github.com/deepmap/oapi-codegen …

chore: add oapi-codegen

---

README.md

For a while now the etcd repository has been at https://github.com/etcd-io/etcd.
The old coreos repository url redirects there but we should ideally just update it to the correct url.

Fix repository url for etcd

---

README.md

bexp Brace Expansion package has moved to new github org. From my personal account github.com/mkungla/bexp
to github.com/happy-sdk/happy-go/strings/bexp

update: bexp import path

---

README.md

- repo link: https://github.com/number571/go-peer
- pkg.go.dev: https://pkg.go.dev/github.com/number571/go-peer
- goreportcard.com: https://goreportcard.com/report/github.com/number571/go-peer
- [] The repo has a continuous integration process that automatically runs tests that must pass before new pull requests are merged.

Add go-peer to Security

---

README.md

The link redirects to a group for learners of the great board game Go, and not golang.
Could not find a corresponding group for golang, so thus removing the link for now.

remove incorrect link

---

README.md

- repo link (github.com, gitlab.com, etc): [https://github.com/z5labs/bedrock](https://github.com/z5labs/bedrock)
- pkg.go.dev: [https://pkg.go.dev/github.com/z5labs/bedrock](https://pkg.go.dev/github.com/z5labs/bedrock)
- goreportcard.com: [https://goreportcard.com/report/github.com/z5labs/bedrock](https://goreportcard.com/report/github.com/z5labs/bedrock)
- coverage service link ([codecov](https://codecov.io/), [coveralls](https://coveralls.io/), etc.): Go coverage is calculated from coverprofile in Github Action runner instead of using an external service. The project README has a badge displaying the coverage.

add z5labs/bedrock

---

README.md

Update pkg link in readme to point to correct repo location

fix: bexp repo url in readme

---

README.md

This adds gomponents to the list of template engines.
I've added a component example directly in the description, which I think is both informative and a bit fun. 😊 If that's frowned upon, I'd be happy to create a more traditional description.
- repo link (github.com, gitlab.com, etc): https://github.com/maragudk/gomponents
- pkg.go.dev: https://pkg.go.dev/github.com/maragudk/gomponents
- goreportcard.com: https://goreportcard.com/report/github.com/maragudk/gomponents
- coverage service link ([codecov](https://codecov.io/), …

Add gomponents to Template Engines

---

README.md

I went over the README to check all godoc.org references.
I removed the libraries which apparently do not meet the quality standard:
- missing tagged version:
- https://godoc.org/github.com/tvastar/test/cmd/testmd
- https://godoc.org/github.com/shurcooL/github_flavored_markdown
- outdated:
- https://github.com/posener/tarfs (no support for `io.FS`, implements the github.com/kr/fs#FileSystem (and not the stdlib io.FS interface), package which has been replaced by kr.dev/walk)
- gowalker.org does not serve Go content
For the others, I replaced the godoc.org link with a pkg.go.dev link.

Remove godoc.org references

---

README.md

This package looks deprecated, archived and not maintained.
https://github.com/asticode/go-astilectron

Remove go-astilectron coz depricated

---

README.md

I checked the 4 `telemetry` occurrences and found 2 projects that should be removed:
- [panoptes-stream](https://github.com/yahoo/panoptes-stream) has not been updated for 3 years (and only one `0.1.0` release)
- [snap](https://github.com/intelsdi-x/snap) has been "archived by the owner on Nov 8, 2022".
---
Idea: for each pull request which aims at adding a project, the author should try to find a project that should not be in the list anymore (for instance by checking other projects of the same category). It should help removing outdated projects (however some care should taken, so that legitimate projects do not get removed).

Remove unmaintained "telemetry" projects

---

.github/PULL_REQUEST_TEMPLATE.md

Hi, in  #5224 I suggested that new Pull Requests should also check if the packages around the submission are still relevant.
I think this would allow to spread the load to check for older packages:
- spread over a larger number of people (since every user making a pull request should participate)
- spread over time for the maintainers (since every PR should only remove a couple of links, preventing stale issues because the numbers of links to check is very high)
I also took the liberty of moving some checkboxes around, to try to better categorize each step:
- read the guidelines
- ensure the submitted repo meets the quality standard
- links to the repo & services
- check of the pull-request content
- check of unmaintained packages around the submission
You can view an empty PR created …

Refactor PR template: hint to curate packages around the submission

---

README.md

- Removing https://github.com/awterman/monkey
- just a wrapper around gomonkey
- just one go source file, hard to be a library
- less pupular
- 8 commits in total
- Removing https://github.com/pasdam/mockit
- archived
- last update 4 years ago(excluding .github/workflow, go.mod update)  …

Add xgo(a mocking library), remove awterman/monkey and pasdam/mockit

---

stale_repositories_test.go

According to the go 1.21 version specified in go.mod, we can replace this string with a built-in constant in the standard library

use the built-in const

---

README.md

removed gologger (archived), logmatic (no activity)
logmatic - 4+ year inactivity
gologger - 7+ year inactivity archived in 2019

remove outdated

---

README.md

Add item `starlet` under `Embeddable Scripting Languages`

---

main.go

There is a TODO comment in main.go.
https://github.com/avelino/awesome-go/blob/18c06bce29392d446b0373d4b9f933419af51e15/main.go#L45-L49
So I implemented it by using `go:embed` directive and `embed.FS`

Use embed.FS for templates

---

README.md

`skelterjohn/go-pkg-complete`: last commit was 7 years ago
`pieterclaerhout/go-james`: the repo has been marked as archived

feat: add go-size-analyzer

---

README.md

Hi! Requesting add after few months of polishing the BCL project. 

add bcl to Configuration section

---

README.md

- repo link (github.com, gitlab.com, etc): https://github.com/adrianosela/multikey
- pkg.go.dev: https://pkg.go.dev/github.com/adrianosela/multikey
- goreportcard.com: https://goreportcard.com/report/github.com/adrianosela/multikey
- coverage service link ([codecov](https://codecov.io/), [coveralls](https://coveralls.io/), etc.): 
```
✔ ~/go/src/github.com/adrianosela/multikey [master|✔]
09:13 $ go test -cover ./...
ok  	github.com/adrianosela/multikey	1.536s	coverage: 90.9% of statements
ok  	github.com/adrianosela/multikey/galois	0.157s	coverage: …
```

add adrianosela/multikey (under security repos)

---

README.md

Add slogor:  A colorful slog handler

---

README.md

I deleted the package:
- [gcfg](https://github.com/go-gcfg/gcfg?tab=readme-ov-file) - The package has not been supported for a long time and there is no documentation in the readme. I went to the godoc documentation, there is a TODO with the task of writing documentation, however, the last release was in 2018. I …

Please add go-cfg (parse flag, env, json, yaml, toml to struct)

---

README.md

Please add knights-analytics/hugot

---

README.md

- repo link (github.com, gitlab.com, etc): https://sr.ht/~jamesponddotco/acopw-go/
- pkg.go.dev: https://pkg.go.dev/git.sr.ht/~jamesponddotco/acopw-go
- goreportcard.com: https://goreportcard.com/report/git.sr.ht/~jamesponddotco/acopw-go
- coverage service link ([codecov](https://codecov.io/), [coveralls](https://coveralls.io/), etc.): https://git.sr.ht/~jamesponddotco/acopw-go/tree/trunk/item/cover.out …

Add acopw-go to the Security category

---

README.md

add smart-home to the IoT category

---

README.md

feat: add Fuego to Web Frameworks section.

---

.github/workflows/run-check.yaml
.github/workflows/site-deploy.yaml
.github/workflows/tests.yaml

This PR bumps the `actions/checkout` from `v3` to `v4`.
_Issue warned on actions tab_
> The following actions uses Node.js version which is deprecated and will be forced to run on node20: actions/checkout@v3. For more info: https://github.blog/changelog/2024-03-07-github-actions-all-actions-will-run-on-node20-instead-of-node16-by-default/

bump actions/checkout to v4

---

README.md

fix(goroutines): added yaitoo/async

---

README.md

The library is designed to save the developer from the headache when working with RabbitMQ. The library covers the needs to auto-reconnect to RabbitMQ in case of problems and supports publish retries with backoff. It takes into account the need to re-declare entities in RabbitMQ after reconnection.
- repo link (github.com, gitlab.com, etc): https://github.com/furdarius/rabbitroutine
- pkg.go.dev: https://pkg.go.dev/github.com/furdarius/rabbitroutine
- goreportcard.com: https://goreportcard.com/report/github.com/furdarius/rabbitroutine
- coverage service link ([codecov](https://codecov.io/), [coveralls](https://coveralls.io/), etc.): https://app.codecov.io/gh/furdarius/rabbitroutine
**The boxes to check**

Add rabbitroutine

---

README.md

- https://github.com/AnikHasibul/queue - Seems unmaintained. No docs, coverage, etc. Seems like it can be replaced with a simple WaitGroup + a semaphore.

Add rill to goroutines category

---

README.md

This adds a new section for Data Integration Frameworks, moves two existing entries into it and adds a new entry (CloudQuery).
- repo link: https://github.com/cloudquery/cloudquery
- pkg.go.dev: https://pkg.go.dev/github.com/cloudquery/plugin-sdk
- goreportcard.com: https://goreportcard.com/report/github.com/cloudquery/cloudquery and  https://goreportcard.com/report/github.com/cloudquery/plugin-sdk

Add section for data integration frameworks and add CloudQuery

---

README.md

* [badio](https://github.com/cavaliergopher/badio) - last commit was 9 years ago, no stable version available.

Includes arch go into Testing section

---

README.md

Repo - https://github.com/wesovilabs/beyond
- It has been 5 years since an update to the repo
- https://github.com/wesovilabs/beyond/issues last closed issue was in 2019 
The documentation is also no longer maintained with an invalid SSL cert - http://wesovilabs.github.io/beyond
Removal issue - https://github.com/wesovilabs/beyond/issues/41

Removing github.com/wesovilabs/beyond for no longer being maintained

---

README.md

- repo link (github.com, gitlab.com, etc): https://github.com/juicedata/juicefs
- pkg.go.dev: https://pkg.go.dev/github.com/juicedata/juicefs
- goreportcard.com: https://goreportcard.com/report/github.com/juicedata/juicefs
- coverage service link ([codecov](https://codecov.io/), [coveralls](https://coveralls.io/), etc.): https://app.codecov.io/gh/juicedata/juicefs …

Add JuiceFS

---

README.md

Repo - https://github.com/olebedev/config
- https://github.com/olebedev/config/issues?q=is%3Aissue+is%3Aclosed last closed issue was in 2018
Related issue: https://github.com/avelino/awesome-go/issues/5136

Remove github.com/olebedev/config

---

README.md

- repo link (github.com, gitlab.com, etc): https://github.com/semihalev/sdns
- pkg.go.dev: https://pkg.go.dev/github.com/semihalev/sdns
- goreportcard.com: https://goreportcard.com/report/github.com/semihalev/sdns
- coverage service link ([codecov](https://codecov.io/), [coveralls](https://coveralls.io/), etc.): https://app.codecov.io/gh/semihalev/sdns …

Add sdns to Networking

---

README.md

https://github.com/kirillDanshin/nulltime
This project is very old (7 years ago), and Go stdlib has been support [sql.NullTime](https://pkg.go.dev/database/sql#NullTime) since Go 1.13.

Remove https://github.com/kirillDanshin/nulltime

---

README.md

Added `moniGo` to the list - MoniGo is a performance monitoring library for Go applications. It provides real-time insights into application performance.

Add MoniGo

---

README.md

Add Go-Shelve: A persistent, map-like object for the Go programming language with support for multiple key-value stores as backend.

Add Go-Shelve

---

README.md

Fix: topk link (missing https://)

---

README.md

feat: add reflection category

---

README.md

Hi :wave: ,
I'd like to add [chromem-go](https://github.com/philippgille/chromem-go) to this list. I added it to the AI section because it doesn't serve as a general database (different from all entries in the database section), and as a vector store its main purpose is storing embeddings (generated with LLMs) and retrieving them based on cosine similarity. It's used in Retrieval-Augmented Generation (RAG) pipelines, where the next step is to feed the fetched documents to an LLM. (See project README and [examples](https://github.com/philippgille/chromem-go/tree/v0.6.0/examples)). Also it integrates with Ollama which is in the AI section. It's already listed on the Ollama README [here](https://github.com/ollama/ollama/blob/v0.1.48/README.md?plain=1#L322).
Regarding coverage, I haven't …

Add chromem-go

---

README.md

- [ x] Continuous integration is used to attempt to catch issues prior to releasing this package to end-users.
> I have only changed the URL of an existing package, as I have consolidated all my Go packages from my personal GH account to a GH org.

changed URL from bnkamalesh/webgo to naughtygopher/webgo

---

README.md

add OpenZiti and related libraries

Add OpenZiti to the list for zero trust

---

README.md

https://github.com/albrow/jobs - archived

Add workflow frameworks and github.com/luno/workflow

---

README.md

added new package pocache 

---

README.md

add go tripper

---

README.md

Added goravel in web frameworks section in README.md

---

README.md

Hi there :wave: 
As I've been investigating Go in the context of web applications, I've found a lot of things in this awesome list, thanks!
But I've also found many dead/unmaintained projects, and to be honest it was a bit of a pain because when you're in the discovery phase like I am, you want an awesome list to be concise and up-to-date. So here is a PR to clean things up.
I've made a first commit with the mass-removal of many obviously dead projects, then other commits with single projects that I'm not sure would fit your criteria for removal.
Related to #5136

Cleanup on Web Frameworks

---

README.md

Added Clace in Server Applications

---

README.md

I deleted the package:
* [amazon-product-advertising-api](https://github.com/ngs/go-amazon-product-advertising-api) - The following package does not have a tagged version nor a `go.mod` file. It was updated 8 years ago last time.

Add aws-encryption-sdk-go

---

README.md

I added [Pixel 2](https://github.com/gopxl/pixel) in Game Development section. 
I also changed description of the original [Pixel](https://github.com/faiface/pixel) about not being actively developed. 

Added Pixel 2 in Game Development section

---

README.md

Remove: https://github.com/neotoolkit/faker
It's now archived. 😞

remove neotoolkit/faker

---

README.md

Remove: https://github.com/cosiner/gohper.

Remove: cosiner/gohper

---

README.md

Remove: https://github.com/mholt/binding.
Reason: Archived

Remove: mholt/binding (archived)

---

README.md

Remove: https://github.com/jinyeom/neat.

Remove: jinyeom/neat

---

README.md

Remove: https://github.com/theia-ide/theia-go-extension

Remove: theia-ide/theia-go-extension

---

README.md

Remove: https://github.com/mholt/golang-graphics

Remove mholt/golang-graphics

---

README.md

Remove: https://github.com/mattn/gom

Remove: mattn/gom

---

README.md

- Forge link: https://github.com/ashwingopalsamy/uuidcheck
- pkg.go.dev: https://pkg.go.dev/github.com/ashwingopalsamy/uuidcheck
- goreportcard.com: https://goreportcard.com/report/github.com/ashwingopalsamy/uuidcheck
- coverage link: https://codecov.io/gh/ashwingopalsamy/uuidcheck
Thanks for reviewing!

Add uuidcheck library to uuid 

---

README.md

Remove: https://github.com/crgimenes/goConfig
Reason: link is dead ( returns 404)

Remove: crgimenes/goConfig

---

README.md

Remove: https://github.com/golang/dep

Remove: `golang/dep` && `vgo`

---

README.md

Remove: https://github.com/laher/goxc (archived)

remove: https://github.com/laher/goxc

---

README.md

remove: https://github.com/firstrow/go-outdated (archived)

remove: https://github.com/firstrow/go-outdated

---

README.md

Remove: https://github.com/go-playground/statics (no action for 8 years)

remove: https://github.com/go-playground/statics

---

README.md

add WebhookX and a new category Webhooks Server

---

README.md

add Gulter for file uploads 

---

README.md

- GitHub: https://github.com/axzilla/goilerplate
- pkg.go.dev: https://pkg.go.dev/github.com/axzilla/goilerplate
- goreportcard.com: https://goreportcard.com/report/github.com/axzilla/goilerplate
- Coverage: (Coming soon)
Goilerplate is a modern UI component library for Go and Templ. It provides a set of reusable components that integrate Alpine.js for enhanced interactivity and Tailwind CSS for styling. The library is designed to simplify the development of web applications in Go by offering type-safe, server-side rendered components.
Key features:
- Go-native implementation
- Templ-first design
- Server-Side Rendering (SSR) focus
- Alpine.js integration
- Tailwind CSS styling
- Accessible components
- Type-safe development
I am actively working on improving test coverage, implementing …

add templui to Web Frameworks

---

README.md

Remove: https://github.com/ftrvxmtrx/tga (archived)

Remove: https://github.com/ftrvxmtrx/tga

---

README.md

REMOVE: https://github.com/davemeehan/Neo4j-GO (archived)

Remove: https://github.com/davemeehan/Neo4j-GO

---

README.md

Remove: https://github.com/bigfile/bigfile (archived)

Remove: https://github.com/bigfile/bigfile

---

README.md

- [+] I have read the [Contribution Guidelines](https://github.com/avelino/awesome-go/blob/main/CONTRIBUTING.md#contribution-guidelines)
- [+] I have read the [Maintainers Note](https://github.com/avelino/awesome-go/blob/main/CONTRIBUTING.md#maintainers)
- [+] I have read the [Quality Standards](https://github.com/avelino/awesome-go/blob/main/CONTRIBUTING.md#quality-standards)
- [+] The repo documentation has a pkg.go.dev link.
- [-] The repo documentation has a coverage service link.
- [+] The repo documentation has a goreportcard link.
- [+] The repo has a version-numbered release and a go.mod file.
- [+] The repo has a continuous integration process that …

add package vadiminshakov/committer

---

README.md

add package ncruces/go-sqlite3

---

README.md

- [Azul3D](https://github.com/azul3d/engine) Unmaintained. No commits since 4 years, no replies to issues. See also this [pinned issue](https://github.com/azul3d/engine/issues/179) by the author.

Add Arche ECS to section Game Development

---

README.md

feat(patcher): adding patcher library to readme file

---

README.md

Update `archiver` library reference to `archives` with new description

---

README.md

Removes old pre- embed (introduced in go 1.16) packages.
vfsgen - https://github.com/shurcooL/vfsgen/issues/91

embed category: remove old entries

---

README.md

Add catboost-cgo

---

README.md

As a the library maintainer a want to remove it from the list as I find it harmful.
Per: 
- https://github.com/fluentassert/verify/pull/152
- https://github.com/fluentassert/verify/pull/153

Remove fluentassert/verify

---

README.md

This project does not have a working pkg.go.dev, because the Go part of the compiler is really only used to perform reflection on the typed AST and send it to the Haxe side via JSON.
No coverage service is linked because the test coverage comes from running the Go stdlib in test mode and related unit tests from Go and Yaegi test suites using a regression system to make sure no passing test is able to regress in the future.
- [esp32-transpiler](https://github.com/andygeiss/esp32-transpiler): because the last commit was 2 years ago, and no activity on the last made issues for more then 2 years.
- [c2go](https://github.com/goplus/c2go) archived and unfinished.
- [tardisgo](https://github.com/tardisgo/tardisgo) On ice, last commit 9 years ago. …

Go compilers category add go2hx

---

README.md

ronykit added
