avelino/awesome-go

README.md
- website: https://www.confetti-framework.com
- github.com repo: https://github.com/confetti-framework/confetti
- pkg.go.dev: https://pkg.go.dev/github.com/confetti-framework/confetti
- goreportcard.com: https://goreportcard.com/report/github.com/confetti-framework/confetti
- coverage service link [codecov](https://github.com/confetti-framework/confetti/blob/main/test/README.md)
=> Add Confetti Framework

README.md
- github.com repo: https://github.com/insidieux/inizio
- pkg.go.dev: https://pkg.go.dev/github.com/insidieux/inizio
- goreportcard.com: https://goreportcard.com/report/github.com/insidieux/inizio
- coverage service link [codecov](https://codecov.io/gh/insidieux/inizio/branch/master)
=> Add insidieux/inizio to Project Layout list

README.md
Reviving #3517
- github.com repo: https://github.com/haveyoudebuggedit/go-patterns
- goreportcard.com: https://goreportcard.com/report/github.com/haveyoudebuggedit/go-patterns
- coverage service link ([codecov](https://codecov.io/), [coveralls](https://coveralls.io/), [gocover](http://gocover.io/) etc.) N/A
=> Adding Debugged.it Go patterns

README.md
- github.com repo:[https://github.com/GuilhermeCaruso/anko](https://github.com/GuilhermeCaruso/anko)
- goreportcard.com: [https://goreportcard.com/report/github.com/GuilhermeCaruso/anko](https://goreportcard.com/report/github.com/GuilhermeCaruso/anko)
- coverage service link: [https://app.codecov.io/gh/GuilhermeCaruso/anko](https://app.codecov.io/gh/GuilhermeCaruso/anko)
Thanks …
=> [Build Automation] Added anko project

README.md
- github.com repo: https://github.com/OldPanda/bloomfilter
- pkg.go.dev: https://pkg.go.dev/github.com/OldPanda/bloomfilter
- goreportcard.com: https://goreportcard.com/report/github.com/OldPanda/bloomfilter
- coverage service link: [codecov](https://app.codecov.io/gh/OldPanda/bloomfilter)
=> Add bloomfilter

README.md
Signed-off-by: Felipe Zipitria <felipe.zipitria@owasp.org>
- github.com repo: https://github.com/bykof/gostradamus
- pkg.go.dev: https://pkg.go.dev/github.com/bykof/gostradamus
- goreportcard.com: https://goreportcard.com/report/github.com/bykof/gostradamus
- coverage service link: https://app.codecov.io/gh/bykof/gostradamus
=> feat(date): add gostradamus

README.md
=> Add "Practical Go lessons" book

README.md
=> Add Golang Kathmandu Meetup

README.md
- github.com repo: https://github.com/x1unix/docker-go-mingw
- pkg.go.dev: **Not applicable**
- goreportcard.com: **Not applicable**
- coverage service link ([codecov](https://codecov.io/), [coveralls](https://coveralls.io/), [gocover](http://gocover.io/) etc.): **Not applicable**
=> Add docker-go-mingw

README.md
- github.com repo: https://github.com/jfcg/yell
- pkg.go.dev: https://pkg.go.dev/github.com/jfcg/yell
- goreportcard.com: https://goreportcard.com/report/github.com/jfcg/yell
- coverage service link: https://gocover.io/github.com/jfcg/yell
=> add jfcg/yell: yet another minimalistic logging library

README.md
- github.com repo: https://github.com/madflojo/tasks
- pkg.go.dev: https://pkg.go.dev/github.com/madflojo/tasks
- goreportcard.com: https://goreportcard.com/report/github.com/madflojo/tasks
- coverage service link ([codecov](https://codecov.io/), [coveralls](https://coveralls.io/), [gocover](http://gocover.io/) etc.) https://coveralls.io/github/madflojo/tasks?branch=master
Thanks …
=> Adding Tasks

README.md
#3551 Changed go-myanimelist webpage
=> #3551 Changed go-myanimelist webpage

README.md
- github.com repo: https://github.com/becheran/roumon
- pkg.go.dev: https://pkg.go.dev/github.com/becheran/roumon
- goreportcard.com: https://goreportcard.com/report/github.com/becheran/roumon
=> Add roumon

README.md
- github.com repo:https://github.com/arxdsilva/golang-ifood-sdk
- pkg.go.dev: https://pkg.go.dev/github.com/arxdsilva/golang-ifood-sdk
- goreportcard.com: [![Go Report Card](https://goreportcard.com/badge/github.com/arxdsilva/golang-ifood-sdk)](https://goreportcard.com/report/github.com/arxdsilva/golang-ifood-sdk)
- coverage service link: [![Coverage Status](https://coveralls.io/repos/github/arxdsilva/golang-ifood-sdk/badge.svg?branch=main)](https://coveralls.io/github/arxdsilva/golang-ifood-sdk?branch=main) …
=> add golang-ifood-sdk

README.md
- github.com repo: https://github.com/IGLOU-EU/go-yapla
- pkg.go.dev: https://pkg.go.dev/git.iglou.eu/Production/go-yapla
- goreportcard.com: https://goreportcard.com/report/git.iglou.eu/Production/go-yapla
- coverage service: https://gocover.io/git.iglou.eu/Production/go-yapla
=> Add go-yapla

README.md
- github.com repo: https://github.com/drewstinnett/go-output-format
- pkg.go.dev: https://pkg.go.dev/github.com/drewstinnett/go-output-format
- goreportcard.com: https://goreportcard.com/report/github.com/drewstinnett/go-output-format
- coverage service link: https://app.codecov.io/gh/drewstinnett/go-output-format
=> Add go-output-format: Output go structures into multiple formats (YAML/JSON/etc) in your command line app.

README.md
- github.com repo: https://github.com/NicoNex/echotron
- pkg.go.dev: https://pkg.go.dev/github.com/NicoNex/echotron/v2
- goreportcard.com: https://goreportcard.com/report/github.com/NicoNex/echotron
- coverage service link:  [coveralls](https://coveralls.io/github/NicoNex/echotron?branch=master/),
=> Add echotron telegram bot library

README.md
- github.com repo: https://github.com/larapulse/migrator
- pkg.go.dev: https://pkg.go.dev/github.com/larapulse/migrator
- goreportcard.com: https://goreportcard.com/report/github.com/larapulse/migrator
- coverage service link [codecov](https://app.codecov.io/gh/larapulse/migrator)
=> Add larapulse/migrator to the Database migrators list

README.md
- github.com repo: https://github.com/hamed-yousefi/gowl
- pkg.go.dev: https://pkg.go.dev/github.com/hamed-yousefi/gowl
- goreportcard.com: https://goreportcard.com/report/github.com/hamed-yousefi/gowl
- coverage service link: https://app.codecov.io/gh/hamed-yousefi/gowl
=> Add Gowl to the Goroutines list

README.md
- github.com repo: https://github.com/avito-tech/normalize
- pkg.go.dev: https://pkg.go.dev/github.com/avito-tech/normalize
- goreportcard.com: https://goreportcard.com/report/github.com/avito-tech/normalize
- coverage service link: [codecov](https://codecov.io/gh/avito-tech/normalize)
=> add normalize lib

README.md
add a k-v database rosedb
- github.com repo: https://github.com/roseduan/rosedb
- pkg.go.dev: https://pkg.go.dev/github.com/roseduan/rosedb
- goreportcard.com: https://goreportcard.com/report/github.com/roseduan/rosedb
- coverage service link ([codecov](https://codecov.io/), [coveralls](https://coveralls.io/), [gocover](http://gocover.io/) etc.): https://app.codecov.io/gh/roseduan/rosedb …
=> add rosedb

README.md
Added github.com/alexeyco/pig
- github.com repo: https://github.com/alexeyco/pig
- pkg.go.dev: https://pkg.go.dev/github.com/alexeyco/pig
- goreportcard.com: https://goreportcard.com/report/github.com/alexeyco/pig
- coverage service link: https://coveralls.io/github/alexeyco/pig?branch=main
=> Added github.com/alexeyco/pig

README.md
Proud to present my first open source project, `godesim`! 
**Disclaimer**: This is the second attempt at adding this library. I have now matched the requirements for a data library to be added.
- github.com repo: https://github.com/soypat/godesim
- pkg.go.dev: https://pkg.go.dev/github.com/soypat/godesim
- goreportcard.com: https://goreportcard.com/report/github.com/soypat/godesim
- coverage service link [codecov](https://codecov.io/gh/soypat/godesim/branch/main)
[![Go Report Card](https://goreportcard.com/badge/github.com/soypat/godesim)](https://goreportcard.com/report/github.com/soypat/godesim)
[![go.dev reference](https://pkg.go.dev/badge/github.com/soypat/godesim)](https://pkg.go.dev/github.com/soypat/godesim)
[![codecov](https://codecov.io/gh/soypat/godesim/branch/main/graph/badge.sv …
=> add godesim & gitaligned

README.md
- github.com repo: https://github.com/gotuna/gotuna
- pkg.go.dev: https://pkg.go.dev/github.com/gotuna/gotuna
- goreportcard.com: https://goreportcard.com/report/github.com/gotuna/gotuna
- coverage service link ([codecov](https://codecov.io/), [coveralls](https://coveralls.io/), [gocover](http://gocover.io/) etc.): https://app.codecov.io/gh/gotuna/gotuna …
=> Added GoTuna

README.md
> 
> **Make sure that you've checked the boxes below before you submit PR:**
> 
> * [x]  I have added my package in alphabetical order.
> * [x]  I have an appropriate description with correct grammar.
> * [x]  I know that this package was not listed before.
> * [x]  I have added pkg.go.dev link to the repo and to my pull request.
> * [x]  I have added coverage service link to the repo and to my pull request.
> * [x]  I have added goreportcard link to the repo and to my pull request.
> * [x]  I have read [Contribution guidelines](https://github.com/avelino/awesome-go/blob/master/CONTRIB …
=> Added Golang Poland meetup

README.md
- github.com repo: https://github.com/IGLOU-EU/go-wildcard
- pkg.go.dev: https://pkg.go.dev/git.iglou.eu/Imported/go-wildcard
- goreportcard.com: https://goreportcard.com/report/git.iglou.eu/Imported/go-wildcard
- coverage service link: https://gocover.io/git.iglou.eu/Imported/go-wildcard
=> Add go-wildcard

README.md
- github.com repo: https://github.com/mikekonan/go-types
- pkg.go.dev: https://pkg.go.dev/github.com/mikekonan/go-types@v1.0.1
- goreportcard.com: https://goreportcard.com/report/github.com/mikekonan/go-types
- coverage service link: https://app.codecov.io/gh/mikekonan/go-types
=> added go-type

README.md
- github.com repo: https://json-to-proto.github.io/, https://github.com/json-to-proto/json-to-proto.github.io
=> Added JSON-to-Proto under Go Tools

README.md
https://github.com/pellared/taskflow has been migrated. 
This PR just updates the name and hyperlink.
---
- github.com repo: https://github.com/goyek/goyek
- pkg.go.dev: https://pkg.go.dev/github.com/goyek/goyek
- goreportcard.com: https://goreportcard.com/report/github.com/goyek/goyek
- coverage service link: https://app.codecov.io/gh/goyek/goyek …
=> taskflow migrated to goyek

README.md
- github.com repo: [https://github.com/nazar256/parapipe](https://github.com/nazar256/parapipe)
- pkg.go.dev: [https://pkg.go.dev/github.com/nazar256/parapipe](https://pkg.go.dev/github.com/nazar256/parapipe)
- goreportcard.com: [https://goreportcard.com/report/github.com/nazar256/parapipe](https://goreportcard.com/report/github.com/nazar256/parapipe)
- coverage service link: [https://gocover.io/github.com/nazar256/parapipe](https://gocover.io/github.com/nazar256/parapipe)
=> Added "Data Structures" -> parapipe

README.md
- github.com repo: https://github.com/cyucelen/marker
- pkg.go.dev: https://pkg.go.dev/github.com/cyucelen/marker
- goreportcard.com: https://goreportcard.com/report/github.com/cyucelen/marker
- coverage service link https://app.codecov.io/gh/cyucelen/marker
=> Added marker

README.md
Submitting a pull request to add GoFlake to the UUID section of the libraries. Contribution guidelines have been read and complied with. Gocover.io lists a 100% code coverage
- github.com repo: https://github.com/Hart87/GoFlake
- pkg.go.dev:  https://pkg.go.dev/github.com/hart87/goflake
- goreportcard.com: https://goreportcard.com/report/github.com/hart87/goflake
- coverage service link gocover](http://gocover.io/ : https://gocover.io/github.com/hart87/goflake
**Note**: that new categories can be added only when there are 3 …
=> Added  GoFlake

README.md
This PR moves ghorg  from "Uncategorized" to  "DevOps".
=> Move ghorg from uncategorized to the devops category

README.md
- github.com repo: https://github.com/hdt3213/godis
- pkg.go.dev:  https://pkg.go.dev/github.com/hdt3213/godis
- goreportcard.com: https://goreportcard.com/report/github.com/HDT3213/godis
- coverage service link: https://coveralls.io/github/HDT3213/godis
=> add godis into database category

README.md
- github.com repo: https://github.com/rainu/go-command-chain
- pkg.go.dev: https://pkg.go.dev/github.com/rainu/go-command-chain@v0.1.0
- goreportcard.com: https://goreportcard.com/report/github.com/rainu/go-command-chain
https://app.codecov.io/gh/rainu/go-command-chain …
=> Add command-chain

README.md
- github.com repo: https://github.com/aler9/gortsplib
- pkg.go.dev: https://pkg.go.dev/github.com/aler9/gortsplib
- goreportcard.com: https://goreportcard.com/report/github.com/aler9/gortsplib
- coverage service link https://codecov.io/gh/aler9/gortsplib/branch/main
=> Add gortsplib

README.md
QR code generator (ASCII & PNG) for SEPA payments.
- github.com repo: https://github.com/jovandeginste/payme
- pkg.go.dev: https://pkg.go.dev/github.com/jovandeginste/payme
- goreportcard.com: https://goreportcard.com/report/github.com/jovandeginste/payme
- coverage service link: http://gocover.io/github.com/jovandeginste/payme
=> Add "jovandeginste/payme"

README.md
Add uConfig configuration management library.
- github.com repo: https://github.com/omeid/uconfig/
- pkg.go.dev: https://pkg.go.dev/github.com/omeid/uconfig/
- goreportcard.com: https://goreportcard.com/report/github.com/omeid/uconfig
- coverage service link https://gocover.io/github.com/omeid/uconfig
=> Add Configuration/uConfig

README.md
- github.com repo: https://github.com/wangyoucao577/go-project-layout
- pkg.go.dev: https://pkg.go.dev/github.com/wangyoucao577/go-project-layout
- goreportcard.com: https://goreportcard.com/report/github.com/wangyoucao577/go-project-layout
- coverage service link: https://app.codecov.io/gh/wangyoucao577/go-project-layout
=> Add go-project-layout

README.md
Hi,
This PR adds [otpgen](https://github.com/grijul/otpgen) to awesome-go.
---
- github.com repo: https://github.com/grijul/otpgen
- pkg.go.dev: https://pkg.go.dev/github.com/grijul/otpgen
- goreportcard.com: https://goreportcard.com/report/github.com/grijul/otpgen
- coverage service link: [gocover](https://gocover.io/github.com/grijul/otpgen) …
=> added otpgen

README.md
- github.com repo: https://github.com/esurdam/go-swagger-ui
- pkg.go.dev: https://pkg.go.dev/github.com/esurdam/go-swagger-ui
- goreportcard.com: https://goreportcard.com/report/github.com/esurdam/go-swagger-ui
Coverage handled in Github Action -- https://github.com/esurdam/go-swagger-ui/suites/2820638238/artifacts/62806919 …
=> Add go-swagger-ui

README.md
- github.com repo: https://github.com/golang-design/clipboard
- pkg.go.dev: https://pkg.go.dev/golang.design/x/clipboard
- goreportcard.com: https://goreportcard.com/report/github.com/golang-design/clipboard
=> Add clipboard

README.md
- github.com repo: https://github.com/alajmo/mani
- pkg.go.dev: https://pkg.go.dev/github.com/alajmo/mani
- goreportcard.com: https://goreportcard.com/report/github.com/alajmo/mani
- coverage service link ([codecov](https://codecov.io/), [coveralls](https://coveralls.io/), [gocover](http://gocover.io/) etc.)  I use integration tests since it's a CLI tool that mainly interacts with the filesystem. See https://github.com/alajmo/mani/tree/main/test.  …
=> Add mani to the Utilities category

README.md
Hi, adding the columnar store I've been working on for a while, it's an in-memory store with full transactional support and extremely fast querying using bitmap indexes. It supports custom columns, and a consistent change stream allowing to build replication systems (CDC). Hopefully of interest to some folks out there!
- github.com repo: https://github.com/kelindar/column
- pkg.go.dev: https://pkg.go.dev/github.com/kelindar/column
- goreportcard.com: https://goreportcard.com/report/github.com/kelindar/column 
- coverage service link: https://coveralls.io/github/kelindar/column (**99%** coverage)  …
=> Add columnar store

README.md
- github.com repo: https://github.com/dnnrly/hoofli
- pkg.go.dev: https://pkg.go.dev/github.com/dnnrly/hoofli
- goreportcard.com: https://goreportcard.com/report/github.com/dnnrly/hoofli
- coverage service link: https://app.codecov.io/gh/dnnrly/hoofli
=> Add hoofli

README.md
This PR adds go-andotp to awesome-go.
---
- github.com repo: https://github.com/grijul/go-andotp
- pkg.go.dev: https://pkg.go.dev/github.com/grijul/go-andotp
- goreportcard.com: https://goreportcard.com/report/github.com/grijul/go-andotp
- coverage service link: https://gocover.io/github.com/grijul/go-andotp
=> Added go-andotp

README.md
- github.com repo: https://github.com/chanify/chanify
- pkg.go.dev: https://pkg.go.dev/github.com/chanify/chanify
- goreportcard.com: https://goreportcard.com/report/github.com/chanify/chanify
- coverage service link: https://codecov.io/gh/chanify/chanify
=> Add chanify.

README.md
Hi folks,
I'm adding a high quality implementation of a dense bitmap/bitset which supports various logical operations, iterating over, filtering and is SIMD-enabled (AVX2) for large dense bitsets. AVX-512 contributions would be welcome, if anyone has CPU that supports these.
- github.com repo: https://github.com/kelindar/bitmap
- pkg.go.dev: https://pkg.go.dev/github.com/kelindar/bitmap
- goreportcard.com: https://goreportcard.com/report/github.com/kelindar/bitmap
- coverage service link: https://coveralls.io/github/kelindar/bitmap (**97% coverage**)
Thanks for reviewing this!
=> Adding kelindar/bitmap

README.md
- github.com repo: https://github.com/xwjdsh/awesome-go-extra
- pkg.go.dev: https://pkg.go.dev/github.com/xwjdsh/awesome-go-extra
- goreportcard.com: https://goreportcard.com/report/github.com/xwjdsh/awesome-go-extra
- coverage service link ([codecov](https://codecov.io/), [coveralls](https://coveralls.io/), [gocover](http://gocover.io/) etc.) https://app.codecov.io/gh/xwjdsh/awesome-go-extra …
=> Add awesome-go-extra

README.md
- github.com repo: https://github.com/hexdigest/execpool
- pkg.go.dev: https://pkg.go.dev/github.com/hexdigest/execpool
- goreportcard.com: https://goreportcard.com/report/github.com/hexdigest/execpool
- coverage service link [coveralls](https://coveralls.io/github/hexdigest/execpool?branch=main)
=> Added hexdingest/execpool to the Goroutines category

README.md
- github.com repo: https://github.com/nikolaydubina/jsonl-graph
- pkg.go.dev: https://pkg.go.dev/github.com/nikolaydubina/jsonl-graph
- goreportcard.com: https://goreportcard.com/report/github.com/nikolaydubina/jsonl-graph
- coverage service link: https://codecov.io/gh/nikolaydubina/jsonl-graph 
=> Added jsonl-graph

README.md
- github.com repo: https://github.com/miladibra10/vjson
- pkg.go.dev: https://pkg.go.dev/github.com/miladibra10/vjson
- goreportcard.com: https://goreportcard.com/report/github.com/miladibra10/vjson
- coverage service link: https://app.codecov.io/gh/miladibra10/vjson
=> Add vjson library

README.md
- github.com repo: https://github.com/elves/elvish
- pkg.go.dev: https://pkg.go.dev/github.com/elves/elvish
- goreportcard.com: https://goreportcard.com/report/github.com/elves/elvish
- coverage service link: https://app.codecov.io/gh/elves/elvish/branch/master
- [ x] I have added my package in alphabetical order.
- [ x] I know that this package was not listed before.
- [ x] I have added pkg.go.dev link to the repo and to my pull request.
- [ x] I have added coverage service link to the repo and to my pull request.
- [ x] I have added goreportcard link to the repo and to my pull request.
- [ x] I have read [Contribution …
=> Elvish Programming Language

README.md
- github.com repo: https://github.com/ncruces/zenity
- pkg.go.dev: https://pkg.go.dev/github.com/ncruces/zenity
- goreportcard.com: https://goreportcard.com/report/github.com/ncruces/zenity
- coverage service link: https://gocover.io/github.com/ncruces/zenity
Very good coverage:
Automated coverage is bellow 80%. Good coverage (~100%) of the bits that are easier to *unit* test, and not that great elsewhere. Testing strategy is to add scripted tests that require specific user interaction, but those won't change automated coverage numbers.
Stable or …
=> Add zenity

README.md
- github.com repo: https://github.com/peterstace/simplefeatures
- pkg.go.dev: https://pkg.go.dev/github.com/peterstace/simplefeatures/geom?tab=doc
- goreportcard.com: https://goreportcard.com/report/github.com/peterstace/simplefeatures
- coverage service link ([codecov](https://codecov.io/), [coveralls](https://coveralls.io/), [gocover](http://gocover.io/) etc.) https://coveralls.io/github/peterstace/simplefeatures …
=> Add simplefeatures

README.md
- repo link https://github.com/mkungla/bexp
- pkg.go.dev: https://pkg.go.dev/github.com/mkungla/bexp/v2
- goreportcard.com: https://goreportcard.com/report/github.com/mkungla/bexp
- coverage service link https://coveralls.io/github/mkungla/bexp?branch=main …
=> Add bexp - Brace Expansion library

README.md
- repo link (github.com, gitlab.com, etc): https://github.com/MarvinJWendt/testza
- pkg.go.dev: https://pkg.go.dev/github.com/MarvinJWendt/testza
- goreportcard.com: https://goreportcard.com/report/github.com/MarvinJWendt/testza
- coverage service link: https://gocover.io/github.com/MarvinJWendt/testza (89.0% - The README badge shows a lower coverage, since Codecov calculates coverage differently than `go test -cover`)
=> add testza

README.md
Hi!
I'd like to remove a library that I added a couple of years ago because it has gone stale and I don't actively maintain it anymore.
By the way, thanks a lot for awesome-go!
=> Remove whiteshtef/clockwork

README.md
- repo link (github.com, gitlab.com, etc): https://github.com/alexliesenfeld/health
- pkg.go.dev: https://pkg.go.dev/github.com/alexliesenfeld/health
- goreportcard.com: https://goreportcard.com/report/github.com/alexliesenfeld/health
- coverage service link: https://app.codecov.io/gh/alexliesenfeld/health …
=> Add github.com/alexliesenfeld/health.

README.md
- repo link (github.com, gitlab.com, etc):https://github.com/golang-module/carbon
- pkg.go.dev:https://pkg.go.dev/github.com/golang-module/carbon
- goreportcard.com:https://goreportcard.com/report/github.com/golang-module/carbon
- coverage service link (codecov, coveralls, gocover etc.):https://codecov.io/gh/golang-module/carbon
_not every repository (project) will fit into …
=> Add carbon as one of datetime packages

README.md
- repo link: [https://github.com/xuri/excelize](https://github.com/xuri/excelize)
- pkg.go.dev:[https://pkg.go.dev/github.com/xuri/excelize/v2](https://pkg.go.dev/github.com/xuri/excelize/v2)
- goreportcard.com: [https://goreportcard.com/report/github.com/xuri/excelize](https://goreportcard.com/report/github.com/xuri/excelize)
- coverage service link: [https://app.codecov.io/gh/qax-os/excelize](https://app.codecov.io/gh/qax-os/excelize)
**Make …
=> Update excelize repo URL

README.md
- github.com repo: [https://github.com/megaease/easegress](https://github.com/megaease/easegress)
- pkg.go.dev: [https://pkg.go.dev/github.com/megaease/easegress]( https://pkg.go.dev/github.com/megaease/easegress)
- goreportcard.com:  A+ [https://goreportcard.com/report/github.com/megaease/easegress](https://goreportcard.com/report/github.com/megaease/easegress)
- coverage service link ([codecov](https://codecov.io/gh/megaease/easegress))
=> Add Easegress

README.md
- repo link (github.com, gitlab.com, etc): https://github.com/sunary/sqlize
- pkg.go.dev: https://pkg.go.dev/github.com/sunary/sqlize
- goreportcard.com: https://goreportcard.com/report/github.com/sunary/sqlize
- coverage service link: https://app.codecov.io/gh/sunary/sqlize …
=> add sunary/sqlize

README.md
- github.com repo: https://github.com/allaboutapps/go-starter
- pkg.go.dev: N/A this is a project layout
- goreportcard.com: https://goreportcard.com/report/github.com/allaboutapps/go-starter
- coverage service link [codecov](https://app.codecov.io/gh/allaboutapps/go-starter)
=> Add go-starter

README.md
- [bafi repo link](https://github.com/mmalcek/bafi)
- pkg.go.dev - Not applicable - Application
- [goreportcard](https://goreportcard.com/report/github.com/mmalcek/bafi)
- [gocover](https://gocover.io/github.com/mmalcek/bafi)
=> Add bafi to Awsome Go list

README.md
- repo link (github.com, gitlab.com, etc): github.com/carlmjohnson/requests
- pkg.go.dev: https://pkg.go.dev/github.com/carlmjohnson/requests
- goreportcard.com: https://goreportcard.com/report/github.com/carlmjohnson/requests
- coverage service link ([codecov](https://codecov.io/), [coveralls](https://coveralls.io/), [gocover](http://gocover.io/) etc.): https://gocover.io/github.com/carlmjohnson/requests …
=> README: Add requests: HTTP requests for Gophers

README.md
Added gotestfmt, a tool to post-process go test output and make it more readable in CI systems.
https://github.com/haveyoudebuggedit/gotestfmt
- repo link (github.com, gitlab.com, etc): https://github.com/haveyoudebuggedit/gotestfmt
- pkg.go.dev: https://pkg.go.dev/github.com/haveyoudebuggedit/gotestfmt
- goreportcard.com: https://goreportcard.com/report/github.com/haveyoudebuggedit/gotestfmt …
=> Added gotestfmt

README.md
- repo link: https://github.com/andy2046/failured
- pkg.go.dev: https://pkg.go.dev/github.com/andy2046/failured
- goreportcard.com: https://goreportcard.com/report/github.com/andy2046/failured
- coverage service link ([codecov](https://codecov.io/), [coveralls](https://coveralls.io/), [gocover](http://gocover.io/) etc.) https://gocover.io/github.com/andy2046/failured
_not …
=> feat: add adaptive accrual failure detector

README.md
- repo link (github.com, gitlab.com, etc): https://github.com/ferama/rospo
- pkg.go.dev: https://pkg.go.dev/github.com/ferama/rospo
- goreportcard.com: https://goreportcard.com/report/github.com/ferama/rospo
- coverage service link: https://app.codecov.io/gh/ferama/rospo …
=> Add github.com/ferama/rospo

README.md
- repo link (github.com, gitlab.com, etc): https://github.com/jonchun/pathtype
- pkg.go.dev: https://pkg.go.dev/github.com/jonchun/pathtype
- goreportcard.com: https://goreportcard.com/report/github.com/jonchun/pathtype
- coverage service link: https://gocover.io/github.com/jonchun/pathtype …
=> Add github.com/jonchun/pathtype

README.md
- repo link (github.com, gitlab.com, etc): https://github.com/chriscross0/go-restcountries
- pkg.go.dev: https://pkg.go.dev/github.com/chriscross0/go-restcountries
- goreportcard.com: https://goreportcard.com/report/github.com/chriscross0/go-restcountries
- coverage service link: https://coveralls.io/github/chriscross0/go-restcountries?branch=master …
=> Add github.com/chriscross0/go-restcountries

README.md
- repo link: [https://github.com/dedalqq/omg.jsonparser](https://github.com/dedalqq/omg.jsonparser):
- pkg.go.dev: [https://pkg.go.dev/github.com/dedalqq/omg.jsonparser](https://pkg.go.dev/github.com/dedalqq/omg.jsonparser)
- goreportcard.com: [https://goreportcard.com/report/github.com/dedalqq/omg.jsonparser](https://goreportcard.com/report/github.com/dedalqq/omg.jsonparser)
- coverage service link: [https://coveralls.io/github/dedalqq/omg.jsonparser?branch=master](https://coveralls.io/github/dedalqq/omg.jsonparser?branch=master)
Very good …
=> add omg.jsonparser

README.md
- repo link (github.com, gitlab.com, etc): [httpc](https://github.com/valord577/httpc)
- pkg.go.dev: [![Go Reference](https://pkg.go.dev/badge/github.com/valord577/httpc.svg)](https://pkg.go.dev/github.com/valord577/httpc)
- goreportcard.com: [![Go Report Card](https://goreportcard.com/badge/github.com/valord577/httpc?t=0)](https://goreportcard.com/report/github.com/valord577/httpc) …
=> add customizable HTTP client library - httpc

README.md
- repo link (github.com, gitlab.com, etc):https://github.com/golang-module/dongle
- pkg.go.dev:https://pkg.go.dev/github.com/golang-module/dongle
- goreportcard.com:https://goreportcard.com/report/github.com/golang-module/dongle
- coverage service link:https://codecov.io/gh/golang-module/dongle
_not every repository (project) will fit into every option, but most projects …
=> Add dongle

README.md
- repo link (github.com, gitlab.com, etc): https://github.com/kolesa-team/go-webp
- pkg.go.dev: https://godoc.org/github.com/kolesa-team/go-webp
- goreportcard.com: https://goreportcard.com/report/github.com/kolesa-team/go-webp
- coverage service link: https://codecov.io/gh/kolesa-team/go-webp
_not every repository (project) will fit into every option, but most projects …
=> add go-webp library

README.md
- repo link (github.com, gitlab.com, etc): https://github.com/BayesWitnesses/m2cgen
- pkg.go.dev: -
- goreportcard.com: -
- coverage service link: https://app.codecov.io/gh/BayesWitnesses/m2cgen
Hey there! Thanks a lot for this list!
I'm not certainly sure whether this contribution fits the project ideology or not. `m2cgen` is **not written** in Go but **generates** Go code. It is a …
=> Add m2cgen for transpiling ML models into Go code

README.md
I added one link to my Gophers artwork and one link to a serie of articles with concrete applications examples.
=> feat: add gophers artwork and learning go by example tutorial

README.md
- repo link (github.com, gitlab.com, etc): https://github.com/DarthPestilane/easytcp
- pkg.go.dev: https://pkg.go.dev/github.com/DarthPestilane/easytcp
- goreportcard.com: https://goreportcard.com/report/github.com/darthPestilane/easytcp
- coverage service link ([codecov](https://codecov.io/), [coveralls](https://coveralls.io/), [gocover](http://gocover.io/) etc.): https://app.codecov.io/gh/DarthPestilane/easytcp …
=> add easytcp

README.md
=> Add gosamples.dev

README.md
- repo link (github.com, gitlab.com, etc): N/A
=> chore: Replace Link for 'Building Web Apps With Go' and 'Build Web Aplication with Golang'

README.md
=> Removed Golang Challenge Website

README.md
=> Add Awesome Golang Workshops

README.md
- repo link (github.com, gitlab.com, etc): https://github.com/wenerme/go-req
- pkg.go.dev: https://pkg.go.dev/github.com/wenerme/go-req
- goreportcard.com: https://goreportcard.com/report/github.com/wenerme/go-req
- coverage service link ([codecov](https://codecov.io/), [coveralls](https://coveralls.io/), [gocover](http://gocover.io/) etc.) https://codecov.io/gh/wenerme/go-req/branch/main …
=> Add go-req

README.md
Just updating the link to this book, as it has a new edition and thus a new landing page.
=> Update 'For the Love of Go' link

README.md
- repo link (github.com, gitlab.com, etc): https://github.com/yudppp/throttle
- pkg.go.dev: https://pkg.go.dev/github.com/yudppp/throttle
- goreportcard.com: https://goreportcard.com/report/github.com/yudppp/throttle
- coverage service link ([codecov](https://codecov.io/), [coveralls](https://coveralls.io/), [gocover](http://gocover.io/) etc.): https://coveralls.io/github/yudppp/throttle?branch=master …
=> Add throttle library

README.md
=> echotron: update description

README.md
- repo link (github.com, gitlab.com, etc): https://github.com/jmattheis/goverter
- pkg.go.dev: https://pkg.go.dev/github.com/jmattheis/goverter (it is more a cli that library)
- goreportcard.com: https://goreportcard.com/report/github.com/jmattheis/goverter
- coverage service link ([codecov](https://codecov.io/), [coveralls](https://coveralls.io/), [gocover](http://gocover.io/) etc.): https://codecov.io/gh/jmattheis/goverter
---
* The golint warnings are for example code which doesn't really need comments, as the structs don't …
=> Add github.com/jmattheis/goverter

README.md
- repo link (github.com, gitlab.com, etc): https://github.com/rookie-ninja/rk-boot
- pkg.go.dev: https://pkg.go.dev/github.com/rookie-ninja/rk-boot
- goreportcard.com: https://goreportcard.com/report/github.com/rookie-ninja/rk-boot
- coverage service link ([codecov](https://app.codecov.io/gh/rookie-ninja/rk-boot))
_not every repository (project) will fit into every option, …
=> Add rookie-ninja/rk-boot under Web Frameworks

README.md
- repo link (github.com, gitlab.com, etc): https://github.com/rookie-ninja/rk-grpc
- pkg.go.dev: https://pkg.go.dev/github.com/rookie-ninja/rk-grpc
- goreportcard.com: https://goreportcard.com/report/github.com/rookie-ninja/rk-grpc
- coverage service link ([codecov](https://codecov.io/gh/rookie-ninja/rk-grpc))
_not every repository (project) will fit into every option, but …
=> Add rookie-ninja/rk-grpc under Middleware

README.md
- repo link (github.com, gitlab.com, etc): https://github.com/rekby/fixenv
- pkg.go.dev: https://pkg.go.dev/github.com/rekby/fixenv
- goreportcard.com: https://goreportcard.com/report/github.com/rekby/fixenv
- coverage service link: https://coveralls.io/github/rekby/fixenv
- [V] I have added …
=> Add github.com/rekby/fixenv test lib

README.md
(I'm not the Author of added tools, I just share awesome projects!)
Cosmos SDK
- repo link (github.com, gitlab.com, etc): https://github.com/cosmos/cosmos-sdk
- pkg.go.dev: https://pkg.go.dev/github.com/cosmos/cosmos-sdk
- goreportcard.com: https://goreportcard.com/report/github.com/cosmos/cosmos-sdk
- coverage service link ([codecov](https://app.codecov.io/gh/cosmos/cosmos-sdk)
go-ethereum
- repo link (github.com, gitlab.com, etc): https://github.com/ethereum/go-ethereum
- pkg.go.dev: …
=> Add new category - Blockchain 

README.md
- repo link (github.com, gitlab.com, etc):  
+ https://github.com/nofeaturesonlybugs/set
- pkg.go.dev:  
+ https://pkg.go.dev/github.com/nofeaturesonlybugs/set
- goreportcard.com:  
+ https://goreportcard.com/report/github.com/nofeaturesonlybugs/set
- coverage service link ([codecov](https://codecov.io/), [coveralls](https://coveralls.io/), [gocover](http://gocover.io/) etc.)  
+ https://app.codecov.io/gh/nofeaturesonlybugs/set
Very good coverage  **100%**
**Make …
=> Add `set` to README.md

README.md
- repo link (github.com, gitlab.com, etc): https://github.com/evrone/go-clean-template
- pkg.go.dev: N/A this is a project layout
- goreportcard.com: https://goreportcard.com/report/github.com/evrone/go-clean-template
- coverage service link ([codecov](https://codecov.io/), [coveralls](https://coveralls.io/), [gocover](http://gocover.io/) etc.): https://app.codecov.io/gh/evrone/go-clean-template/ …
=> Add go clean template

README.md
- repo link (github.com, gitlab.com, etc): https://github.com/shoobyban/sshman
- pkg.go.dev: https://pkg.go.dev/github.com/shoobyban/sshman
- goreportcard.com: https://goreportcard.com/report/github.com/shoobyban/sshman
- coverage service link ([codecov](https://codecov.io/), [coveralls](https://coveralls.io/), [gocover](http://gocover.io/) etc.) https://gocover.io/github.com/shoobyban/sshman …
=> adding sshman

README.md
=> remove waveform archived

README.md
- repo link: github.com/gyozatech/noodlog
- pkg.go.dev: https://pkg.go.dev/github.com/gyozatech/noodlog
- goreportcard.com: https://goreportcard.com/report/github.com/gyozatech/noodlog
- coverage service link: https://app.codecov.io/gh/gyozatech/noodlog
Very good coverage: 99%
=> added noodlog library to the list for the loggers

README.md
add a i18n package
- repo link (github.com, gitlab.com, etc): https://github.com/youthlin/t
- pkg.go.dev: https://pkg.go.dev/github.com/youthlin/t
- goreportcard.com: https://goreportcard.com/report/github.com/youthlin/t
- coverage service link ([codecov](https://codecov.io/), [coveralls](https://coveralls.io/), [gocover](http://gocover.io/) etc.): https://codecov.io/gh/youthlin/t …
=> add `github.com/youthlin/t`

README.md
- repo link (https://gitlab.com/so_literate/genmock):
- pkg.go.dev: https://pkg.go.dev/gitlab.com/so_literate/genmock
- goreportcard.com: https://goreportcard.com/report/gitlab.com/so_literate/genmock
- coverage service link: https://app.codecov.io/gl/so_literate/genmock …
=> Add genmock (interface mocking with code generator)

README.md
=> Add Thessaloniki golang meetup

README.md
Adding sttr cross-platform, cli app to perform various operations on string.
- repo link (github.com, gitlab.com, etc): https://github.com/abhimanyu003/sttr
- pkg.go.dev: https://pkg.go.dev/github.com/abhimanyu003/sttr
- goreportcard.com: https://goreportcard.com/report/github.com/abhimanyu003/sttr
- coverage service link ([codecov](https://codecov.io/), [coveralls](https://coveralls.io/), [gocover](http://gocover.io/) etc.) https://gocover.io/github.com/abhimanyu003/sttr
**Note**: _that new categories can be added only when …
=> Add sttr to awesome-go

README.md
update description of `checksum`, with a couple of newly supported hashes.
=> update description with newly supported hashes

README.md
- repo link (github.com, gitlab.com, etc): https://github.com/ironsmile/euterpe
- pkg.go.dev: https://pkg.go.dev/github.com/ironsmile/euterpe
- goreportcard.com: https://goreportcard.com/report/github.com/ironsmile/euterpe
- coverage service link ([codecov](https://codecov.io/), [coveralls](https://coveralls.io/), [gocover](http://gocover.io/) etc.): https://coveralls.io/github/ironsmile/euterpe …
=> Add Euterpe to the list of servers

README.md
=> add belgrade golang meetup

README.md
=> Fixed two Typos

README.md
- repo link (github.com, gitlab.com, etc): https://github.com/preslavmihaylov/todocheck
- pkg.go.dev: https://pkg.go.dev/github.com/preslavmihaylov/todocheck
- goreportcard.com: https://goreportcard.com/report/github.com/preslavmihaylov/todocheck
- coverage service link ([codecov](https://codecov.io/), [coveralls](https://coveralls.io/), [gocover](http://gocover.io/) etc.): This one is not applicable as the project is tested via a custom testing framework which doesn't support code coverage
**Note**: _that new categories can be …
=> Add todocheck to awesome-go

README.md
There's significant controversy over golang-standards/project-layout. https://github.com/golang-standards/project-layout/issues/117 . Added warning/note of such. 
- pkg.go.dev: …
=> Update README.md with controversy

README.md
- repo link (github.com, gitlab.com, etc): https://github.com/andygeiss/esp32-transpiler
- pkg.go.dev: https://pkg.go.dev/github.com/andygeiss/esp32-transpiler
- goreportcard.com: https://goreportcard.com/report/github.com/andygeiss/esp32-transpiler
- coverage service link ([codecov](https://codecov.io/), [coveralls](https://coveralls.io/), [gocover](http://gocover.io/) etc.): https://gocover.io/github.com/andygeiss/esp32-transpiler …
=> add andygeiss/esp32-transpiler - transpile from go to Arduino code.

README.md
- repo link (github.com, gitlab.com, etc): https://github.com/rs/xid
- pkg.go.dev: https://pkg.go.dev/github.com/rs/xid
- goreportcard.com: https://goreportcard.com/report/github.com/rs/xid
- coverage service link ([codecov](https://codecov.io/), [coveralls](https://coveralls.io/), [gocover](http://gocover.io/) etc.): https://gocover.io/github.com/rs/xid
_not every repository (project) will fit …
=> Add xid library

README.md
- repo link (github.com, gitlab.com, etc): https://github.com/tg123/go-htpasswd
- pkg.go.dev: https://pkg.go.dev/github.com/tg123/go-htpasswd
- goreportcard.com: https://goreportcard.com/report/github.com/tg123/go-htpasswd
- coverage service link ([codecov](https://codecov.io/), [coveralls](https://coveralls.io/), [gocover](http://gocover.io/) etc.): https://coveralls.io/github/tg123/go-htpasswd …
=> add go-htpasswd

README.md
Added 2 tutorial sites for Go lang
=> Updated README.md with tutorials

README.md
- repo link (github.com, gitlab.com, etc): https://github.com/matryer/is
- pkg.go.dev: https://pkg.go.dev/github.com/matryer/is
- goreportcard.com: https://goreportcard.com/report/github.com/matryer/is
- coverage service link ([codecov](https://codecov.io/), [coveralls](https://coveralls.io/), [gocover](http://gocover.io/) etc.): https://gocover.io/github.com/matryer/is …
=> Add "is" testing framework

README.md
- repo link (github.com, gitlab.com, etc): https://github.com/cristalhq/acmd
- pkg.go.dev: https://pkg.go.dev/github.com/cristalhq/acmd
- goreportcard.com: https://goreportcard.com/report/github.com/cristalhq/acmd
- coverage service link ([codecov](https://codecov.io/), [coveralls](https://coveralls.io/), [gocover](http://gocover.io/) etc.): https://app.codecov.io/gh/cristalhq/acmd
_not every …
=> add cristalhq/acmd

README.md
this just fixes a typo in a previous submission. thanks!
=> fix teleterm typo

README.md
- repo link: https://github.com/dedalqq/omg.testingtools
- pkg.go.dev: https://pkg.go.dev/github.com/dedalqq/omg.testingtools
- goreportcard.com: https://goreportcard.com/report/github.com/dedalqq/omg.testingtools
- coverage service link: https://coveralls.io/github/dedalqq/omg.testingtools?branch=master …
=> github.com/dedalqq/omg.testingtools add packager

README.md
- repo link (github.com, gitlab.com, etc): https://github.com/maargenton/go-testpredicate
- pkg.go.dev: https://pkg.go.dev/github.com/maargenton/go-testpredicate
- goreportcard.com: https://goreportcard.com/report/github.com/maargenton/go-testpredicate
- coverage service link ([codecov](https://codecov.io/), [coveralls](https://coveralls.io/), [gocover](http://gocover.io/) etc.): https://app.codecov.io/gh/maargenton/go-testpredicate …
=> Add `maargenton/go-testpredicate` under Testing

README.md
I'm the original author.  BlueOwl declined to work with me on continued development so I kept going without them.
- repo link (github.com, gitlab.com, etc): https://github.com/muir/nject
- pkg.go.dev: https://pkg.go.dev/github.com/muir/nject
- goreportcard.com: https://goreportcard.com/report/github.com/muir/nject
- coverage service link ([codecov](https://codecov.io/), [coveralls](https://coveralls.io/), [gocover](http://gocover.io/) etc.): https://app.codecov.io/gh/muir/nject/commits?page=1
**Note**: _that new categories can be added only when …
=> my fork of nject represents the ongoing development

README.md
- repo link (github.com, gitlab.com, etc): https://github.com/mosajjal/dnsmonster
- pkg.go.dev: https://pkg.go.dev/github.com/mosajjal/dnsmonster
- goreportcard.com: https://goreportcard.com/report/github.com/mosajjal/dnsmonster
_not every repository (project) …
=> add: dnsmonster

README.md
- repo link (github.com, gitlab.com, etc): https://github.com/prisma/prisma-client-go
- pkg.go.dev: https://pkg.go.dev/github.com/prisma/prisma-client-go
- goreportcard.com: https://goreportcard.com/report/github.com/prisma/prisma-client-go
_not …
=> add: prisma client go orm

README.md
- repo link (github.com, gitlab.com, etc): https://github.com/Yiling-J/cacheme-go
- pkg.go.dev: https://pkg.go.dev/github.com/Yiling-J/cacheme-go
- goreportcard.com: https://goreportcard.com/report/github.com/Yiling-J/cacheme-go
_not every repository (project) …
=> add cacheme

README.md
The library is currently on `v0.6.2` and is already used in production for several
products by OTA-Insight. We aim to have to be on a stable version in the near future.
In order to do so we are waiting on:
- the stabilisation of the Storage API used for one of three possible clients under the hood;
- opt-in data write error handling with managed retry: decide whether we want it or not, and if so, lock this into the API;
- repo link (github.com, gitlab.com, etc): <https://github.com/ota-insight/bqwriter>
- pkg.go.dev: …
=> add bqwriter to the list of Third-Party APIs

README.md
- github.com repo: [github](https://github.com/ezeoleaf/larry)
- pkg.go.dev: [https://pkg.go.dev/github.com/ezeoleaf/larry](https://pkg.go.dev/github.com/ezeoleaf/larry)
- goreportcard.com: [goreportcard](https://goreportcard.com/report/github.com/ezeoleaf/larry)
- coverage service link [coveralls](https://coveralls.io/github/ezeoleaf/larry)
_not every repository (project) will fit into every …
=> Add new bot builder - larry

README.md
- repo link (github.com, gitlab.com, etc): https://github.com/alecthomas/kong
- pkg.go.dev: https://pkg.go.dev/github.com/alecthomas/kong
- goreportcard.com: https://goreportcard.com/report/github.com/alecthomas/kong
=> add github.com/alecthomas/kong

README.md
- repo link (github.com, gitlab.com, etc): https://github.com/s0rg/crawley
- pkg.go.dev: https://pkg.go.dev/github.com/s0rg/crawley
- goreportcard.com: https://goreportcard.com/report/github.com/s0rg/crawley
- coverage service link ([codecov](https://codecov.io/), [coveralls](https://coveralls.io/), [gocover](http://gocover.io/) etc.): https://codeclimate.com/github/s0rg/crawley
=> add crawley

README.md
- repo link (github.com, gitlab.com, etc): https://github.com/mocktools/go-smtp-mock
- pkg.go.dev: https://pkg.go.dev/github.com/mocktools/go-smtp-mock
- goreportcard.com: https://goreportcard.com/report/github.com/mocktools/go-smtp-mock
- coverage service link ([codecov](https://codecov.io/), [coveralls](https://coveralls.io/), [gocover](http://gocover.io/) etc.): [codecov](https://app.codecov.io/gh/mocktools/go-smtp-mock) …
=> Add smtpmock

README.md
- repo link (github.com, gitlab.com, etc): https://github.com/go-lark/lark
- pkg.go.dev: https://pkg.go.dev/github.com/go-lark/lark
- goreportcard.com: https://goreportcard.com/report/github.com/go-lark/lark
- coverage service link ([codecov](https://codecov.io/), [coveralls](https://coveralls.io/), [gocover](http://gocover.io/) etc.): https://app.codecov.io/gh/go-lark/lark
_not every …
=> add go-lark

README.md
A novel, lightweight query builder with 100% coverage, A+ Go Report, full documentation, and at least monthly updates. 
- repo link (github.com, gitlab.com, etc): https://github.com/nullism/bqb
- pkg.go.dev: https://godoc.org/github.com/nullism/bqb
- goreportcard.com: https://goreportcard.com/report/github.com/nullism/bqb
- coverage service link ([codecov](https://codecov.io/), [coveralls](https://coveralls.io/), [gocover](http://gocover.io/) etc.): https://github.com/nullism/bqb/actions/workflows/tests.yml
Thanks …
=> Add bqb "Basic Query Builder"

README.md
Closes  https://github.com/qustavo/sqlhooks/issues/48
- repo link (github.com, gitlab.com, etc): https://github.com/qustavo/sqlhooks
- pkg.go.dev: https://pkg.go.dev/github.com/qustavo/sqlhooks/v2
- goreportcard.com: https://goreportcard.com/report/github.com/qustavo/sqlhooks
- coverage service link ([codecov](https://codecov.io/), [coveralls](https://coveralls.io/), [gocover](http://gocover.io/) etc.): https://coveralls.io/github/qustavo/sqlhooks?branch=master
- [] I have read [Contribution guidelines](https://github.com/avelino/awesome-go/blob/master/CONTRIBUTING.md#contribution-guidelines), [maintainers note](https://github.com/avelino/awesome-go/blob/master/CONTRIBUTING.md#maintainers) and [Quality standard](https://github.com/avelino/awesome-go/blob/master/CONTRIBUTING.md#quality-stan …
=> add sqlhooks

README.md
- repo link: https://github.com/HnH/di
- pkg.go.dev: https://pkg.go.dev/github.com/HnH/di
- goreportcard.com: https://goreportcard.com/report/github.com/HnH/di (A+)
- coverage: https://app.codecov.io/gh/HnH/di (100%)
**Checklist:**
=> HnH/di - DI container library

README.md
- repo link (github.com, gitlab.com, etc): https://github.com/chmike/varint
- pkg.go.dev: https://pkg.go.dev/github.com/chmike/varint
- goreportcard.com: https://goreportcard.com/report/github.com/chmike/varint
- coverage service link ([codecov](https://codecov.io/), [coveralls](https://coveralls.io/), [gocover](http://gocover.io/) etc.): https://gocover.io/github.com/chmike/varint
_not every …
=> add the varint package in the Miscellaneous/Uncategorized section

README.md
It's definitely a component to make console UIs, and not really a "utility".
- repo link (github.com, gitlab.com, etc): N/A
=> Move spinner project under Advanced Console UIs

README.md
=> update description with a newly supported hash - BLAKE2s

.github/PULL_REQUEST_TEMPLATE.md, .github/workflows/tests.yaml, CODE_OF_CONDUCT.md, CONTRIBUTING.md, MAINTAINERS
=> rename all hard ref branch master to main

README.md
- repo link (github.com, gitlab.com, etc): https://github.com/Code-Hex/Neo-cowsay
- pkg.go.dev: https://pkg.go.dev/github.com/Code-Hex/Neo-cowsay/v2
- goreportcard.com: https://goreportcard.com/report/github.com/Code-Hex/Neo-cowsay
- coverage service link ([codecov](https://codecov.io/), [coveralls](https://coveralls.io/), [gocover](http://gocover.io/) etc.): https://app.codecov.io/gh/Code-Hex/Neo-cowsay
_not every repository (project) will fit into every option, but most …
=> added neo cowsay

README.md
Reverts avelino/awesome-go#3896
=> Revert "added neo cowsay"

README.md
=> re-add neo-cowsay

README.md
- repo link (github.com, gitlab.com, etc): https://github.com/chyroc/lark
- pkg.go.dev: https://pkg.go.dev/github.com/chyroc/lark
- goreportcard.com: https://goreportcard.com/report/github.com/chyroc/lark
- coverage service link ([codecov](https://codecov.io/), [coveralls](https://coveralls.io/), [gocover](http://gocover.io/) etc.): https://codecov.io/gh/chyroc/lark/branch/master/graph/badge.svg …
=> feat: add lark sdk

.github/workflows/site-deploy.yaml
=> fixed typo action needs attr

README.md
- repo link (github.com, gitlab.com, etc): https://github.com/icelain/jokeapi
- pkg.go.dev: https://pkg.go.dev/github.com/icelain/jokeapi
- goreportcard.com: https://goreportcard.com/report/github.com/icelain/jokeapi
- coverage service link ([codecov](https://codecov.io/), [coveralls](https://coveralls.io/), [gocover](http://gocover.io/) etc.): https://gocover.io/github.com/icelain/jokeapi
_not …
=> add jokeapi-go

README.md
=> Fixes "leraning" spelling

README.md
Related
- https://github.com/avelino/awesome-go/pull/3401
- https://github.com/avelino/awesome-go/pull/3891
- repo link (github.com, gitlab.com, etc): https://github.com/magefile/mage
- pkg.go.dev: https://pkg.go.dev/github.com/magefile/mage
- goreportcard.com: https://goreportcard.com/report/github.com/magefile/mage …
=> feat: add mage to build automation category

README.md
- repo link (github.com, gitlab.com, etc): https://github.com/ichiban/prolog
- pkg.go.dev: https://pkg.go.dev/github.com/ichiban/prolog
- goreportcard.com: https://goreportcard.com/report/github.com/ichiban/prolog
- coverage service link ([codecov](https://codecov.io/), [coveralls](https://coveralls.io/), [gocover](http://gocover.io/) etc.): https://app.codecov.io/gh/ichiban/prolog
_not every …
=> add prolog

README.md
- repo link (github.com, gitlab.com, etc): https://github.com/mymmrac/telego
- pkg.go.dev: https://pkg.go.dev/github.com/mymmrac/telego
- goreportcard.com: https://goreportcard.com/report/github.com/mymmrac/telego
- coverage service link ([codecov](https://codecov.io/), [coveralls](https://coveralls.io/), [gocover](http://gocover.io/) etc.): https://sonarcloud.io/project/overview?id=mymmrac_telego …
=> Added telego

README.md
- repo link (github.com, gitlab.com, etc): https://github.com/hashicorp/go-retryablehttp
- pkg.go.dev: https://pkg.go.dev/github.com/hashicorp/go-retryablehttp
- goreportcard.com: https://goreportcard.com/report/github.com/hashicorp/go-retryablehttp
_not every …
=> Add hashicorp / go-retryablehttp

README.md
A library for easy and safe convert any value to another type, with 99% coverage, 1000+ test case, A+ Go Report, full documentation, and at least monthly updates. 
- repo link (github.com, gitlab.com, etc): https://github.com/shockerli/cvt
- pkg.go.dev: https://pkg.go.dev/github.com/shockerli/cvt
- goreportcard.com: https://goreportcard.com/report/github.com/shockerli/cvt
- coverage service link ([codecov](https://codecov.io/), [coveralls](https://coveralls.io/), [gocover](http://gocover.io/) etc.): https://app.codecov.io/gh/shockerli/cvt
_not every repository (project) will fit into every option, …
=> Add cvt "Convert any value to another type"

README.md
non-updated package
ref: #3976
=> remove goji/httpauth

README.md
- repo link (github.com, gitlab.com, etc): https://github.com/jfrog/froggit-go
- pkg.go.dev: https://pkg.go.dev/github.com/jfrog/froggit-go
- goreportcard.com: https://goreportcard.com/report/github.com/jfrog/froggit-go
_not every repository (project) will fit into …
=> feat: add froggit-go

README.md
- repo link (github.com, gitlab.com, etc):  https://github.com/abahmed/kwatch
- pkg.go.dev: https://pkg.go.dev/github.com/abahmed/kwatch?tab=doc
- goreportcard.com:  https://goreportcard.com/report/github.com/abahmed/kwatch
- coverage service link ([codecov](https://codecov.io/), [coveralls](https://coveralls.io/), [gocover](http://gocover.io/) etc.): https://codecov.io/gh/abahmed/kwatch
_not …
=> add kwatch

README.md
- repo link (github.com, gitlab.com, etc): https://github.com/google/wire
- pkg.go.dev: https://pkg.go.dev/github.com/google/wire
- goreportcard.com: https://goreportcard.com/report/github.com/google/wire
- coverage service link ([codecov](https://codecov.io/), [coveralls](https://coveralls.io/), [gocover](http://gocover.io/) etc.): https://app.codecov.io/gh/google/wire …
=> Add google/wire to the list of DI libraries

README.md
[![](https://goreportcard.com/badge/github.com/servusdei2018/protoncheck)](https://goreportcard.com/report/github.com/servusdei2018/protoncheck) [![Go Reference](https://pkg.go.dev/badge/github.com/servusdei2018/protoncheck.svg)](https://pkg.go.dev/github.com/servusdei2018/protoncheck) [![](https://sonarcloud.io/api/project_badges/measure?project=servusdei2018_protoncheck&metric=alert_status)](https://sonarcloud.io/project/overview?id=servusdei2018_protoncheck)
ProtonMail module for waybar/polybar/yabar/i3blocks 
- repo link: https://github.com/servusdei2018/protoncheck
- pkg.go.dev: https://pkg.go.dev/github.com/servusdei2018/protoncheck
- goreportcard.com: https://goreportcard.com/report/github.com/servusdei2018/protoncheck
- coverage: https://app.codecov.io/gh/servusdei2018/protoncheck
=> doc: add protoncheck

README.md
- repo link: https://github.com/romshark/jscan
- pkg.go.dev: [![Go Reference](https://pkg.go.dev/badge/github.com/romshark/jscan.svg)](https://pkg.go.dev/github.com/romshark/jscan)
- goreportcard.com: [![Go Report Card](https://goreportcard.com/badge/github.com/romshark/jscan)](https://goreportcard.com/report/github.com/romshark/jscan)
- coverage service link: [![Coverage Status](https://coveralls.io/repos/github/romshark/jscan/badge.svg?branch=main)](https://coveralls.io/github/romshark/jscan?branch=main)
**Note**: _that new categories can be added …
=> Add romshark/jscan

README.md
- repo link (github.com, gitlab.com, etc): https://github.com/datarootsio/cheek
- pkg.go.dev: https://pkg.go.dev/github.com/datarootsio/cheek
- goreportcard.com: https://goreportcard.com/report/github.com/datarootsio/cheek
- coverage service link ([codecov](https://codecov.io/), [coveralls](https://coveralls.io/), [gocover](http://gocover.io/) etc.): https://app.codecov.io/gh/datarootsio/cheek …
=> add cheek job scheduler

README.md
- repo link (github.com, gitlab.com, etc):https://github.com/cloudwego/netpoll
- pkg.go.dev:https://pkg.go.dev/github.com/cloudwego/netpoll
- goreportcard.com:https://goreportcard.com/report/github.com/cloudwego/netpoll
- coverage service link ([codecov](https://codecov.io/), [coveralls](https://coveralls.io/), [gocover](http://gocover.io/) etc.):https://gocover.io/github.com/cloudwego/netpoll …
=> add a new networking lib

README.md
- repo link (github.com, gitlab.com, etc): https://github.com/embano1/memlog
- pkg.go.dev: https://pkg.go.dev/github.com/embano1/memlog
- goreportcard.com: https://goreportcard.com/report/github.com/embano1/memlog
- coverage service link ([codecov](https://codecov.io/), [coveralls](https://coveralls.io/), [gocover](http://gocover.io/) etc.): https://codecov.io/gh/embano1/memlog
_not every …
=> Add `memlog`

README.md
Follow up PR for https://github.com/avelino/awesome-go/pull/4004
- updated the table of contents
- change subcategory titles in markdown from h2 to h3
=> update contents and change headings for ebooks section

README.md
=> Add 'The Power of Go: Tools' ebook

README.md
- repo link (github.com, gitlab.com, etc): https://github.com/structy/log
- pkg.go.dev: https://pkg.go.dev/github.com/structy/log
- goreportcard.com: https://goreportcard.com/report/github.com/structy/log
- coverage service link ([codecov](https://codecov.io/), [coveralls](https://coveralls.io/), [gocover](http://gocover.io/) etc.): https://app.codecov.io/gh/structy/log …
=> add structy/log

README.md
- repo link (github.com, gitlab.com, etc): https://github.com/ctreminiom/go-atlassian
- pkg.go.dev: https://pkg.go.dev/github.com/ctreminiom/go-atlassian
- goreportcard.com: https://goreportcard.com/report/github.com/ctreminiom/go-atlassian
- coverage service link ([codecov](https://codecov.io/), [coveralls](https://coveralls.io/), [gocover](http://gocover.io/) etc.): https://app.codecov.io/gh/ctreminiom/go-atlassian …
=> :sparkles: add go-atlassian

README.md
- repo link (github.com, gitlab.com, etc): https://github.com/junk1tm/env
- pkg.go.dev: https://pkg.go.dev/github.com/junk1tm/env
- goreportcard.com: https://goreportcard.com/report/github.com/junk1tm/env
- coverage service link ([codecov](https://codecov.io/), [coveralls](https://coveralls.io/), [gocover](http://gocover.io/) etc.): https://app.codecov.io/gh/junk1tm/env …
=> add junk1tm/env

README.md
add lotusdb in database
- repo link (github.com, gitlab.com, etc):https://github.com/flower-corp/lotusdb
- pkg.go.dev:https://pkg.go.dev/github.com/flower-corp/lotusdb
- goreportcard.com:https://goreportcard.com/report/github.com/flower-corp/lotusdb
- coverage service link ([codecov](https://codecov.io/), [coveralls](https://coveralls.io/), [gocover](http://gocover.io/) etc.):https://app.codecov.io/gh/flower-corp/lotusdb …
=> add lotusdb

README.md
- repo link (github.com, gitlab.com, etc): https://github.com/rueian/rueidis
- pkg.go.dev: https://pkg.go.dev/github.com/rueian/rueidis
- goreportcard.com: https://goreportcard.com/report/github.com/rueian/rueidis
- coverage service link ([codecov](https://codecov.io/), [coveralls](https://coveralls.io/), [gocover](http://gocover.io/) etc.): https://codeclimate.com/github/rueian/rueidis
_not …
=> add rueidis

README.md
- repo link (github.com, gitlab.com, etc): https://github.com/chenquan/go-pkg
- pkg.go.dev: [![Godoc](https://img.shields.io/badge/godoc-reference-brightgreen)](https://pkg.go.dev/github.com/chenquan/go-pkg)
- goreportcard.com: [![Go Report Card](https://goreportcard.com/badge/github.com/chenquan/go-pkg)](https://goreportcard.com/report/github.com/chenquan/go-pkg) …
=> doc(readme): add go-pkg repository

README.md
=> Added ariga/atlas to Database schema migration.

README.md
- repo link (github.com, gitlab.com, etc): https://github.com/rsjethani/secret
- pkg.go.dev: https://pkg.go.dev/github.com/rsjethani/secret/v2
- goreportcard.com: https://goreportcard.com/report/github.com/rsjethani/secret
- coverage service link ([codecov](https://codecov.io/), [coveralls](https://coveralls.io/), [gocover](http://gocover.io/) etc.):  https://github.com/rsjethani/secret/actions OR https://gocover.io/github.com/rsjethani/secret …
=> Add github.com/rsjethani/secret to security

README.md
- repo link (github.com, gitlab.com, etc): [bingo (github)](https://github.com/iancmcc/bingo)
- pkg.go.dev: [bingo (pkg.go.dev)](https://pkg.go.dev/github.com/iancmcc/bingo)
- goreportcard.com: [bingo (goreportcard.com)](https://goreportcard.com/report/github.com/iancmcc/bingo)
- coverage service link: [bingo (coveralls)](https://coveralls.io/github/iancmcc/bingo)
_not every repository (project) …
=> Add bingo to README

README.md
ref: #4016
https://github.com/square/go-jose/pull/334
=> remove mccoyst/vorbis

README.md
=> remove RichardKnop/go-oauth2-server

README.md
=> remove robbert229/jwt

README.md
- repo link (github.com, gitlab.com, etc): https://github.com/neotoolkit/faker
- pkg.go.dev: https://pkg.go.dev/github.com/neotoolkit/faker
- goreportcard.com: https://goreportcard.com/report/github.com/neotoolkit/faker
- coverage service link ([codecov](https://codecov.io/), [coveralls](https://coveralls.io/), [gocover](http://gocover.io/) etc.): https://app.codecov.io/gh/neotoolkit/faker
_not …
=> feat(README): add faker

README.md
=> fix faker github link

README.md
- repo link (github.com, gitlab.com, etc): https://github.com/go-dummy/dummy
- pkg.go.dev: https://pkg.go.dev/search?q=github.com%2Fgo-dummy%2Fdummy
- goreportcard.com: https://goreportcard.com/report/github.com/go-dummy/dummy
- coverage service link ([codecov](https://codecov.io/), [coveralls](https://coveralls.io/), [gocover](http://gocover.io/) etc.): https://app.codecov.io/gh/go-dummy/dummy …
=> feat(README): add go-dummy

README.md
Thanks @avelino for the translation
=> Add Trybe's style guide

README.md
- repo link (github.com, gitlab.com, etc): [carapace](https://github.com/rsteube/carapace) [carapace-bin](https://github.com/rsteube/carapace-bin)
- pkg.go.dev: [![PkgGoDev](https://pkg.go.dev/badge/github.com/rsteube/carapace)](https://pkg.go.dev/github.com/rsteube/carapace) [![PkgGoDev](https://pkg.go.dev/badge/github.com/rsteube/carapace-bin/pkg/actions)](https://pkg.go.dev/github.com/rsteube/carapace-bin/pkg/actions)
- goreportcard.com: [![GoReportCard](https://goreportcard.com/badge/github.com/rsteube/carapace)](https://goreportcard.com/report/gi …
=> added carapace and carapace-bin

README.md
- repo link (github.com, gitlab.com, etc): https://github.com/neotoolkit/openapi
- pkg.go.dev: https://pkg.go.dev/github.com/neotoolkit/openapi
- goreportcard.com: https://goreportcard.com/report/github.com/neotoolkit/openapi
- coverage service link ([codecov](https://codecov.io/), [coveralls](https://coveralls.io/), [gocover](http://gocover.io/) etc.): https://app.codecov.io/gh/neotoolkit/openapi …
=> docs(README): add openapi

README.md
- repo link (github.com, gitlab.com, etc): https://github.com/rekby/objwalker
- pkg.go.dev: https://pkg.go.dev/github.com/rekby/objwalker
- goreportcard.com:https://goreportcard.com/report/github.com/rekby/objwalker
- coverage service link ([codecov](https://codecov.io/), [coveralls](https://coveralls.io/), [gocover](http://gocover.io/) etc.): https://coveralls.io/github/rekby/objwalker?branch=master …
=> Add objwalker

README.md
- repo link (github.com, gitlab.com, etc): https://github.com/mikestefanello/pagoda
- pkg.go.dev: https://pkg.go.dev/github.com/mikestefanello/pagoda
- goreportcard.com: https://goreportcard.com/report/github.com/mikestefanello/pagoda
- coverage service link ([codecov](https://codecov.io/), [coveralls](https://coveralls.io/), [gocover](http://gocover.io/) etc.): Please see https://github.com/avelino/awesome-go/issues/4036 since this is a starter kit / base project. …
=> Add pagoda

README.md
- repo link: https://github.com/valord577/mailx
- pkg.go.dev: [![Go Reference](https://pkg.go.dev/badge/github.com/valord577/mailx.svg)](https://pkg.go.dev/github.com/valord577/mailx)
- goreportcard.com: [![Go Report Card](https://goreportcard.com/badge/github.com/valord577/mailx)](https://goreportcard.com/report/github.com/valord577/mailx)
**Note**: _that new categories can be added only when there are 3 packages or …
=> add Mailx library

README.md
- repo link (github.com, gitlab.com, etc): https://github.com/ostafen/clover
- pkg.go.dev: https://pkg.go.dev/github.com/ostafen/clover
- goreportcard.com: https://goreportcard.com/report/github.com/ostafen/clover
- coverage service link ([codecov](https://codecov.io/), [coveralls](https://coveralls.io/), [gocover](http://gocover.io/) etc.):  https://app.codecov.io/gh/ostafen/clover
_not every …
=> Add clover to "Database" section

README.md
- repo link (github.com, gitlab.com, etc): https://github.com/fieldryand/goflow
- pkg.go.dev: https://pkg.go.dev/github.com/fieldryand/goflow
- goreportcard.com: https://goreportcard.com/report/github.com/fieldryand/goflow
- coverage service link ([codecov](https://codecov.io/), [coveralls](https://coveralls.io/), [gocover](http://gocover.io/) etc.): https://app.codecov.io/gh/fieldryand/goflow …
=> Add Goflow

README.md
- repo link (github.com, gitlab.com, etc): https://github.com/ggicci/httpin
- pkg.go.dev: https://pkg.go.dev/github.com/ggicci/httpin
- goreportcard.com: https://goreportcard.com/report/github.com/ggicci/httpin
- coverage service link ([codecov](https://codecov.io/), [coveralls](https://coveralls.io/), [gocover](http://gocover.io/) etc.): https://app.codecov.io/gh/ggicci/httpin
_not every …
=> feat(Forms): add httpin package

README.md
- repo link (github.com, gitlab.com, etc): https://github.com/hashicorp/go-cleanhttp
- pkg.go.dev: https://pkg.go.dev/github.com/hashicorp/go-cleanhttp
- goreportcard.com: https://goreportcard.com/report/github.com/hashicorp/go-cleanhttp …
=> add go-cleanhttp

README.md
- repo link (github.com, gitlab.com, etc): https://github.com/charmbracelet/wish
- pkg.go.dev: https://pkg.go.dev/github.com/charmbracelet/wish
- goreportcard.com: https://goreportcard.com/report/github.com/charmbracelet/wish
- coverage service link ([codecov](https://codecov.io/), [coveralls](https://coveralls.io/), [gocover](http://gocover.io/) etc.): https://app.codecov.io/gh/charmbracelet/wish …
=> adds charmbracelet/wish

README.md
=> fix: readme.md Beego link

README.md
- repo link (github.com, gitlab.com, etc): https://github.com/rafaelespinoza/godfish
- pkg.go.dev: https://pkg.go.dev/github.com/rafaelespinoza/godfish
- goreportcard.com: https://goreportcard.com/report/github.com/rafaelespinoza/godfish
- coverage service link ([codecov](https://codecov.io/), [coveralls](https://coveralls.io/), [gocover](http://gocover.io/) etc.): https://codecov.io/gh/rafaelespinoza/godfish …
=> Add godfish

README.md
- repo link (github.com, gitlab.com, etc): https://github.com/danielgtaylor/huma/
- pkg.go.dev: https://pkg.go.dev/github.com/danielgtaylor/huma
- goreportcard.com: https://goreportcard.com/report/github.com/danielgtaylor/huma
- coverage service link ([codecov](https://codecov.io/), [coveralls](https://coveralls.io/), [gocover](http://gocover.io/) etc.): https://app.codecov.io/gh/danielgtaylor/huma
=> feat: add Huma to Web Frameworks section.

README.md
=> fix: make back to the content clickable

README.md
- repo link (github.com, gitlab.com, etc): https://github.com/bmf-san/goblin
- pkg.go.dev: https://pkg.go.dev/github.com/bmf-san/goblin
- goreportcard.com: https://goreportcard.com/report/github.com/bmf-san/goblin
- coverage service link ([codecov](https://codecov.io/), [coveralls](https://coveralls.io/), [gocover](http://gocover.io/) etc.): https://app.codecov.io/gh/bmf-san/goblin …
=> Add goblin to router

README.md
- repo link (github.com, gitlab.com, etc): https://github.com/jimlambrt/gldap
- pkg.go.dev: https://pkg.go.dev/github.com/jimlambrt/gldap
- goreportcard.com: https://goreportcard.com/report/github.com/jimlambrt/gldap
- coverage service link ([codecov](https://codecov.io/), [coveralls](https://coveralls.io/), [gocover](http://gocover.io/) etc.): generated in CI via a GitHub action.  See README for badge: https://github.com/jimlambrt/gldap#readme …
=> feature: add gldap to readme

README.md
- repo link (github.com, gitlab.com, etc): https://github.com/mantil-io/mantil
- pkg.go.dev: https://pkg.go.dev/github.com/mantil-io/mantil.go
- goreportcard.com: https://goreportcard.com/report/github.com/mantil-io/mantil.go
- coverage service link ([codecov](https://codecov.io/), [coveralls](https://coveralls.io/), [gocover](http://gocover.io/) etc.): https://app.codecov.io/gh/mantil-io/mantil …
=> Add Mantil to DevOps Tools

README.md
It's a contained web app for go developers to make it easier for users to install their CLI apps.
- pkg.go.dev:
_Not every repository (project) will require every option, but most projects …
=> Add goblin - https://goblin.reaper.im

README.md
- repo link (github.com, gitlab.com, etc): https://github.com/go-the-way/validator
- pkg.go.dev: https://pkg.go.dev/github.com/go-the-way/validator
- goreportcard.com: https://goreportcard.com/report/github.com/go-the-way/validator
- coverage service link ([codecov](https://codecov.io/), [coveralls](https://coveralls.io/), [gocover](http://gocover.io/) etc.): https://codecov.io/gh/go-the-way/validator …
=> Add validator

README.md
As always, thanks to the maintainers: your kind attention is much appreciated.
=> Add 'Know Go: Generics' to paid ebooks list

README.md
- repo link (github.com, gitlab.com, etc): https://github.com/hedhyw/gherkingen
- pkg.go.dev: https://pkg.go.dev/github.com/hedhyw/gherkingen
- goreportcard.com: https://goreportcard.com/report/github.com/hedhyw/gherkingen
- coverage service link: https://coveralls.io/github/hedhyw/gherkingen?branch=main
=> Adding gherkingen

README.md
Removing gofpdf as it has been officially abandoned by its author.
@jung-kurt, @phpdave11, if you know of a new maintainer for gofpdf, please reply so we can update awesome-go. Otherwise, we will remove gofpdf from the awesome-go list.
=> Removing gofpdf

README.md
Bitset has changed organizations, but is still being maintained
=> Changing organization of bitset package

README.md
Moving this entry. It has a new repo location.
=> Moving the willf/bloom entry to bits-and-blooms/bloom

README.md
The project is officially archived by the author and no longer actively maintained.
=> Removing slowpoke. 

README.md
Hi,
I would like to add my library underscore[https://github.com/rjNemo/underscore] to the list.
It provides functional programming helpers based on Go generics.
Thank you very much for reviewing. 👍 
**Links:**
- [repo link](https://github.com/rjNemo/underscore) 
- pkg.go.dev: [link](https://pkg.go.dev/github.com/rjNemo/underscore)
- goreportcard.com: [link](https://goreportcard.com/report/github.com/rjNemo/underscore)
- coverage service link: [codecov](https://app.codecov.io/gh/rjNemo/underscore)
=> add underscore to functional programming section

README.md
- repo link (github.com, gitlab.com, etc): https://github.com/Kachit/dusupay-sdk-go
- pkg.go.dev: https://pkg.go.dev/github.com/kachit/dusupay-sdk-go
- goreportcard.com: https://goreportcard.com/report/github.com/kachit/dusupay-sdk-go
- coverage service link ([codecov](https://codecov.io/), [coveralls](https://coveralls.io/), [gocover](http://gocover.io/) etc.): https://app.codecov.io/gh/Kachit/dusupay-sdk-go …
=> Add Kachit/dusupay-sdk-go package v2

README.md
- Last commit was over 2 years ago
- There are a number of open issues that are over 5 years old
- Does not have a link to a GoReportCard report
- Does not have link to a code coverage report
@charneykaye, @vulpivia, @haswalt, @kikht. 
Go-mix is scheduled to be removed from awesome-go by March 21, 2022 for the above mentioned reasons. If you would like to keep go-mix on awesome-go, please reply with updates to the repo.
=> Removing Go-Mix:

README.md
- repo link (github.com, gitlab.com, etc): https://github.com/HDT3213/rdb
- pkg.go.dev: https://pkg.go.dev/github.com/hdt3213/rdb
- goreportcard.com: https://goreportcard.com/report/github.com/HDT3213/rdb
- coverage service link: https://coveralls.io/github/HDT3213/rdb?branch=master
_Not every repository (project) will require every option, but most projects should. Check the …
=> add rdb into database tools

README.md
- repo link (github.com, gitlab.com, etc): https://github.com/NdoleStudio/go-otelroundtripper
- pkg.go.dev: https://pkg.go.dev/github.com/NdoleStudio/go-otelroundtripper
- goreportcard.com: https://goreportcard.com/report/github.com/NdoleStudio/go-otelroundtripper
- coverage service link ([codecov](https://codecov.io/), [coveralls](https://coveralls.io/), [gocover](http://gocover.io/) etc.): https://app.codecov.io/gh/NdoleStudio/go-otelroundtripper …
=> Add go-otelroundtripper

README.md
- repo link: https://github.com/ysmood/got
- pkg.go.dev: https://pkg.go.dev/github.com/ysmood/got
- goreportcard.com: https://goreportcard.com/report/github.com/ysmood/got
- coverage service link: https://codecov.io/github/ysmood/got
=> Add ysmood/got package

README.md
- repo link (github.com, gitlab.com, etc): https://github.com/golobby/router
- pkg.go.dev: https://pkg.go.dev/github.com/golobby/router
- goreportcard.com: https://goreportcard.com/report/github.com/golobby/router
- coverage service link ([codecov](https://codecov.io/), [coveralls](https://coveralls.io/), [gocover](http://gocover.io/) etc.): https://coveralls.io/github/golobby/router?branch=master …
=> Add golobby/router package

README.md
- repo link (github.com, gitlab.com, etc): https://github.com/corazawaf/coraza
- pkg.go.dev:https://pkg.go.dev/github.com/corazawaf/coraza/v2
- goreportcard.com: https://goreportcard.com/report/github.com/corazawaf/coraza/v2
- coverage service link: https://sonarcloud.io/project/overview?id=jptosso_coraza-waf
=> Add OWASP Coraza to the list

README.md
=> Added `ko` CLI tool for Devops

README.md
- repo link (github.com, gitlab.com, etc): https://github.com/go-the-way/anoweb
- pkg.go.dev: https://pkg.go.dev/github.com/go-the-way/anoweb
- goreportcard.com: https://goreportcard.com/report/github.com/go-the-way/anoweb
- coverage service link ([codecov](https://codecov.io/), [coveralls](https://coveralls.io/), [gocover](http://gocover.io/) etc.): https://codecov.io/gh/go-the-way/anoweb …
=> Add anoweb

README.md
Implementing CRUD in Golang REST API with Mux & GORM
- pkg.go.dev:
_Not every repository (project) will require every option, but most projects should. Check the Contribution Guidelines for …
=> added Golang CRUD tutorial

README.md
[https://github.com/kyleconroy/sqlc](https://github.com/kyleconroy/sqlc)
- pkg.go.dev:
[https://pkg.go.dev/github.com/kyleconroy/sqlc](https://pkg.go.dev/github.com/kyleconroy/sqlc)
[https://goreportcard.com/report/github.com/kyleconroy/sqlc](https://goreportcard.com/report/github.com/kyleconroy/sqlc)
[https://github.com/kyleconroy/sqlc/actions/workflows/ci.yml] …
=> Add sqlc in "SQL Query Builder" section

README.md
- repo link (github.com, gitlab.com, etc): https://github.com/goradd/html5tag
- pkg.go.dev: https://pkg.go.dev/github.com/goradd/html5tag
- goreportcard.com: https://goreportcard.com/report/github.com/goradd/html5tag
- coverage service link ([codecov](https://codecov.io/), [coveralls](https://coveralls.io/), [gocover](http://gocover.io/) etc.): https://app.codecov.io/gh/goradd/html5tag
- [ x] The package has been added to the list in alphabetical order.
- [ …
=> Adding html5tag

README.md
- repo link (github.com, gitlab.com, etc): - https://github.com/barweiss/go-tuple
- pkg.go.dev: https://pkg.go.dev/github.com/barweiss/go-tuple
- goreportcard.com: https://goreportcard.com/report/github.com/barweiss/go-tuple
- coverage service link ([codecov](https://codecov.io/), [coveralls](https://coveralls.io/), [gocover](http://gocover.io/) etc.): https://coveralls.io/github/barweiss/go-tuple …
=> Add go-tuple to Data Structure packages

README.md
- repo link (github.com, gitlab.com, etc): https://github.com/jorelosorio/web-mercator-projection
- pkg.go.dev: https://pkg.go.dev/github.com/jorelosorio/web-mercator-projection
- goreportcard.com: https://goreportcard.com/report/github.com/jorelosorio/web-mercator-projection
- coverage service link ([codecov](https://codecov.io/), [coveralls](https://coveralls.io/), [gocover](http://gocover.io/) etc.): https://coveralls.io/github/jorelosorio/web-mercator-projection?branch=main
**Note**: _that new categories can be added only when there are 3 …
=> Add - Web mercator projection

README.md
- repo link (github.com, gitlab.com, etc): https://github.com/xorcare/pointer
- pkg.go.dev: https://pkg.go.dev/github.com/xorcare/pointer
- goreportcard.com: https://goreportcard.com/report/github.com/xorcare/pointer
- coverage service link ([codecov](https://codecov.io/), [coveralls](https://coveralls.io/), [gocover](http://gocover.io/) etc.): https://app.codecov.io/gh/xorcare/pointer …
=> Add package pointer to utilities section

README.md
- repo link (github.com, gitlab.com, etc): https://github.com/muir/nchi
- pkg.go.dev: https://pkg.go.dev/github.com/muir/nchi
- goreportcard.com: https://goreportcard.com/report/github.com/muir/nchi
- coverage service link ([codecov](https://codecov.io/), [coveralls](https://coveralls.io/), [gocover](http://gocover.io/) etc.): https://app.codecov.io/gh/muir/nchi …
=> add nchi http router

README.md
- repo link (github.com, gitlab.com, etc): https://github.com/muir/reflectutils
- pkg.go.dev: https://pkg.go.dev/github.com/muir/reflectutils
- goreportcard.com: https://goreportcard.com/report/github.com/muir/reflectutils
- coverage service link ([codecov](https://codecov.io/), [coveralls](https://coveralls.io/), [gocover](http://gocover.io/) etc.): https://app.codecov.io/gh/muir/reflectutils …
=> add reflectutils

README.md
Refactoring:
Data Structures
Database
Database Drivers
- Clarifying categories
- Fixing mis-categorized items
- Adding new categories where possible to make smaller groups
Removed "riot" as it has been officially archived by the author.
=> Data section restructure

README.md
- repo link (github.com, gitlab.com, etc): https://github.com/dnnrly/wait-for
- pkg.go.dev: https://pkg.go.dev/github.com/dnnrly/wait-for
- goreportcard.com: https://goreportcard.com/report/github.com/dnnrly/wait-for
- coverage service link ([codecov](https://codecov.io/), [coveralls](https://coveralls.io/), [gocover](http://gocover.io/) etc.): https://codecov.io/gh/dnnrly/wait-for …
=> Add wait-for

README.md
- repo link (github.com, gitlab.com, etc): https://github.com/Kachit/fasapay-sdk-go
- pkg.go.dev: https://pkg.go.dev/github.com/kachit/fasapay-sdk-go
- goreportcard.com: https://goreportcard.com/report/github.com/kachit/fasapay-sdk-go
- coverage service link ([codecov](https://codecov.io/), [coveralls](https://coveralls.io/), [gocover](http://gocover.io/) etc.): https://app.codecov.io/gh/Kachit/fasapay-sdk-go …
=> Add fasapay-sdk-go package

README.md
govader-backend under the title of Natural Language Processing
- repo link (github.com, gitlab.com, etc): https://github.com/PIMPfiction/govader_backend
- pkg.go.dev: https://pkg.go.dev/github.com/PIMPfiction/govader_backend
- goreportcard.com: https://goreportcard.com/report/github.com/PIMPfiction/govader_backend
- coverage service link ([codecov](https://codecov.io/), [coveralls](https://coveralls.io/), [gocover](http://gocover.io/) etc.): https://app.codecov.io/gh/PIMPfiction/govader_backend
**Note**: _that new categories can be added only when …
=> add govader-backend

README.md
- repo link (github.com, gitlab.com, etc): https://github.com/repeale/fp-go
- pkg.go.dev: https://pkg.go.dev/github.com/repeale/fp-go
- goreportcard.com: https://goreportcard.com/report/github.com/repeale/fp-go
- coverage service link ([codecov](https://codecov.io/), [coveralls](https://coveralls.io/), [gocover](http://gocover.io/) etc.): https://app.codecov.io/gh/repeale/fp-go
_Not …
=> add fp-go to Functional packages

README.md
- repo link (github.com, gitlab.com, etc): https://github.com/twharmon/golamb
- pkg.go.dev: https://pkg.go.dev/github.com/twharmon/golamb
- goreportcard.com: https://goreportcard.com/report/github.com/twharmon/golamb
- coverage service link ([codecov](https://codecov.io/), [coveralls](https://coveralls.io/), [gocover](http://gocover.io/) etc.): https://codecov.io/gh/twharmon/golamb …
=> Add golamb

README.md
- repo link (github.com, gitlab.com, etc): https://github.com/golobby/orm
- pkg.go.dev: https://pkg.go.dev/github.com/golobby/orm
- goreportcard.com: https://goreportcard.com/report/github.com/golobby/orm
https://coveralls.io/github/golobby/orm?branch=master
=> Adds Golobby/orm

README.md
- repo link (github.com, gitlab.com, etc): https://github.com/golobby/container
- pkg.go.dev: https://pkg.go.dev/github.com/golobby/container
- goreportcard.com: https://goreportcard.com/report/github.com/golobby/container
- coverage service link ([codecov](https://codecov.io/), [coveralls](https://coveralls.io/), [gocover](http://gocover.io/) etc.): https://coveralls.io/github/golobby/container …
=> Rename package "container" to "GoLobby/Container"

README.md
Since package name is simple, we've prepended the org name to it.
- repo link (github.com, gitlab.com, etc): https://github.com/golobby/router
- pkg.go.dev: https://pkg.go.dev/github.com/golobby/router
- goreportcard.com: https://goreportcard.com/report/github.com/golobby/router
- coverage service link ([codecov](https://codecov.io/), [coveralls](https://coveralls.io/), [gocover](http://gocover.io/) etc.): https://coveralls.io/github/golobby/router …
=> Rename package "router" to "GoLobby/Router"

README.md
- repo link (github.com, gitlab.com, etc): https://github.com/golobby/config
- pkg.go.dev: https://pkg.go.dev/github.com/golobby/config
- goreportcard.com: https://goreportcard.com/report/github.com/golobby/config
- coverage service link ([codecov](https://codecov.io/), [coveralls](https://coveralls.io/), [gocover](http://gocover.io/) etc.): https://coveralls.io/github/golobby/config?branch=master …
=> Rename package "config" to "GoLobby/Config"

README.md
- repo link (github.com, gitlab.com, etc): https://github.com/muir/nfigure
- pkg.go.dev: https://pkg.go.dev/github.com/muir/nfigure
- goreportcard.com: https://goreportcard.com/report/github.com/muir/nfigure
- coverage service link ([codecov](https://codecov.io/), [coveralls](https://coveralls.io/), [gocover](http://gocover.io/) etc.): https://app.codecov.io/gh/muir/nfigure
_Not every …
=> add nfigure

README.md
- repo link (github.com, gitlab.com, etc): https://github.com/twharmon/slices
- pkg.go.dev: https://pkg.go.dev/github.com/twharmon/slices
- goreportcard.com: https://goreportcard.com/report/github.com/twharmon/slices
- coverage service link ([codecov](https://codecov.io/), [coveralls](https://coveralls.io/), [gocover](http://gocover.io/) etc.): https://app.codecov.io/gh/twharmon/slices …
=> Add twharmon/slices

README.md
- repo link (github.com, gitlab.com, etc): https://github.com/mouuff/go-rocket-update
- pkg.go.dev: https://pkg.go.dev/github.com/mouuff/go-rocket-update
- goreportcard.com: https://goreportcard.com/report/github.com/mouuff/go-rocket-update
- coverage service link ([codecov](https://codecov.io/), [coveralls](https://coveralls.io/), [gocover](http://gocover.io/) etc.): https://app.codecov.io/gh/mouuff/go-rocket-update …
=> Add go-rocket-update

README.md
- repo link (github.com, gitlab.com, etc): https://github.com/switchupcb/copygen
- pkg.go.dev: https://pkg.go.dev/github.com/switchupcb/copygen
- goreportcard.com: https://goreportcard.com/report/github.com/switchupcb/copygen
- coverage service link ([codecov](https://codecov.io/), [coveralls](https://coveralls.io/), [gocover](http://gocover.io/) etc.): https://github.com/switchupcb/copygen/tree/main/examples …
=> add Copygen

README.md
- repo link (github.com, gitlab.com, etc): https://github.com/daichi-m/go18ds
- pkg.go.dev: https://pkg.go.dev/github.com/daichi-m/go18ds
- goreportcard.com: https://goreportcard.com/report/github.com/daichi-m/go18ds
- coverage service link ([codecov](https://codecov.io/), [coveralls](https://coveralls.io/), [gocover](http://gocover.io/) etc.): https://app.codecov.io/gh/daichi-m/go18ds …
=> Adding go18ds

README.md
- repo link (github.com, gitlab.com, etc): https://github.com/goradd/maps
- pkg.go.dev: https://pkg.go.dev/github.com/goradd/maps
- goreportcard.com: https://goreportcard.com/report/github.com/goradd/maps
- coverage service link ([codecov](https://codecov.io/), [coveralls](https://coveralls.io/), [gocover](http://gocover.io/) etc.): https://codecov.io/gh/goradd/maps
=> Add goradd maps.

README.md
- repo link (github.com, gitlab.com, etc): https://github.com/elliotwutingfeng/go-fasttld
- pkg.go.dev: https://pkg.go.dev/github.com/elliotwutingfeng/go-fasttld
- goreportcard.com: https://goreportcard.com/report/github.com/elliotwutingfeng/go-fasttld
- coverage service link ([codecov](https://codecov.io/), [coveralls](https://coveralls.io/), [gocover](http://gocover.io/) etc.): https://app.codecov.io/gh/elliotwutingfeng/go-fasttld …
=> Add go-fasttld

README.md
- repo link (github.com, gitlab.com, etc): https://github.com/wneessen/go-mail
- pkg.go.dev: https://pkg.go.dev/github.com/wneessen/go-mail
- goreportcard.com: https://goreportcard.com/report/github.com/wneessen/go-mail
- coverage service link ([codecov](https://codecov.io/), [coveralls](https://coveralls.io/), [gocover](http://gocover.io/) etc.): https://app.codecov.io/gh/wneessen/go-mail …
=> Add go-mail

README.md
- repo link (github.com, gitlab.com, etc): https://github.com/wneessen/go-hibp
- pkg.go.dev: https://pkg.go.dev/github.com/wneessen/go-hibp
- goreportcard.com: https://goreportcard.com/report/github.com/wneessen/go-hibp
- coverage service link ([codecov](https://codecov.io/), [coveralls](https://coveralls.io/), [gocover](http://gocover.io/) etc.): https://app.codecov.io/gh/wneessen/go-hibp/ …
=> Add go-hibp

README.md
- repo link (github.com, gitlab.com, etc):  https://github.com/nwillc/genfuncs
- pkg.go.dev: https://pkg.go.dev/github.com/nwillc/genfuncs
- goreportcard.com: https://goreportcard.com/report/github.com/nwillc/genfuncs
- coverage service link ([codecov](https://codecov.io/), [coveralls](https://coveralls.io/), [gocover](http://gocover.io/) etc.): https://codecov.io/github/nwillc/genfuncs?branch=master …
=> Adding genfuncs.

README.md
- repo link (github.com, gitlab.com, etc): https://github.com/wabarc/wayback
- pkg.go.dev: https://pkg.go.dev/github.com/wabarc/wayback
- goreportcard.com: https://goreportcard.com/report/github.com/wabarc/wayback
- coverage service link ([codecov](https://codecov.io/), [coveralls](https://coveralls.io/), [gocover](http://gocover.io/) etc.): It generates coverage using GitHub Actions, e.g. [actions/runs](https://github.com/wabarc/wayback/actions/runs/2257044454) …
=> Add wayback

README.md
- repo link (github.com, gitlab.com, etc): https://github.com/francesconi/go-rampart
- pkg.go.dev: https://pkg.go.dev/github.com/francesconi/go-rampart
- goreportcard.com: https://goreportcard.com/report/github.com/francesconi/go-rampart
- coverage service link ([codecov](https://codecov.io/), [coveralls](https://coveralls.io/), [gocover](http://gocover.io/) etc.): https://app.codecov.io/gh/francesconi/go-rampart
**Make sure that you've checked the boxes below that …
=> Add go-rampart

README.md
Repo Link: https://github.com/Forceu/gokapi
Goreportcard: https://goreportcard.com/report/github.com/forceu/gokapi
Coverage: No coverage service, but code coverage is >80%.
=> Added Gokapi

README.md
- repo link (github.com, gitlab.com, etc):  https://github.com/mmadfox/go-geojson2h3
- pkg.go.dev: https://pkg.go.dev/github.com/mmadfox/go-geojson2h3
- goreportcard.com: https://goreportcard.com/report/github.com/mmadfox/go-geojson2h3
- coverage service link ([codecov](https://codecov.io/), [coveralls](https://coveralls.io/), [gocover](http://gocover.io/) etc.): https://coveralls.io/github/mmadfox/go-geojson2h3?branch=main …
=> Add geojson2h3

README.md
- repo link (github.com, gitlab.com, etc):  https://github.com/mmadfox/go-h3geo-dist
- pkg.go.dev:  https://pkg.go.dev/github.com/mmadfox/go-h3geo-dist
- goreportcard.com:  https://goreportcard.com/report/github.com/mmadfox/go-h3geo-dist
- coverage service link ([codecov](https://codecov.io/), [coveralls](https://coveralls.io/), [gocover](http://gocover.io/) etc.): https://coveralls.io/github/mmadfox/go-h3geo-dist?branch=main&1 …
=> Add H3GeoDist

README.md
- repo link (github.com, gitlab.com, etc): https://github.com/rsteube/carapace-spec
- pkg.go.dev: [![PkgGoDev](https://pkg.go.dev/badge/github.com/rsteube/carapace-spec/pkg/actions)](https://pkg.go.dev/github.com/rsteube/carapace-spec)
- goreportcard.com: [![GoReportCard](https://goreportcard.com/badge/github.com/rsteube/carapace-spec)](https://goreportcard.com/report/github.com/rsteube/carapace-spec)
- coverage service link ([codecov](https://codecov.io/), [coveralls](https://coveralls.io/), [gocover](http://gocover.io/) etc.): [![Coverage …
=> add carapace-spec

README.md
- repo link (github.com, gitlab.com, etc): https://github.com/lab210-dev/async-job
- pkg.go.dev: https://pkg.go.dev/github.com/lab210-dev/async-job
- goreportcard.com: https://goreportcard.com/report/github.com/lab210-dev/async-job
- coverage service link ([codecov](https://codecov.io/), [coveralls](https://coveralls.io/), [gocover](http://gocover.io/) etc.): https://app.codecov.io/gh/lab210-dev/async-job …
=> Add async-job

README.md
- repo link (github.com, gitlab.com, etc): https://github.com/vorlif/spreak
- pkg.go.dev: [![PkgGoDev](https://pkg.go.dev/badge/github.com/vorlif/spreak)](https://pkg.go.dev/github.com/vorlif/spreak)
- goreportcard.com: [![Go Report Card](https://goreportcard.com/badge/github.com/vorlif/spreak)](https://goreportcard.com/report/github.com/vorlif/spreak)
- coverage service link ([codecov](https://codecov.io/), [coveralls](https://coveralls.io/), [gocover](http://gocover.io/) etc.): [![codecov](https://codecov.io/gh/vorlif/spreak/branch/main/graph/badge. …
=> Add spreak

README.md
- repo link (github.com, gitlab.com, etc): https://github.com/nikolaydubina/fpdecimal
- pkg.go.dev: https://pkg.go.dev/github.com/nikolaydubina/fpdecimal
- goreportcard.com: https://goreportcard.com/report/github.com/nikolaydubina/fpdecimal
- coverage service link: https://codecov.io/gh/nikolaydubina/fpdecimal
---
=> Added github.com/nikolaydubina/fpdecimal

README.md
- repo link (github.com, gitlab.com, etc): https://github.com/num30/config
- pkg.go.dev: https://pkg.go.dev/github.com/num30/config
- goreportcard.com: https://goreportcard.com/report/github.com/num30/config
- coverage service link ([codecov](https://codecov.io/), [coveralls](https://coveralls.io/), [gocover](http://gocover.io/) etc.): [codecov](https://codecov.io/gh/num30/config)
_Not …
=> Add num30/config

README.md
- repo link (github.com, gitlab.com, etc):https://github.com/rbrahul/exception
- pkg.go.dev:https://pkg.go.dev/github.com/rbrahul/exception
- goreportcard.com:https://goreportcard.com/report/github.com/rbrahul/exception
- coverage service link ([codecov](https://codecov.io/), [coveralls](https://coveralls.io/), [gocover](http://gocover.io/) etc.):https://app.codecov.io/gh/rbrahul/exception …
=> Added exception package in the readme.md.

README.md
- repo link (github.com, gitlab.com, etc): https://github.com/carlmjohnson/be
- pkg.go.dev: https://pkg.go.dev/github.com/carlmjohnson/be
- goreportcard.com: https://goreportcard.com/report/github.com/carlmjohnson/be
- coverage service link: https://gocover.io/github.com/carlmjohnson/be
_Not every repository (project) will require every option, but most projects should. Check the …
=> Add carlmjohnson/be

README.md
- repo link (github.com, gitlab.com, etc): https://github.com/reugn/wifiqr
- pkg.go.dev: https://pkg.go.dev/github.com/reugn/wifiqr
- goreportcard.com: https://goreportcard.com/report/github.com/reugn/wifiqr
- coverage service link: https://codecov.io/gh/reugn/wifiqr
_Not every repository (project) will require every option, but most projects should. Check the Contribution Guidelines …
=> Add wifiqr

README.md
- repo link (github.com, gitlab.com, etc): https://github.com/yuin/goldmark
- pkg.go.dev: https://pkg.go.dev/github.com/yuin/goldmark
- goreportcard.com: https://goreportcard.com/report/github.com/yuin/goldmark
- coverage service link ([codecov](https://codecov.io/), [coveralls](https://coveralls.io/), [gocover](http://gocover.io/) etc.): https://coveralls.io/github/yuin/goldmark
_Not …
=> Add goldmark

README.md
- repo link (github.com, gitlab.com, etc): https://github.com/kazu/loncha
- pkg.go.dev: https://pkg.go.dev/github.com/kazu/loncha
- goreportcard.com: https://goreportcard.com/report/github.com/kazu/loncha
- coverage service link ([codecov](https://codecov.io/), [coveralls](https://coveralls.io/), [gocover](http://gocover.io/) etc.): https://goreportcard.com/report/github.com/kazu/loncha …
=> add loncha

README.md
This PR is just for renaming an existing repository Ebiten to Ebitengine.
- repo link (github.com, gitlab.com, etc): https://github.com/hajimehoshi/ebiten
- pkg.go.dev: https://pkg.go.dev/github.com/hajimehoshi/ebiten
_Not every …
=> rename Ebiten -> Ebitengine

README.md
This PR servers to update and rm dead links
- pkg.go.dev: …
=> Link updates and cleanup

README.md
- repo link (github.com, gitlab.com, etc): https://github.com/megaease/easeprobe
- pkg.go.dev: https://pkg.go.dev/github.com/megaease/easeprobe
- goreportcard.com: https://goreportcard.com/report/github.com/megaease/easeprobe
- coverage service link ([codecov](https://codecov.io/), [coveralls](https://coveralls.io/), [gocover](http://gocover.io/) etc.): https://codecov.io/gh/megaease/easeprobe …
=> Add the EaseProbe

README.md
_Beware this is a web tool that's **not** open source. I built it because the Go community finds it useful. Feel free to merge._ 
- repo link (github.com, gitlab.com, etc): _not open source_
- pkg.go.dev: _not open source_
- goreportcard.com: _not open source_
- coverage service link ([codecov](https://codecov.io/), [coveralls](https://coveralls.io/), [gocover](http://gocover.io/) etc.): _not open source_ …
=> add gotemplate.io

README.md
- repo link (github.com, gitlab.com, etc): https://github.com/staskobzar/goagi
- pkg.go.dev: https://pkg.go.dev/github.com/staskobzar/goagi
- goreportcard.com: https://goreportcard.com/report/github.com/staskobzar/goagi
- coverage service link ([codecov](https://codecov.io/), [coveralls](https://coveralls.io/), [gocover](http://gocover.io/) etc.): https://app.codecov.io/gh/staskobzar/goagi …
=> add goagi library

README.md
- repo link (github.com, gitlab.com, etc): https://github.com/arikama/go-mysql-test-container
- pkg.go.dev: https://pkg.go.dev/github.com/arikama/go-mysql-test-container
- goreportcard.com: https://goreportcard.com/report/github.com/arikama/go-mysql-test-container
- coverage service link ([codecov](https://codecov.io/), [coveralls](https://coveralls.io/), [gocover](http://gocover.io/) etc.): https://app.codecov.io/gh/arikama/go-mysql-test-container …
=> Add go-mysql-test-container

README.md
=> Add CodeCrafters Golang Track

README.md
- repo link (github.com, gitlab.com, etc): https://github.com/gookit/slog
- pkg.go.dev: https://pkg.go.dev/github.com/gookit/slog
- goreportcard.com: https://goreportcard.com/report/github.com/gookit/slog
- coverage service link ([codecov](https://codecov.io/), [coveralls](https://coveralls.io/), [gocover](http://gocover.io/) etc.): https://coveralls.io/github/gookit/slog?branch=master …
=> add github.com/gookit/slog

README.md
as title. the performance benchmark is here https://github.com/phuslu/log#high-performance
=> update phuslu/log description.

README.md
- repo link (github.com, gitlab.com, etc): https://github.com/nikolaydubina/fpmoney
- pkg.go.dev: https://pkg.go.dev/github.com/nikolaydubina/fpmoney
- goreportcard.com: https://goreportcard.com/report/github.com/nikolaydubina/fpmoney
- coverage service link ([codecov](https://codecov.io/), [coveralls](https://coveralls.io/), [gocover](http://gocover.io/) etc.): https://app.codecov.io/gh/nikolaydubina/fpmoney
_Not every …
=> Added fpmoney

README.md
- repo link (github.com, gitlab.com, etc): https://github.com/Kachit/gorm-seeder
- pkg.go.dev: https://pkg.go.dev/github.com/kachit/gorm-seeder
- goreportcard.com: https://goreportcard.com/report/github.com/kachit/gorm-seeder
- coverage service link ([codecov](https://codecov.io/), [coveralls](https://coveralls.io/), [gocover](http://gocover.io/) etc.): https://codecov.io/gh/Kachit/gorm-seeder …
=> Add Kachit/gorm-seeder package

.github/PULL_REQUEST_TEMPLATE.md, README.md
- repo link (github.com, gitlab.com, etc):https://github.com/staskobzar/goami2
- pkg.go.dev:https://pkg.go.dev/github.com/staskobzar/goami2
- goreportcard.com:https://goreportcard.com/report/github.com/staskobzar/goami2
- coverage service link ([codecov](https://codecov.io/), [coveralls](https://coveralls.io/), [gocover](http://gocover.io/) etc.):https://app.codecov.io/gh/staskobzar/goami2 …
=> add goami2

README.md
- repo link (github.com, gitlab.com, etc): https://github.com/go-zoox/fetch
- pkg.go.dev: [![PkgGoDev](https://pkg.go.dev/badge/github.com/go-zoox/fetch)](https://pkg.go.dev/github.com/go-zoox/fetch)
- goreportcard.com: [![Go Report Card](https://goreportcard.com/badge/github.com/go-zoox/fetch)](https://goreportcard.com/report/github.com/go-zoox/fetch)
- coverage service link ([codecov](https://codecov.io/), [coveralls](https://coveralls.io/), [gocover](http://gocover.io/) etc.): [![Coverage …
=> Add go-zoox/fetch

README.md
- repo link (github.com, gitlab.com, etc): https://github.com/viney-shih/go-cache
- pkg.go.dev: https://pkg.go.dev/github.com/viney-shih/go-cache
- goreportcard.com: https://goreportcard.com/report/github.com/viney-shih/go-cache
- coverage service link ([codecov](https://app.codecov.io/gh/viney-shih/go-cache), [coveralls](https://coveralls.io/github/viney-shih/go-cache?branch=master)) …
=> Add go-cache to Caches

README.md
- repo link (github.com, gitlab.com, etc): https://github.com/hedhyw/rex
- pkg.go.dev: https://pkg.go.dev/github.com/hedhyw/rex
- goreportcard.com: https://goreportcard.com/report/github.com/hedhyw/rex
- coverage service link: https://coveralls.io/github/hedhyw/rex?branch=main
_Not every repository (project) will require every option, but most projects should. Check the Contribution …
=> Add hedhyw/rex

README.md
- URL to fullproxy project ( https://github.com/shoriwe/fullproxy )
- pkg.go.dev ( https://pkg.go.dev/github.com/shoriwe/fullproxy/v3 )
- Go report ( https://goreportcard.com/report/github.com/shoriwe/fullproxy/v3 )
- pkg.go.dev: …
=> Add: fullproxy repository to awesome-go

README.md
- repo link: http://github.com/gkampitakis/go-snaps
- pkg.go.dev: https://pkg.go.dev/github.com/gkampitakis/go-snaps
- goreportcard.com: https://goreportcard.com/report/github.com/gkampitakis/go-snaps
- coverage service link ([codecov](https://codecov.io/), [coveralls](https://coveralls.io/), [gocover](http://gocover.io/) etc.): https://gocover.io/github.com/gkampitakis/go-snaps/snaps …
=> add github.com/gkampitakis/go-snaps

README.md
- repo link (github.com, gitlab.com, etc): https://github.com/alfiankan/crab-config-files-templating
- pkg.go.dev: https://pkg.go.dev/github.com/alfiankan/crab-config-files-templating
- goreportcard.com: https://goreportcard.com/report/github.com/alfiankan/crab-config-files-templating
- coverage service link ([codecov](https://codecov.io/), [coveralls](https://coveralls.io/), [gocover](http://gocover.io/) etc.): https://codecov.io/gh/alfiankan/crab-config-files-templating
=> add crab-config-files-templating

README.md
- repo link (github.com, gitlab.com, etc): https://github.com/ory/keto
- pkg.go.dev: https://pkg.go.dev/github.com/ory/keto
- goreportcard.com: https://goreportcard.com/report/github.com/ory/keto
- coverage service link ([codecov](https://codecov.io/), [coveralls](https://coveralls.io/), [gocover](http://gocover.io/) etc.): https://coveralls.io/github/ory/keto?branch=master
_Not every …
=> add ory/keto

README.md
https://github.com/PerimeterX/marshmallow
marshmallow is an open-source version of a long-maintained internal library written at PerimeterX.
The repository is relatively new but contribution is pretty continous
=> adding marshmallow

README.md
=> remove extra mailto

README.md
=> Remove "Learning Golang - From zero to hero"

README.md
- repo link (github.com, gitlab.com, etc): https://github.com/alajmo/sake
- pkg.go.dev: https://pkg.go.dev/github.com/alajmo/sake
- goreportcard.com: https://goreportcard.com/report/github.com/alajmo/sake
- coverage service link ([codecov](https://codecov.io/), [coveralls](https://coveralls.io/), [gocover](http://gocover.io/) etc.):  I use integration tests mainly since it's a CLI tool that mainly interacts with remote servers. See https://github.com/alajmo/sake/tree/main/test
**Note**: _that new categories can be added only when there are 3 packages …
=> Add sake to Other Software

README.md
Add the faabiosr/middleware and update the cachego github user.
- repo link (github.com, gitlab.com, etc): [https://github.com/faabiosr/echo-middleware](https://github.com/faabiosr/echo-middleware)
- pkg.go.dev: [https://pkg.go.dev/github.com/faabiosr/echo-middleware](https://pkg.go.dev/github.com/faabiosr/echo-middleware)
- goreportcard.com: [https://goreportcard.com/report/github.com/faabiosr/echo-middleware](https://goreportcard.com/report/github.com/faabiosr/echo-middleware)
- coverage service link ([codecov](https://codecov.io/), …
=> add faabiosr/middleware

README.md
=> feat: add usestdlibvars linter

README.md
- repo link (github.com, gitlab.com, etc): https://github.com/isacikgoz/gitbatch
- pkg.go.dev: https://pkg.go.dev/github.com/isacikgoz/gitbatch
- goreportcard.com: https://goreportcard.com/report/github.com/isacikgoz/gitbatch
- coverage service link ([codecov](https://codecov.io/), [coveralls](https://coveralls.io/), [gocover](http://gocover.io/) etc.): https://app.codecov.io/gh/isacikgoz/gitbatch …
=> add gitbatch

README.md
https://github.com/avelino/awesome-go/pull/4181
=> update Copygen description

README.md
Placed under devops tools.
Repo link- https://github.com/fleetdm/fleet
pkg.go.dev page- https://pkg.go.dev/github.com/fleetdm/fleet/v4
Go report card- https://goreportcard.com/report/github.com/fleetdm/fleet
Code coverage report- https://app.codecov.io/gh/fleetdm/fleet
- pkg.go.dev:
**Note**: _that new categories can be added only when there are 3 packages or …
=> Added Fleet device management

README.md
Description: The core idea on KSQL is to offer an easy to use interface, the actual communication with the database is decoupled so we can use KSQL on top of pgx, database/sql and possibly other tools. You can even create you own backend adapter for KSQL which is useful in some situations.
A blog post explaining the package, by the author.
[Go and SQL: Pitfalls With Existing Libraries (and a Better Solution)](https://betterprogramming.pub/golang-sql-problems-with-existing-libraries-145a037261b8)
- [github link](https://github.com/VinGarcia/ksql)
- https://pkg.go.dev/github.com/vingarcia/ksql
[![Go Reference](https://pkg.go.dev/badge/github.com/vingarcia/ksql.svg)](https://pkg.go.dev/github.com/vingarcia/ksql)
- https://goreportcard.com/report/github.com/vingarcia/ksql
[![Go Report …
=> Meet KSQL — A library to address the problems of Golang and SQL

README.md
go-pg is in maintenance mode. Official successor is bun.
- repo link (github.com, gitlab.com, etc): https://github.com/uptrace/bun 
- pkg.go.dev: https://pkg.go.dev/github.com/uptrace/bun
- goreportcard.com: https://goreportcard.com/report/github.com/uptrace/bun …
=> replaced go-pg with bun

README.md
- repo link (github.com, gitlab.com, etc): https://github.com/bytebase/bytebase
- pkg.go.dev: https://pkg.go.dev/github.com/bytebase/bytebase
- goreportcard.com: https://goreportcard.com/report/github.com/bytebase/bytebase …
=> Add Bytebase to Database Schema Migration

README.md
https://github.com/Unrud/remote-touchpad
Control mouse and keyboard from a smartphone.
This is an extremely useful utility.
- repo link (github.com, gitlab.com, etc): https://github.com/Unrud/remote-touchpad
_Not …
=> add remote-touchpad

README.md
- repo link (github.com, gitlab.com, etc): https://github.com/ydb-platform/ydb-go-sdk
- pkg.go.dev: https://pkg.go.dev/github.com/ydb-platform/ydb-go-sdk/v3
- goreportcard.com: https://goreportcard.com/report/github.com/ydb-platform/ydb-go-sdk/v3
- coverage service link ([codecov](https://codecov.io/), [coveralls](https://coveralls.io/), [gocover](http://gocover.io/) etc.): https://app.codecov.io/gh/ydb-platform/ydb-go-sdk …
=> Add `ydb-go-sdk` to `RDBMS` drivers and messaging systems

README.md
- repo link (github.com, gitlab.com, etc): https://github.com/asty-org/asty
- pkg.go.dev: https://pkg.go.dev/github.com/asty-org/asty
- goreportcard.com: https://goreportcard.com/report/github.com/asty-org/asty
- coverage service link ([codecov](https://codecov.io/), [coveralls](https://coveralls.io/), [gocover](http://gocover.io/) etc.): https://app.codecov.io/gh/asty-org/asty
_Not …
=> added asty

README.md
- repo link: https://github.com/skovtunenko/graterm
- pkg.go.dev: https://pkg.go.dev/github.com/skovtunenko/graterm
- goreportcard.com: https://goreportcard.com/report/github.com/skovtunenko/graterm
- coverage service link: https://app.codecov.io/gh/skovtunenko/graterm
_Not every repository (project) will require every option, but most projects should. Check the Contribution Guidelines …
=> Add `graterm` library

README.md
- repo link (github.com, gitlab.com, etc): https://github.com/zenthangplus/go-workerpool
- pkg.go.dev: https://pkg.go.dev/github.com/zenthangplus/go-workerpool
- goreportcard.com: https://goreportcard.com/report/github.com/zenthangplus/go-workerpool
- coverage service link ([codecov](https://codecov.io/), [coveralls](https://coveralls.io/), [gocover](http://gocover.io/) etc.): https://codecov.io/gh/zenthangplus/go-workerpool …
=> Add go-workerpool

README.md
- repo link (github.com, gitlab.com, etc): https://github.com/timandy/routine
- pkg.go.dev: https://pkg.go.dev/github.com/timandy/routine
- goreportcard.com: https://goreportcard.com/report/github.com/timandy/routine
- coverage service link ([codecov](https://codecov.io/), [coveralls](https://coveralls.io/), [gocover](http://gocover.io/) etc.): https://app.codecov.io/gh/timandy/routine …
=> Add ThreadLocal library - routine

README.md
Resubmitting https://github.com/avelino/awesome-go/pull/4348, which timed out.
- repo link (github.com, gitlab.com, etc): https://github.com/bobg/go-generics
- pkg.go.dev: https://pkg.go.dev/github.com/bobg/go-generics
- goreportcard.com: https://goreportcard.com/report/github.com/bobg/go-generics
- coverage service link ([codecov](https://codecov.io/), [coveralls](https://coveralls.io/), [gocover](http://gocover.io/) etc.): https://coveralls.io/github/bobg/go-generics?branch=master
_Not every repository (project) will require every option, but most projects should. Check the …
=> Add github.com/bobg/go-generics.

README.md
- repo link (github.com, gitlab.com, etc): [https://github.com/GuilhermeCaruso/mooncake](https://github.com/GuilhermeCaruso/mooncake)
- pkg.go.dev: [https://pkg.go.dev/github.com/GuilhermeCaruso/mooncake?utm_source=godoc](https://pkg.go.dev/github.com/GuilhermeCaruso/mooncake?utm_source=godoc)
- goreportcard.com: [https://goreportcard.com/report/github.com/GuilhermeCaruso/mooncake](https://goreportcard.com/report/github.com/GuilhermeCaruso/mooncake)
- coverage service link ([codecov](https://codecov.io/), [coveralls](https://coveralls.io/), …
=> adds mooncake

README.md
- repo link (github.com, gitlab.com, etc): https://github.com/s0rg/quadtree
- pkg.go.dev: https://pkg.go.dev/github.com/s0rg/quadtree
- goreportcard.com: https://goreportcard.com/report/github.com/s0rg/quadtree
- coverage service link ([codecov](https://codecov.io/), [coveralls](https://coveralls.io/), [gocover](http://gocover.io/) etc.): https://codeclimate.com/github/s0rg/quadtree …
=> add quadtree

README.md
- repo link (github.com, gitlab.com, etc): https://github.com/kkyr/go-recipe
- pkg.go.dev: https://pkg.go.dev/github.com/kkyr/go-recipe?tab=doc
- goreportcard.com: https://goreportcard.com/report/github.com/kkyr/go-recipe
- coverage service link ([codecov](https://codecov.io/), [coveralls](https://coveralls.io/), [gocover](http://gocover.io/) etc.): https://coveralls.io/github/kkyr/go-recipe?branch=main …
=> Add github.com/kkyr/go-recipe

README.md
- repo link: [https://github.com/pioz/countries](https://github.com/pioz/countries)
- pkg.go.dev: [https://pkg.go.dev/github.com/pioz/countries](https://pkg.go.dev/github.com/pioz/countries)
- goreportcard.com: [https://goreportcard.com/report/github.com/pioz/countries](https://goreportcard.com/report/github.com/pioz/countries)
- coverage service link: [codecov](https://app.codecov.io/gh/pioz/countries) …
=> Add github.com/pioz/countries package

README.md
- repo link (github.com, gitlab.com, etc): https://github.com/wroge/scan
- pkg.go.dev: https://pkg.go.dev/github.com/wroge/scan
- goreportcard.com: https://goreportcard.com/report/github.com/wroge/scan
- coverage service link ([codecov](https://codecov.io/), [coveralls](https://coveralls.io/), [gocover](http://gocover.io/) etc.): https://codecov.io/gh/wroge/scan …
=> add wroge/scan

README.md
=> gameswithgo.org doesn't exist anymore

README.md
Change-Id: I11acc3ada7b02d6766b9b1d8b18a32a80cdd9e4b
- repo link (github.com, gitlab.com, etc): https://github.com/jxskiss/mcli
- pkg.go.dev: https://pkg.go.dev/github.com/jxskiss/mcli
- goreportcard.com: https://goreportcard.com/report/github.com/jxskiss/mcli
- coverage service link ([codecov](https://codecov.io/), [coveralls](https://coveralls.io/), [gocover](http://gocover.io/) etc.): https://codecov.io/gh/jxskiss/mcli …
=> add jxsksis/mcli

README.md
=> Change golangcode to gophercoding new site

README.md
- repo link (github.com, gitlab.com, etc): https://github.com/s0rg/fantasyname
- pkg.go.dev: https://pkg.go.dev/github.com/s0rg/fantasyname
- goreportcard.com: https://goreportcard.com/report/github.com/s0rg/fantasyname
- coverage service link ([codecov](https://codecov.io/), [coveralls](https://coveralls.io/), [gocover](http://gocover.io/) etc.): https://codeclimate.com/github/s0rg/fantasyname …
=> add fantasyname

README.md
- repo link (github.com, gitlab.com, etc): https://github.com/nao1215/gup
- pkg.go.dev: https://pkg.go.dev/github.com/nao1215/gup
- goreportcard.com: https://goreportcard.com/report/github.com/nao1215/gup
- coverage service link ([codecov](https://codecov.io/), [coveralls](https://coveralls.io/), [gocover](http://gocover.io/) etc.): https://app.codecov.io/gh/nao1215/gup
_Not every …
=> add package gup

README.md
- repo link (github.com, gitlab.com, etc): https://github.com/xybor-x/xylog
- pkg.go.dev: https://pkg.go.dev/github.com/xybor-x/xylog
- goreportcard.com: https://goreportcard.com/report/github.com/xybor-x/xylog
- coverage service link ([codecov](https://codecov.io/), [coveralls](https://coveralls.io/), [gocover](http://gocover.io/) etc.): https://app.codacy.com/gh/xybor-x/xylog
_Not …
=> Add package xylog

README.md
This is just a fix for one word.
- repo link (github.com, gitlab.com, etc): https://github.com/hajimehoshi/ebiten
- pkg.go.dev: https://pkg.go.dev/github.com/hajimehoshi/ebiten/v2 …
=> replace the word 'library' with 'engine' for Ebitengine

README.md
restcountries.eu is now countrylayer.com
see https://github.com/chriscross0/go-restcountries
- [x ] The package has been added to the list in alphabetical order.
- [ x] The package has an appropriate description with correct grammar.
- [ x] As far as I …
=> Updated link for restcountries

README.md
- repo link (github.com, gitlab.com, etc): https://github.com/avast/retry-go
- pkg.go.dev: https://pkg.go.dev/github.com/avast/retry-go/v4
- goreportcard.com: https://goreportcard.com/report/github.com/avast/retry-go
- coverage service link ([codecov](https://codecov.io/), [coveralls](https://coveralls.io/), [gocover](http://gocover.io/) etc.): https://codecov.io/github/avast/retry-go?branch=master …
=> add avast/retry-go

README.md
- repo link: [https://github.com/vladopajic/go-actor](https://github.com/vladopajic/go-actor)
- pkg.go.dev: https://pkg.go.dev/github.com/vladopajic/go-actor
- goreportcard.com: https://goreportcard.com/report/github.com/vladopajic/go-actor
- coverage service link: https://codecov.io/gh/vladopajic/go-actor
=> add goactor

README.md
=> Add new tutorial: Go in 7 days

README.md
=> Add w3basic to tutorials

README.md
- repo link (github.com, gitlab.com, etc): https://github.com/google/starlark-go
- pkg.go.dev: https://pkg.go.dev/go.starlark.net/starlark
- goreportcard.com: https://goreportcard.com/report/go.starlark.net …
=> add google/starlark-go

README.md
- repo link (github.com, gitlab.com, etc): https://github.com/ijt/go-anytime
- pkg.go.dev: https://pkg.go.dev/github.com/ijt/go-anytime
- goreportcard.com: https://goreportcard.com/report/github.com/ijt/go-anytime
- coverage service link ([codecov](https://codecov.io/), [coveralls](https://coveralls.io/), [gocover](http://gocover.io/) etc.): https://app.codecov.io/gh/ijt/go-anytime …
=> add go-anytime

README.md
=> removed some grammatical omission till Standard CLI in readme.md

README.md
=> Add "Effective Go" book to resources

.github/PULL_REQUEST_TEMPLATE.md
- pkg.go.dev:
**I am just fixing a typo, not adding anything …
=> correct spelling of 'details' in pr template

README.md
I was going through the markdown and noticed some inconsistencies in formatting I wanted to address. 
- pkg.go.dev:
_Not every repository (project) will require every option, but most projects …
=> use standard dashes between project names and descriptions

README.md
=> remove deprecated bindings

README.md
- repo link (github.com, gitlab.com, etc): https://github.com/k0kubun/pp
- pkg.go.dev: https://pkg.go.dev/github.com/k0kubun/pp/v3
- goreportcard.com: https://goreportcard.com/report/github.com/k0kubun/pp …
=> add k0kubun/pp

README.md
- repo link (github.com, gitlab.com, etc): https://github.com/k0kubun/pp
- pkg.go.dev: https://pkg.go.dev/github.com/k0kubun/pp/v3
- goreportcard.com: https://goreportcard.com/report/github.com/k0kubun/pp …
=> fix k0kubun/pp repo url

README.md
=> Add valix (request validator)

README.md
- https://github.com/etherlabsio/go-m3u8
- https://pkg.go.dev/github.com/etherlabsio/go-m3u8
- goreportcard.com: https://goreportcard.com/report/github.com/etherlabsio/go-m3u8
- coverage service link : https://app.codecov.io/gh/etherlabsio/go-m3u8
Thanks …
=> Add etherlabsio/go-m3u8 module

README.md
- repo link (github.com, gitlab.com, etc): https://github.com/FreeLeh/GoFreeDB
- pkg.go.dev: https://pkg.go.dev/github.com/FreeLeh/GoFreeDB
- goreportcard.com: https://goreportcard.com/report/github.com/FreeLeh/GoFreeDB
- coverage service link ([codecov](https://codecov.io/), [coveralls](https://coveralls.io/), [gocover](http://gocover.io/) etc.): https://github.com/FreeLeh/GoFreeDB/blob/main/README.md (manually generated badge) …
=> Add `GoFreeDB`

README.md
- repo link (github.com, gitlab.com, etc): https://github.com/axllent/mailpit
- pkg.go.dev:
- goreportcard.com:https://goreportcard.com/report/github.com/axllent/mailpit …
=> Add Mailpit

README.md
- repo link (github.com, gitlab.com, etc): https://github.com/chai2010/go-ast-book
- pkg.go.dev:
- coverage service link ([codecov](https://codecov.io/), [coveralls](https://coveralls.io/), [gocover](http://gocover.io/) etc.): https://github.com/chai2010/go-ast-book/actions/workflows/book.yml
_Not every repository (project) will require every option, but most …
=> add Go ast book

README.md
- repo link (github.com, gitlab.com, etc): https://github.com/savsgio/atreugo
- pkg.go.dev: https://pkg.go.dev/github.com/savsgio/atreugo/v11
- goreportcard.com: https://goreportcard.com/report/github.com/savsgio/atreugo
- coverage service link ([codecov](https://codecov.io/), [coveralls](https://coveralls.io/), [gocover](http://gocover.io/) etc.): https://coveralls.io/github/savsgio/atreugo?branch=master …
=> Add Atruego in Web Frameworks

README.md
- repo link (github.com, gitlab.com, etc): https://github.com/objectbox/objectbox-go
- pkg.go.dev: https://pkg.go.dev/github.com/objectbox/objectbox-go/objectbox
- goreportcard.com: https://goreportcard.com/report/github.com/objectbox/objectbox-go
- coverage service link ([codecov](https://codecov.io/), [coveralls](https://coveralls.io/), [gocover](http://gocover.io/) etc.): don't have it, but the code is extensively tested (see https://github.com/objectbox/objectbox-go/tree/main/test)
**Note**: _that new categories can be added only when there are 3 …
=> Add ObjectBox Go to Databases

README.md
Added [Microservices with Go](https://www.youtube.com/playlist?list=PLmD8u-IFdreyh6EUfevBcbiuCKzFk0EW_) to the Tutorials section.
=> Add 'Microservices with Go' in the Tutorials section

README.md
- pkg.go.dev:
- The coverage tests are on the C++ side of the …
=> Added Harfang3D engine

CONTRIBUTING.md
Corrected grammatically incorrect sentences, punctuations and typos for better readability.
- pkg.go.dev: …
=> Corrected grammatically incorrect sentences, punctuations and typos for better readability.

README.md
- repo link (github.com, gitlab.com, etc): https://github.com/terrastruct/diff
- pkg.go.dev: https://pkg.go.dev/oss.terrastruct.com/diff
- goreportcard.com: https://goreportcard.com/report/oss.terrastruct.com/diff
- coverage service link ([codecov](https://codecov.io/), [coveralls](https://coveralls.io/), [gocover](http://gocover.io/) etc.): https://coveralls.io/github/terrastruct/diff …
=> Add `diff`

README.md
- repo link (github.com, gitlab.com, etc): https://github.com/cloudwego/hertz
- pkg.go.dev: https://pkg.go.dev/github.com/cloudwego/hertz
- goreportcard.com: https://goreportcard.com/report/github.com/cloudwego/hertz
- coverage service link ([codecov](https://codecov.io/), [coveralls](https://coveralls.io/), [gocover](http://gocover.io/) etc.): https://app.codecov.io/gh/cloudwego/hertz …
=> feat(Web Frameworks): add a new web framework

README.md
Hello - request review and approval on the inclusion of Explore Go Libraries & Projects on your list. It would be a good addition under WEBSITES section of this article. Would you like to include it in your list? We'd love to hear your feedback. Thanks!
- pkg.go.dev:
**Make …
=> add kandi.openweaver.com

README.md
=> Add swag to Third-party APIs

README.md
- repo link (github.com, gitlab.com, etc): https://github.com/mingard/sitemap-format
- pkg.go.dev: https://pkg.go.dev/github.com/mingard/sitemap-format
- goreportcard.com: https://goreportcard.com/report/github.com/mingard/sitemap-format
- coverage service link ([codecov](https://codecov.io/), [coveralls](https://coveralls.io/), [gocover](http://gocover.io/) etc.): Managed by action: https://github.com/mingard/sitemap-format/blob/main/.github/workflows/production.yml#L29-L32
**Note**: _that new categories can be added only when there are 3 packages …
=> Add mingard/sitemap-format

README.md
- repo link (github.com, gitlab.com, etc): https://github.com/nikolaydubina/go-instrument
- pkg.go.dev: https://pkg.go.dev/github.com/nikolaydubina/go-instrument
- goreportcard.com: https://goreportcard.com/report/github.com/nikolaydubina/go-instrument
- coverage service link ([codecov](https://codecov.io/), [coveralls](https://coveralls.io/), [gocover](http://gocover.io/) etc.): https://codecov.io/gh/nikolaydubina/go-instrument …
=> Added go-instrument

README.md
Fixed the Harfang Go.dev URL, the missing `HTTPS` caused a 404 error. Sorry, the mistake was on our side on the initial PR.
- pkg.go.dev: …
=> Fixed the Harfang Go.dev URL

README.md
- repo link (github.com, gitlab.com, etc): https://github.com/charmbracelet/bubbletea
- pkg.go.dev: https://pkg.go.dev/github.com/charmbracelet/bubbletea
- goreportcard.com: https://goreportcard.com/report/github.com/charmbracelet/bubbletea
- coverage service link ([codecov](https://codecov.io/), [coveralls](https://coveralls.io/), [gocover](http://gocover.io/) etc.): https://github.com/charmbracelet/bubbletea/actions/runs/3457278931/jobs/5770599579 …
=> Add https://github.com/charmbracelet/bubbletea

README.md
- repo link (github.com, gitlab.com, etc): https://github.com/cristalhq/builq
- pkg.go.dev: https://pkg.go.dev/github.com/cristalhq/builq
- goreportcard.com: https://goreportcard.com/report/github.com/cristalhq/builq
- coverage service link ([codecov](https://codecov.io/), [coveralls](https://coveralls.io/), [gocover](http://gocover.io/) etc.): https://app.codecov.io/gh/cristalhq/builq …
=> Add cristalhq/builq

README.md
- repo: https://github.com/charmbracelet/lipgloss
- pkg.go.dev: https://pkg.go.dev/github.com/charmbracelet/lipgloss
- goreportcard.com: https://goreportcard.com/report/github.com/charmbracelet/lipgloss
- coverage service link: https://github.com/charmbracelet/lipgloss/actions/workflows/coverage.yml
=> Add https://github.com/charmbracelet/lipgloss

README.md
=> Drop project that archived.

README.md
Add Golang Rotterdam Meetup
https://www.meetup.com/golang-rotterdam/
=> Update README.md (add meetup)

README.md
I am the [author](https://github.com/elliotwutingfeng/go-fasttld) of go-fasttld. I have recently changed my project description. Thanks again for listing my work!
=> Update go-fasttld description

README.md
- repo link (github.com, gitlab.com, etc): https://github.com/uber/h3-go
- pkg.go.dev: https://pkg.go.dev/github.com/uber/h3-go
- goreportcard.com: https://goreportcard.com/report/github.com/uber/h3-go
- coverage service link [coveralls](https://coveralls.io/): https://coveralls.io/github/uber/h3-go …
=> fix link to h3-go entry

README.md
- repo link (github.com, gitlab.com, etc): https://github.com/sourcegraph/conc
- pkg.go.dev: https://pkg.go.dev/github.com/sourcegraph/conc
- goreportcard.com: https://goreportcard.com/report/github.com/sourcegraph/conc
- coverage service link ([codecov](https://codecov.io/), [coveralls](https://coveralls.io/), [gocover](http://gocover.io/) etc.): https://app.codecov.io/gh/sourcegraph/conc …
=> add conc library to manage goroutine

README.md
- repo link (github.com, gitlab.com, etc): https://github.com/go-survey/survey
- pkg.go.dev: https://pkg.go.dev/github.com/AlecAivazis/survey
- goreportcard.com: github.com/AlecAivazis/survey/v2
- coverage service link ([codecov](https://codecov.io/), [coveralls](https://coveralls.io/), [gocover](http://gocover.io/) etc.): https://gocover.io/github.com/AlecAivazis/survey
_Not every …
=> Add go-survey/survey

README.md
ref: https://github.com/vieux/gocover.io/commit/6ef5fb11adef14bff5a513a52492ec8fc77927aa
=> remove gocover.io

README.md
- repo link (github.com, gitlab.com, etc): https://github.com/kitabisa/teler-waf
- pkg.go.dev: http://pkg.go.dev/github.com/kitabisa/teler-waf
- goreportcard.com: https://goreportcard.com/report/github.com/kitabisa/teler-waf
- coverage service link ([codecov](https://codecov.io/), [coveralls](https://coveralls.io/), etc.): https://coveralls.io/github/kitabisa/teler-waf
_Not every …
=> add teler-waf

README.md
Hello, please consider Go Faster for the ebooks (paid) section.
As a book link, the PR guidelines that apply are just these I believe.
Thank you.
=> Add 'Go Faster' book to ebooks (paid) section

README.md
repo https://github.com/averageflow/gohooks has been deleted
=> remove gohooks

README.md
Signed-off-by: Gaius <gaius.qi@gmail.com>
- repo link (github.com, gitlab.com, etc): https://github.com/dragonflyoss/Dragonfly2
- pkg.go.dev: https://pkg.go.dev/github.com/dragonflyoss/Dragonfly2/v2
- goreportcard.com: https://goreportcard.com/report/github.com/dragonflyoss/Dragonfly2#golint
- coverage service link ([codecov](https://codecov.io/), [coveralls](https://coveralls.io/), etc.): https://app.codecov.io/gh/dragonflyoss/Dragonfly2 …
=> Add dragonfly to distributed systems

README.md
- repo link (github.com, gitlab.com, etc): https://github.com/esimov/gogu
- pkg.go.dev: https://pkg.go.dev/github.com/esimov/gogu
- goreportcard.com: https://goreportcard.com/report/github.com/esimov/gogu
- coverage service link ([codecov](https://codecov.io/), [coveralls](https://coveralls.io/), etc.): https://camo.githubusercontent.com/1fd3ffa45b54cd399568f860c8479cc52feddd792dc08c198018ace9a90b5780/68747470733a2f2f696d672e736869656c64732e696f2f62616467652f436f7665726167652d39332e392532352d627269676874677265656e
**Note**: _that new categories can …
=> doc: add gogu to utility function libraries

README.md
Added a new ebook to the list.
=> add ebook: lets-go

README.md
- repo link (github.com, gitlab.com, etc): https://github.com/edwingeng/wuid
- pkg.go.dev: https://pkg.go.dev/github.com/edwingeng/wuid
- goreportcard.com: https://goreportcard.com/report/github.com/edwingeng/wuid
- coverage service link ([codecov](https://codecov.io/), [coveralls](https://coveralls.io/), etc.): It is too hard to set up a test environment on these websites for code coverage.
```
master > go test -cover
PASS
coverage: 99.0% of statements
ok      github.com/edwingeng/wuid/internal      0.231s
```
**Note**: _that new categories can be …
=> update the description of github.com/edwingeng/wuid

README.md
- repo link (github.com, gitlab.com, etc): https://github.com/edwingeng/hotswap
- pkg.go.dev: https://pkg.go.dev/github.com/edwingeng/hotswap
- goreportcard.com: https://goreportcard.com/report/github.com/edwingeng/hotswap
- coverage service link ([codecov](https://codecov.io/), [coveralls](https://coveralls.io/), etc.): It takes too much time to run all the test cases online.
```
main > go test -trimpath -cover
PASS
coverage: 80.6% of statements in github.com/edwingeng/hotswap
ok      github.com/edwingeng/hotswap    447.500s
```
**Note**: _that new …
=> add github.com/edwingeng/hotswap

README.md
- repo link (github.com, gitlab.com, etc): https://github.com/testcontainers/testcontainers-go
- pkg.go.dev: https://pkg.go.dev/github.com/testcontainers/testcontainers-go
- goreportcard.com: https://goreportcard.com/report/github.com/testcontainers/testcontainers-go
- coverage service link ([codecov](https://codecov.io/), [coveralls](https://coveralls.io/), etc.): https://app.codecov.io/gh/testcontainers/testcontainers-go …
=> docs: add Testcontainers for Go

README.md
https://lets-go-further.alexedwards.net
- pkg.go.dev: …
=> Updates paid ebooks list with let's-go-further book

README.md
=> add https://github.com/go-telegram/bot to Bot Building section

README.md
=> Mention booster initramfs generator

README.md
Domain golangbootcamp.com on parking
- pkg.go.dev:
=> Link does not available. Domain on sale

README.md
- repo link (github.com, gitlab.com, etc): https://github.com/abusomani/go-palette
- pkg.go.dev: https://pkg.go.dev/github.com/abusomani/go-palette@v1.0.0
- goreportcard.com: https://goreportcard.com/report/github.com/abusomani/go-palette
- coverage service link ([codecov](https://codecov.io/), [coveralls](https://coveralls.io/), etc.): https://coveralls.io/github/abusomani/go-palette?branch=main …
=> Add go-palette

README.md
- repo link (github.com, gitlab.com, etc): https://github.com/otiai10/openaigo
- pkg.go.dev: https://pkg.go.dev/github.com/otiai10/openaigo
- goreportcard.com: https://goreportcard.com/report/github.com/otiai10/openaigo
- coverage service link ([codecov](https://codecov.io/), [coveralls](https://coveralls.io/), etc.): https://app.codecov.io/github/otiai10/openaigo …
=> Add openaigo

README.md
- repo link (github.com, gitlab.com, etc): https://github.com/abusomani/jsonhandlers
- pkg.go.dev: https://pkg.go.dev/github.com/abusomani/jsonhandlers
- goreportcard.com: https://goreportcard.com/report/github.com/abusomani/jsonhandlers
- coverage service link ([codecov](https://codecov.io/), [coveralls](https://coveralls.io/), etc.): https://coveralls.io/github/abusomani/jsonhandlers?branch=main …
=> Add jsonhandlers

README.md
- [repo link](https://github.com/kazhuravlev/options-gen)
- [pkg.go.dev](https://pkg.go.dev/github.com/kazhuravlev/options-gen)
- [goreportcard.com](https://goreportcard.com/report/github.com/kazhuravlev/options-gen)
- [codecov](https://app.codecov.io/gh/kazhuravlev/options-gen). @avelino please note that this *60%* is include `examples` directory.  …
=> Add kazhuravlev/options-gen

README.md
- repo link (github.com, gitlab.com, etc): https://github.com/sashabaranov/go-openai
- pkg.go.dev: https://pkg.go.dev/github.com/sashabaranov/go-openai
- goreportcard.com: https://goreportcard.com/report/github.com/sashabaranov/go-openai
- coverage service link ([codecov](https://codecov.io/), [coveralls](https://coveralls.io/), etc.): https://app.codecov.io/gh/sashabaranov/go-openai …
=> add go-openai

README.md
Communication: https://redis.com/blog/go-redis-official-redis-client/
- repo link (github.com, gitlab.com, etc): https://github.com/redis/go-redis
- pkg.go.dev: https://pkg.go.dev/github.com/redis/go-redis
- goreportcard.com: https://goreportcard.com/report/github.com/redis/go-redis
_Not …
=> update redis repo

README.md
- repo link (github.com, gitlab.com, etc): https://github.com/nikolaydubina/htmljson
- pkg.go.dev: https://pkg.go.dev/github.com/nikolaydubina/htmljson
- goreportcard.com: https://goreportcard.com/report/github.com/nikolaydubina/htmljson
- coverage service link ([codecov](https://codecov.io/), [coveralls](https://coveralls.io/), etc.): https://codecov.io/gh/nikolaydubina/htmljson
_Not …
=> Added https://github.com/nikolaydubina/htmljson

README.md
- repo link (github.com, gitlab.com, etc): https://github.com/nikolaydubina/watchhttp
- pkg.go.dev: https://pkg.go.dev/github.com/nikolaydubina/watchhttp
- goreportcard.com: https://goreportcard.com/report/github.com/nikolaydubina/watchhttp
- coverage service link ([codecov](https://codecov.io/), [coveralls](https://coveralls.io/), etc.): https://codecov.io/gh/nikolaydubina/watchhttp …
=> Added https://github.com/nikolaydubina/watchhttp

README.md
- [repo link](https://github.com/hmdsefi/gograph)
- [pkg.go.dev](https://pkg.go.dev/github.com/hmdsefi/gograph)
- [goreportcard.com](https://goreportcard.com/report/github.com/hmdsefi/gograph)
- [codecov](https://app.codecov.io/gh/hmdsefi/gograph)
Thanks …
=> added hmdsefi/gograph

README.md
- repo link (github.com, gitlab.com, etc):github.com/contextplus/contextplus
- pkg.go.dev: https://pkg.go.dev/github.com/contextplus/contextplus
- goreportcard.com: https://goreportcard.com/report/github.com/contextplus/contextplus …
=> Add contextplus

README.md
Update branch name, `master` => `main`
=> Update the contribution guidelines link

README.md
- repo link (github.com, gitlab.com, etc): https://github.com/fluentassert/verify
- pkg.go.dev: https://pkg.go.dev/github.com/fluentassert/verify
- goreportcard.com: https://goreportcard.com/report/github.com/fluentassert/verify
- coverage service link: https://app.codecov.io/gh/fluentassert/verify …
=> Add fluentassert to Testing

README.md
- repo link (github.com, gitlab.com, etc): https://github.com/nikolaydubina/htmlyaml
- pkg.go.dev: https://pkg.go.dev/github.com/nikolaydubina/htmlyaml
- goreportcard.com: https://goreportcard.com/report/github.com/nikolaydubina/htmlyaml
- coverage service link ([codecov](https://codecov.io/), [coveralls](https://coveralls.io/), etc.): https://codecov.io/gh/nikolaydubina/htmlyaml
_Not …
=> added https://github.com/nikolaydubina/htmlyaml

README.md
- [repo link](https://github.com/kazhuravlev/just)
- [pkg.go.dev](https://pkg.go.dev/github.com/kazhuravlev/just)
- [goreportcard.com](https://goreportcard.com/report/github.com/kazhuravlev/just) 
- [codecov](https://app.codecov.io/gh/kazhuravlev/just) …
=> Add kazhuravlev/just

README.md
- repo link: https://github.com/vladopajic/go-test-coverage
- pkg.go.dev: https://pkg.go.dev/github.com/vladopajic/go-test-coverage
- goreportcard.com: https://goreportcard.com/report/github.com/vladopajic/go-test-coverage
- coverage service link: https://github.com/vladopajic/go-test-coverage/tree/badges
=> add go-test-coverage

README.md
- repo link (github.com, gitlab.com, etc): https://github.com/Yiling-J/theine-go
- pkg.go.dev: https://pkg.go.dev/github.com/Yiling-J/theine-go
- coverage service link ([codecov](https://codecov.io/), [coveralls](https://coveralls.io/), etc.): https://app.codecov.io/gh/Yiling-J/theine-go
_Not every repository (project) will require every option, but most projects …
=> add theine to cache

README.md
- repo link (github.com, gitlab.com, etc): https://github.com/erni27/imcache
- pkg.go.dev: https://pkg.go.dev/github.com/erni27/imcache
- goreportcard.com: https://goreportcard.com/report/github.com/erni27/imcache
- coverage service link ([codecov](https://codecov.io/), [coveralls](https://coveralls.io/), etc.): https://app.codecov.io/gh/erni27/imcache …
=> Add imcache

README.md
=> add color-extractor

README.md
- repo link (github.com, gitlab.com, etc): https://github.com/gopulse/pulse
- pkg.go.dev: https://pkg.go.dev/github.com/gopulse/pulse
- goreportcard.com: https://goreportcard.com/report/github.com/gopulse/pulse
- coverage service link ([codecov](https://codecov.io/), [coveralls](https://coveralls.io/), etc.): https://codecov.io/gh/gopulse/pulse …
=> add Pulse web framework

README.md
- repo link (github.com, gitlab.com, etc): [https://github.com/no-src/log](https://github.com/no-src/log)
- pkg.go.dev: [https://pkg.go.dev/github.com/no-src/log](https://pkg.go.dev/github.com/no-src/log)
- goreportcard.com: [https://goreportcard.com/report/github.com/no-src/log](https://goreportcard.com/report/github.com/no-src/log)
- coverage service link ([codecov](https://codecov.io/), [coveralls](https://coveralls.io/), etc.): [https://app.codecov.io/gh/no-src/log](https://app.codecov.io/gh/no-src/log)
**Note**: _that new categories can be added …
=> Add no-src/log

README.md
- repo link (github.com, gitlab.com, etc): https://github.com/octomation/go-module
- pkg.go.dev: https://pkg.go.dev/go.octolab.org/template/module, useless
- goreportcard.com: https://goreportcard.com/report/go.octolab.org/template/module, useless
- coverage service link ([codecov](https://codecov.io/), [coveralls](https://coveralls.io/), etc.): https://codecov.io/gh/octomation/go-module (useless) …
=> add go-module to project layout section

README.md
- repo link (github.com, gitlab.com, etc): https://github.com/samber/slog-multi
- pkg.go.dev: https://pkg.go.dev/github.com/samber/slog-multi
- goreportcard.com: https://goreportcard.com/report/github.com/samber/slog-multi
- coverage service link ([codecov](https://codecov.io/), [coveralls](https://coveralls.io/), etc.): https://app.codecov.io/gh/samber/slog-multi …
=> feat: adding slog-multi

README.md
- repo link (github.com, gitlab.com, etc): [https://github.com/no-src/nscache](https://github.com/no-src/nscache)
- pkg.go.dev: [https://pkg.go.dev/github.com/no-src/nscache](https://pkg.go.dev/github.com/no-src/nscache)
- goreportcard.com: [https://goreportcard.com/report/github.com/no-src/nscache](https://goreportcard.com/report/github.com/no-src/nscache)
- coverage service link ([codecov](https://codecov.io/), [coveralls](https://coveralls.io/), etc.): [https://app.codecov.io/gh/no-src/nscache](https://app.codecov.io/gh/no-src/nscache)
**Note**: …
=> Add no-src/nscache

README.md
- repo link (github.com, gitlab.com, etc): https://github.com/adrianbrad/queue
- pkg.go.dev: https://pkg.go.dev/github.com/adrianbrad/queue
- goreportcard.com: https://goreportcard.com/report/github.com/adrianbrad/queue
- coverage service link ([codecov](https://codecov.io/), [coveralls](https://coveralls.io/), etc.): https://app.codecov.io/gh/adrianbrad/queue …
=> add github.com/adrianbrad/queue

README.md
- repo link (github.com, gitlab.com, etc): https://github.com/SpatiumPortae/portal
- pkg.go.dev: https://pkg.go.dev/github.com/SpatiumPortae/portal
- goreportcard.com: https://goreportcard.com/report/github.com/SpatiumPortae/portal
- coverage service link ([codecov](https://codecov.io/), [coveralls](https://coveralls.io/), etc.): https://app.codecov.io/gh/SpatiumPortae/portal/tree/master
=> add portal

README.md
=> Add sqlgen

README.md
=> Add LibraDB and Chronos

README.md
- pkg.go.dev:
- [ y] The package has been added to the list in …
=> Added vacuum to the Code Analysis tools

README.md
- repo link (github.com, gitlab.com, etc): https://github.com/reedom/convergen
- pkg.go.dev: https://pkg.go.dev/github.com/reedom/convergen
- goreportcard.com: https://goreportcard.com/report/github.com/reedom/convergen
- coverage service link ([codecov](https://codecov.io/), [coveralls](https://coveralls.io/), etc.): [https://camo.githubusercontent.com/…](https://camo.githubusercontent.com/89392c586383ebde8de87ccbe7614477c9f1f4af52475743388e6f3559c9b898/68747470733a2f2f696d672e736869656c64732e696f2f62616467652f436f7665726167652d36372e362532352d79656c …
=> add convergen

README.md
=> add gws: High-Performance WebSocket Server & Client With AsyncIO Supporting

README.md
The PR fixes description for an existing library. A minor syntax amendment.
=> Gosip description fix

README.md
=> Update README.md - adds kevincobain2000/gobrew 

README.md
poke @lmittmann
- repo link (github.com, gitlab.com, etc): https://github.com/lmittmann/tint
- pkg.go.dev: https://pkg.go.dev/github.com/lmittmann/tint
- goreportcard.com: https://goreportcard.com/report/github.com/lmittmann/tint
_Not every repository (project) will require every option, …
=> Feat: Adding lmittmann/tint

README.md
- repo link (github.com, gitlab.com, etc): https://github.com/limiu82214/gojmapr
- pkg.go.dev: https://pkg.go.dev/github.com/limiu82214/gojmapr [![Go Reference](https://pkg.go.dev/badge/github.com/limiu82214/gojmapr.svg)](https://pkg.go.dev/github.com/limiu82214/gojmapr)
- goreportcard.com: https://goreportcard.com/report/github.com/limiu82214/gojmapr [![Go Report Card](https://goreportcard.com/badge/github.com/limiu82214/gojmapr)](https://goreportcard.com/report/github.com/limiu82214/gojmapr)
- coverage service link ([codecov](https://codecov.io/), …
=> add limiu82214/gojmapr

README.md
- github.com repo: https://github.com/kubevela/kubevela
- pkg.go.dev: https://pkg.go.dev/github.com/oam-dev/kubevela
- goreportcard.com: https://goreportcard.com/report/github.com/kubevela/kubevela
- coverage service link: ([codecov](https://codecov.io/), [coveralls](https://coveralls.io/), [gocover](https://gocover.io/) etc.): https://codecov.io/gh/kubevela/kubevela
_Not every …
=> Add github.com/kubevela/kubevela

README.md
- repo link (github.com, gitlab.com, etc): https://github.com/lf-edge/ekuiper
- pkg.go.dev: https://pkg.go.dev/github.com/emqx/kuiper
- coverage service link ([codecov](https://codecov.io/), [coveralls](https://coveralls.io/), etc.): https://app.codecov.io/gh/lf-edge/ekuiper
_Not every repository (project) will require every option, but most projects should. Check …
=> add ekuiper to IOT

README.md
- repo link (github.com, gitlab.com, etc): [https://github.com/kubeservice-stack/common](https://github.com/kubeservice-stack/common)
- pkg.go.dev: [https://pkg.go.dev/github.com/kubeservice-stack/common](https://pkg.go.dev/github.com/kubeservice-stack/common)
- goreportcard.com:  [https://goreportcard.com/report/github.com/kubeservice-stack/common](https://goreportcard.com/report/github.com/kubeservice-stack/common) …
=> Add Golang Common Library for Server Framework

.github/workflows/pull-request-first-comment.yaml
I noticed this typo after submitting my first PR.
=> Fix typo in github action workflow

README.md
A lot of developers ask on /r/golang questions such as "how can I learn Go?". Given the frequency of these questions, I felt it was appropriate to add a guided-learning section to this doc which will hopefully contain a comprehensive list of online paths that new Go developers can follow.
The TutorialEdge path contains a fairly comprehensive list of free and paid resources (mine and other Go content creators such as Alex Edwards, Ardan Labs etc). The Roadmap link contains a visual mind-map of all the various concepts and packages that a Go developer can try to work through.
If there are other resources that should be added, please let me know and I can add and rebase this PR.
N/A - these are new learning resources 
Links are:
[The Go Learning …
=> Added a guided learning section to list resources that help guide new go developers

README.md
=> Add "A Comprehensive Guide to Structured Logging in Go" to Tutorials

README.md
=> adress: Multiple broken hyperlinks #4888

README.md
- repo link (github.com, gitlab.com, etc): https://github.com/samber/oops
- pkg.go.dev: https://pkg.go.dev/github.com/samber/oops
- goreportcard.com: https://goreportcard.com/report/github.com/samber/oops
- coverage service link ([codecov](https://codecov.io/), [coveralls](https://coveralls.io/), etc.): https://codecov.io/gh/samber/oops
_Not every repository (project) will require …
=> Adding samber/oops

README.md
=> surrealdb added

README.md
- repo link (github.com, gitlab.com, etc): https://github.com/datarootsio/tf-profile
- pkg.go.dev: https://pkg.go.dev/github.com/QuintenBruynseraede/tf-profile
- goreportcard.com: https://goreportcard.com/report/github.com/QuintenBruynseraede/tf-profile
- coverage service link ([codecov](https://codecov.io/), [coveralls](https://coveralls.io/), etc.): https://github.com/datarootsio/tf-profile …
=> add tf-profile

README.md
- repo link (github.com, gitlab.com, etc): https://github.com/cyucelen/walker
- pkg.go.dev: https://pkg.go.dev/github.com/cyucelen/walker
- goreportcard.com: https://goreportcard.com/report/github.com/cyucelen/walker
- coverage service link ([codecov](https://codecov.io/), [coveralls](https://coveralls.io/), etc.): https://app.codecov.io/gh/cyucelen/walker
=> Add walker

README.md
- repo link (github.com, gitlab.com, etc): https://github.com/Andrew-M-C/go.jsonvalue
- pkg.go.dev: [![GoDoc](https://godoc.org/github.com/Andrew-M-C/go.jsonvalue?status.svg&date=221104)](https://pkg.go.dev/github.com/Andrew-M-C/go.jsonvalue@v1.3.3)
- goreportcard.com: [![Go report](https://goreportcard.com/badge/github.com/Andrew-M-C/go.jsonvalue?date=221104)](https://goreportcard.com/report/github.com/Andrew-M-C/go.jsonvalue) …
=> Add Andrew-M-C/go.jsonvalue

README.md
- repo link (github.com, gitlab.com, etc): https://github.com/reeflective/readline
- pkg.go.dev: https://pkg.go.dev/github.com/reeflective/readline
- goreportcard.com: https://goreportcard.com/report/github.com/reeflective/readline
- coverage service link ([codecov](https://codecov.io/), [coveralls](https://coveralls.io/), [gocover](http://gocover.io/) etc.): https://app.codecov.io/gh/reeflective/readline …
=> Add reeflective/readline

README.md
- repo link (github.com, gitlab.com, etc): https://github.com/temporalio/sdk-go
- pkg.go.dev: https://pkg.go.dev/go.temporal.io/sdk
- goreportcard.com: https://goreportcard.com/report/go.temporal.io/sdk …
=> Add Temporal

README.md
Part of https://github.com/avelino/avelino.run/pull/41.
=> Update Keygen sponsor tagline

README.md
- repo link (github.com, gitlab.com, etc): https://github.com/abemedia/go-don
- pkg.go.dev: https://pkg.go.dev/github.com/abemedia/go-don
- goreportcard.com: https://goreportcard.com/report/github.com/abemedia/go-don
- coverage service link ([codecov](https://codecov.io/), [coveralls](https://coveralls.io/), etc.): https://app.codecov.io/gh/abemedia/go-don
=> Add Don to Web Frameworks

README.md
A data race-free Go ache library with high performance and auto purge functionality
repo link (github.com, gitlab.com, etc): [github.com/yuseferi/gocache](https://github.com/avelino/awesome-go/pull/github.com/yuseferi/gocache)
pkg.go.dev: [https://pkg.go.dev/github.com/yuseferi/gocache](https://pkg.go.dev/github.com/yuseferi/gocache)
goreportcard.com:[https://goreportcard.com/report/github.com/yuseferi/gocache](https://goreportcard.com/report/github.com/yuseferi/gocache)
coverage service link ([codecov](https://codecov.io/), …
=> adding a high performance race free gocache with auto expring

README.md
Zax is a  simple wrapper around the Zap which helps zap to work context and you do not need to pass logger to any function, global parameters like `trace_id` etc could be log easier without repeating them in every downstream method.
[github.com/yuseferi/zax](github.com/yuseferi/zax)
more details what it's doing : https://medium.com/@yuseferi/zax-a-golang-package-to-add-context-on-top-of-zap-logger-e33ac3bdcddc
- repo link (github.com, gitlab.com, etc): [github.com/yuseferi/zax](github.com/yuseferi/zax)
- pkg.go.dev: …
=> Add Zax logger

README.md
Add cometbft
- repo link: https://github.com/cometbft/cometbft
- pkg.go.dev: https://pkg.go.dev/github.com/cometbft/cometbft
- goreportcard.com: https://goreportcard.com/report/github.com/cometbft/cometbft
=> Added CometBFT to Blockchain section

README.md
- repo link (github.com, gitlab.com, etc): https://github.com/Evertras/bubble-table
- pkg.go.dev: https://pkg.go.dev/github.com/evertras/bubble-table/table
- goreportcard.com: https://goreportcard.com/report/github.com/evertras/bubble-table
- coverage service link ([codecov](https://codecov.io/), [coveralls](https://coveralls.io/), etc.): https://coveralls.io/github/Evertras/bubble-table?branch=main …
=> Add bubble-table

README.md
- repo link (github.com, gitlab.com, etc):https://github.com/reaganiwadha/grapher
- pkg.go.dev:https://pkg.go.dev/github.com/reaganiwadha/grapher
- goreportcard.com:https://goreportcard.com/report/github.com/reaganiwadha/grapher
- coverage service link ([codecov](https://codecov.io/), [coveralls](https://coveralls.io/), etc.):https://app.codecov.io/gh/reaganiwadha/grapher
_Not every …
=> Added grapher to the Query Language section

README.md
Adding [Hex Monscape](https://github.com/Haraj-backend/hex-monscape), a getting started guidelines in writing maintainable code using Hexagonal Architecture
- repo link (github.com, gitlab.com, etc): https://github.com/Haraj-backend/hex-monscape
- pkg.go.dev: https://pkg.go.dev/github.com/Haraj-backend/hex-monscape
- goreportcard.com: https://goreportcard.com/report/github.com/Haraj-backend/hex-monscape
- coverage service link ([codecov](https://codecov.io/), [coveralls](https://coveralls.io/), etc.): - https://coveralls.io/github/Haraj-backend/hex-monscape?branch=master
Note: *that new categories can be added only when there are 3 packages or more.*
Contribution Guidelines:
=> Add hex-monscape

README.md
=> bubble-table link fix

README.md
GoNB: https://github.com/janpfeifer/gonb
- repo link (github.com, gitlab.com, etc): https://github.com/janpfeifer/gonb
- pkg.go.dev: https://pkg.go.dev/github.com/janpfeifer/gonb
- goreportcard.com: https://goreportcard.com/report/github.com/janpfeifer/gonb
- coverage service link ([codecov](https://codecov.io/), [coveralls](https://coveralls.io/), etc.): N/A
Coverage is generated by `go tool cover ...` triggered by github actions (following example given by awesome-go actually) and it updates a badge in README.md file of the project. It's low …
=> Added GoNB to README.md

README.md
- repo link (github.com, gitlab.com, etc): https://github.com/wagoodman/dive
- pkg.go.dev: https://pkg.go.dev/github.com/wagoodman/dive
- goreportcard.com: https://goreportcard.com/report/github.com/wagoodman/dive
- coverage service link ([codecov](https://codecov.io/), [coveralls](https://coveralls.io/), [gocover](http://gocover.io/) etc.): n/a …
=> add wagoodman/dive

README.md
- repo link (github.com, gitlab.com, etc): https://github.com/cheng-zhongliang/event
- pkg.go.dev: https://pkg.go.dev/github.com/cheng-zhongliang/event
- goreportcard.com: https://goreportcard.com/report/github.com/cheng-zhongliang/event
- coverage service link ([codecov](https://codecov.io/), [coveralls](https://coveralls.io/), etc.): https://app.codecov.io/gh/cheng-zhongliang/event …
=> Add event to networking

.github/PULL_REQUEST_TEMPLATE.md
Allow trunk-based workflows for awesome projects. This PR changes the pull request template to reflect this.
See https://github.com/avelino/awesome-go/issues/4975
=> Allow trunk-based workflows for awesome projects

README.md
- repo link (github.com, gitlab.com, etc): https://github.com/antham/yogo
- pkg.go.dev: https://pkg.go.dev/github.com/antham/yogo
- goreportcard.com: https://goreportcard.com/report/github.com/antham/yogo
- coverage service link ([codecov](https://codecov.io/), [coveralls](https://coveralls.io/), etc.): https://app.codecov.io/gh/antham/yogo
_Not every repository (project) will require …
=> add antham/yogo

README.md
https://github.com/kubeshark/kubeshark
=> mizu: renamed to kubeshark

README.md
- repo link (github.com, gitlab.com, etc): [https://github.com/piglig/go-qr](https://github.com/piglig/go-qr)
- pkg.go.dev: [https://pkg.go.dev/github.com/piglig/go-qr](https://pkg.go.dev/github.com/piglig/go-qr)
- goreportcard.com: [https://goreportcard.com/report/github.com/piglig/go-qr](https://goreportcard.com/report/github.com/piglig/go-qr)
- coverage service link ([codecov](https://codecov.io/), [coveralls](https://coveralls.io/), etc.): [https://app.codecov.io/github/piglig/go-qr](https://app.codecov.io/github/piglig/go-qr)
**Note**: _that new …
=> add go-qr to README.md

README.md
- repo link (github.com, gitlab.com, etc): https://github.com/PhakornKiong/go-pattern-match
- pkg.go.dev: https://pkg.go.dev/github.com/phakornkiong/go-pattern-match
- goreportcard.com: https://goreportcard.com/report/github.com/phakornkiong/go-pattern-match
- coverage service link ([codecov](https://codecov.io/), [coveralls](https://coveralls.io/), etc.): https://app.codecov.io/gh/PhakornKiong/go-pattern-match
**Make sure that you've checked the boxes below that …
=> Add go-pattern-match

README.md
- repo link https://github.com/codingconcepts/dg
- pkg.go.dev: https://pkg.go.dev/github.com/codingconcepts/dg
- goreportcard.com: https://goreportcard.com/report/github.com/codingconcepts/dg
- coverage service link https://app.codecov.io/gh/codingconcepts/dg
=> Add dg to README

README.md
=> add go-dbw

README.md
- repo link (github.com, gitlab.com, etc): https://github.com/motrboat/hotcoal
- pkg.go.dev: https://pkg.go.dev/github.com/motrboat/hotcoal
- goreportcard.com: https://goreportcard.com/report/github.com/motrboat/hotcoal
- coverage service link ([codecov](https://codecov.io/), [coveralls](https://coveralls.io/), etc.): generate badge using CI https://github.com/motrboat/hotcoal/blob/main/.github/workflows/coverage.yaml …
=> Add Hotcoal package

README.md
- repo link (github.com, gitlab.com, etc): https://github.com/lindb/lindb
- pkg.go.dev: https://pkg.go.dev/github.com/lindb/lindb
- goreportcard.com: https://goreportcard.com/report/github.com/lindb/lindb
- coverage service link ([codecov](https://codecov.io/), [coveralls](https://coveralls.io/), etc.): https://app.codecov.io/gh/lindb/lindb
_Not every repository (project) will require …
=> Add LinDB to database

README.md
- repo link (github.com, gitlab.com, etc): https://github.com/NVIDIA/gontainer
- pkg.go.dev: https://pkg.go.dev/github.com/NVIDIA/gontainer
- goreportcard.com: https://goreportcard.com/report/github.com/NVIDIA/gontainer
- coverage service link ([codecov](https://codecov.io/), [coveralls](https://coveralls.io/), etc.): no
_Not every repository (project) will require every option, but …
=> Add gontainer

README.md
- repo link (github.com, gitlab.com, etc): https://github.com/pipe-cd/pipecd
- pkg.go.dev: https://pkg.go.dev/github.com/pipe-cd/pipecd
- goreportcard.com: https://goreportcard.com/report/github.com/pipe-cd/pipecd
- coverage service link ([codecov](https://codecov.io/), [coveralls](https://coveralls.io/), etc.): https://app.codecov.io/gh/pipe-cd/pipecd
=> Add PipeCD

README.md
=> fix broken link (re2dfa)

README.md
- repo link (github.com, gitlab.com, etc): https://github.com/boot-go/boot
- pkg.go.dev: https://pkg.go.dev/github.com/boot-go/boot
- goreportcard.com: https://goreportcard.com/report/github.com/boot-go/boot
- coverage service link ([codecov](https://codecov.io/), [coveralls](https://coveralls.io/), etc.): https://htmlpreview.github.io/?https://gist.githubusercontent.com/boot-go/c77b22000b3e249510dfb4542847c708/raw/ae9b2e83e9a4adafed6da2160e40855f86ca58a8/cover.html#file0
_Not every repository (project) will require every option, but most projects should. Check the Contribution …
=> Added boot-go to dependency injection

README.md
repo https://github.com/erni27/mob has been deleted
=> remove mob

README.md
- repo link (github.com, gitlab.com, etc): https://github.com/stanipetrosyan/go-eventbus
- pkg.go.dev: https://pkg.go.dev/github.com/stanipetrosyan/go-eventbus
- goreportcard.com: https://goreportcard.com/report/github.com/stanipetrosyan/go-eventbus
- coverage service link ([codecov](https://codecov.io/), [coveralls](https://coveralls.io/), etc.): https://app.codecov.io/gh/stanipetrosyan/go-eventbus …
=> Add go-eventbus

README.md
Plinko is a finite state machine and workflow coordinator that compiles operations for extremely fast execution, workflow coordination and supports side-effect operations.  Plinko also auto-generates state digrams based on configuration for documentation purposes.  Plinko has received adoption well beyond Shipt and currently has more than 140 stars.
- repo link (github.com, gitlab.com, etc):  https://github.com/shipt/plinko
- pkg.go.dev: https://pkg.go.dev/github.com/shipt/plinko …
=> added plinko finite state machine and workflow orchestrator

README.md
- repo link (github.com, gitlab.com, etc): https://github.com/flannel-io/flannel
- pkg.go.dev: https://pkg.go.dev/github.com/xiaomaojames/flannel-io
- goreportcard.com:  https://goreportcard.com/report/github.com/flannel-io/flannel
- coverage service link ([codecov](https://codecov.io/), [coveralls](https://coveralls.io/), etc.):  …
=> Add Flannel

README.md
add a ClickHouse SQL client driver
- repo link (github.com, gitlab.com, etc): https://github.com/ClickHouse/clickhouse-go/
- pkg.go.dev: https://pkg.go.dev/github.com/ClickHouse/clickhouse-go/v2
- goreportcard.com: https://goreportcard.com/report/github.com/ClickHouse/clickhouse-go/v2
**Make sure that you've checked the boxes below that …
=> clickhouse-go client

README.md
- repo link: https://github.com/kdomanski/iso9660
- pkg.go.dev: https://pkg.go.dev/github.com/kdomanski/iso9660
- goreportcard.com: https://goreportcard.com/report/github.com/kdomanski/iso9660
- coverage service link: https://codecov.io/gh/kdomanski/iso9660
=> add iso9660

README.md
The aws-sdk-go version 2 is GA and recommended for new projects.
- pkg.go.dev:
Thanks for …
=> Updated aws-sdk-go to version 2

README.md
There is one permanent redirect and one broken link in the list. I've updated these two links.
=> Fix Oversight and GopherCon India links

README.md
- repo link (github.com, gitlab.com, etc): https://github.com/owenthereal/upterm
- pkg.go.dev: https://pkg.go.dev/github.com/owenthereal/upterm
- goreportcard.com: https://goreportcard.com/report/github.com/owenthereal/upterm
- coverage service link ([codecov](https://codecov.io/), [coveralls](https://coveralls.io/), etc.): coverage not tracked but tests are there https://github.com/owenthereal/upterm/actions/runs/6366320456/job/17283923361#step:4:758
**Make sure …
=> add upterm

README.md
Add energy
- repo link (github.com, gitlab.com, etc): https://github.com/energye/energy
- pkg.go.dev: https://pkg.go.dev/github.com/energye/energy/v2
- goreportcard.com: https://goreportcard.com/report/github.com/energye/energy/v2
- coverage service link ([codecov](https://codecov.io/), [coveralls](https://coveralls.io/), etc.): https://app.codecov.io/gh/energye/energy
_Not every …
=> Add energy

README.md
- repo link (github.com, gitlab.com, etc): [bin](https://github.com/gontainer/gontainer), [library](https://github.com/gontainer/gontainer-helpers)
- pkg.go.dev: [bin](https://pkg.go.dev/github.com/gontainer/gontainer), [library](https://pkg.go.dev/github.com/gontainer/gontainer-helpers)
- goreportcard.com: [bin](https://goreportcard.com/report/github.com/gontainer/gontainer), [library](https://goreportcard.com/report/github.com/gontainer/gontainer-helpers)
- coverage service link ([codecov](https://codecov.io/), [coveralls](https://coveralls.io/), …
=> Add gontainer/gontainer

README.md
- repo link (github.com, gitlab.com, etc): https://github.com/grafana/k6
- pkg.go.dev: https://pkg.go.dev/go.k6.io/k6
- goreportcard.com: https://goreportcard.com/report/go.k6.io/k6
- coverage service link ([codecov](https://codecov.io/), [coveralls](https://coveralls.io/), etc.): https://app.codecov.io/gh/grafana/k6
_Not every repository (project) will require every option, but most …
=> add grafana's k6 load testing tool

README.md
- repo link (github.com, gitlab.com, etc): https://github.com/kubernetes/minikube
- pkg.go.dev: https://pkg.go.dev/github.com/kubernetes/minikube
- goreportcard.com: https://goreportcard.com/report/github.com/kubernetes/minikube
_Not every repository (project) will require every option, …
=> Add minikube

README.md
=> Add "Go with the domain" Book by Three Dots Labs

README.md
- repo link (github.com, gitlab.com, etc): https://github.com/mk-5/fjira
- pkg.go.dev: https://pkg.go.dev/github.com/mk-5/fjira
- goreportcard.com: https://goreportcard.com/report/github.com/mk-5/fjira
- coverage service link ([codecov](https://codecov.io/), [coveralls](https://coveralls.io/), [gocover](http://gocover.io/) etc.): https://codecov.io/gh/mk-5/fjira 
⬆️ project has ~81% coverage when you run tests via cli, like: `go test -coverpkg=./... -covermode=count -coverprofile=coverage.out ./internal/...` - but via Codecov it got 77%
**Note**: …
=> Add fjira - fuzzy-find command line app for JIra

README.md
- repo link (github.com, gitlab.com, etc): https://github.com/opus-domini/fast-shot
- pkg.go.dev: https://pkg.go.dev/github.com/opus-domini/fast-shot
- goreportcard.com: https://goreportcard.com/report/github.com/opus-domini/fast-shot
- coverage service link ([codecov](https://codecov.io/), [coveralls](https://coveralls.io/), etc.): https://app.codecov.io/gh/opus-domini/fast-shot
_Not …
=> Add Fast-Shot

README.md
- repo link (github.com, gitlab.com, etc):https://github.com/lim-yoona/tcpack
- pkg.go.dev:https://pkg.go.dev/github.com/lim-yoona/tcpack
- goreportcard.com:https://goreportcard.com/report/github.com/lim-yoona/tcpack
- coverage service link ([codecov](https://codecov.io/), [coveralls](https://coveralls.io/), etc.):https://github.com/lim-yoona/tcpack/actions/runs/6465037269/job/17550588870#step:6:54 …
=> Add tcpack

README.md
This PR fix the typo that was present in `README.md` file.
```pseudo
plugable > pluggable
compability > compatibility
unmarshaling > unmarshalling
convinient > convenient
wirtten > written
utitlity > utility
fo > of
vaccum > vacuum
```
=> Chore: Typo fixed in README.md

README.md
- repo link (github.com, gitlab.com, etc): https://github.com/ipfs/kubo
- pkg.go.dev: https://pkg.go.dev/github.com/ipfs/kubo
- goreportcard.com: https://goreportcard.com/report/github.com/ipfs/kubo
- coverage service link ([codecov](https://codecov.io/), [coveralls](https://coveralls.io/), etc.): https://app.codecov.io/gh/ipfs/kubo …
=> Add kubo framework

README.md
- repo link (github.com, gitlab.com, etc): https://github.com/oracle/coherence-go-client
- pkg.go.dev: https://pkg.go.dev/github.com/oracle/coherence-go-client/coherence
- goreportcard.com: https://goreportcard.com/report/github.com/oracle/coherence-go-client
- coverage service link ([codecov](https://codecov.io/), [coveralls](https://coveralls.io/), etc.): WIP …
=> Add coherence-go-client

README.md
- repo link (github.com, gitlab.com, etc): https://github.com/mariocandela/beelzebub
- pkg.go.dev: https://pkg.go.dev/github.com/mariocandela/beelzebub/v3
- goreportcard.com: https://goreportcard.com/report/github.com/mariocandela/beelzebub/v3
- coverage service link ([codecov](https://codecov.io/), [coveralls](https://coveralls.io/), etc.): https://app.codecov.io/gh/mariocandela/beelzebub …
=> Add beelzebub

main.go
=> fix comment

README.md
Repository link:
https://github.com/cinar/checker
A link to the project's pkg.go.dev page 
https://pkg.go.dev/github.com/cinar/checker
A link to the project's Go Report Card report
https://goreportcard.com/report/github.com/cinar/checker
A link to a code coverage report
https://app.codecov.io/gh/cinar/checker
=> Adding Checker library to Forms section.

README.md
- repo link (github.com, gitlab.com, etc): https://github.com/Antonboom/testifylint
- pkg.go.dev: https://pkg.go.dev/github.com/Antonboom/testifylint
- goreportcard.com: https://goreportcard.com/report/github.com/Antonboom/testifylint
- coverage service link: https://coveralls.io/github/Antonboom/testifylint?branch=master
_Not every repository (project) will require every option, but …
=> Add testifylint

README.md
- repo link: https://github.com/golangci/golangci-lint
- pkg.go.dev: https://pkg.go.dev/github.com/golangci/golangci-lint
- goreportcard.com: https://goreportcard.com/report/github.com/golangci/golangci-lint …
=> Add golangci-lint

README.md
- repo link: https://github.com/mgechev/revive
- pkg.go.dev: https://pkg.go.dev/github.com/mgechev/revive
- goreportcard.com: https://goreportcard.com/report/github.com/mgechev/revive
=> Replace archived golint with revive

README.md
Adds templ to the Template Engines subsection of the README.
- repo link (github.com, gitlab.com, etc): https://github.com/a-h/templ
- pkg.go.dev: https://pkg.go.dev/github.com/a-h/templ
- goreportcard.com: https://goreportcard.com/report/github.com/a-h/templ …
=> Adds templ to README

README.md
syndfeed doesn't seem to be available
https://github.com/zhengchun/syndfeed
=> Removed syndfeed

README.md
Add [Maddy](https://maddy.email/) emails server
- repo link (github.com, gitlab.com, etc): https://github.com/foxcpp/maddy
- pkg.go.dev: https://pkg.go.dev/github.com/foxcpp/maddy
- goreportcard.com: https://goreportcard.com/report/github.com/foxcpp/maddy
- coverage service link ([codecov](https://codecov.io/), [coveralls](https://coveralls.io/), etc.): n/a …
=> Add Maddy email server

README.md
- repo link (github.com, gitlab.com, etc): https://gitlab.com/tozd/go/errors
- pkg.go.dev: https://pkg.go.dev/gitlab.com/tozd/go/errors
- goreportcard.com: https://goreportcard.com/report/gitlab.com/tozd/go/errors
- coverage service link ([codecov](https://codecov.io/), [coveralls](https://coveralls.io/), etc.): https://gitlab.com/tozd/go/errors/-/graphs/main/charts
=> Add gitlab.com/tozd/go/errors

README.md
- pkg.go.dev: https://pkg.go.dev/bitbucket.org/rj/goey
- goreportcard.com: https://goreportcard.com/report/bitbucket.org/rj/goey
I have no idea sorry
_Not every repository (project) will require every option, but most projects should. Check the …
=> Goey added.

README.md
- repo link (github.com, gitlab.com, etc):https://github.com/raszia/gotiny
- pkg.go.dev:https://pkg.go.dev/github.com/raszia/gotiny?utm_source=godoc
- goreportcard.com:https://goreportcard.com/report/github.com/raszia/gotiny
- coverage service link ([codecov](https://codecov.io/), [coveralls](https://coveralls.io/), etc.):https://app.codecov.io/gh/raszia/gotiny …
=> add gotiny

README.md
**Please provide package links to:** 
- repo link (github.com, gitlab.com, etc): https://github.com/g4s8/envdoc
- pkg.go.dev: https://pkg.go.dev/github.com/g4s8/envdoc
- goreportcard.com: https://goreportcard.com/report/github.com/g4s8/envdoc
- coverage service link: [codecov](https://app.codecov.io/gh/g4s8/envdoc/)
_Not every repository (project) will require every option, but most projects should. Check the Contribution …
=> Add envdoc

README.md
Adds an new AI category with some initial entries.
=> Add AI category, some initial entries.

README.md
- repo link (github.com, gitlab.com, etc): https://github.com/zitadel/passwap
- pkg.go.dev: https://pkg.go.dev/github.com/zitadel/passwap
- goreportcard.com: https://goreportcard.com/report/github.com/zitadel/passwap
- coverage service link ([codecov](https://codecov.io/), [coveralls](https://coveralls.io/), etc.): https://app.codecov.io/gh/zitadel/passwap …
=> add passwap (security)

README.md
- repo link (github.com, gitlab.com, etc): https://github.com/trpc-group/trpc-go
- pkg.go.dev: https://pkg.go.dev/trpc.group/trpc-go/trpc-go
- goreportcard.com: https://goreportcard.com/report/trpc.group/trpc-go/trpc-go
- coverage service link ([codecov](https://codecov.io/), [coveralls](https://coveralls.io/), etc.): https://app.codecov.io/gh/trpc-group/trpc-go/tree/main
_Not every …
=> README: add trpc-go package to the Distributed Systems list

.github/workflows/pull-request-first-comment.yaml
This PR suggests a few small tweaks (for grammar and accuracy) to the wording in the PR comment added by the "first comment" GitHub Action.
=> Wording tweaks to the PR comment added by the first-comment GH Action

README.md
- repo link (github.com, gitlab.com, etc): https://github.com/jvcoutinho/lit
- pkg.go.dev: https://pkg.go.dev/github.com/jvcoutinho/lit
- goreportcard.com: https://goreportcard.com/report/github.com/jvcoutinho/lit
- coverage service link ([codecov](https://codecov.io/), [coveralls](https://coveralls.io/), etc.): https://app.codecov.io/github/jvcoutinho/lit …
=> Add Lit to README's Web Frameworks section

README.md
- repo link (github.com, gitlab.com, etc): [https://github.com/zhufuyi/sponge](https://github.com/zhufuyi/sponge)
- pkg.go.dev: [https://pkg.go.dev/github.com/zhufuyi/sponge](https://pkg.go.dev/github.com/zhufuyi/sponge)
- goreportcard.com: [https://goreportcard.com/report/github.com/zhufuyi/sponge](https://goreportcard.com/report/github.com/zhufuyi/sponge)
- coverage service link ([codecov](https://codecov.io/), [coveralls](https://coveralls.io/), etc.): [https://codecov.io/gh/zhufuyi/sponge](https://codecov.io/gh/zhufuyi/sponge)
**Note**: _that new …
=> add sponge

README.md
- repo link (github.com, gitlab.com, etc): https://github.com/nar10z/go-accumulator
- pkg.go.dev: https://pkg.go.dev/github.com/nar10z/go-accumulator
- goreportcard.com: https://goreportcard.com/report/github.com/nar10z/go-accumulator
- coverage service link ([codecov](https://codecov.io/), [coveralls](https://coveralls.io/), etc.): https://app.codecov.io/gh/nar10z/go-accumulator
_Not …
=> add go-accumulator

README.md
- Repo link: https://github.com/Pixboost/transformimgs
- pkg.go.dev: https://pkg.go.dev/github.com/Pixboost/transformimgs/v8
- goreportcard.com: https://goreportcard.com/report/github.com/Pixboost/transformimgs/v8
- coverage service link ([codecov](https://codecov.io/), [coveralls](https://coveralls.io/), etc.): https://app.codecov.io/gh/Pixboost/transformimgs …
=> Added transformimgs to images section

README.md
- repo link (github.com, gitlab.com, etc): https://github.com/elastic/go-freelru
- pkg.go.dev: https://pkg.go.dev/github.com/elastic/go-freelru
- goreportcard.com: https://goreportcard.com/report/github.com/elastic/go-freelru
- coverage service link ([codecov](https://codecov.io/), [coveralls](https://coveralls.io/), etc.): https://coveralls.io/github/elastic/go-freelru?branch=main …
=> Add go-freelru

README.md
- repo link (github.com, gitlab.com, etc): https://github.com/bobg/decouple
- pkg.go.dev: https://pkg.go.dev/github.com/bobg/decouple
- goreportcard.com: https://goreportcard.com/report/github.com/bobg/decouple
- coverage service link ([codecov](https://codecov.io/), [coveralls](https://coveralls.io/), etc.): https://coveralls.io/github/bobg/decouple?branch=main …
=> Add decouple.

README.md
- repo link (github.com, gitlab.com, etc): https://github.com/tarmac-project/tarmac
- pkg.go.dev: https://pkg.go.dev/github.com/tarmac-project/tarmac/pkg/sdk
- goreportcard.com: https://goreportcard.com/report/github.com/tarmac-project/tarmac
- coverage service link ([codecov](https://codecov.io/), [coveralls](https://coveralls.io/), etc.): https://app.codecov.io/gh/tarmac-project/tarmac …
=> Add Tarmac

README.md
- repo link (github.com, gitlab.com, etc): https://github.com/mr-linch/go-tg
- pkg.go.dev: https://pkg.go.dev/github.com/mr-linch/go-tg
- goreportcard.com: https://goreportcard.com/report/github.com/mr-linch/go-tg
- coverage service link ([codecov](https://codecov.io/), [coveralls](https://coveralls.io/), etc.): https://app.codecov.io/gh/mr-linch/go-tg …
=> Add `go-tg` 

README.md
- repo link (github.com, gitlab.com, etc): https://github.com/go-kod/kod
- pkg.go.dev: [pkg.go.dev/github.com/go-kod/kod](https://pkg.go.dev/github.com/go-kod/kod)
- goreportcard.com: https://goreportcard.com/report/github.com/go-kod/kod
- coverage service link ([codecov](https://codecov.io/), [coveralls](https://coveralls.io/), etc.): https://app.codecov.io/github/go-kod/kod
_Not …
=> Add go-kod

README.md
- repo link (github.com, gitlab.com, etc): https://github.com/rhosocial/go-dag
- pkg.go.dev: https://pkg.go.dev/github.com/rhosocial/go-dag
- goreportcard.com: https://goreportcard.com/report/github.com/rhosocial/go-dag
- coverage service link ([codecov](https://codecov.io/), [coveralls](https://coveralls.io/), etc.): https://app.codecov.io/gh/rhosocial/go-dag/tree/r1.0
_Not every …
=> Add `go-dag`

README.md
- repo link (github.com, gitlab.com, etc): https://github.com/fogfish/dynamo
- pkg.go.dev: https://pkg.go.dev/github.com/fogfish/dynamo/v3
- goreportcard.com: https://goreportcard.com/report/github.com/fogfish/dynamo/v3
- coverage service link ([coveralls](https://coveralls.io/), etc.): https://coveralls.io/github/fogfish/dynamo?branch=main
_Not every repository (project) will require every option, but most projects should. Check the Contribution Guidelines for …
=> Add dynamo - key-value abstraction over AWS services

README.md
- repo link (github.com, gitlab.com, etc): https://github.com/aliexpressru/gomemcached
- pkg.go.dev: https://pkg.go.dev/github.com/aliexpressru/gomemcached
- goreportcard.com: https://goreportcard.com/report/github.com/aliexpressru/gomemcached
- coverage service link ([codecov](https://codecov.io/), [coveralls](https://coveralls.io/), etc.): Generated a badge as part of a continuous integration process: [coverage badge](https://github.com/aliexpressru/gomemcached/blob/main/README.md?plain=1#L11)
**Note**: _that new categories can be added only when …
=> Add gomemcached

README.md
- repo link (github.com, gitlab.com, etc): https://gitlab.com/cosban/di
- pkg.go.dev: https://pkg.go.dev/gitlab.com/cosban/di/v2
- goreportcard.com: https://goreportcard.com/report/gitlab.com/cosban/di/v2
- coverage service link: https://app.codecov.io/gl/cosban/di
_Not every repository (project) will require every option, but most projects should. Check the Contribution Guidelines for …
=> add cosban/di to the dependency injection category

README.md
- repo link (github.com, gitlab.com, etc): https://github.com/saleh-rahimzadeh/go-words
- pkg.go.dev: https://pkg.go.dev/github.com/saleh-rahimzadeh/go-words
- goreportcard.com: https://goreportcard.com/report/github.com/saleh-rahimzadeh/go-words
- coverage service link ([codecov](https://codecov.io/), [coveralls](https://coveralls.io/), etc.): https://codecov.io/gh/saleh-rahimzadeh/go-words …
=> Add go-words

README.md
I added one link to a serie of articles explaining Go visually.
=> readme: add go in a visual way

README.md
- repo link (github.com, gitlab.com, etc):https://github.com/deatil/go-datebin
- pkg.go.dev:https://pkg.go.dev/github.com/deatil/go-datebin
- goreportcard.com:https://goreportcard.com/report/github.com/deatil/go-datebin
- coverage service link ([codecov](https://codecov.io/), [coveralls](https://coveralls.io/), etc.):https://app.codecov.io/gh/deatil/go-datebin …
=> add go-datebin

README.md
- repo link (github.com, gitlab.com, etc): https://github.com/LimeChain/gosemble.git
- pkg.go.dev: https://pkg.go.dev/github.com/LimeChain/gosemble
- goreportcard.com: https://goreportcard.com/report/github.com/LimeChain/gosemble
- coverage service link ([codecov](https://codecov.io/), [coveralls](https://coveralls.io/), etc.): https://app.codecov.io/github/LimeChain/gosemble
_Not …
=> Add Gosemble

README.md
- repo link: https://codeberg.org/pfad.fr/swift
- pkg.go.dev: https://pkg.go.dev/code.pfad.fr/swift (documentation is also self-hosted: https://code.pfad.fr/swift/)
- goreportcard.com: https://goreportcard.com/report/code.pfad.fr/swift
- coverage service link: the CI checks that the reachable code has 80%+ test coverage https://codeberg.org/pfad.fr/swift/src/branch/main/Makefile#L12
=> Add code.pfad.fr/swift

README.md
- repo link (github.com, gitlab.com, etc): https://github.com/firasdarwish/ore
- pkg.go.dev: https://pkg.go.dev/github.com/firasdarwish/ore
- goreportcard.com: https://goreportcard.com/report/github.com/firasdarwish/ore
- coverage service link ([codecov](https://codecov.io/), [coveralls](https://coveralls.io/), etc.): https://codeclimate.com/github/firasdarwish/ore
=> Add ore package

README.md
[go-lambda-cleanup](https://github.com/karl-cardenas-coding/go-lambda-cleanup)
- repo link (github.com, gitlab.com, etc): https://github.com/karl-cardenas-coding/go-lambda-cleanup
- pkg.go.dev: https://pkg.go.dev/github.com/karl-cardenas-coding/go-lambda-cleanup/v2
- goreportcard.com: https://goreportcard.com/report/github.com/karl-cardenas-coding/go-lambda-cleanup/v2
- coverage service link: https://app.codecov.io/gh/karl-cardenas-coding/go-lambda-cleanup …
=> Add go-lambda-cleanup

README.md
- repo link (github.com, gitlab.com, etc): https://github.com/gogf/gf
- pkg.go.dev: https://pkg.go.dev/github.com/gogf/gf/v2#section-readme
- coverage service link ([codecov](https://codecov.io/), [coveralls](https://coveralls.io/), etc.):  https://app.codecov.io/gh/gogf/gf …
=> Update description of GoFrame

README.md
Hi,
Stjepan from Manning here. I thought this title might be a good match for your list. Thank you for considering it.
Best,
- pkg.go.dev: …
=> Added Go in Practice, Second Edition

README.md
=> Added github.com/taubyte/tau to the DevOps category

README.md
- repo link (github.com, gitlab.com, etc): https://github.com/openfga/openfga
- pkg.go.dev: https://pkg.go.dev/github.com/openfga/openfga
- goreportcard.com: https://goreportcard.com/report/github.com/openfga/openfga
- coverage service link ([codecov](https://codecov.io/), [coveralls](https://coveralls.io/), etc.): https://app.codecov.io/gh/openfga/openfga …
=> add openfga

README.md
- repo link (github.com, gitlab.com, etc): https://github.com/kubenetworks/kubevpn
- pkg.go.dev: https://pkg.go.dev/github.com/wencaiwulue/kubevpn
- goreportcard.com: https://goreportcard.com/report/github.com/wencaiwulue/kubevpn
- coverage service link ([codecov](https://codecov.io/), [coveralls](https://coveralls.io/), etc.): https://app.codecov.io/gh/wencaiwulue/kubevpn
_Not every …
=> Add kubevpn

README.md
- repo link (github.com, gitlab.com, etc): https://github.com/Boeing/config-file-validator
- pkg.go.dev: https://pkg.go.dev/github.com/Boeing/config-file-validator
- goreportcard.com: https://goreportcard.com/report/github.com/Boeing/config-file-validator
- coverage service link ([codecov](https://codecov.io/), [coveralls](https://coveralls.io/), etc.): Badge on README
_Not every …
=> Add config-file-validator

README.md
- https://github.com/ip2location/ip2location-io-go
- pkg.go.dev:
- https://pkg.go.dev/github.com/ip2location/ip2location-io-go
- https://goreportcard.com/report/github.com/ip2location/ip2location-io-go
- https://app.codecov.io/gh/ip2location/ip2location-io-go …
=> Added IP2Location.io Go SDK

README.md
- repo link: https://github.com/navidys/gopensky
- pkg.go.dev: https://pkg.go.dev/github.com/navidys/gopensky
- goreportcard.com: https://goreportcard.com/report/github.com/navidys/gopensky
- coverage service link : https://app.codecov.io/gh/navidys/gopensky
=> Add gopensky (go client for opensky network live's API)

README.md
Go Faster has an optional payment, it is possible to get this e-book without payment.
- [ X ] I have read the [Contribution Guidelines](https://github.com/avelino/awesome-go/blob/main/CONTRIBUTING.md#contribution-guidelines)
- [ X ] I have read the [Maintainers Note](https://github.com/avelino/awesome-go/blob/main/CONTRIBUTING.md#maintainers)
- [ X ] I have read the [Quality Standards](https://github.com/avelino/awesome-go/blob/main/CONTRIBUTING.md#quality-standards)
- [ X ] The package has been added to the list in alphabetical order.
- [ X ] The package has an appropriate description with correct grammar.
- [ X ] As far as I know, the package has not been …
=> fix: move Go Faster to the Free e-books section

README.md
=> adding Wave Terminal to the tools list

README.md
=> add natiu-mqtt

README.md
=> update README - meetups section

README.md
=> docs(networking): add fwdctl project

README.md
=> add hvalid project

README.md
- repo link (github.com, gitlab.com, etc): https://github.com/asticode/go-astiav
- pkg.go.dev: https://pkg.go.dev/github.com/asticode/go-astiav
- goreportcard.com: https://goreportcard.com/report/github.com/asticode/go-astiav
- coverage service link ([codecov](https://codecov.io/), [coveralls](https://coveralls.io/), etc.): https://coveralls.io/github/asticode/go-astiav
_Not every …
=> Add go-astiav

README.md
=> Add go-semver-release project under continuous integration

README.md
- repo link (github.com, gitlab.com, etc): https://github.com/wa-lang/wa
- pkg.go.dev:
- goreportcard.com: https://goreportcard.com/report/github.com/wa-lang/wa
- coverage service link ([codecov](https://codecov.io/), [coveralls](https://coveralls.io/), [gocover](http://gocover.io/) etc.): https://coveralls.io/github/wa-lang/wa
_Not every repository (project) will require every option, …
=> add wa language

README.md
=> add go-beautiful-html-coverage

README.md
=> add pebble

README.md
=> add wescale

README.md
=> add kubeblocks

README.md
=> restructure testing category

README.md
=> Adding testcerts to Testing Section 

README.md
=> Add Spot: a reactive, cross-platform desktop GUI toolkit.

README.md
=> add pocketbase to Authentication and OAuth

README.md
=> add go-array

README.md
including the Go SDK from the Extism project, https://extism.org
- repo link (github.com, gitlab.com, etc): https://github.com/extism/go-sdk
- pkg.go.dev: https://pkg.go.dev/github.com/extism/go-sdk
- goreportcard.com: https://goreportcard.com/report/github.com/extism/go-pdk
=> feat: add extism go-sdk

README.md
Note: This is not a package I maintain, but I believe it meets the qualifications for inclusion on this list.
=> Add goal embeddable scripting language

README.md
=> Add go-mongox

README.md
=> Add EchoVault to Database, Caches

README.md
=> Add sturdyc

README.md
- [go-sptrans](https://github.com/sergioaugrod/go-sptrans) - No release since 2017, and the documentation says it is no longer maintained @sergioaugrod 
- [go-redoc](https://github.com/mvrilo/go-redoc) - No stable v1.0.0 release, and no code coverage link @mvrilo 
=> add go-salesforce under Third-party APIs category

README.md
=> Add failsafe-go

README.md
=> Add go-blueprint quick create project tool

README.md
_Most of the code is generated so we don't make tests for it._
=> Add DarwinKit

README.md
=> Add github.com/romshark/yamagiconf

README.md
=> Add xgzlucario/rotom

README.md
=> Add godump

README.md
- repo link (github.com, gitlab.com, etc): https://cs.opensource.google/go/x/net
- pkg.go.dev: https://pkg.go.dev/golang.org/x/net
- goreportcard.com: https://goreportcard.com/report/golang.org/x/net
_Not every repository (project) will require every option, …
=> add net in networking

README.md
=> Add go-csvlib

README.md
=> Add go-validator

README.md
=> feat: add ecs

README.md
- pkg.go.dev:
- [ x] I have read the [Contribution …
=> Added Last Commit Badge

README.md
Please note that this test coverage, while unideal, is similar to many of the other GUI packages in awesome go.
=> Add Cogent Core

README.md
This PR fixes a small bug related to markdown syntax.
=> feat (md syntax): Fix inappropriate space between link label and url

README.md
- repo link: https://github.com/pemistahl/lingua-go
- pkg.go.dev: https://pkg.go.dev/github.com/pemistahl/lingua-go
- goreportcard.com: https://goreportcard.com/report/github.com/pemistahl/lingua-go
- coverage service link: https://app.codecov.io/gh/pemistahl/lingua-go
_Not every repository (project) will require every option, but most projects should. Check the Contribution Guidelines …
=> Add lingua-go library

README.md
- [ x] I have read the [Contribution Guidelines](https://github.com/avelino/awesome-go/blob/main/CONTRIBUTING.md#contribution-guidelines)
- [ x] I have read the [Maintainers Note](https://github.com/avelino/awesome-go/blob/main/CONTRIBUTING.md#maintainers)
- [ x] I have read the [Quality Standards](https://github.com/avelino/awesome-go/blob/main/CONTRIBUTING.md#quality-standards)
- [ x] The repo documentation has a pkg.go.dev link.
- [ x] The repo has a version-numbered release and a go.mod file.
- [ x] forge link (github.com, gitlab.com, etc): https://github.com/arunsupe/semantic-grep
- [ x] pkg.go.dev: https://pkg.go.dev/github.com/arunsupe/semantic-grep
- …
=> Add w2vgrep to the list of utilities

README.md
- repo link (github.com, gitlab.com, etc): https://github.com/SimonWaldherr/golang-benchmarks
- pkg.go.dev: is no package, has no documentation 
- goreportcard.com: https://goreportcard.com/report/github.com/SimonWaldherr/golang-benchmarks
- coverage service link ([codecov](https://codecov.io/), [coveralls](https://coveralls.io/), [gocover](http://gocover.io/) etc.): is no package, has no test coverage  …
=> add github.com/SimonWaldherr/golang-benchmarks

README.md
- repo link (github.com, gitlab.com, etc): https://github.com/rekby/fastuuid
- pkg.go.dev: https://pkg.go.dev/github.com/rekby/fastuuid
- goreportcard.com: https://goreportcard.com/report/github.com/rekby/fastuuid
- coverage service link ([codecov](https://codecov.io/), [coveralls](https://coveralls.io/), etc.): https://codecov.io/gh/rekby/fastuuid …
=> add https://github.com/rekby/fastuuid

README.md
- repo link (github.com, gitlab.com, etc): https://github.com/mochi-co/mqtt
- pkg.go.dev: https://pkg.go.dev/github.com/mochi-co/mqtt/v2
- goreportcard.com: https://goreportcard.com/report/github.com/mochi-co/mqtt/v2
- coverage service link ([codecov](https://codecov.io/), [coveralls](https://coveralls.io/), [gocover](http://gocover.io/) etc.): https://coveralls.io/github/mochi-co/mqtt?branch=master …
=> Add Mochi MQTT

README.md
=> Add sonic library for JSON manipulation

README.md
- repo link (github.com, gitlab.com, etc): https://github.com/42Atomys/webhooked
- pkg.go.dev: https://pkg.go.dev/atomys.codes/webhooked
- goreportcard.com: https://goreportcard.com/report/atomys.codes/webhooked
- coverage service link ([codecov](https://codecov.io/), [coveralls](https://coveralls.io/), [gocover](http://gocover.io/) etc.): https://app.codecov.io/gh/42Atomys/webhooked …
=> docs: add webhooked to networking listing

README.md
=> Mention luks.go - a library to manage LUKS encrypted partitions

README.md
Hi everyone, Sprig are a templating package unmaintained and not updated as all, sprout are the replacement of the package, following references:
- [Last commit on Nov 2022](https://github.com/Masterminds/sprig/commits/master/)
- https://github.com/Masterminds/sprig/issues/396 _No response since 6 months_
- [Motivation of Sprout (new)](https://github.com/go-sprout/sprout?tab=readme-ov-file#motivation)
=> replace sprig (unmaintained) with go-sprout/sprout (replacement)

README.md
=> Add actor model libraries

README.md
- Note: library has less than 80% (but higher than 70%) code coverage because it is integrating many external APIs where it is hard to test all the error paths which bring the coverage down.
=> Add gitlab.com/tozd/go/fun package

README.md
- repo link (github.com, gitlab.com, etc): https://github.com/lvyahui8/goenum
- pkg.go.dev: https://pkg.go.dev/github.com/lvyahui8/goenum#section-readme
- goreportcard.com: https://goreportcard.com/report/github.com/lvyahui8/goenum
- coverage service link ([codecov](https://codecov.io/), [coveralls](https://coveralls.io/), etc.): https://app.codecov.io/gh/lvyahui8/goenum
_Not every …
=> Add goenum

README.md
- repo link (github.com, gitlab.com, etc): https://github.com/cshum/imagor
- pkg.go.dev: https://pkg.go.dev/github.com/cshum/imagor
- goreportcard.com: https://goreportcard.com/report/github.com/cshum/imagor
- coverage service link ([codecov](https://codecov.io/), [coveralls](https://coveralls.io/), [gocover](http://gocover.io/) etc.): https://coveralls.io/github/cshum/imagor
_Not …
=> Add cshum/imagor 

README.md
- repo link (github.com, gitlab.com, etc): https://github.com/xjasonlyu/tun2socks
- pkg.go.dev: https://pkg.go.dev/github.com/xjasonlyu/tun2socks/v2
- goreportcard.com: https://goreportcard.com/report/github.com/xjasonlyu/tun2socks/v2
- coverage service link ([codecov](https://codecov.io/), [coveralls](https://coveralls.io/), etc.): N/A
_Not every repository (project) will require …
=> Add tun2socks to Networking

README.md
=> Add Alaz - Effortless, Low-Overhead, eBPF-based Kubernetes Monitoring

README.md
- Report output: https://github.com/gomlx/gomlx/blob/main/docs/coverage.out
- Report generating script: https://github.com/gomlx/gomlx/blob/main/cmd/run_coverage.sh
=> Added GoMLX entry to Machine Learning section.

README.md
=> Add GatewayD

README.md
- repo link (github.com, gitlab.com, etc): https://github.com/SimonWaldherr/golang-examples
- pkg.go.dev: https://pkg.go.dev/github.com/SimonWaldherr/golang-examples
- goreportcard.com: https://goreportcard.com/report/github.com/simonwaldherr/golang-examples
- coverage service link ([codecov](https://codecov.io/), [coveralls](https://coveralls.io/), [gocover](http://gocover.io/) etc.): no  …
=> add SimonWaldherr/golang-examples

README.md
This PR only fixes order issues caused by last merged PR (#4494 )
=> Fix order issue

README.md
- repo link (github.com, gitlab.com, etc): https://github.com/hasura/learn-graphql/blob/master/tutorials/backend/backend-stack/tutorial-site/content/languages/go.md
=> add GraphQL with Go tutorial

README.md
:wave: I would like to clarify some details about the project, which will help to quickly consider this PR:
If you are checking code quality manually, please be aware that we use special utilities to develop this package and run tests. Tests won't work without them. 
They run from the command line and require Python (the docker file with the Python version is in  https://github.com/componego/componego/tree/master/scripts)
`make tests` - run all tests
`make tests-cover` - run all tests with test coverage
`make lint` - run linters
`make security` - run security checks
The same utilities are launched via GitHub Actions.
Thank you!
_Note that new categories can …
=> Add Componego

README.md
=> Add DI autowire

README.md
=> doc: add wrapcheck linter

README.md
- repo link (github.com, gitlab.com, etc): https://github.com/gnolang/gno
- pkg.go.dev: https://pkg.go.dev/github.com/gnolang/gno
- goreportcard.com: https://goreportcard.com/report/github.com/gnolang/gno
- coverage service link ([codecov](https://codecov.io/), [coveralls](https://coveralls.io/), etc.): https://app.codecov.io/gh/gnolang/gno
=> feat: add Blockchain/gno

README.md
- repo link (github.com, gitlab.com, etc): https://github.com/jeroenrinzema/psql-wire
- pkg.go.dev: https://pkg.go.dev/github.com/jeroenrinzema/psql-wire
- goreportcard.com: https://goreportcard.com/report/github.com/jeroenrinzema/psql-wire
- coverage service link ([codecov](https://codecov.io/), [coveralls](https://coveralls.io/), [gocover](http://gocover.io/) etc.) n/a:
_Not every …
=> add jeroenrinzema/psql-wire

README.md
- repo link (github.com, gitlab.com, etc): https://github.com/slack-io/slacker
- pkg.go.dev: https://godoc.org/github.com/slack-io/slacker
- goreportcard.com: https://goreportcard.com/report/github.com/slack-io/slacker …
=> Update Slacker Repo name after moving to a Github Organization

README.md
Mox is a modern full-featured open source secure mail server for low-maintenance self-hosted email. It implements IMAP, SMTP, SPF, DKIM, DMARC, TLSRPT, MTA-STS and more.
- repo link (github.com, gitlab.com, etc): https://github.com/mjl-/mox
- pkg.go.dev: https://pkg.go.dev/github.com/mjl-/mox
- goreportcard.com: https://goreportcard.com/report/github.com/mjl-/mox
- coverage service link ([codecov](https://codecov.io/), [coveralls](https://coveralls.io/), etc.): Tests are run in a github action, with the coverage HTML file as an artifact. E.g. …
=> Add github.com/mjl-/mox, a modern email server

README.md
Add alternatives since they are very useful https://github.com/lycheeverse/lychee#features
=> add muffet and alternatives

README.md
- [ x] The package has been added to the list in alphabetical order.
- [ x] The package has an appropriate description with correct grammar.
- [ X] As far as I know, the package has not been listed here before.
=> added godocx

README.md
=> Update README.md, added Poly to Science section

README.md
- repo link (github.com, gitlab.com, etc): https://github.com/go-hep/hep
- pkg.go.dev: https://pkg.go.dev/go-hep.org/x/hep
- goreportcard.com: https://goreportcard.com/report/go-hep.org/x/hep
- coverage service link ([codecov](https://codecov.io/), [coveralls](https://coveralls.io/), [gocover](http://gocover.io/) etc.): https://codecov.io/gh/go-hep/hep …
=> add go-hep

README.md
=> Add hypermatch

README.md
=> Add cimgui-go

README.md
=> Add keilerkonzept/topk

README.md
- repo link (github.com, gitlab.com, etc): https://github.com/hedhyw/json-log-viewer
- pkg.go.dev: not relevant
- goreportcard.com: [![Go Report Card](https://goreportcard.com/badge/github.com/hedhyw/json-log-viewer)](https://goreportcard.com/report/github.com/hedhyw/json-log-viewer)
- coverage service link ([codecov](https://codecov.io/), [coveralls](https://coveralls.io/), etc.): [![Coverage Status](https://coveralls.io/repos/github/hedhyw/json-log-viewer/badge.svg?branch=main)](https://coveralls.io/github/hedhyw/json-log-viewer?branch=main) …
=> feat: add interactive viewer for JSON logs

README.md
=> Add goxygen

README.md
* [nut](https://github.com/owenthereal/nut) - I removed because there hasn't been a PR or release since 2015/2016, there is no documentation for this package in pkg.go.dev, and it doesn't look like it's been imported in any Go projects or packages.
=> Add syft to Awesome-Go Package Management section

README.md
…tygopher
**_I recently decided to consolidate my Go projects under a new GH org github.com/naughtygopher_**
=> chore: update the link of packages to new GH org, bnkamalesh to naughtygopher

README.md
=> add hatchet

README.md
=> Fix to https scheme

README.md
=> Add udecimal

README.md
I work at LabEx, a unique learning platform that has offered Linux and Programming hands-on labs for 7 years. Thanks for this excellent repository. Please let me know if any changes are needed.
=> Add Go skill tree to Guided Learning section

README.md
A foundational and practical guide for effectively learning the fundamental blockchain concepts and progressively building a blockchain from scratch in Go with gRPC. An interesting and challenging adventure that takes you from the foundational concepts and purpose through the technical design and implementation to the practical testing and usage of the proposed blockchain
Packages added a long time ago might not meet the current guidelines anymore. It would be very helpful if you could check 3-5 packages above and below your submission to ensure that they also still meet the …
=> book: add Build a blockchain from scratch in Go with gRPC

README.md
=> Added Cloudflared to Networking

README.md
=> Add QRCode Generator

README.md
=> Add Golang nugget

README.md
> Deleted remember-go as it seems unmaintained. It has issues which are not addressed for a long time, no CI checks, no coverage report.
=> removed remember-go

README.md
The gnatsd project is outdated, this replaces it with the correct link
> not sure that outboxer meets requirements, but I'm not comfortable removing it from the list.
=> Update NATS Entry

README.md
This updates the import path, and description for nats.go
> Some of the packages around my change haven't been touched in many years, but I'm not comfortable removing them from the list.
=> Update NATS Go Client Entry

README.md
=> Adding go-gerrit - Go cient library for Gerrit Code Review

README.md
=> Added vdf - A Lexer and Parser for Valves Data Format (known as vdf) written in Go

README.md
=> add fatcontext

CONTRIBUTING.md, README.md
This PR adds a new rule to contributing guide:
>Projects must have al least 5 months of history since their first commit
=> contributing guide: add 5-month maturity quality standard.

README.md
-[x] I removed the following packages around my addition: (please give a short reason for each removal)
**gospin** - not updated in over 5 years, very little usage
=> add htmgo.dev

README.md
=> revise go-taskflow desc

README.md
* [gst](https://github.com/ziutek/gst) - Go bindings for GST has not been updated for several years,
lacks go.mod file and also says "Retired. I don't use/develop this package anymore."
* [libgosubs](https://github.com/wargarblgarbl/libgosubs)  has not been updated for 6 years and lacks go.mod file …
=> Add github.com/Eyevinn/mp4ff repo

README.md
=> added bed to utilities

README.md
=> add goiabada

README.md
The strcase and bytcase libraries provide efficient case-insensitive search functions that are Unicode aware and are a drop-in replacement for the strings/bytes packages.
Docs: https://pkg.go.dev/github.com/charlievieth/strcase@master
Report: https://goreportcard.com/report/github.com/charlievieth/strcase
Coverage: https://app.codecov.io/github/charlievieth/strcase
- **NB:** I can add a link to the [goreportcard](https://goreportcard.com/report/github.com/charlievieth/strcase), but never thought it necessary considering how exhaustive/exacting the current CI tests are.
Packages …
=> Add strcase

README.md
=> Added Bifröst

README.md
=> Update golang-nugget newsletter address

README.md
=> Add kickstart.go

README.md
Remove: https://github.com/alxrm/ugo (Archived)
=> Remove: alxrm/ugo

README.md
Remove: https://github.com/contextplus/contextplus (404)
=> Remove:  https://github.com/contextplus/contextplus

README.md
add package bart, this is a modified routing algorithm, based on Donald Knuth's ART (Allotment Routing Table), but balanced in terms of memory consumption versus lookup time.
=> add package bart under Networking, providing a fast routing algorithm

README.md
Remove: https://github.com/mjibson/esc (archived)
=> remove: https://github.com/mjibson/esc

README.md
=> Add go-eagle framework

README.md
Hi, I just changed my github username from `creativecreature` to `viccon` and would like to update the path to `sturdyc`
=> Update sturdyc path

README.md
This PR adds [Chapar](https://github.com/chapar-rest/chapar)  to other softwares section. Chapar is build with go (gioui framework) and provides functionality similar to Postman.
=> Add Chapar

README.md
=> added go-enum-encoding

README.md
=> add tls-client

README.md
=> Added entpassgen

README.md
=> Add Noooste/azuretls-client

README.md
Remove: https://github.com/dtm-labs/dtf (archived)
=> Remove: https://github.com/dtm-labs/dtf

README.md
- Thanks for your PR, you're awesome! :sunglasses:
=> add package neilotoole/sq

README.md
=> add pashagolub/pgxmock

README.md
=> Added Golang Roma to Meetups section

README.md
=> Added Golang Torino to Meetups section

README.md
=> Added Golang Milano to Meetups section

README.md
I come from a gitlab pipeline world, where third-parties aren't used. So I [wrote my own testing pipeline](https://github.com/baalimago/simple-go-pipeline/blob/main/.github/workflows/validate.yml) which [sets the test coverage](https://github.com/baalimago/wd-41/actions/runs/11615869697/job/32347484803) resulting in [updated readme's](https://github.com/baalimago/wd-41/commit/23acfa030c9ecfb0391338360d7cc8a2c9b57223) without the need of registering anywhere externally. 
Packages added a long time ago might not meet the current guidelines anymore. It would be very helpful if you …
=> Added entry for wd-41

README.md
- tcpprobe: The last commit was 5 years ago and it is missing pkg.go.dev link in its readme.
- term-quiz: The last commit was 8 years ago and its test coverage is 43%
=> Adding tinycare-tui to Other Software

README.md
=> add package sqlite

README.md
=> chore: add goblin.run

README.md
=> added axios4go

README.md
Ideally the historically useful among these could be moved to ARCHIVED.md or so.
But for now I don't have any such plans.
=> remove a few archived repos

README.md
=> Add elazarl/goproxy library

README.md
=> Added RBAC Tutorial

README.md
=> add ristretto

README.md
=> add Breeze0806/go-etl project

README.md
=> Add Go Ireland Meetup to the list

README.md
I've just changed the repo url for an existing project, so most of the MR template is not relevant so I cut those checkboxes.
=> Update aptly to use the official repo

README.md
=> fix: remove broken project link from README.md file

README.md
=> genny: remove

README.md
=> add lazyjournal

README.md
`Carbon` has been donated to [dromara](https://dromara.org/ "dromara") organization, the repository URL has changed.
=> repository url has changed

README.md
1. https://github.com/songgao/colorgo
- Appears to be no longer maintained, the last commit was 9 years ago.
- Open issues dating back to 2019 reporting faulty behavior.
- Open PRs dating back to 2019 with no response from the maintainer.
2. https://github.com/KyleBanks/depth
- Appears to be no longer maintained, the …
=> docs(Go tools): Add `go-template-playground` project

README.md
- **Forge link (GitHub, GitLab, etc.):** [https://github.com/getsentry/sentry-go](https://github.com/getsentry/sentry-go)
- **pkg.go.dev:** [https://pkg.go.dev/github.com/getsentry/sentry-go](https://pkg.go.dev/github.com/getsentry/sentry-go)
- **goreportcard.com:** [https://goreportcard.com/report/github.com/getsentry/sentry-go](https://goreportcard.com/report/github.com/getsentry/sentry-go)
- **Coverage service link:** _[If available, add link here, otherwise leave blank]_
**Related Issue:**
Fixes : #5652
=> Add Sentry to Awesome Go Repository

README.md
Removed Arche, as Ark (added with this PR) is the official successor. PR creator is the author of both.
=> Replace Arche by its successor Ark

README.md
=> Add kazhuravlev/git-tools

README.md
=> Add kazhuravlev/optional

README.md
=> Add kazhuravlev/healthcheck

README.md
- repo link (github.com, gitlab.com, etc): [https://github.com/optimus-hft/go-ipmux](https://github.com/optimus-hft/go-ipmux)
- pkg.go.dev: [https://pkg.go.dev/github.com/optimus-hft/go-ipmux](https://pkg.go.dev/github.com/optimus-hft/go-ipmux)
- goreportcard.com: [https://goreportcard.com/report/github.com/optimus-hft/go-ipmux](https://goreportcard.com/report/github.com/optimus-hft/go-ipmux)
- coverage service link ([codecov](https://codecov.io/), [coveralls](https://coveralls.io/), etc.): [https://app.codecov.io/gh/optimus-hft/go-ipmux](https://app. …
=> chore: add go-ipmux

README.md
Added gobl to the list of financial libraries.
=> Add gobl to financial libraries list

README.md
- repo link (github.com, gitlab.com, etc): https://github.com/leberKleber/go-mpris
- pkg.go.dev: https://pkg.go.dev/github.com/leberKleber/go-mpris
- goreportcard.com: https://goreportcard.com/report/github.com/leberKleber/go-mpris
- coverage service link ([codecov](https://codecov.io/), [coveralls](https://coveralls.io/), etc.): https://app.codecov.io/gh/leberKleber/go-mpris
_Not …
=> Add leberKleber/go-mpris

README.md
- repo link (github.com, gitlab.com, etc): https://github.com/cilium/ebpf
- pkg.go.dev: https://pkg.go.dev/github.com/cilium/ebpf
- goreportcard.com: https://goreportcard.com/report/github.com/cilium/ebpf
- coverage service link ([codecov](https://codecov.io/), [coveralls](https://coveralls.io/), etc.): https://github.com/cilium/ebpf/actions/runs/6589788640/job/17905066139 (this project do not expose coverage)
**Make sure that you've checked the boxes below that …
=> Adds Cillium eBPF Golang library to the Performance list

README.md
Aims for better readability in the main README as the table of content is quite large.
=> Updated README with expandable table of content.
